Abstract to 3d
BadgerTechnologies/badger_amcl pull request #2
Opened 2019-11-06 22:01 UTC by 12tbuchman

Still lots of work to do but I think it is ready for an initial review.

2020-01-21 16:14 UTC, c-andy-martin requested changes
> Reviewed 1 of 47 files at r1.
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/amcl/2)* status: 1 of 47 files reviewed, 1 unresolved discussion (waiting on @12tbuchman and @c-andy-martin)

___
*[package.xml, line 39 at r1](https://reviewable.io/reviews/badgertechnologies/amcl/2#-Lz7sH8yAHyiRZyaTqJr:-Lz7sH8z66l-k5d3GpU-:bqavqe1) ([raw file](https://github.com/badgertechnologies/amcl/blob/ba6da8b7912ca1f1c7e7b5dc81bd48de469c440f/package.xml#L39)):*
> ```XML
>     <build_depend>octomap_msgs</build_depend>
>     <build_depend>pcl_ros</build_depend>
>     <build_depend>eigen_conversions</build_depend>
> ```

I would like to go ahead and switch the package.xml to format 2 along with this rewrite. In format 2, you don't have to repeat yourself for build and run depends:
http://wiki.ros.org/catkin/package.xml


<!-- Sent from Reviewable.io -->

2020-01-21 16:14 UTC, c-andy-martin reviewed
> Reviewed 1 of 47 files at r1.
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/amcl/2)* status: 2 of 47 files reviewed, 1 unresolved discussion (waiting on @12tbuchman and @c-andy-martin)



<!-- Sent from Reviewable.io -->

2020-01-21 16:20 UTC, c-andy-martin commented
___
*[cfg/AMCL.cfg, line 10 at r1](https://reviewable.io/reviews/badgertechnologies/amcl/2#-Lz7t_Er5HJ0XmubXvj1:-Lz7t_Er5HJ0XmubXvj2:b-hi9tt9) ([raw file](https://github.com/badgertechnologies/amcl/blob/ba6da8b7912ca1f1c7e7b5dc81bd48de469c440f/cfg/AMCL.cfg#L10)):*
> ```INI
> gen = ParameterGenerator()
> 
> gen.add("planar_scan_topic", str_t, 0, "ROS Topic that amcl subscribes to for planar scans", "/scans/mark_and_clear")
> ```

Because AMCL should not be specific to our robot, I'd like to change the default topics to something generic. Either remap these when we launch, or change the param in the launch file to our topics. I'd make the default here '/scan', which is a reasonable default for a ROS system.


<!-- Sent from Reviewable.io -->

2020-01-21 16:23 UTC, c-andy-martin requested changes
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/amcl/2)* status: 2 of 47 files reviewed, 3 unresolved discussions (waiting on @12tbuchman and @c-andy-martin)

___
*[cfg/AMCL.cfg, line 11 at r1](https://reviewable.io/reviews/badgertechnologies/amcl/2#-Lz7uSfX-rciPm5qbAHc:-Lz7uSfX-rciPm5qbAHd:b-zaetp5) ([raw file](https://github.com/badgertechnologies/amcl/blob/ba6da8b7912ca1f1c7e7b5dc81bd48de469c440f/cfg/AMCL.cfg#L11)):*
> ```INI
> 
> gen.add("planar_scan_topic", str_t, 0, "ROS Topic that amcl subscribes to for planar scans", "/scans/mark_and_clear")
> gen.add("point_cloud_scan_topic", str_t, 0, "ROS Topic that amcl subscribes to for point cloud scans", "/scans/top/points_filtered")
> ```

And I'd make the default topic here "/points" or "/cloud", i've seen both as defaults for a point cloud topic.


<!-- Sent from Reviewable.io -->

2020-01-21 16:29 UTC, c-andy-martin commented
___
*[cfg/AMCL.cfg, line 47 at r1](https://reviewable.io/reviews/badgertechnologies/amcl/2#-Lz7vosC2rP-a_qk_q3n:-Lz7vosC2rP-a_qk_q3o:b-q2liqj) ([raw file](https://github.com/badgertechnologies/amcl/blob/ba6da8b7912ca1f1c7e7b5dc81bd48de469c440f/cfg/AMCL.cfg#L47)):*
> ```INI
> gen.add("tf_reverse", bool_t, 0, "When set to true, reverse published TF.", False)
> gen.add("gui_publish_rate", double_t, 0, "Maximum rate (Hz) at which scans and paths are published for visualization, -1.0 to disable.", -1, -1, 100)
> gen.add("transform_publish_rate", double_t, 0, "Rate (Hz) at which to publish the transform between map and odom to tf.", 50, 5, 100)
> ```

A user should be allowed to set a rate slower than 5hz I think. I'd make the minimum either 1 or something like 0.1 (so if they only want to publish every 10 seconds they can).


<!-- Sent from Reviewable.io -->

2020-01-21 16:31 UTC, c-andy-martin commented
___
*[cfg/AMCL.cfg, line 48 at r1](https://reviewable.io/reviews/badgertechnologies/amcl/2#-Lz7wEMr6va2YAmYmb66:-Lz7wEMr6va2YAmYmb67:buiqhc0) ([raw file](https://github.com/badgertechnologies/amcl/blob/ba6da8b7912ca1f1c7e7b5dc81bd48de469c440f/cfg/AMCL.cfg#L48)):*
> ```INI
> gen.add("gui_publish_rate", double_t, 0, "Maximum rate (Hz) at which scans and paths are published for visualization, -1.0 to disable.", -1, -1, 100)
> gen.add("transform_publish_rate", double_t, 0, "Rate (Hz) at which to publish the transform between map and odom to tf.", 50, 5, 100)
> gen.add("save_pose_to_server_rate", double_t, 0, "Maximum rate (Hz) at which to store the last estimated pose and covariance to the parameter server, in the variables ~initial_pose_* and ~initial_cov_*. This saved pose will be used on subsequent runs to initialize the filter. -1.0 to disable.", 2.0, 0, 10)
> ```

The original desc of "-1.0 to disable" doesn't make much sense given the minimum is 0. I'd adjust the min to include -1.0 if the feature still exists.


<!-- Sent from Reviewable.io -->

2020-01-21 16:32 UTC, c-andy-martin commented
___
*[cfg/AMCL.cfg, line 49 at r1](https://reviewable.io/reviews/badgertechnologies/amcl/2#-Lz7wS5j1fx_WA33amxh:-Lz7wS5j1fx_WA33amxi:b-hq7p89) ([raw file](https://github.com/badgertechnologies/amcl/blob/ba6da8b7912ca1f1c7e7b5dc81bd48de469c440f/cfg/AMCL.cfg#L49)):*
> ```INI
> gen.add("transform_publish_rate", double_t, 0, "Rate (Hz) at which to publish the transform between map and odom to tf.", 50, 5, 100)
> gen.add("save_pose_to_server_rate", double_t, 0, "Maximum rate (Hz) at which to store the last estimated pose and covariance to the parameter server, in the variables ~initial_pose_* and ~initial_cov_*. This saved pose will be used on subsequent runs to initialize the filter. -1.0 to disable.", 2.0, 0, 10)
> gen.add("save_pose_to_file_rate", double_t, 0, "Maximum rate (Hz) at which to store the last estimated pose and covariance to the file in BAR_COMMON. This saved pose will be used on subsequent runs to initialize the filter if the param server does not have the parameters stored. -1.0 to disable.", 0.1, 0, 10)
> ```

Do not mention anything specific to our robot, like BAR_COMMON. If there is a separate config for the path, mention that variable name instead. Also, same issue w/ -1.0 as above.


<!-- Sent from Reviewable.io -->

2020-01-21 16:32 UTC, c-andy-martin commented
___
*[cfg/AMCL.cfg, line 53 at r1](https://reviewable.io/reviews/badgertechnologies/amcl/2#-Lz7wdRKBzqqla8w-09f:-Lz7wdRKBzqqla8w-09g:b-57h8z6) ([raw file](https://github.com/badgertechnologies/amcl/blob/ba6da8b7912ca1f1c7e7b5dc81bd48de469c440f/cfg/AMCL.cfg#L53)):*
> ```INI
> gen.add("use_map_topic", bool_t, 0, "When set to true, AMCL will subscribe to the map topic rather than making a service call to receive its map.", False)
> gen.add("first_map_only", bool_t, 0, "When set to true, AMCL will only use the first map it subscribes to, rather than updating each time a new one is received.", False)
> gen.add("wait_for_occupancy_map", bool_t, 0, "When set to true and map type is 3, AMCL will wait for the occupancy map message before creating the OctoMap", True)
> ```

Change 'map type is 3' to whatever you name the enumeration I asked for above.


<!-- Sent from Reviewable.io -->

2020-01-21 21:36 UTC, c-andy-martin requested changes
> Reviewed 1 of 47 files at r1.
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/amcl/2)* status: 3 of 47 files reviewed, 10 unresolved discussions (waiting on @12tbuchman)

___
*[cfg/AMCL.cfg, line 13 at r1](https://reviewable.io/reviews/badgertechnologies/amcl/2#-Lz7uguC1MLNH1IPG7lr:-Lz7uguC1MLNH1IPG7ls:b5hlf3d) ([raw file](https://github.com/badgertechnologies/amcl/blob/ba6da8b7912ca1f1c7e7b5dc81bd48de469c440f/cfg/AMCL.cfg#L13)):*
> ```INI
> gen.add("point_cloud_scan_topic", str_t, 0, "ROS Topic that amcl subscribes to for point cloud scans", "/scans/top/points_filtered")
> 
> gen.add("map_type", int_t, 0, "Type of map to use - 2: 2d map, 3: 3d map, else: none", 0, 0, 3)
> ```

this should be an enumeration with 2 options. If you want an example, I know navigation/costmap_2d/cfg/ObstaclePlugin.cfg has an enumeration.
___
*[cfg/AMCL.cfg, line 24 at r1](https://reviewable.io/reviews/badgertechnologies/amcl/2#-Lz7vdBQ0d-XSkoJDQQ2:-Lz7vdBQ0d-XSkoJDQQ3:bybhrww) ([raw file](https://github.com/badgertechnologies/amcl/blob/ba6da8b7912ca1f1c7e7b5dc81bd48de469c440f/cfg/AMCL.cfg#L24)):*
> ```INI
> gen.add("update_min_a", double_t, 0, "Rotational movement required before performing a filter update.", pi/6, 0, 2*pi)
> 
> gen.add("resample_interval", int_t, 0, "Number of filter updates required before resampling.", 1, 0, 20)
> ```

why did you change the default here?
___
*[cfg/AMCL.cfg, line 156 at r1](https://reviewable.io/reviews/badgertechnologies/amcl/2#-Lz910OL9OtF2ULTISdW:-Lz910OL9OtF2ULTISdX:bel4wnd) ([raw file](https://github.com/badgertechnologies/amcl/blob/ba6da8b7912ca1f1c7e7b5dc81bd48de469c440f/cfg/AMCL.cfg#L156)):*
> ```INI
> 
> gen.add("save_pose", bool_t, 0, "If the node should save the pose to the param server and to a persistent file.", True)
> gen.add("saved_pose_filename", str_t, 0, "Name of file to store saved poses.", "savedpose.yaml")
> ```

if you don't already have a config for the full path to the savedpose, this might be a good place to put it. Again, we don't want to hardcode any paths to robot specific locations in this code. Paths should be setup by a launch file in ant_navigation or bar_launchers.


<!-- Sent from Reviewable.io -->

2020-01-21 21:41 UTC, c-andy-martin commented
___
*[include/amcl/map/map.h, line 24 at r1](https://reviewable.io/reviews/badgertechnologies/amcl/2#-Lz926KZ7Hj0JbyTRpXg:-Lz926KZ7Hj0JbyTRpXh:bg8ur7p) ([raw file](https://github.com/badgertechnologies/amcl/blob/ba6da8b7912ca1f1c7e7b5dc81bd48de469c440f/include/amcl/map/map.h#L24)):*
> ```objc
>  * Desc: Global map (grid-based)
>  * Author: Andrew Howard
>  * Mainainer: Tyler Buchman (tyler_buchman@jabil.com)
> ```

Do you have a badger-technologies email address? If not, I suggest you see if Brian Lee will give you one, and use that here. Badger is how we want to face the world, and if somehow we ever changed owners, we would still present as badger


<!-- Sent from Reviewable.io -->

2020-01-21 22:06 UTC, c-andy-martin commented
___
*[include/amcl/map/map.h, line 38 at r1](https://reviewable.io/reviews/badgertechnologies/amcl/2#-Lz92QV_CnzVBzJ2gU3i:-Lz92QV_CnzVBzJ2gU3j:b1txz1f) ([raw file](https://github.com/badgertechnologies/amcl/blob/ba6da8b7912ca1f1c7e7b5dc81bd48de469c440f/include/amcl/map/map.h#L38)):*
> ```objc
> class Map
> {
>   public:
> ```

The roscpp style guide says to not indent `public` and `private` at all. Look at the example in section 6:
http://wiki.ros.org/CppStyleGuide

Also, I find this tool extremely useful:
https://github.com/davetcoleman/roscpp_code_format

I previously committed and pushed the .clang_format file the way we want it in our catkin_ws, so you can just use it by going to your `amcl` directory and doing:
`find . -name "*.cpp" -o -name "*.h" | xargs clang-format-3.8 -i -style=file`
Note that this changes all your files, so you will want to start with a clean git workspace (all changes committed) and then you can commit this relatively big re-write. Note that rewriting like this is going to make it hard to rebase your changes later, which is OK to me, because we are already doing so much.


<!-- Sent from Reviewable.io -->

2020-01-21 22:20 UTC, 12tbuchman reviewed
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/amcl/2)* status: 3 of 47 files reviewed, 12 unresolved discussions (waiting on @12tbuchman and @c-andy-martin)

___
*[include/amcl/map/map.h, line 24 at r1](https://reviewable.io/reviews/badgertechnologies/amcl/2#-Lz926KZ7Hj0JbyTRpXg:-Lz9BFK09OGLEsBe2Y-e:bgot89m) ([raw file](https://github.com/badgertechnologies/amcl/blob/ba6da8b7912ca1f1c7e7b5dc81bd48de469c440f/include/amcl/map/map.h#L24)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

Do you have a badger-technologies email address? If not, I suggest you see if Brian Lee will give you one, and use that here. Badger is how we want to face the world, and if somehow we ever changed owners, we would still present as badger
</blockquote></details>

I don't, I still only have the "(non-jabil)" jabil email address. Ill send Brian a message.


<!-- Sent from Reviewable.io -->

2020-01-22 15:57 UTC, 12tbuchman reviewed
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/amcl/2)* status: 2 of 48 files reviewed, 12 unresolved discussions (waiting on @12tbuchman and @c-andy-martin)

___
*[package.xml, line 39 at r1](https://reviewable.io/reviews/badgertechnologies/amcl/2#-Lz7sH8yAHyiRZyaTqJr:-LzCyL8H2IO9iP0NW-zk:b-896fix) ([raw file](https://github.com/badgertechnologies/amcl/blob/ba6da8b7912ca1f1c7e7b5dc81bd48de469c440f/package.xml#L39)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

I would like to go ahead and switch the package.xml to format 2 along with this rewrite. In format 2, you don't have to repeat yourself for build and run depends:
http://wiki.ros.org/catkin/package.xml
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-01-22 17:21 UTC, 12tbuchman reviewed
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/amcl/2)* status: 2 of 48 files reviewed, 12 unresolved discussions (waiting on @12tbuchman and @c-andy-martin)

___
*[include/amcl/map/map.h, line 38 at r1](https://reviewable.io/reviews/badgertechnologies/amcl/2#-Lz92QV_CnzVBzJ2gU3i:-LzDF8exE8FDPkuNdUBZ:b-896fix) ([raw file](https://github.com/badgertechnologies/amcl/blob/ba6da8b7912ca1f1c7e7b5dc81bd48de469c440f/include/amcl/map/map.h#L38)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

The roscpp style guide says to not indent `public` and `private` at all. Look at the example in section 6:
http://wiki.ros.org/CppStyleGuide

Also, I find this tool extremely useful:
https://github.com/davetcoleman/roscpp_code_format

I previously committed and pushed the .clang_format file the way we want it in our catkin_ws, so you can just use it by going to your `amcl` directory and doing:
`find . -name "*.cpp" -o -name "*.h" | xargs clang-format-3.8 -i -style=file`
Note that this changes all your files, so you will want to start with a clean git workspace (all changes committed) and then you can commit this relatively big re-write. Note that rewriting like this is going to make it hard to rebase your changes later, which is OK to me, because we are already doing so much.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-01-22 17:32 UTC, c-andy-martin commented
___
*[package.xml, line 24 at r2](https://reviewable.io/reviews/badgertechnologies/amcl/2#-LzDIn3o0ZRRiEm3VhL9:-LzDIn3o0ZRRiEm3VhLA:bodbewu) ([raw file](https://github.com/badgertechnologies/amcl/blob/bbbafd470c81f3bf418c310bd0334bc4469d4b08/package.xml#L24)):*
> ```XML
>     <author>Brian P. Gerkey</author>
>     <author>contradict@gmail.com</author>
>     <maintainer email="tylerbuchman@jabil.com">Tyler Buchman</maintainer>
> ```

as before, I don't want jabil.com if we can help it. If you can't get a badger-tech, maybe just list me as the maintainer? This repo is public, and I think our public persona should be Badger


<!-- Sent from Reviewable.io -->

2020-01-22 17:35 UTC, c-andy-martin commented
___
*[include/amcl/map/map.h, line 38 at r1](https://reviewable.io/reviews/badgertechnologies/amcl/2#-Lz92QV_CnzVBzJ2gU3i:-LzDJVDq9hCbZJ6J8rv0:b-wn7pe6) ([raw file](https://github.com/badgertechnologies/amcl/blob/ba6da8b7912ca1f1c7e7b5dc81bd48de469c440f/include/amcl/map/map.h#L38)):*
<details><summary><i>Previously, 12tbuchman (Tyler Buchman) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Its still not how the style guide says, it should look like:
```
class Map
{
public:
  Map();
  ~Map();
...
```


<!-- Sent from Reviewable.io -->

2020-01-22 17:45 UTC, c-andy-martin commented
___
*[include/amcl/map/map.h, line 51 at r2](https://reviewable.io/reviews/badgertechnologies/amcl/2#-LzDKBEKBEjljFN1nK2Y:-LzDKBEKBEjljFN1nK2Z:b-71scny) ([raw file](https://github.com/badgertechnologies/amcl/blob/bbbafd470c81f3bf418c310bd0334bc4469d4b08/include/amcl/map/map.h#L51)):*
> ```objc
>     virtual std::vector<int> getSize() = 0;
>     virtual std::vector<double> getOrigin() = 0;
>     virtual void setOrigin(std::vector<double> _origin) = 0;
> ```

3 things:
1) I'd pass this by const-reference
2) the name should not start w/ an underscore.
3) In general, it would be more efficient to not use std::vector for coordinates, and just have the 2D version ignore the z value. I'd recommend using pcl::PointXYZ since we are already depending on PCL, but I wouldn't use it directly, I'd define a new amcl::Point in some header, under the amcl namespace:
```
using Point = pcl::PointXYZ;
```
Then instead of passing `const std::vector<double>&` I would pass `const Point&`


<!-- Sent from Reviewable.io -->

2020-01-22 17:45 UTC, c-andy-martin commented
___
*[include/amcl/map/map.h, line 54 at r2](https://reviewable.io/reviews/badgertechnologies/amcl/2#-LzDLygc-cvwg4j0ODEP:-LzDLygc-cvwg4j0ODEQ:b-ab0gq1) ([raw file](https://github.com/badgertechnologies/amcl/blob/bbbafd470c81f3bf418c310bd0334bc4469d4b08/include/amcl/map/map.h#L54)):*
> ```objc
>     bool isCSpaceCreated();
>     double getScale();
>     void setScale(double _scale);
> ```

again, do not start argument w/ an underscore


<!-- Sent from Reviewable.io -->

2020-01-22 17:50 UTC, c-andy-martin commented
___
*[include/amcl/map/map.h, line 65 at r2](https://reviewable.io/reviews/badgertechnologies/amcl/2#-LzDMbLw8BTa3EPUE2Tt:-LzDMbLw8BTa3EPUE2Tu:b-7jwmdl) ([raw file](https://github.com/badgertechnologies/amcl/blob/bbbafd470c81f3bf418c310bd0334bc4469d4b08/include/amcl/map/map.h#L65)):*
> ```objc
> }
> 
> #endif
> ```

while not explicit in the ROS CPP style guide, in the google c++ style guide its based on they always end a macro guard w/ a comment (separated by two white spaces, as the guide suggests for inline comments):
```
#endif  // AMCL_MAP_H
```


<!-- Sent from Reviewable.io -->

2020-01-22 17:50 UTC, c-andy-martin commented
___
*[include/amcl/map/map.h, line 61 at r2](https://reviewable.io/reviews/badgertechnologies/amcl/2#-LzDMCKxDJJJb4ug2HBF:-LzDMCKyEjpwV9QLP_CY:bgrpb71) ([raw file](https://github.com/badgertechnologies/amcl/blob/bbbafd470c81f3bf418c310bd0334bc4469d4b08/include/amcl/map/map.h#L61)):*
> ```objc
>     double max_occ_dist_;
>     std::atomic<bool> cspace_created_;
> };
> ```

while not explicit in the ROS CPP style guide, in the google c++ style guide its based on they always end a namespace w/ a comment (separated by two white spaces, as the guide suggests for inline comments):
```
};  // namespace amcl
```



<!-- Sent from Reviewable.io -->

2020-01-22 18:32 UTC, 12tbuchman reviewed
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/amcl/2)* status: 2 of 48 files reviewed, 17 unresolved discussions (waiting on @12tbuchman and @c-andy-martin)

___
*[include/amcl/map/map.h, line 38 at r1](https://reviewable.io/reviews/badgertechnologies/amcl/2#-Lz92QV_CnzVBzJ2gU3i:-LzDWcBrALwPRYutXJli:bfodpky) ([raw file](https://github.com/badgertechnologies/amcl/blob/ba6da8b7912ca1f1c7e7b5dc81bd48de469c440f/include/amcl/map/map.h#L38)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

Its still not how the style guide says, it should look like:
```
class Map
{
public:
  Map();
  ~Map();
...
```
</blockquote></details>

Thats what I have


<!-- Sent from Reviewable.io -->

2020-01-22 18:33 UTC, 12tbuchman reviewed
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/amcl/2)* status: 2 of 48 files reviewed, 17 unresolved discussions (waiting on @12tbuchman and @c-andy-martin)

___
*[include/amcl/map/map.h, line 38 at r1](https://reviewable.io/reviews/badgertechnologies/amcl/2#-Lz92QV_CnzVBzJ2gU3i:-LzDWvlo0ABmGDOFCIcm:b-gg72rq) ([raw file](https://github.com/badgertechnologies/amcl/blob/ba6da8b7912ca1f1c7e7b5dc81bd48de469c440f/include/amcl/map/map.h#L38)):*
<details><summary><i>Previously, 12tbuchman (Tyler Buchman) wrote…</i></summary><blockquote>

Thats what I have
</blockquote></details>

Whoops, I pushed my changes to the wrong branch. Should be updated now.


<!-- Sent from Reviewable.io -->

2020-01-22 19:23 UTC, c-andy-martin commented
___
*[include/amcl/map/map.h, line 53 at r2](https://reviewable.io/reviews/badgertechnologies/amcl/2#-LzDhL9y9aGnzNBJdOPr:-LzDhL9y9aGnzNBJdOPs:b-qie0p0) ([raw file](https://github.com/badgertechnologies/amcl/blob/bbbafd470c81f3bf418c310bd0334bc4469d4b08/include/amcl/map/map.h#L53)):*
> ```objc
>     virtual void setOrigin(std::vector<double> _origin) = 0;
>     bool isCSpaceCreated();
>     double getScale();
> ```

"Scale" makes less sense to me than "Resolution". Was scale their old term for it? Would it be OK to rename Scale => Resolution?


<!-- Sent from Reviewable.io -->

2020-01-22 19:26 UTC, c-andy-martin commented
___
*[include/amcl/map/map.h, line 49 at r2](https://reviewable.io/reviews/badgertechnologies/amcl/2#-LzDhdEdBAUp9VnHF9p8:-LzDhdEe4TKxRNXJ10Kk:bkc1gov) ([raw file](https://github.com/badgertechnologies/amcl/blob/bbbafd470c81f3bf418c310bd0334bc4469d4b08/include/amcl/map/map.h#L49)):*
> ```objc
>     // Test to see if the given map coords lie within the absolute map bounds.
>     virtual bool isValid(std::vector<int> coords) = 0;
>     virtual std::vector<int> getSize() = 0;
> ```

I would prefer to set and get the size using world coordinate units (meters) and not map cells, would that be OK? So, you would pass a Point in meters representing the width/height/depth. This matches up w/ the origin which is in meters. Also, you could store the size in world units, and then update the number of map cell units when the resolution is changed


<!-- Sent from Reviewable.io -->

2020-01-22 19:27 UTC, c-andy-martin commented
___
*[include/amcl/map/map.h, line 49 at r2](https://reviewable.io/reviews/badgertechnologies/amcl/2#-LzDhdEdBAUp9VnHF9p8:-LzDiFkI9TzQg_SekboB:bx6gjzm) ([raw file](https://github.com/badgertechnologies/amcl/blob/bbbafd470c81f3bf418c310bd0334bc4469d4b08/include/amcl/map/map.h#L49)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

I would prefer to set and get the size using world coordinate units (meters) and not map cells, would that be OK? So, you would pass a Point in meters representing the width/height/depth. This matches up w/ the origin which is in meters. Also, you could store the size in world units, and then update the number of map cell units when the resolution is changed
</blockquote></details>

Actually, I don't really care which way you do this too much, and you probably are getting the size in cells from the map itself, so I'm OK leaving this.


<!-- Sent from Reviewable.io -->

2020-01-22 19:30 UTC, c-andy-martin requested changes
> Reviewed 1 of 55 files at r1, 2 of 22 files at r2.
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/amcl/2)* status: 4 of 48 files reviewed, 26 unresolved discussions (waiting on @12tbuchman and @c-andy-martin)

___
*[package.xml, line 3 at r2](https://reviewable.io/reviews/badgertechnologies/amcl/2#-LzDI_er8uzxeyktRv8I:-LzDI_er8uzxeyktRv8J:byrxkit) ([raw file](https://github.com/badgertechnologies/amcl/blob/bbbafd470c81f3bf418c310bd0334bc4469d4b08/package.xml#L3)):*
> ```XML
> <package format="2">
>     <name>amcl</name>
>     <version>1.0.0</version>
> ```

It doesn't make sense to go backwards on the version number. If anything, you can bump the major version to 2, maybe make this `2.0.0`.
___
*[include/amcl/map/map.h, line 24 at r1](https://reviewable.io/reviews/badgertechnologies/amcl/2#-Lz926KZ7Hj0JbyTRpXg:-LzDJC_rBiWvwbsDW2t9:bcpcc1) ([raw file](https://github.com/badgertechnologies/amcl/blob/ba6da8b7912ca1f1c7e7b5dc81bd48de469c440f/include/amcl/map/map.h#L24)):*
<details><summary><i>Previously, 12tbuchman (Tyler Buchman) wrote…</i></summary><blockquote>

I don't, I still only have the "(non-jabil)" jabil email address. Ill send Brian a message.
</blockquote></details>

FWIW, I think we can get rid of all 'Maintainer: ' from every file, and just use the one listed in package.xml.
___
*[include/amcl/map/map.h, line 48 at r2](https://reviewable.io/reviews/badgertechnologies/amcl/2#-LzDK49B2O9CHzy9lF5g:-LzDK49B2O9CHzy9lF5h:b-4jrk79) ([raw file](https://github.com/badgertechnologies/amcl/blob/bbbafd470c81f3bf418c310bd0334bc4469d4b08/include/amcl/map/map.h#L48)):*
> ```objc
>                                    std::vector<int> *map_coords) = 0;
>     // Test to see if the given map coords lie within the absolute map bounds.
>     virtual bool isValid(std::vector<int> coords) = 0;
> ```

I typically pass complex objects, like `std::vector` by const-reference as inputs to save copies
___
*[include/amcl/map/map.h, line 49 at r3](https://reviewable.io/reviews/badgertechnologies/amcl/2#-LzDirgY1Yd9Kc-mo8FV:-LzDirgY1Yd9Kc-mo8FW:b-ifwr4b) ([raw file](https://github.com/badgertechnologies/amcl/blob/770d4c63beb80b8977948e006adb7bdbc3c1d735/include/amcl/map/map.h#L49)):*
> ```objc
>   virtual std::vector<double> getOrigin() = 0;
>   virtual void setOrigin(std::vector<double> _origin) = 0;
>   bool isCSpaceCreated();
> ```

I would make every method of this class virtual, not just the pure-virtual ones. This way, children can override behavior (such as re-allocating an octomap w/ the correct resolution on a resolution change).
___
*[include/amcl/map/occupancy_map.h, line 2 at r2](https://reviewable.io/reviews/badgertechnologies/amcl/2#-LzDfQjg1dyDxxey3m_b:-LzDfQjh8PN0jkUFpO8q:b-p02932) ([raw file](https://github.com/badgertechnologies/amcl/blob/bbbafd470c81f3bf418c310bd0334bc4469d4b08/include/amcl/map/occupancy_map.h#L2)):*
> ```objc
> /*
>  *  Player - One Hell of a Robot Server
> ```

Let's get rid of all the references to Player which is very obsolete (more than 12 years old). Keep the copyright and authorship, but we don't have to mention the player robot server anywhere.
___
*[include/amcl/map/occupancy_map.h, line 24 at r2](https://reviewable.io/reviews/badgertechnologies/amcl/2#-LzDfbH93_CR3EQnC6pc:-LzDfbH93_CR3EQnC6pd:bmw2mj3) ([raw file](https://github.com/badgertechnologies/amcl/blob/bbbafd470c81f3bf418c310bd0334bc4469d4b08/include/amcl/map/occupancy_map.h#L24)):*
> ```objc
>  * Desc: Global map (grid-based)
>  * Author: Andrew Howard
>  * Maintainter: Tyler Buchman (tyler_buchman@jabil.com)
> ```

Let's leave maintainer out of source files. However, feel free to add yourself as another author, as you have (re) authored most of this. And as before, I prefer a badger-technologies.com email here for consistency of communication to the world.
___
*[include/amcl/map/occupancy_map.h, line 32 at r2](https://reviewable.io/reviews/badgertechnologies/amcl/2#-LzDfo7y8VUTNEzUSTLP:-LzDfo7y8VUTNEzUSTLQ:b-xt54no) ([raw file](https://github.com/badgertechnologies/amcl/blob/bbbafd470c81f3bf418c310bd0334bc4469d4b08/include/amcl/map/occupancy_map.h#L32)):*
> ```objc
> #include "map/map.h"
> 
> #include <math.h>
> ```

I would prefer making this `<cmath>`. This may require adding `std::` in a few places, but I'd rather do that and make it explicit to avoid any potential name conflicts.
___
*[include/amcl/map/occupancy_map.h, line 33 at r2](https://reviewable.io/reviews/badgertechnologies/amcl/2#-LzDg0kP8nS6GFpgpHpM:-LzDg0kP8nS6GFpgpHpN:b9tu6cy) ([raw file](https://github.com/badgertechnologies/amcl/blob/bbbafd470c81f3bf418c310bd0334bc4469d4b08/include/amcl/map/occupancy_map.h#L33)):*
> ```objc
> 
> #include <math.h>
> ```

I don't think you need a vertical white-space here as these are still standard headers.
___
*[include/amcl/map/occupancy_map.h, line 51 at r2](https://reviewable.io/reviews/badgertechnologies/amcl/2#-LzD_brb6RAOCcP-Oogl:-LzD_brb6RAOCcP-Oogm:bmtbpl2) ([raw file](https://github.com/badgertechnologies/amcl/blob/bbbafd470c81f3bf418c310bd0334bc4469d4b08/include/amcl/map/occupancy_map.h#L51)):*
> ```objc
> class OccupancyMap : public Map
> {
>   public:
> ```

same comment on spacing as `map.h`, please fix it everywhere, I won't comment again to not have a bunch of comments on the same issue
___
*[include/amcl/map/occupancy_map.h, line 53 at r2](https://reviewable.io/reviews/badgertechnologies/amcl/2#-LzDgDfk7cnU4Gwm0Gqx:-LzDgDfk7cnU4Gwm0Gqy:b-rp7l4m) ([raw file](https://github.com/badgertechnologies/amcl/blob/bbbafd470c81f3bf418c310bd0334bc4469d4b08/include/amcl/map/occupancy_map.h#L53)):*
> ```objc
>   public:
>     OccupancyMap();
>     ~OccupancyMap() {};
> ```

I would prefer to mark this and all other public methods virtual, since the parent class is a pure virtual class.
___
*[include/amcl/map/occupancy_map.h, line 121 at r2](https://reviewable.io/reviews/badgertechnologies/amcl/2#-LzD_NoB0B-t6EM3bMHa:-LzD_NoCE0Bjrk3INYO5:bhppc1q) ([raw file](https://github.com/badgertechnologies/amcl/blob/bbbafd470c81f3bf418c310bd0334bc4469d4b08/include/amcl/map/occupancy_map.h#L121)):*
> ```objc
>     void setMapOccDist(int i, int j, float d);
>     bool enqueue(int i, int j, int src_i, int src_j,
> 	             std::priority_queue<CellData>& Q);
> ```

we don't want to use tab characters. I suggest getting your editor setup to never emit tabs and to replace them with the correct shifts.


<!-- Sent from Reviewable.io -->

2020-01-22 19:59 UTC, c-andy-martin requested changes
> Reviewed 1 of 32 files at r3.
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/amcl/2)* status: 5 of 48 files reviewed, 34 unresolved discussions (waiting on @12tbuchman)

___
*[include/amcl/map/occupancy_map.h, line 79 at r3](https://reviewable.io/reviews/badgertechnologies/amcl/2#-LzDoBmg9ktNWj9KM2yj:-LzDoBmg9ktNWj9KM2yk:b-3o9y7g) ([raw file](https://github.com/badgertechnologies/amcl/blob/770d4c63beb80b8977948e006adb7bdbc3c1d735/include/amcl/map/occupancy_map.h#L79)):*
> ```objc
>   struct CellData
>   {
>     OccupancyMap* occMap;
> ```

I'd either make this end in underscore, or not have `i_`, `J_` etc. end in underscores, its OK for public member variables to not end in an underscore.
___
*[include/amcl/map/occupancy_map.h, line 80 at r3](https://reviewable.io/reviews/badgertechnologies/amcl/2#-LzDo77YCrDTG6g8JVin:-LzDo77YCrDTG6g8JVio:bly19pw) ([raw file](https://github.com/badgertechnologies/amcl/blob/770d4c63beb80b8977948e006adb7bdbc3c1d735/include/amcl/map/occupancy_map.h#L80)):*
> ```objc
>   {
>     OccupancyMap* occMap;
>     CellData(OccupancyMap* _occMap) : occMap(_occMap)
> ```

I'd prefer not using underscores at beginning, and just pick a different name (I'm fine w/ just `o`, or `map`, or `newOccMap`, etc.)
___
*[include/amcl/map/occupancy_map.h, line 83 at r3](https://reviewable.io/reviews/badgertechnologies/amcl/2#-LzDo15I15B7YGpji4yJ:-LzDo15J5cJNDqWxNKsL:b-kk2m4o) ([raw file](https://github.com/badgertechnologies/amcl/blob/770d4c63beb80b8977948e006adb7bdbc3c1d735/include/amcl/map/occupancy_map.h#L83)):*
> ```objc
>     {
>     }
>     int i_, j_;
> ```

you don't have to use trailing underscores on public members of a struct or class. I think its OK to do so, but not required.
___
*[include/amcl/map/occupancy_map.h, line 90 at r3](https://reviewable.io/reviews/badgertechnologies/amcl/2#-LzDoarvDVlMEKvkSvjK:-LzDoarvDVlMEKvkSvjL:b-bgvtl5) ([raw file](https://github.com/badgertechnologies/amcl/blob/770d4c63beb80b8977948e006adb7bdbc3c1d735/include/amcl/map/occupancy_map.h#L90)):*
> ```objc
>   {
>   public:
>     double** distances_;
> ```

do these member variables need to be public? if not, move them into protected space
___
*[include/amcl/map/occupancy_map.h, line 90 at r3](https://reviewable.io/reviews/badgertechnologies/amcl/2#-LzDozUt8UOX4pQy-YVv:-LzDozUu3mRcPcVmTfFy:bltaowq) ([raw file](https://github.com/badgertechnologies/amcl/blob/770d4c63beb80b8977948e006adb7bdbc3c1d735/include/amcl/map/occupancy_map.h#L90)):*
> ```objc
>   {
>   public:
>     double** distances_;
> ```

I would make `distances_` a member `std::vector<std::vector<double>>`.
___
*[include/amcl/map/occupancy_map.h, line 95 at r3](https://reviewable.io/reviews/badgertechnologies/amcl/2#-LzDpSQ35WFzZKOEPaBb:-LzDpSQ35WFzZKOEPaBc:b-4de6bx) ([raw file](https://github.com/badgertechnologies/amcl/blob/770d4c63beb80b8977948e006adb7bdbc3c1d735/include/amcl/map/occupancy_map.h#L95)):*
> ```objc
>     int cell_radius_;
> 
>     CachedDistanceMap(double scale, double max_dist) : distances_(nullptr), scale_(scale), max_dist_(max_dist)
> ```

again, I prefer `resolution` over `scale`, if thats ok
___
*[include/amcl/map/occupancy_map.h, line 98 at r3](https://reviewable.io/reviews/badgertechnologies/amcl/2#-LzDp7QZC6uIuWgiatIc:-LzDp7QZC6uIuWgiatId:b-qzecue) ([raw file](https://github.com/badgertechnologies/amcl/blob/770d4c63beb80b8977948e006adb7bdbc3c1d735/include/amcl/map/occupancy_map.h#L98)):*
> ```objc
>     {
>       cell_radius_ = max_dist / scale;
>       distances_ = new double*[cell_radius_ + 2];
> ```

if you follow my idea above, this becomes `distances_.resize(cell_radius_+2);`
___
*[include/amcl/map/occupancy_map.h, line 101 at r3](https://reviewable.io/reviews/badgertechnologies/amcl/2#-LzDpCWVDQkGdZzdHyv8:-LzDpCWVDQkGdZzdHyv9:b-bdwwp3) ([raw file](https://github.com/badgertechnologies/amcl/blob/770d4c63beb80b8977948e006adb7bdbc3c1d735/include/amcl/map/occupancy_map.h#L101)):*
> ```objc
>       for (int i = 0; i <= cell_radius_ + 1; i++)
>       {
>         distances_[i] = new double[cell_radius_ + 2];
> ```

if you follow my idea above, this becomes `distances_[i].resize(cell_radius_+2);`
___
*[include/amcl/map/occupancy_map.h, line 114 at r3](https://reviewable.io/reviews/badgertechnologies/amcl/2#-LzDpI3M7LuzIPWd_tb2:-LzDpI3M7LuzIPWd_tb3:b-bmqjyx) ([raw file](https://github.com/badgertechnologies/amcl/blob/770d4c63beb80b8977948e006adb7bdbc3c1d735/include/amcl/map/occupancy_map.h#L114)):*
> ```objc
>       {
>         for (int i = 0; i <= cell_radius_ + 1; i++)
>           delete[] distances_[i];
> ```

if you follow my idea above, you don't need any of this code


<!-- Sent from Reviewable.io -->

2020-01-22 20:31 UTC, c-andy-martin requested changes
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/amcl/2)* status: 5 of 48 files reviewed, 35 unresolved discussions (waiting on @12tbuchman)

___
*[include/amcl/map/occupancy_map.h, line 144 at r3](https://reviewable.io/reviews/badgertechnologies/amcl/2#-LzDpb2MAkMUiBE1CHjJ:-LzDpb2MAkMUiBE1CHjK:bfufb3k) ([raw file](https://github.com/badgertechnologies/amcl/blob/770d4c63beb80b8977948e006adb7bdbc3c1d735/include/amcl/map/occupancy_map.h#L144)):*
> ```objc
>   return a.occMap->getOccDist(a.i_, a.j_) > b.occMap->getOccDist(b.i_, b.j_);
> }
> }
> ```

please add 


<!-- Sent from Reviewable.io -->

2020-01-22 20:32 UTC, c-andy-martin requested changes
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/amcl/2)* status: 5 of 48 files reviewed, 35 unresolved discussions (waiting on @12tbuchman)

___
*[include/amcl/map/occupancy_map.h, line 144 at r3](https://reviewable.io/reviews/badgertechnologies/amcl/2#-LzDpb2MAkMUiBE1CHjJ:-LzDx5iPE8y5R9p4tw3n:byjgwfg) ([raw file](https://github.com/badgertechnologies/amcl/blob/770d4c63beb80b8977948e006adb7bdbc3c1d735/include/amcl/map/occupancy_map.h#L144)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

please add 
</blockquote></details>

the comment for namespace, here and everywhere.


<!-- Sent from Reviewable.io -->

2020-01-22 20:42 UTC, c-andy-martin commented
___
*[include/amcl/map/occupancy_map.h, line 123 at r3](https://reviewable.io/reviews/badgertechnologies/amcl/2#-LzDxJjy67TeH2eNSHib:-LzDxJjy67TeH2eNSHic:b-z3pw7t) ([raw file](https://github.com/badgertechnologies/amcl/blob/770d4c63beb80b8977948e006adb7bdbc3c1d735/include/amcl/map/occupancy_map.h#L123)):*
> ```objc
>   bool enqueue(int i, int j, int src_i, int src_j, std::priority_queue<CellData>& Q);
> 
>   friend bool operator<(const OccupancyMap::CellData& a, const OccupancyMap::CellData& b);
> ```

There is no reason that I can see to define the `operator<` outside the CellData struct. Instead just put `operator<` in the struct which just takes a right-hand-side, and not mess with the friend and outside the class thing. So, in the `struct CellData` just add:
```
  bool operator<(const CellData& rhs)
  {
    return occMap->getOccDist(i_, j_) > rhs.occMap->getOccDist(rhs.i_, rhs.j_);
  }
```
that *should* work the same way and be simpler to follow, and not add a new `operator<`to the `amcl::` namespace


<!-- Sent from Reviewable.io -->

2020-01-22 20:49 UTC, c-andy-martin reviewed
> Reviewed 1 of 32 files at r3.
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/amcl/2)* status: 6 of 48 files reviewed, 36 unresolved discussions (waiting on @12tbuchman)



<!-- Sent from Reviewable.io -->

2020-01-23 16:21 UTC, c-andy-martin commented
___
*[include/amcl/map/octomap.h, line 2 at r3](https://reviewable.io/reviews/badgertechnologies/amcl/2#-LzIByu64-Qhyc5Dr2up:-LzIByu71tNV_Qh8lmI0:b-xyyewc) ([raw file](https://github.com/badgertechnologies/amcl/blob/770d4c63beb80b8977948e006adb7bdbc3c1d735/include/amcl/map/octomap.h#L2)):*
> ```objc
> /*
>  *  This library is free software; you can redistribute it and/or
> ```

Like in map.h, there should be an assignment of copyright above the license. I suggest starting the file (and any other new ones) like this:
```
/*
 * Copyright (C) 2020 Badger Technologies, LLC
 *
 * This library is free software; you can redistribute it and/or
```


<!-- Sent from Reviewable.io -->

2020-01-23 16:23 UTC, c-andy-martin commented
___
*[include/amcl/map/octomap.h, line 17 at r3](https://reviewable.io/reviews/badgertechnologies/amcl/2#-LzICNRj92lvSsgJh8mB:-LzICNRj92lvSsgJh8mC:b30th9w) ([raw file](https://github.com/badgertechnologies/amcl/blob/770d4c63beb80b8977948e006adb7bdbc3c1d735/include/amcl/map/octomap.h#L17)):*
> ```objc
>  *
>  */
> ///////////////////////////////////////////////////////////////////////////
> ```

I'd prefer this block comment to be in C form matching the above block comment, something like this:
```
/*
 * Octomap for 3D AMCL
 *
 * (Anything else you want to say goes here.)
 */
```
Alternatively, it may look even better to just extend the above comment, after the license text, write what the description


<!-- Sent from Reviewable.io -->

2020-01-23 16:24 UTC, c-andy-martin commented
___
*[include/amcl/map/octomap.h, line 24 at r3](https://reviewable.io/reviews/badgertechnologies/amcl/2#-LzICoPo1XsE44V2vh2L:-LzICoPo1XsE44V2vh2M:byh81oo) ([raw file](https://github.com/badgertechnologies/amcl/blob/770d4c63beb80b8977948e006adb7bdbc3c1d735/include/amcl/map/octomap.h#L24)):*
> ```objc
> ///////////////////////////////////////////////////////////////////////////
> 
> #ifndef AMCL_OCTOMAP_H
> ```

to follow convention, all the macro guards should really have each part of the path represented (so if you had a `amcl/other_dir/octomap.h` there would be no name conflict):
```
#ifndef AMCL_MAP_OCTOMAP_H
```
I'd check all the headers and follow this convention.


<!-- Sent from Reviewable.io -->

2020-01-23 16:27 UTC, c-andy-martin commented
___
*[include/amcl/map/octomap.h, line 27 at r3](https://reviewable.io/reviews/badgertechnologies/amcl/2#-LzID2YS1c2-S9z5rjc_:-LzID2YS1c2-S9z5rjca:bc1419o) ([raw file](https://github.com/badgertechnologies/amcl/blob/770d4c63beb80b8977948e006adb7bdbc3c1d735/include/amcl/map/octomap.h#L27)):*
> ```objc
> #define AMCL_OCTOMAP_H
> 
> #include "map/map.h"
> ```

the header include order in the style guides says to include standard headers, then other library headers, then the local code headers, so these are all backwards. Instead, start with `<limits>` and the like, then the octomap headers, then local headers like `map.h`. For the C++ files, you are supposed to first include the header that declares the code you are about to define first, then follow the same order:

https://google.github.io/styleguide/cppguide.html#Names_and_Order_of_Includes

the clang format file can be changed to try and do this for you, but my guess is it doesn't do a perfect job. feel free to try it if you want.


<!-- Sent from Reviewable.io -->

2020-01-23 16:28 UTC, c-andy-martin requested changes
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/amcl/2)* status: 6 of 48 files reviewed, 42 unresolved discussions (waiting on @12tbuchman)

___
*[include/amcl/map/octomap.h, line 20 at r3](https://reviewable.io/reviews/badgertechnologies/amcl/2#-LzIBoLq2XnmPNA7ECp7:-LzIBoLq2XnmPNA7ECp8:bmwzlta) ([raw file](https://github.com/badgertechnologies/amcl/blob/770d4c63beb80b8977948e006adb7bdbc3c1d735/include/amcl/map/octomap.h#L20)):*
> ```objc
> //
> // Desc: OctoMap for 3D AMCL
> // Author: Tyler Buchman (tyler_buchman@jabil.com)
> ```

I think we can just have you listed in one place, in package.xml.
___
*[include/amcl/map/octomap.h, line 43 at r3](https://reviewable.io/reviews/badgertechnologies/amcl/2#-LzIDvMA2h2LkfLRXUGv:-LzIDvMA2h2LkfLRXUGw:b-4mskpb) ([raw file](https://github.com/badgertechnologies/amcl/blob/770d4c63beb80b8977948e006adb7bdbc3c1d735/include/amcl/map/octomap.h#L43)):*
> ```objc
> public:
>   OctoMap(bool wait_for_occupancy_map);
>   ~OctoMap(){};
> ```

if the destructor isn't going to do anything, there is little point in declaring one, you can just use the default


<!-- Sent from Reviewable.io -->

2020-01-23 16:30 UTC, c-andy-martin requested changes
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/amcl/2)* status: 6 of 48 files reviewed, 43 unresolved discussions (waiting on @12tbuchman)

___
*[include/amcl/map/map.h, line 39 at r3](https://reviewable.io/reviews/badgertechnologies/amcl/2#-LzIE4XhC9vxHQQwBWyT:-LzIE4XhC9vxHQQwBWyU:beidmek) ([raw file](https://github.com/badgertechnologies/amcl/blob/770d4c63beb80b8977948e006adb7bdbc3c1d735/include/amcl/map/map.h#L39)):*
> ```objc
> public:
>   Map();
>   ~Map();
> ```

Oh, you should make this destructor `virtual`. Anytime you have a class with virtual methods you should do that. Otherwise, destruction can be broken when destroying from a base pointer to a derived class.


<!-- Sent from Reviewable.io -->

2020-01-23 16:45 UTC, c-andy-martin commented
___
*[include/amcl/map/octomap.h, line 131 at r3](https://reviewable.io/reviews/badgertechnologies/amcl/2#-LzIHFe74dPccxQ9nB1a:-LzIHFe74dPccxQ9nB1b:b-g40d26) ([raw file](https://github.com/badgertechnologies/amcl/blob/770d4c63beb80b8977948e006adb7bdbc3c1d735/include/amcl/map/octomap.h#L131)):*
> ```objc
>   std::vector<double> map_min_bounds_, map_max_bounds_;
>   std::vector<int> cropped_min_cells_, cropped_max_cells_, full_cells_;
>   double lidar_height_;
> ```

this looks unused, get rid of it, and all references to lidar height, as the data should be transformed from the sensor frame in the input cloud to whatever frame the map is in outside of this code. also remove the parameter "point_cloud_scanner_height", and all related variables elsewhere (Such as in point_cloud_scanner) as I don't think its necessary or being used anywhere


<!-- Sent from Reviewable.io -->

2020-01-23 16:45 UTC, c-andy-martin requested changes
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/amcl/2)* status: 6 of 48 files reviewed, 51 unresolved discussions (waiting on @12tbuchman)

___
*[include/amcl/map/octomap.h, line 64 at r3](https://reviewable.io/reviews/badgertechnologies/amcl/2#-LzIEpBIBgrD7XPaTRBq:-LzIEpBJ6D0kC_WUPhv6:baevt6g) ([raw file](https://github.com/badgertechnologies/amcl/blob/770d4c63beb80b8977948e006adb7bdbc3c1d735/include/amcl/map/octomap.h#L64)):*
> ```objc
> 
> private:
>   const double EPSILON_DOUBLE = std::numeric_limits<double>::epsilon();
> ```

this should be `static constexpr double` so you don't store the value in your object and you ensure its evaluated at compile time. Also, I think it would be fine to just call this EPSILON to avoid having to type more letters, and to make the code more compact, since you don't have any other epsilon
___
*[include/amcl/map/octomap.h, line 67 at r3](https://reviewable.io/reviews/badgertechnologies/amcl/2#-LzIFaJu7n8X4sxlRSR-:-LzIFaJu7n8X4sxlRSR0:b-j81ybi) ([raw file](https://github.com/badgertechnologies/amcl/blob/770d4c63beb80b8977948e006adb7bdbc3c1d735/include/amcl/map/octomap.h#L67)):*
> ```objc
>   struct CellData
>   {
>     OctoMap* octoMap;
> ```

this should be an `OctoMap&`, and should be named following the `under_scored` convention as `octo_map` or more simply maybe `octomap`. You'll need to alter the code everywhere to use reference notation instead of pointer notation.
___
*[include/amcl/map/octomap.h, line 68 at r3](https://reviewable.io/reviews/badgertechnologies/amcl/2#-LzIFz-V8ux_n0OdHvI-:-LzIFz-V8ux_n0OdHvI0:b27c3h0) ([raw file](https://github.com/badgertechnologies/amcl/blob/770d4c63beb80b8977948e006adb7bdbc3c1d735/include/amcl/map/octomap.h#L68)):*
> ```objc
>   {
>     OctoMap* octoMap;
>     CellData(OctoMap& _octoMap) : octoMap(&_octoMap)
> ```

I prefer not using leading `_`, just call this something else (`o` is fine or `octo_map_arg` or `new_octo_map` or anything, but should use under_scores as an argument name)
___
*[include/amcl/map/octomap.h, line 71 at r3](https://reviewable.io/reviews/badgertechnologies/amcl/2#-LzIFmF19DfTvXJ3kyF2:-LzIFmF19DfTvXJ3kyF3:b-n77xvs) ([raw file](https://github.com/badgertechnologies/amcl/blob/770d4c63beb80b8977948e006adb7bdbc3c1d735/include/amcl/map/octomap.h#L71)):*
> ```objc
>     {
>     }
>     int i_, j_, k_;
> ```

these don't need to end in `_` since they are public members
___
*[include/amcl/map/octomap.h, line 78 at r3](https://reviewable.io/reviews/badgertechnologies/amcl/2#-LzIGGmABa2VmvySBBqG:-LzIGGmABa2VmvySBBqH:b-1e5ony) ([raw file](https://github.com/badgertechnologies/amcl/blob/770d4c63beb80b8977948e006adb7bdbc3c1d735/include/amcl/map/octomap.h#L78)):*
> ```objc
>   {
>   public:
>     double*** distances_;
> ```

yuck. any reason to not use an octomap to store these distances? Or is this where we are putting the hash table? There is no reason to not just make this a vector of vector of vectors similar as I suggested on the occupancy_map.h
___
*[include/amcl/map/octomap.h, line 101 at r3](https://reviewable.io/reviews/badgertechnologies/amcl/2#-LzIGapN5ZZWh9pkH7S9:-LzIGapN5ZZWh9pkH7SA:b-hrgyp6) ([raw file](https://github.com/badgertechnologies/amcl/blob/770d4c63beb80b8977948e006adb7bdbc3c1d735/include/amcl/map/octomap.h#L101)):*
> ```objc
>     }
> 
>     ~CachedDistanceMap()
> ```

if you directly use vector or any other data type (because there is no need to make them dynamic) the destructor can just be empty
___
*[include/amcl/map/octomap.h, line 122 at r3](https://reviewable.io/reviews/badgertechnologies/amcl/2#-LzIHmBZ4t5W3ia1LbkH:-LzIHmBZ4t5W3ia1LbkI:bsz4vw7) ([raw file](https://github.com/badgertechnologies/amcl/blob/770d4c63beb80b8977948e006adb7bdbc3c1d735/include/amcl/map/octomap.h#L122)):*
> ```objc
>   unsigned int computeCellIndex(int i, int j, int k);
> 
>   friend bool operator<(const OctoMap::CellData& a, const OctoMap::CellData& b);
> ```

same idea as in occupancy_grid, make this a member of CachedDistanceMap and define it inline w/ the declaration


<!-- Sent from Reviewable.io -->

2020-01-23 16:48 UTC, c-andy-martin commented
___
*[src/amcl/sensors/point_cloud_scanner.cpp, line 40 at r3](https://reviewable.io/reviews/badgertechnologies/amcl/2#-LzII5Sb2nEmgqxWlmSh:-LzII5Sb2nEmgqxWlmSi:bweweel) ([raw file](https://github.com/badgertechnologies/amcl/blob/770d4c63beb80b8977948e006adb7bdbc3c1d735/src/amcl/sensors/point_cloud_scanner.cpp#L40)):*
> ```cpp
> PointCloudScanner::PointCloudScanner() : Sensor()
> {
>   this->max_beams_ = 0;
> ```

I would not use `this->` as its redundant and adds extra code. The benefit of following the naming convention w/ the trailing under score is that indicates to the reader that it is a member variable. I would remove `this->` from all your code except where absolutely necessary (which is typically only when using inheritance or templates or to disambiguate duplicate names, none of which should apply here I think)


<!-- Sent from Reviewable.io -->

2020-01-23 16:49 UTC, c-andy-martin commented
___
*[include/amcl/node/node.h, line 73 at r3](https://reviewable.io/reviews/badgertechnologies/amcl/2#-LzIIe3a7mF7o479g9cx:-LzIIe3a7mF7o479g9cy:btv2bfi) ([raw file](https://github.com/badgertechnologies/amcl/blob/770d4c63beb80b8977948e006adb7bdbc3c1d735/include/amcl/node/node.h#L73)):*
> ```objc
> {
> // Pose hypothesis
> typedef struct
> ```

There is no need to use typdef here in C++, this is a vestige from C. Just make this `struct PoseHypothesis`. Get rid of the comment above as it becomes redundant, and try not to use AMCL in names since you are already in the amcl namespace.


<!-- Sent from Reviewable.io -->

2020-01-23 16:55 UTC, c-andy-martin commented
___
*[include/amcl/node/node.h, line 106 at r3](https://reviewable.io/reviews/badgertechnologies/amcl/2#-LzIJylU1tigU08JSpqr:-LzIJylU1tigU08JSpqs:b-eanqz8) ([raw file](https://github.com/badgertechnologies/amcl/blob/770d4c63beb80b8977948e006adb7bdbc3c1d735/include/amcl/node/node.h#L106)):*
> ```objc
>   };
> 
>   const int INDEX_XX_ = 6 * 0 + 0;
> ```

constants in the class should be `static constexpr` and should not end in `_`.


<!-- Sent from Reviewable.io -->

2020-01-23 16:58 UTC, c-andy-martin requested changes
> Reviewed 1 of 32 files at r3.
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/amcl/2)* status: 7 of 48 files reviewed, 57 unresolved discussions (waiting on @12tbuchman)

___
*[include/amcl/node/node.h, line 79 at r3](https://reviewable.io/reviews/badgertechnologies/amcl/2#-LzIJKcz3-A8-JXu9u50:-LzIIxYm9llmR2qAE6Az:b-g89tw7) ([raw file](https://github.com/badgertechnologies/amcl/blob/770d4c63beb80b8977948e006adb7bdbc3c1d735/include/amcl/node/node.h#L79)):*
> ```objc
> 
>   // Mean of pose esimate
>   PFVector pf_pose_mean;
> ```

Maybe this should just be named `mean` as the struct is already a `PoseHypothesis`. In which case, the below could just be `covariance` (cov is too dense for me). Not sure the comments on these two add much value. I'm also OK w/ `pose_mean` or just `pose` depending on which makes the most sense. I don't think the `pf_` prefix is necessary.
___
*[include/amcl/node/node.h, line 110 at r3](https://reviewable.io/reviews/badgertechnologies/amcl/2#-LzIK7vO-8X82SIDA7q4:-LzIK7vO-8X82SIDA7q5:b-worgj6) ([raw file](https://github.com/badgertechnologies/amcl/blob/770d4c63beb80b8977948e006adb7bdbc3c1d735/include/amcl/node/node.h#L110)):*
> ```objc
>   const int INDEX_AA_ = 6 * 5 + 5;
> 
>   static PFVector uniformPoseGenerator(Node* arg);
> ```

this should not be static, and then get rid of arg, and just access the members directly, and the name should become `generateUniformPose`
___
*[include/amcl/node/node.h, line 111 at r3](https://reviewable.io/reviews/badgertechnologies/amcl/2#-LzIKIvdBZ1AqRF8ctdb:-LzIKIvdBZ1AqRF8ctdc:b-l4ao5v) ([raw file](https://github.com/badgertechnologies/amcl/blob/770d4c63beb80b8977948e006adb7bdbc3c1d735/include/amcl/node/node.h#L111)):*
> ```objc
> 
>   static PFVector uniformPoseGenerator(Node* arg);
>   static std::vector<std::pair<int, int> > free_space_indices_;
> ```

this must not be static, as if we ever had two instances of the node, they would share this variable, and they should not.


<!-- Sent from Reviewable.io -->

2020-01-23 17:51 UTC, c-andy-martin commented
___
*[include/amcl/node/node.h, line 114 at r3](https://reviewable.io/reviews/badgertechnologies/amcl/2#-LzIVy3B9QbYBraIWAf_:-LzIVy3B9QbYBraIWAfa:b-656i2g) ([raw file](https://github.com/badgertechnologies/amcl/blob/770d4c63beb80b8977948e006adb7bdbc3c1d735/include/amcl/node/node.h#L114)):*
> ```objc
> 
>   void init2D();
>   void init3D();
> ```

OK, so this is a bigger ask, and I'm not sure yet all the implications for your code. But, I'd much rather see three different objects here in 3 headers, one just called Node, which defines whatever abstract APIs nodes share in common (like scorePose, init, etc.). Then have a Node2DMap and Node3DMap (or maybe just Node2D and Node3D) that implement those apis for the 2 cases. Then, I would have the main.cpp read the map_type parameter, and then instantiate either Node2D or Node3D based on the parameter.

This fits an object oriented model better, will result in more readable and maintainable code, provide a path to add a Node3DLocalizer someday if you wanted to add a sub class that tracks all 6 dof in the particle filter, reduce the duplication of names like scorePose scorePose2D scorePose3D.


<!-- Sent from Reviewable.io -->

2020-01-23 18:21 UTC, c-andy-martin commented
___
*[cfg/AMCL.cfg, line 48 at r3](https://reviewable.io/reviews/badgertechnologies/amcl/2#-LzIc_YuEpV9EO68IJYB:-LzIc_YuEpV9EO68IJYC:b-lsb9ef) ([raw file](https://github.com/badgertechnologies/amcl/blob/8a8873533e84b3894a5f385b1d56234ebbe31d7e/cfg/AMCL.cfg#L48)):*
> ```INI
> 
> # Laser Model Parameters
> gen.add("laser_min_range", double_t, 0, "Minimum scan range to be considered; -1.0 will cause the laser's reported minimum range to be used.", -1, -1, 1000)
> ```

Thinking about these changes. If we want others to adopt our fork of AMCL it will be much easier if we do not change the name of existing parameters. Could we just keep these as `laser_*`? Also, why not use the same parameter names to control both the 2D and 3D matching processes where appropriate instead of having a dupilcate version of the parameter?


<!-- Sent from Reviewable.io -->

2020-01-23 18:53 UTC, 12tbuchman reviewed
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/amcl/2)* status: 7 of 48 files reviewed, 59 unresolved discussions (waiting on @12tbuchman and @c-andy-martin)

___
*[package.xml, line 24 at r2](https://reviewable.io/reviews/badgertechnologies/amcl/2#-LzDIn3o0ZRRiEm3VhL9:-LzIk0Gh3ERXJ8N3r26R:b-bwv3yk) ([raw file](https://github.com/badgertechnologies/amcl/blob/bbbafd470c81f3bf418c310bd0334bc4469d4b08/package.xml#L24)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

as before, I don't want jabil.com if we can help it. If you can't get a badger-tech, maybe just list me as the maintainer? This repo is public, and I think our public persona should be Badger
</blockquote></details>

Still waiting on Brian's reply. Lets hold off on deciding what to do until we find out if I will get a Badger email or not.


<!-- Sent from Reviewable.io -->

2020-01-23 19:10 UTC, 12tbuchman reviewed
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/amcl/2)* status: 6 of 48 files reviewed, 59 unresolved discussions (waiting on @12tbuchman and @c-andy-martin)

___
*[package.xml, line 3 at r2](https://reviewable.io/reviews/badgertechnologies/amcl/2#-LzDI_er8uzxeyktRv8I:-LzIo6yW9gfnnUKQHGiv:b-896fix) ([raw file](https://github.com/badgertechnologies/amcl/blob/bbbafd470c81f3bf418c310bd0334bc4469d4b08/package.xml#L3)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

It doesn't make sense to go backwards on the version number. If anything, you can bump the major version to 2, maybe make this `2.0.0`.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-01-23 19:40 UTC, 12tbuchman reviewed
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/amcl/2)* status: 6 of 48 files reviewed, 59 unresolved discussions (waiting on @12tbuchman and @c-andy-martin)

___
*[include/amcl/map/map.h, line 48 at r2](https://reviewable.io/reviews/badgertechnologies/amcl/2#-LzDK49B2O9CHzy9lF5g:-LzIrut6E94yPSFnsvbz:bwderh6) ([raw file](https://github.com/badgertechnologies/amcl/blob/bbbafd470c81f3bf418c310bd0334bc4469d4b08/include/amcl/map/map.h#L48)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

I typically pass complex objects, like `std::vector` by const-reference as inputs to save copies
</blockquote></details>

Done. Will be in next push.
___
*[include/amcl/map/map.h, line 49 at r2](https://reviewable.io/reviews/badgertechnologies/amcl/2#-LzDhdEdBAUp9VnHF9p8:-LzItfyS1hwK0jlcy6g_:b-ouorxu) ([raw file](https://github.com/badgertechnologies/amcl/blob/bbbafd470c81f3bf418c310bd0334bc4469d4b08/include/amcl/map/map.h#L49)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

Actually, I don't really care which way you do this too much, and you probably are getting the size in cells from the map itself, so I'm OK leaving this.
</blockquote></details>

I think we should have both maybe. It is unclear to say "getSize" and refer to the pixels, where as "getOrigin" refers to meters. Of course you can look at the return value but imo the function name should be clear.
Looking at usage, the getSize function is called once in the 2d code to refer to pixels and once to refer to meters. In the 3d code it is called once to refer to meters and not called to refer to pixels. In cases where it is called to refer to meters the returned value of pixels is sent back to the map in the convertMapToWorld function, thus effectively returning the map size in meters. Instead I could make a "getMapSize" and "getWorldSize" function in 2d and just a "getWorldSize" function in 3d, and the base map class can either require the "getWorldSize" or not require this function at all. What do you think?
___
*[include/amcl/map/map.h, line 39 at r3](https://reviewable.io/reviews/badgertechnologies/amcl/2#-LzIE4XhC9vxHQQwBWyT:-LzIphlv3sCZFFuDaGOz:bwderh6) ([raw file](https://github.com/badgertechnologies/amcl/blob/770d4c63beb80b8977948e006adb7bdbc3c1d735/include/amcl/map/map.h#L39)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

Oh, you should make this destructor `virtual`. Anytime you have a class with virtual methods you should do that. Otherwise, destruction can be broken when destroying from a base pointer to a derived class.
</blockquote></details>

Done. Will be in next push.


<!-- Sent from Reviewable.io -->

2020-01-23 20:53 UTC, 12tbuchman reviewed
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/amcl/2)* status: 6 of 48 files reviewed, 59 unresolved discussions (waiting on @12tbuchman and @c-andy-martin)

___
*[include/amcl/map/map.h, line 51 at r2](https://reviewable.io/reviews/badgertechnologies/amcl/2#-LzDKBEKBEjljFN1nK2Y:-LzJAGLh2keLzZ8_e1qd:bk58dt0) ([raw file](https://github.com/badgertechnologies/amcl/blob/bbbafd470c81f3bf418c310bd0334bc4469d4b08/include/amcl/map/map.h#L51)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

3 things:
1) I'd pass this by const-reference
2) the name should not start w/ an underscore.
3) In general, it would be more efficient to not use std::vector for coordinates, and just have the 2D version ignore the z value. I'd recommend using pcl::PointXYZ since we are already depending on PCL, but I wouldn't use it directly, I'd define a new amcl::Point in some header, under the amcl namespace:
```
using Point = pcl::PointXYZ;
```
Then instead of passing `const std::vector<double>&` I would pass `const Point&`
</blockquote></details>

Looking again at my implementation, for 2D I am storing the origin as double values, and for 3D I am storing the origin as a vector of double values. This is inconsistent and I should probably pick something and use it for both. Would you recommend introducing the pcl Point over using double values (origin_x_, origin_y_, origin_z)?


<!-- Sent from Reviewable.io -->

2020-01-23 20:55 UTC, 12tbuchman reviewed
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/amcl/2)* status: 6 of 48 files reviewed, 60 unresolved discussions (waiting on @12tbuchman and @c-andy-martin)

___
*[include/amcl/map/map.h, line 47 at r3](https://reviewable.io/reviews/badgertechnologies/amcl/2#-LzJAoWRB6emabjaeVTy:-LzJAoWRB6emabjaeVTz:brsywgz) ([raw file](https://github.com/badgertechnologies/amcl/blob/770d4c63beb80b8977948e006adb7bdbc3c1d735/include/amcl/map/map.h#L47)):*
> ```objc
>   virtual bool isValid(std::vector<int> coords) = 0;
>   virtual std::vector<int> getSize() = 0;
>   virtual std::vector<double> getOrigin() = 0;
> ```

Going off your other comments, should I return the size and origin by reference or value?


<!-- Sent from Reviewable.io -->

2020-01-23 21:08 UTC, 12tbuchman reviewed
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/amcl/2)* status: 6 of 48 files reviewed, 60 unresolved discussions (waiting on @12tbuchman and @c-andy-martin)

___
*[include/amcl/map/map.h, line 53 at r2](https://reviewable.io/reviews/badgertechnologies/amcl/2#-LzDhL9y9aGnzNBJdOPr:-LzJDy9H4hhVFMZOmlP4:b-27v1gr) ([raw file](https://github.com/badgertechnologies/amcl/blob/bbbafd470c81f3bf418c310bd0334bc4469d4b08/include/amcl/map/map.h#L53)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

"Scale" makes less sense to me than "Resolution". Was scale their old term for it? Would it be OK to rename Scale => Resolution?
</blockquote></details>

Done. Will be in next push.

I have the getter method, but it is never actually used. Should this be kept in or should I remove it until the future if someone actually needed it they could add it back in?
___
*[include/amcl/map/map.h, line 49 at r3](https://reviewable.io/reviews/badgertechnologies/amcl/2#-LzDirgY1Yd9Kc-mo8FV:-LzJAyTPBerqxycRSNTr:bw0qxq0) ([raw file](https://github.com/badgertechnologies/amcl/blob/770d4c63beb80b8977948e006adb7bdbc3c1d735/include/amcl/map/map.h#L49)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

I would make every method of this class virtual, not just the pure-virtual ones. This way, children can override behavior (such as re-allocating an octomap w/ the correct resolution on a resolution change).
</blockquote></details>

Done, will be in next push.


<!-- Sent from Reviewable.io -->

2020-01-23 21:21 UTC, 12tbuchman reviewed
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/amcl/2)* status: 6 of 48 files reviewed, 60 unresolved discussions (waiting on @12tbuchman and @c-andy-martin)

___
*[include/amcl/map/map.h, line 54 at r2](https://reviewable.io/reviews/badgertechnologies/amcl/2#-LzDLygc-cvwg4j0ODEP:-LzJEFlzCr3Dy5_JtPHa:bw0qxq0) ([raw file](https://github.com/badgertechnologies/amcl/blob/bbbafd470c81f3bf418c310bd0334bc4469d4b08/include/amcl/map/map.h#L54)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

again, do not start argument w/ an underscore
</blockquote></details>

Done, will be in next push.
___
*[include/amcl/map/map.h, line 61 at r2](https://reviewable.io/reviews/badgertechnologies/amcl/2#-LzDMCKxDJJJb4ug2HBF:-LzJGtv5AhfxkWHU9Dxk:bx3unnn) ([raw file](https://github.com/badgertechnologies/amcl/blob/bbbafd470c81f3bf418c310bd0334bc4469d4b08/include/amcl/map/map.h#L61)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

while not explicit in the ROS CPP style guide, in the google c++ style guide its based on they always end a namespace w/ a comment (separated by two white spaces, as the guide suggests for inline comments):
```
};  // namespace amcl
</blockquote></details>

Done, for all .h files, will be published in next push


<!-- Sent from Reviewable.io -->

2020-01-23 21:30 UTC, 12tbuchman reviewed
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/amcl/2)* status: 6 of 48 files reviewed, 60 unresolved discussions (waiting on @12tbuchman and @c-andy-martin)

___
*[include/amcl/map/map.h, line 65 at r2](https://reviewable.io/reviews/badgertechnologies/amcl/2#-LzDMbLw8BTa3EPUE2Tt:-LzJIwZPCvpS6V2Q32Zs:b6kjva7) ([raw file](https://github.com/badgertechnologies/amcl/blob/bbbafd470c81f3bf418c310bd0334bc4469d4b08/include/amcl/map/map.h#L65)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

while not explicit in the ROS CPP style guide, in the google c++ style guide its based on they always end a macro guard w/ a comment (separated by two white spaces, as the guide suggests for inline comments):
```
#endif  // AMCL_MAP_H
```
</blockquote></details>

Done, for all .h files. Will be in next push.


<!-- Sent from Reviewable.io -->

2020-01-23 21:36 UTC, 12tbuchman reviewed
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/amcl/2)* status: 6 of 48 files reviewed, 60 unresolved discussions (waiting on @12tbuchman and @c-andy-martin)

___
*[include/amcl/map/occupancy_map.h, line 2 at r2](https://reviewable.io/reviews/badgertechnologies/amcl/2#-LzDfQjg1dyDxxey3m_b:-LzJKHj53Vu-jkozTgya:bf8bfwq) ([raw file](https://github.com/badgertechnologies/amcl/blob/bbbafd470c81f3bf418c310bd0334bc4469d4b08/include/amcl/map/occupancy_map.h#L2)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

Let's get rid of all the references to Player which is very obsolete (more than 12 years old). Keep the copyright and authorship, but we don't have to mention the player robot server anywhere.
</blockquote></details>

Done, for all files. Will be in the next push.


<!-- Sent from Reviewable.io -->

2020-01-23 21:37 UTC, 12tbuchman reviewed
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/amcl/2)* status: 6 of 48 files reviewed, 60 unresolved discussions (waiting on @12tbuchman and @c-andy-martin)

___
*[include/amcl/map/occupancy_map.h, line 24 at r2](https://reviewable.io/reviews/badgertechnologies/amcl/2#-LzDfbH93_CR3EQnC6pc:-LzJKQmp9fAr8eey9Q1e:b-6h99jm) ([raw file](https://github.com/badgertechnologies/amcl/blob/bbbafd470c81f3bf418c310bd0334bc4469d4b08/include/amcl/map/occupancy_map.h#L24)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

Let's leave maintainer out of source files. However, feel free to add yourself as another author, as you have (re) authored most of this. And as before, I prefer a badger-technologies.com email here for consistency of communication to the world.
</blockquote></details>

As I mentioned before, Ill leave the Jabil email at least until we hear from Brian Lee and / or Bryan Ethington regarding the Badger email. So you prefer that I list myself as an author over listing myself as the maintainer?


<!-- Sent from Reviewable.io -->

2020-01-23 21:41 UTC, 12tbuchman reviewed
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/amcl/2)* status: 6 of 48 files reviewed, 60 unresolved discussions (waiting on @12tbuchman and @c-andy-martin)

___
*[include/amcl/map/occupancy_map.h, line 33 at r2](https://reviewable.io/reviews/badgertechnologies/amcl/2#-LzDg0kP8nS6GFpgpHpM:-LzJLFm7Eq6BnbPDp4ab:b-f3102) ([raw file](https://github.com/badgertechnologies/amcl/blob/bbbafd470c81f3bf418c310bd0334bc4469d4b08/include/amcl/map/occupancy_map.h#L33)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

I don't think you need a vertical white-space here as these are still standard headers.
</blockquote></details>

Going off of the Google C++ Style Guide, https://google.github.io/styleguide/cppguide.html#Names_and_Order_of_Includes
all c system headers and c++ system headers should be separated by a blank line.


<!-- Sent from Reviewable.io -->

2020-01-23 22:41 UTC, 12tbuchman reviewed
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/amcl/2)* status: 6 of 48 files reviewed, 60 unresolved discussions (waiting on @12tbuchman and @c-andy-martin)

___
*[include/amcl/map/occupancy_map.h, line 51 at r2](https://reviewable.io/reviews/badgertechnologies/amcl/2#-LzD_brb6RAOCcP-Oogl:-LzJQR8M82TQBQWDKyA1:b-896fix) ([raw file](https://github.com/badgertechnologies/amcl/blob/bbbafd470c81f3bf418c310bd0334bc4469d4b08/include/amcl/map/occupancy_map.h#L51)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

same comment on spacing as `map.h`, please fix it everywhere, I won't comment again to not have a bunch of comments on the same issue
</blockquote></details>

Done.
___
*[include/amcl/map/occupancy_map.h, line 53 at r2](https://reviewable.io/reviews/badgertechnologies/amcl/2#-LzDgDfk7cnU4Gwm0Gqx:-LzJQVQx5XDDb09IlJdc:bhrx43k) ([raw file](https://github.com/badgertechnologies/amcl/blob/bbbafd470c81f3bf418c310bd0334bc4469d4b08/include/amcl/map/occupancy_map.h#L53)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

I would prefer to mark this and all other public methods virtual, since the parent class is a pure virtual class.
</blockquote></details>

https://google.github.io/styleguide/cppguide.html#Names_and_Order_of_Includes
According to the Google C++ Style Guide I should list these functions explicitly as "Override" or "Final", but should specifically not list it as "Virtual". We can discuss this more in person.


<!-- Sent from Reviewable.io -->

2020-01-23 22:41 UTC, 12tbuchman reviewed
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/amcl/2)* status: 6 of 48 files reviewed, 60 unresolved discussions (waiting on @12tbuchman and @c-andy-martin)

___
*[include/amcl/map/occupancy_map.h, line 53 at r2](https://reviewable.io/reviews/badgertechnologies/amcl/2#-LzDgDfk7cnU4Gwm0Gqx:-LzJZMDl8npKRbZobyDI:b-r8ygms) ([raw file](https://github.com/badgertechnologies/amcl/blob/bbbafd470c81f3bf418c310bd0334bc4469d4b08/include/amcl/map/occupancy_map.h#L53)):*
<details><summary><i>Previously, 12tbuchman (Tyler Buchman) wrote…</i></summary><blockquote>

https://google.github.io/styleguide/cppguide.html#Names_and_Order_of_Includes
According to the Google C++ Style Guide I should list these functions explicitly as "Override" or "Final", but should specifically not list it as "Virtual". We can discuss this more in person.
</blockquote></details>

Wrong link, here is the correct one: https://google.github.io/styleguide/cppguide.html#Inheritance


<!-- Sent from Reviewable.io -->

2020-01-23 22:47 UTC, 12tbuchman reviewed
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/amcl/2)* status: 6 of 48 files reviewed, 60 unresolved discussions (waiting on @12tbuchman and @c-andy-martin)

___
*[include/amcl/map/occupancy_map.h, line 79 at r3](https://reviewable.io/reviews/badgertechnologies/amcl/2#-LzDoBmg9ktNWj9KM2yj:-LzJ_UrgBdO8gSySsI-l:b-715zt) ([raw file](https://github.com/badgertechnologies/amcl/blob/770d4c63beb80b8977948e006adb7bdbc3c1d735/include/amcl/map/occupancy_map.h#L79)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

I'd either make this end in underscore, or not have `i_`, `J_` etc. end in underscores, its OK for public member variables to not end in an underscore.
</blockquote></details>

Thanks, I overlooked this. I have changed this for both Map types. Let me know what you think of the changes. They will be in the next push.


<!-- Sent from Reviewable.io -->

2020-01-23 22:47 UTC, 12tbuchman reviewed
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/amcl/2)* status: 6 of 48 files reviewed, 60 unresolved discussions (waiting on @12tbuchman and @c-andy-martin)

___
*[include/amcl/map/occupancy_map.h, line 80 at r3](https://reviewable.io/reviews/badgertechnologies/amcl/2#-LzDo77YCrDTG6g8JVin:-LzJ_dN9DQ5kmQDDnTC9:byr4ffv) ([raw file](https://github.com/badgertechnologies/amcl/blob/770d4c63beb80b8977948e006adb7bdbc3c1d735/include/amcl/map/occupancy_map.h#L80)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

I'd prefer not using underscores at beginning, and just pick a different name (I'm fine w/ just `o`, or `map`, or `newOccMap`, etc.)
</blockquote></details>

see above


<!-- Sent from Reviewable.io -->

2020-01-23 22:51 UTC, 12tbuchman reviewed
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/amcl/2)* status: 6 of 48 files reviewed, 60 unresolved discussions (waiting on @12tbuchman and @c-andy-martin)

___
*[include/amcl/map/occupancy_map.h, line 83 at r3](https://reviewable.io/reviews/badgertechnologies/amcl/2#-LzDo15I15B7YGpji4yJ:-LzJa50JEW9MGj3DTfHq:bzbyf8g) ([raw file](https://github.com/badgertechnologies/amcl/blob/770d4c63beb80b8977948e006adb7bdbc3c1d735/include/amcl/map/occupancy_map.h#L83)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

you don't have to use trailing underscores on public members of a struct or class. I think its OK to do so, but not required.
</blockquote></details>

https://google.github.io/styleguide/cppguide.html#Variable_Names
http://wiki.ros.org/CppStyleGuide#Variables
Members of structs shouldnt have trailing underscores, so I will correct this. I dont see anything about an exception for public members.


<!-- Sent from Reviewable.io -->

2020-01-23 23:08 UTC, 12tbuchman reviewed
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/amcl/2)* status: 6 of 48 files reviewed, 60 unresolved discussions (waiting on @12tbuchman and @c-andy-martin)

___
*[include/amcl/map/occupancy_map.h, line 90 at r3](https://reviewable.io/reviews/badgertechnologies/amcl/2#-LzDoarvDVlMEKvkSvjK:-LzJeHZR-_ZUo7hKJPCU:b-yuq2ax) ([raw file](https://github.com/badgertechnologies/amcl/blob/770d4c63beb80b8977948e006adb7bdbc3c1d735/include/amcl/map/occupancy_map.h#L90)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

do these member variables need to be public? if not, move them into protected space
</blockquote></details>

If I move them to protected or private, I would need to write setter/getter methods. Do you think that is necessary?


<!-- Sent from Reviewable.io -->

2020-01-23 23:16 UTC, 12tbuchman reviewed
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/amcl/2)* status: 6 of 48 files reviewed, 60 unresolved discussions (waiting on @12tbuchman and @c-andy-martin)

___
*[include/amcl/map/occupancy_map.h, line 90 at r3](https://reviewable.io/reviews/badgertechnologies/amcl/2#-LzDozUt8UOX4pQy-YVv:-LzJgHxO2LMsWSMUskIv:b-w7dw47) ([raw file](https://github.com/badgertechnologies/amcl/blob/770d4c63beb80b8977948e006adb7bdbc3c1d735/include/amcl/map/occupancy_map.h#L90)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

I would make `distances_` a member `std::vector<std::vector<double>>`.
</blockquote></details>

Done. Will be in the next push.


<!-- Sent from Reviewable.io -->

2020-01-23 23:19 UTC, 12tbuchman reviewed
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/amcl/2)* status: 6 of 48 files reviewed, 60 unresolved discussions (waiting on @12tbuchman and @c-andy-martin)

___
*[include/amcl/map/occupancy_map.h, line 95 at r3](https://reviewable.io/reviews/badgertechnologies/amcl/2#-LzDpSQ35WFzZKOEPaBb:-LzJgcxt1rCGRkeAySic:b-w7dw47) ([raw file](https://github.com/badgertechnologies/amcl/blob/770d4c63beb80b8977948e006adb7bdbc3c1d735/include/amcl/map/occupancy_map.h#L95)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

again, I prefer `resolution` over `scale`, if thats ok
</blockquote></details>

Done. Will be in the next push.
___
*[include/amcl/map/occupancy_map.h, line 98 at r3](https://reviewable.io/reviews/badgertechnologies/amcl/2#-LzDp7QZC6uIuWgiatIc:-LzJghrD-yVdcaPrjmtd:b-w7dw47) ([raw file](https://github.com/badgertechnologies/amcl/blob/770d4c63beb80b8977948e006adb7bdbc3c1d735/include/amcl/map/occupancy_map.h#L98)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

if you follow my idea above, this becomes `distances_.resize(cell_radius_+2);`
</blockquote></details>

Done. Will be in the next push.
___
*[include/amcl/map/occupancy_map.h, line 101 at r3](https://reviewable.io/reviews/badgertechnologies/amcl/2#-LzDpCWVDQkGdZzdHyv8:-LzJh2d334FluUniuhV8:b-w7dw47) ([raw file](https://github.com/badgertechnologies/amcl/blob/770d4c63beb80b8977948e006adb7bdbc3c1d735/include/amcl/map/occupancy_map.h#L101)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

if you follow my idea above, this becomes `distances_[i].resize(cell_radius_+2);`
</blockquote></details>

Done. Will be in the next push.
___
*[include/amcl/map/occupancy_map.h, line 114 at r3](https://reviewable.io/reviews/badgertechnologies/amcl/2#-LzDpI3M7LuzIPWd_tb2:-LzJh4cp5Yd1VsnZhSJJ:b-w7dw47) ([raw file](https://github.com/badgertechnologies/amcl/blob/770d4c63beb80b8977948e006adb7bdbc3c1d735/include/amcl/map/occupancy_map.h#L114)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

if you follow my idea above, you don't need any of this code
</blockquote></details>

Done. Will be in the next push.


<!-- Sent from Reviewable.io -->

2020-01-23 23:20 UTC, 12tbuchman reviewed
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/amcl/2)* status: 6 of 48 files reviewed, 60 unresolved discussions (waiting on @12tbuchman and @c-andy-martin)

___
*[include/amcl/map/occupancy_map.h, line 121 at r2](https://reviewable.io/reviews/badgertechnologies/amcl/2#-LzD_NoB0B-t6EM3bMHa:-LzJhHNP56Zq2KMSuJDO:b-n9vwje) ([raw file](https://github.com/badgertechnologies/amcl/blob/bbbafd470c81f3bf418c310bd0334bc4469d4b08/include/amcl/map/occupancy_map.h#L121)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

we don't want to use tab characters. I suggest getting your editor setup to never emit tabs and to replace them with the correct shifts.
</blockquote></details>

Where are you seeing a tab character?


<!-- Sent from Reviewable.io -->

2020-01-24 00:00 UTC, 12tbuchman reviewed
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/amcl/2)* status: 6 of 48 files reviewed, 61 unresolved discussions (waiting on @12tbuchman and @c-andy-martin)

___
*[include/amcl/map/occupancy_map.h, line 123 at r3](https://reviewable.io/reviews/badgertechnologies/amcl/2#-LzDxJjy67TeH2eNSHib:-LzJpR_38F8xGhwsQrwK:b-5s5jdd) ([raw file](https://github.com/badgertechnologies/amcl/blob/770d4c63beb80b8977948e006adb7bdbc3c1d735/include/amcl/map/occupancy_map.h#L123)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

There is no reason that I can see to define the `operator<` outside the CellData struct. Instead just put `operator<` in the struct which just takes a right-hand-side, and not mess with the friend and outside the class thing. So, in the `struct CellData` just add:
```
  bool operator<(const CellData& rhs)
  {
    return occMap->getOccDist(i_, j_) > rhs.occMap->getOccDist(rhs.i_, rhs.j_);
  }
```
that *should* work the same way and be simpler to follow, and not add a new `operator<`to the `amcl::` namespace
</blockquote></details>

When I was writing this section i tried that but it gives me a build error. I may be writing it incorrectly. Lets discuss this further.


<!-- Sent from Reviewable.io -->

2020-01-24 00:06 UTC, 12tbuchman reviewed
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/amcl/2)* status: 6 of 48 files reviewed, 61 unresolved discussions (waiting on @12tbuchman and @c-andy-martin)

___
*[include/amcl/map/occupancy_map.h, line 144 at r3](https://reviewable.io/reviews/badgertechnologies/amcl/2#-LzDpb2MAkMUiBE1CHjJ:-LzJqR_GCP-jseTUikOL:bwderh6) ([raw file](https://github.com/badgertechnologies/amcl/blob/770d4c63beb80b8977948e006adb7bdbc3c1d735/include/amcl/map/occupancy_map.h#L144)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

the comment for namespace, here and everywhere.
</blockquote></details>

Done. Will be in next push.
___
*[include/amcl/map/octomap.h, line 2 at r3](https://reviewable.io/reviews/badgertechnologies/amcl/2#-LzIByu64-Qhyc5Dr2up:-LzJrc877EJ5jUsoylfX:bay17j1) ([raw file](https://github.com/badgertechnologies/amcl/blob/770d4c63beb80b8977948e006adb7bdbc3c1d735/include/amcl/map/octomap.h#L2)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

Like in map.h, there should be an assignment of copyright above the license. I suggest starting the file (and any other new ones) like this:
```
/*
 * Copyright (C) 2020 Badger Technologies, LLC
 *
 * This library is free software; you can redistribute it and/or
```
</blockquote></details>

Done. Will be in the next push. What should I do with the eig.h/cpp files? I didn't originally write them, but they didn't have a copywrite on the initial files.


<!-- Sent from Reviewable.io -->

2020-01-24 00:11 UTC, 12tbuchman reviewed
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/amcl/2)* status: 6 of 48 files reviewed, 61 unresolved discussions (waiting on @12tbuchman and @c-andy-martin)

___
*[include/amcl/map/octomap.h, line 17 at r3](https://reviewable.io/reviews/badgertechnologies/amcl/2#-LzICNRj92lvSsgJh8mB:-LzJsqUNC1-4-NvrLpFX:b-w7dw47) ([raw file](https://github.com/badgertechnologies/amcl/blob/770d4c63beb80b8977948e006adb7bdbc3c1d735/include/amcl/map/octomap.h#L17)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

I'd prefer this block comment to be in C form matching the above block comment, something like this:
```
/*
 * Octomap for 3D AMCL
 *
 * (Anything else you want to say goes here.)
 */
```
Alternatively, it may look even better to just extend the above comment, after the license text, write what the description
</blockquote></details>

Done. Will be in the next push.
___
*[include/amcl/map/octomap.h, line 20 at r3](https://reviewable.io/reviews/badgertechnologies/amcl/2#-LzIBoLq2XnmPNA7ECp7:-LzJssrnEZRewjSwu0Uk:b-b5wxnx) ([raw file](https://github.com/badgertechnologies/amcl/blob/770d4c63beb80b8977948e006adb7bdbc3c1d735/include/amcl/map/octomap.h#L20)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

I think we can just have you listed in one place, in package.xml.
</blockquote></details>

We can discuss this.


<!-- Sent from Reviewable.io -->

2020-01-24 00:25 UTC, 12tbuchman reviewed
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/amcl/2)* status: 6 of 48 files reviewed, 61 unresolved discussions (waiting on @12tbuchman and @c-andy-martin)

___
*[include/amcl/map/octomap.h, line 24 at r3](https://reviewable.io/reviews/badgertechnologies/amcl/2#-LzICoPo1XsE44V2vh2L:-LzJw2cC7FO7q370Gm05:b-w7dw47) ([raw file](https://github.com/badgertechnologies/amcl/blob/770d4c63beb80b8977948e006adb7bdbc3c1d735/include/amcl/map/octomap.h#L24)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

to follow convention, all the macro guards should really have each part of the path represented (so if you had a `amcl/other_dir/octomap.h` there would be no name conflict):
```
#ifndef AMCL_MAP_OCTOMAP_H
```
I'd check all the headers and follow this convention.
</blockquote></details>

Done. Will be in the next push.


<!-- Sent from Reviewable.io -->

2020-01-24 00:30 UTC, 12tbuchman reviewed
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/amcl/2)* status: 6 of 48 files reviewed, 61 unresolved discussions (waiting on @12tbuchman and @c-andy-martin)

___
*[include/amcl/map/octomap.h, line 27 at r3](https://reviewable.io/reviews/badgertechnologies/amcl/2#-LzID2YS1c2-S9z5rjc_:-LzJx8ge-ZJujyxkHHXn:b6qh7kd) ([raw file](https://github.com/badgertechnologies/amcl/blob/770d4c63beb80b8977948e006adb7bdbc3c1d735/include/amcl/map/octomap.h#L27)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

the header include order in the style guides says to include standard headers, then other library headers, then the local code headers, so these are all backwards. Instead, start with `<limits>` and the like, then the octomap headers, then local headers like `map.h`. For the C++ files, you are supposed to first include the header that declares the code you are about to define first, then follow the same order:

https://google.github.io/styleguide/cppguide.html#Names_and_Order_of_Includes

the clang format file can be changed to try and do this for you, but my guess is it doesn't do a perfect job. feel free to try it if you want.
</blockquote></details>

Lets discuss this.


<!-- Sent from Reviewable.io -->

2020-01-24 00:31 UTC, 12tbuchman reviewed
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/amcl/2)* status: 6 of 48 files reviewed, 61 unresolved discussions (waiting on @12tbuchman and @c-andy-martin)

___
*[include/amcl/map/octomap.h, line 43 at r3](https://reviewable.io/reviews/badgertechnologies/amcl/2#-LzIDvMA2h2LkfLRXUGv:-LzJxVrx5VyYecr60Ph_:b-w7dw47) ([raw file](https://github.com/badgertechnologies/amcl/blob/770d4c63beb80b8977948e006adb7bdbc3c1d735/include/amcl/map/octomap.h#L43)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

if the destructor isn't going to do anything, there is little point in declaring one, you can just use the default
</blockquote></details>

Done. Will be in the next push.


<!-- Sent from Reviewable.io -->

2020-01-24 00:42 UTC, 12tbuchman reviewed
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/amcl/2)* status: 6 of 48 files reviewed, 61 unresolved discussions (waiting on @12tbuchman and @c-andy-martin)

___
*[include/amcl/map/octomap.h, line 64 at r3](https://reviewable.io/reviews/badgertechnologies/amcl/2#-LzIEpBIBgrD7XPaTRBq:-LzJyX_2-S-g1hC0yr5B:b-w7dw47) ([raw file](https://github.com/badgertechnologies/amcl/blob/770d4c63beb80b8977948e006adb7bdbc3c1d735/include/amcl/map/octomap.h#L64)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

this should be `static constexpr double` so you don't store the value in your object and you ensure its evaluated at compile time. Also, I think it would be fine to just call this EPSILON to avoid having to type more letters, and to make the code more compact, since you don't have any other epsilon
</blockquote></details>

Done. Will be in the next push.
___
*[include/amcl/map/octomap.h, line 67 at r3](https://reviewable.io/reviews/badgertechnologies/amcl/2#-LzIFaJu7n8X4sxlRSR-:-LzJzxCI7JP-BsssQNFK:b-5my9sr) ([raw file](https://github.com/badgertechnologies/amcl/blob/770d4c63beb80b8977948e006adb7bdbc3c1d735/include/amcl/map/octomap.h#L67)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

this should be an `OctoMap&`, and should be named following the `under_scored` convention as `octo_map` or more simply maybe `octomap`. You'll need to alter the code everywhere to use reference notation instead of pointer notation.
</blockquote></details>

I am getting errors when I try this. Lets discuss.


<!-- Sent from Reviewable.io -->

2020-01-24 00:43 UTC, 12tbuchman reviewed
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/amcl/2)* status: 6 of 48 files reviewed, 61 unresolved discussions (waiting on @12tbuchman and @c-andy-martin)

___
*[include/amcl/map/octomap.h, line 68 at r3](https://reviewable.io/reviews/badgertechnologies/amcl/2#-LzIFz-V8ux_n0OdHvI-:-LzK-1GH91xyV5pnrdnC:b-w7dw47) ([raw file](https://github.com/badgertechnologies/amcl/blob/770d4c63beb80b8977948e006adb7bdbc3c1d735/include/amcl/map/octomap.h#L68)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

I prefer not using leading `_`, just call this something else (`o` is fine or `octo_map_arg` or `new_octo_map` or anything, but should use under_scores as an argument name)
</blockquote></details>

Done. Will be in the next push.
___
*[include/amcl/map/octomap.h, line 71 at r3](https://reviewable.io/reviews/badgertechnologies/amcl/2#-LzIFmF19DfTvXJ3kyF2:-LzK-4dH9UxHSZpuuolL:bh9a80y) ([raw file](https://github.com/badgertechnologies/amcl/blob/770d4c63beb80b8977948e006adb7bdbc3c1d735/include/amcl/map/octomap.h#L71)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

these don't need to end in `_` since they are public members
</blockquote></details>

Done. As mentioned above they don't need the _ because they are in a struct, but I am not seeing where public has an implication.


<!-- Sent from Reviewable.io -->

2020-01-24 00:45 UTC, 12tbuchman reviewed
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/amcl/2)* status: 6 of 48 files reviewed, 61 unresolved discussions (waiting on @12tbuchman and @c-andy-martin)

___
*[include/amcl/map/octomap.h, line 78 at r3](https://reviewable.io/reviews/badgertechnologies/amcl/2#-LzIGGmABa2VmvySBBqG:-LzK-Mo-8m-OnGXrBz-k:bewsoid) ([raw file](https://github.com/badgertechnologies/amcl/blob/770d4c63beb80b8977948e006adb7bdbc3c1d735/include/amcl/map/octomap.h#L78)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

yuck. any reason to not use an octomap to store these distances? Or is this where we are putting the hash table? There is no reason to not just make this a vector of vector of vectors similar as I suggested on the occupancy_map.h
</blockquote></details>

Done. I initially just derived this from the existing code because it is extremely contained and efficient, but I am fine changing it to a vector.


<!-- Sent from Reviewable.io -->

2020-01-24 00:45 UTC, 12tbuchman reviewed
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/amcl/2)* status: 6 of 48 files reviewed, 61 unresolved discussions (waiting on @12tbuchman and @c-andy-martin)

___
*[include/amcl/map/octomap.h, line 101 at r3](https://reviewable.io/reviews/badgertechnologies/amcl/2#-LzIGapN5ZZWh9pkH7S9:-LzK-cs_9KnP68xkOS13:b-w7dw47) ([raw file](https://github.com/badgertechnologies/amcl/blob/770d4c63beb80b8977948e006adb7bdbc3c1d735/include/amcl/map/octomap.h#L101)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

if you directly use vector or any other data type (because there is no need to make them dynamic) the destructor can just be empty
</blockquote></details>

Done. Will be in the next push.


<!-- Sent from Reviewable.io -->

2020-01-24 00:45 UTC, 12tbuchman reviewed
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/amcl/2)* status: 6 of 48 files reviewed, 61 unresolved discussions (waiting on @12tbuchman and @c-andy-martin)

___
*[include/amcl/map/octomap.h, line 122 at r3](https://reviewable.io/reviews/badgertechnologies/amcl/2#-LzIHmBZ4t5W3ia1LbkH:-LzK-gF57W16envalZ3T:bhuilrl) ([raw file](https://github.com/badgertechnologies/amcl/blob/770d4c63beb80b8977948e006adb7bdbc3c1d735/include/amcl/map/octomap.h#L122)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

same idea as in occupancy_grid, make this a member of CachedDistanceMap and define it inline w/ the declaration
</blockquote></details>

Lets discuss.


<!-- Sent from Reviewable.io -->

2020-01-24 00:46 UTC, 12tbuchman reviewed
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/amcl/2)* status: 6 of 48 files reviewed, 61 unresolved discussions (waiting on @12tbuchman and @c-andy-martin)

___
*[include/amcl/map/octomap.h, line 131 at r3](https://reviewable.io/reviews/badgertechnologies/amcl/2#-LzIHFe74dPccxQ9nB1a:-LzK-vG51xeki2cu_oHF:b7wesnt) ([raw file](https://github.com/badgertechnologies/amcl/blob/770d4c63beb80b8977948e006adb7bdbc3c1d735/include/amcl/map/octomap.h#L131)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

this looks unused, get rid of it, and all references to lidar height, as the data should be transformed from the sensor frame in the input cloud to whatever frame the map is in outside of this code. also remove the parameter "point_cloud_scanner_height", and all related variables elsewhere (Such as in point_cloud_scanner) as I don't think its necessary or being used anywhere
</blockquote></details>

Lets discuss. The height is being used to create the c_space.


<!-- Sent from Reviewable.io -->

2020-01-24 14:56 UTC, 12tbuchman reviewed
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/amcl/2)* status: 6 of 48 files reviewed, 61 unresolved discussions (waiting on @12tbuchman and @c-andy-martin)

___
*[include/amcl/map/occupancy_map.h, line 32 at r2](https://reviewable.io/reviews/badgertechnologies/amcl/2#-LzDfo7y8VUTNEzUSTLP:-LzN2QHbBu3D6BsgoK1Q:b-w7dw47) ([raw file](https://github.com/badgertechnologies/amcl/blob/bbbafd470c81f3bf418c310bd0334bc4469d4b08/include/amcl/map/occupancy_map.h#L32)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

I would prefer making this `<cmath>`. This may require adding `std::` in a few places, but I'd rather do that and make it explicit to avoid any potential name conflicts.
</blockquote></details>

Done. Will be in the next push.


<!-- Sent from Reviewable.io -->

2020-01-27 19:01 UTC, 12tbuchman reviewed
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/amcl/2)* status: 3 of 48 files reviewed, 61 unresolved discussions (waiting on @12tbuchman and @c-andy-martin)

___
*[include/amcl/node/node.h, line 73 at r3](https://reviewable.io/reviews/badgertechnologies/amcl/2#-LzIIe3a7mF7o479g9cx:-LzNrxzb2ZVjJRpxGsap:b84jtet) ([raw file](https://github.com/badgertechnologies/amcl/blob/770d4c63beb80b8977948e006adb7bdbc3c1d735/include/amcl/node/node.h#L73)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

There is no need to use typdef here in C++, this is a vestige from C. Just make this `struct PoseHypothesis`. Get rid of the comment above as it becomes redundant, and try not to use AMCL in names since you are already in the amcl namespace.
</blockquote></details>

Done. Will be in the next push
___
*[include/amcl/node/node.h, line 106 at r3](https://reviewable.io/reviews/badgertechnologies/amcl/2#-LzIJylU1tigU08JSpqr:-LzcN7ww-HyqA8d_i41M:b-bbaucj) ([raw file](https://github.com/badgertechnologies/amcl/blob/770d4c63beb80b8977948e006adb7bdbc3c1d735/include/amcl/node/node.h#L106)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

constants in the class should be `static constexpr` and should not end in `_`.
</blockquote></details>

for some reason im getting an error when converting these to `static constexpr int` but the EPSILON worked fine from octomap.h. Lets talk about this.


<!-- Sent from Reviewable.io -->

2020-01-27 19:14 UTC, 12tbuchman reviewed
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/amcl/2)* status: 3 of 48 files reviewed, 61 unresolved discussions (waiting on @12tbuchman and @c-andy-martin)

___
*[include/amcl/node/node.h, line 79 at r3](https://reviewable.io/reviews/badgertechnologies/amcl/2#-LzIJKcz3-A8-JXu9u50:-LzcQEvaE1xI0nkySKLC:b-w7dw47) ([raw file](https://github.com/badgertechnologies/amcl/blob/770d4c63beb80b8977948e006adb7bdbc3c1d735/include/amcl/node/node.h#L79)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

Maybe this should just be named `mean` as the struct is already a `PoseHypothesis`. In which case, the below could just be `covariance` (cov is too dense for me). Not sure the comments on these two add much value. I'm also OK w/ `pose_mean` or just `pose` depending on which makes the most sense. I don't think the `pf_` prefix is necessary.
</blockquote></details>

Done. Will be in the next push.


<!-- Sent from Reviewable.io -->

2020-01-27 19:23 UTC, 12tbuchman reviewed
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/amcl/2)* status: 3 of 48 files reviewed, 61 unresolved discussions (waiting on @12tbuchman and @c-andy-martin)

___
*[include/amcl/node/node.h, line 110 at r3](https://reviewable.io/reviews/badgertechnologies/amcl/2#-LzIK7vO-8X82SIDA7q4:-LzcSOfr4U4UlSNPRaSn:b6qh7kd) ([raw file](https://github.com/badgertechnologies/amcl/blob/770d4c63beb80b8977948e006adb7bdbc3c1d735/include/amcl/node/node.h#L110)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

this should not be static, and then get rid of arg, and just access the members directly, and the name should become `generateUniformPose`
</blockquote></details>

Lets discuss this.
___
*[include/amcl/node/node.h, line 111 at r3](https://reviewable.io/reviews/badgertechnologies/amcl/2#-LzIKIvdBZ1AqRF8ctdb:-LzcSLoj6Huy67SoiP4b:b-w7dw47) ([raw file](https://github.com/badgertechnologies/amcl/blob/770d4c63beb80b8977948e006adb7bdbc3c1d735/include/amcl/node/node.h#L111)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

this must not be static, as if we ever had two instances of the node, they would share this variable, and they should not.
</blockquote></details>

Done. Will be in the next push.


<!-- Sent from Reviewable.io -->

2020-01-27 19:26 UTC, 12tbuchman reviewed
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/amcl/2)* status: 3 of 48 files reviewed, 61 unresolved discussions (waiting on @12tbuchman and @c-andy-martin)

___
*[include/amcl/node/node.h, line 114 at r3](https://reviewable.io/reviews/badgertechnologies/amcl/2#-LzIVy3B9QbYBraIWAf_:-LzcShOY8bYswBR303Qt:b-eabc4u) ([raw file](https://github.com/badgertechnologies/amcl/blob/770d4c63beb80b8977948e006adb7bdbc3c1d735/include/amcl/node/node.h#L114)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

OK, so this is a bigger ask, and I'm not sure yet all the implications for your code. But, I'd much rather see three different objects here in 3 headers, one just called Node, which defines whatever abstract APIs nodes share in common (like scorePose, init, etc.). Then have a Node2DMap and Node3DMap (or maybe just Node2D and Node3D) that implement those apis for the 2 cases. Then, I would have the main.cpp read the map_type parameter, and then instantiate either Node2D or Node3D based on the parameter.

This fits an object oriented model better, will result in more readable and maintainable code, provide a path to add a Node3DLocalizer someday if you wanted to add a sub class that tracks all 6 dof in the particle filter, reduce the duplication of names like scorePose scorePose2D scorePose3D.
</blockquote></details>

We will likely still want to create a 2D node when we have a 3D map, though the opposite probably would not be true.


<!-- Sent from Reviewable.io -->

2020-01-27 19:34 UTC, 12tbuchman reviewed
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/amcl/2)* status: 3 of 48 files reviewed, 61 unresolved discussions (waiting on @12tbuchman and @c-andy-martin)

___
*[src/amcl/sensors/point_cloud_scanner.cpp, line 40 at r3](https://reviewable.io/reviews/badgertechnologies/amcl/2#-LzII5Sb2nEmgqxWlmSh:-LzcUmTdBVFVwXYxXTnz:b-w7dw47) ([raw file](https://github.com/badgertechnologies/amcl/blob/770d4c63beb80b8977948e006adb7bdbc3c1d735/src/amcl/sensors/point_cloud_scanner.cpp#L40)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

I would not use `this->` as its redundant and adds extra code. The benefit of following the naming convention w/ the trailing under score is that indicates to the reader that it is a member variable. I would remove `this->` from all your code except where absolutely necessary (which is typically only when using inheritance or templates or to disambiguate duplicate names, none of which should apply here I think)
</blockquote></details>

Done. Will be in the next push.


<!-- Sent from Reviewable.io -->

2020-03-03 22:16 UTC, c-andy-martin commented
___
*[include/amcl/map/map.h, line 39 at r3](https://reviewable.io/reviews/badgertechnologies/amcl/2#-LzIE4XhC9vxHQQwBWyT:-M1XT-DX1TDX5JAdMIWT:b-5uh2ib) ([raw file](https://github.com/badgertechnologies/amcl/blob/770d4c63beb80b8977948e006adb7bdbc3c1d735/include/amcl/map/map.h#L39)):*
<details><summary><i>Previously, 12tbuchman (Tyler Buchman) wrote…</i></summary><blockquote>

Done. Will be in next push.
</blockquote></details>

This still isn't fixed. I don't think removing the destructor will not make it virtual. You should make a virtual destructor that does nothing.


<!-- Sent from Reviewable.io -->

2020-03-03 22:22 UTC, c-andy-martin commented
___
*[include/amcl/map/map.h, line 51 at r2](https://reviewable.io/reviews/badgertechnologies/amcl/2#-LzDKBEKBEjljFN1nK2Y:-M1XUUYh1Rewe76i8H-6:b-y4ea4c) ([raw file](https://github.com/badgertechnologies/amcl/blob/bbbafd470c81f3bf418c310bd0334bc4469d4b08/include/amcl/map/map.h#L51)):*
<details><summary><i>Previously, 12tbuchman (Tyler Buchman) wrote…</i></summary><blockquote>

Looking again at my implementation, for 2D I am storing the origin as double values, and for 3D I am storing the origin as a vector of double values. This is inconsistent and I should probably pick something and use it for both. Would you recommend introducing the pcl Point over using double values (origin_x_, origin_y_, origin_z)?
</blockquote></details>

pcl point is sufficient and used in lots of places. I'd go for that.


<!-- Sent from Reviewable.io -->

2020-03-03 22:23 UTC, c-andy-martin commented
___
*[include/amcl/map/map.h, line 53 at r2](https://reviewable.io/reviews/badgertechnologies/amcl/2#-LzDhL9y9aGnzNBJdOPr:-M1XUjMT2GySzD-Bfn4S:b-dlovhr) ([raw file](https://github.com/badgertechnologies/amcl/blob/bbbafd470c81f3bf418c310bd0334bc4469d4b08/include/amcl/map/map.h#L53)):*
<details><summary><i>Previously, 12tbuchman (Tyler Buchman) wrote…</i></summary><blockquote>

Done. Will be in next push.

I have the getter method, but it is never actually used. Should this be kept in or should I remove it until the future if someone actually needed it they could add it back in?
</blockquote></details>

if something isn't used, delete it. we can always add it back later, and it makes less code to maintain.


<!-- Sent from Reviewable.io -->

2020-03-03 22:24 UTC, c-andy-martin reviewed
> Reviewed 2 of 38 files at r4.
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/amcl/2)* status: 3 of 52 files reviewed, 54 unresolved discussions (waiting on @12tbuchman and @c-andy-martin)

___
*[include/amcl/map/map.h, line 49 at r2](https://reviewable.io/reviews/badgertechnologies/amcl/2#-LzDhdEdBAUp9VnHF9p8:-M1XTZ4f-szY91KVeK6I:b-alxkn) ([raw file](https://github.com/badgertechnologies/amcl/blob/bbbafd470c81f3bf418c310bd0334bc4469d4b08/include/amcl/map/map.h#L49)):*
<details><summary><i>Previously, 12tbuchman (Tyler Buchman) wrote…</i></summary><blockquote>

I think we should have both maybe. It is unclear to say "getSize" and refer to the pixels, where as "getOrigin" refers to meters. Of course you can look at the return value but imo the function name should be clear.
Looking at usage, the getSize function is called once in the 2d code to refer to pixels and once to refer to meters. In the 3d code it is called once to refer to meters and not called to refer to pixels. In cases where it is called to refer to meters the returned value of pixels is sent back to the map in the convertMapToWorld function, thus effectively returning the map size in meters. Instead I could make a "getMapSize" and "getWorldSize" function in 2d and just a "getWorldSize" function in 3d, and the base map class can either require the "getWorldSize" or not require this function at all. What do you think?
</blockquote></details>

yes, that sounds better
___
*[include/amcl/map/map.h, line 47 at r3](https://reviewable.io/reviews/badgertechnologies/amcl/2#-LzJAoWRB6emabjaeVTy:-M1XTbY85rHnDQKB_A9t:bi38h8z) ([raw file](https://github.com/badgertechnologies/amcl/blob/770d4c63beb80b8977948e006adb7bdbc3c1d735/include/amcl/map/map.h#L47)):*
<details><summary><i>Previously, 12tbuchman (Tyler Buchman) wrote…</i></summary><blockquote>

Going off your other comments, should I return the size and origin by reference or value?
</blockquote></details>

you can't return by reference, unless the vector has life longer than the function. that probably isn't a good idea either, unless you know it won't change while its being used elsewhere. here I would return by value, or you can pass a pointer into getOrigin to assign the origin to. But the compiler can usually eliminate the double copy on return, so I think just leave this as is


<!-- Sent from Reviewable.io -->

2020-03-03 22:46 UTC, c-andy-martin commented
___
*[include/amcl/map/occupancy_map.h, line 24 at r2](https://reviewable.io/reviews/badgertechnologies/amcl/2#-LzDfbH93_CR3EQnC6pc:-M1XZxKN9kx2Q8YkY9et:b-8ckj57) ([raw file](https://github.com/badgertechnologies/amcl/blob/bbbafd470c81f3bf418c310bd0334bc4469d4b08/include/amcl/map/occupancy_map.h#L24)):*
<details><summary><i>Previously, 12tbuchman (Tyler Buchman) wrote…</i></summary><blockquote>

As I mentioned before, Ill leave the Jabil email at least until we hear from Brian Lee and / or Bryan Ethington regarding the Badger email. So you prefer that I list myself as an author over listing myself as the maintainer?
</blockquote></details>

Lets remove your name from every source file, and just put it in the package.xml.


<!-- Sent from Reviewable.io -->

2020-03-04 00:13 UTC, c-andy-martin commented
___
*[include/amcl/map/occupancy_map.h, line 33 at r2](https://reviewable.io/reviews/badgertechnologies/amcl/2#-LzDg0kP8nS6GFpgpHpM:-M1XszKO5JrL10SujgKL:b-ciey3m) ([raw file](https://github.com/badgertechnologies/amcl/blob/bbbafd470c81f3bf418c310bd0334bc4469d4b08/include/amcl/map/occupancy_map.h#L33)):*
<details><summary><i>Previously, 12tbuchman (Tyler Buchman) wrote…</i></summary><blockquote>

Going off of the Google C++ Style Guide, https://google.github.io/styleguide/cppguide.html#Names_and_Order_of_Includes
all c system headers and c++ system headers should be separated by a blank line.
</blockquote></details>

ok, thanks


<!-- Sent from Reviewable.io -->

2020-03-04 00:14 UTC, c-andy-martin commented
___
*[include/amcl/map/occupancy_map.h, line 33 at r2](https://reviewable.io/reviews/badgertechnologies/amcl/2#-LzDg0kP8nS6GFpgpHpM:-M1Xt3D65ZkWakH0j5ou:b-ed0myy) ([raw file](https://github.com/badgertechnologies/amcl/blob/bbbafd470c81f3bf418c310bd0334bc4469d4b08/include/amcl/map/occupancy_map.h#L33)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

ok, thanks
</blockquote></details>

oh, but now this is a c++ header, so you can remove the line


<!-- Sent from Reviewable.io -->

2020-03-04 00:18 UTC, c-andy-martin commented
___
*[include/amcl/map/occupancy_map.h, line 53 at r2](https://reviewable.io/reviews/badgertechnologies/amcl/2#-LzDgDfk7cnU4Gwm0Gqx:-M1XtXOkBcgjmQT2nlwX:b-4usqko) ([raw file](https://github.com/badgertechnologies/amcl/blob/bbbafd470c81f3bf418c310bd0334bc4469d4b08/include/amcl/map/occupancy_map.h#L53)):*
<details><summary><i>Previously, 12tbuchman (Tyler Buchman) wrote…</i></summary><blockquote>

Wrong link, here is the correct one: https://google.github.io/styleguide/cppguide.html#Inheritance
</blockquote></details>

I disagree with the style guide a bit here. You should mark these all virtual, as you don't know if sometime down the road you will want to inherit from this class. Also, I mark everything protected for that reason too, unless there is some reason a child class must not use a private variable. Such cases are rare. I'm all the time running into code upstream where they only make a few things virtual, or they make the data I need to change the behavior of private. The style guide makes sense if you are writing closed source code you are sure is never going to get reused, but I tend to think the more flexible the better. The only exception I make to this in new code for myself is when I have performance critical code paths. Those I might make inline and not virtual. Or if I'm writing a class or struct that I'm pretty sure will never be inherited from, in such cases I would not mark anything virtual (but I wouldn't bother with the 'final' keyword).


<!-- Sent from Reviewable.io -->

2020-03-04 00:19 UTC, c-andy-martin commented
___
*[include/amcl/map/occupancy_map.h, line 83 at r3](https://reviewable.io/reviews/badgertechnologies/amcl/2#-LzDo15I15B7YGpji4yJ:-M1XuJPJ2x2xIW52GcKN:b-ba9cuk) ([raw file](https://github.com/badgertechnologies/amcl/blob/770d4c63beb80b8977948e006adb7bdbc3c1d735/include/amcl/map/occupancy_map.h#L83)):*
<details><summary><i>Previously, 12tbuchman (Tyler Buchman) wrote…</i></summary><blockquote>

https://google.github.io/styleguide/cppguide.html#Variable_Names
http://wiki.ros.org/CppStyleGuide#Variables
Members of structs shouldnt have trailing underscores, so I will correct this. I dont see anything about an exception for public members.
</blockquote></details>

Basically, I take their idea to be a struct is a class w/ public data members. So for a public data member, you can leave off the trailing under score. It becomes part of the API. This is OK now


<!-- Sent from Reviewable.io -->

2020-03-04 16:36 UTC, c-andy-martin commented
___
*[include/amcl/map/occupancy_map.h, line 90 at r3](https://reviewable.io/reviews/badgertechnologies/amcl/2#-LzDoarvDVlMEKvkSvjK:-M1aOzam7Au998dpOJBU:b-edf2gv) ([raw file](https://github.com/badgertechnologies/amcl/blob/770d4c63beb80b8977948e006adb7bdbc3c1d735/include/amcl/map/occupancy_map.h#L90)):*
<details><summary><i>Previously, 12tbuchman (Tyler Buchman) wrote…</i></summary><blockquote>

If I move them to protected or private, I would need to write setter/getter methods. Do you think that is necessary?
</blockquote></details>

This is OK. This class is an inner private class, so its interface is OK to be public.


<!-- Sent from Reviewable.io -->

2020-03-04 16:38 UTC, c-andy-martin commented
___
*[include/amcl/map/occupancy_map.h, line 121 at r2](https://reviewable.io/reviews/badgertechnologies/amcl/2#-LzD_NoB0B-t6EM3bMHa:-M1aPE-9EbJ5ZuHkmoqy:bmiy5ie) ([raw file](https://github.com/badgertechnologies/amcl/blob/bbbafd470c81f3bf418c310bd0334bc4469d4b08/include/amcl/map/occupancy_map.h#L121)):*
<details><summary><i>Previously, 12tbuchman (Tyler Buchman) wrote…</i></summary><blockquote>

Where are you seeing a tab character?
</blockquote></details>

you already fixed it in a previous commit (probably when you ran `clang-format`).


<!-- Sent from Reviewable.io -->

2020-03-04 17:41 UTC, c-andy-martin commented
___
*[include/amcl/map/occupancy_map.h, line 123 at r3](https://reviewable.io/reviews/badgertechnologies/amcl/2#-LzDxJjy67TeH2eNSHib:-M1ac_SN0MBAUHsGH8UK:b-uh51tp) ([raw file](https://github.com/badgertechnologies/amcl/blob/770d4c63beb80b8977948e006adb7bdbc3c1d735/include/amcl/map/occupancy_map.h#L123)):*
<details><summary><i>Previously, 12tbuchman (Tyler Buchman) wrote…</i></summary><blockquote>

When I was writing this section i tried that but it gives me a build error. I may be writing it incorrectly. Lets discuss this further.
</blockquote></details>

Here is exactly what you need to do. Delete this line, and the `operator<` below. Then back up around line 82 (inside `struct CellData` add:

```
    inline bool operator<(const CellData& rhs) const                                                                             
    {                                                                                                                            
      return occ_map->getOccDist(i, j) > rhs.occ_map->getOccDist(rhs.i, rhs.j);                                                  
    }                                                                                                                            
```
I tested this and it compiles fine.
       


<!-- Sent from Reviewable.io -->

2020-03-04 17:43 UTC, c-andy-martin commented
___
*[include/amcl/map/octomap.h, line 2 at r3](https://reviewable.io/reviews/badgertechnologies/amcl/2#-LzIByu64-Qhyc5Dr2up:-M1adDWN50jwVdQNjUpn:bupfdtw) ([raw file](https://github.com/badgertechnologies/amcl/blob/770d4c63beb80b8977948e006adb7bdbc3c1d735/include/amcl/map/octomap.h#L2)):*
<details><summary><i>Previously, 12tbuchman (Tyler Buchman) wrote…</i></summary><blockquote>

Done. Will be in the next push. What should I do with the eig.h/cpp files? I didn't originally write them, but they didn't have a copywrite on the initial files.
</blockquote></details>

leave those as they were (don't add a new copyright)


<!-- Sent from Reviewable.io -->

2020-03-04 17:44 UTC, c-andy-martin commented
___
*[include/amcl/map/octomap.h, line 37 at r5](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M1adTT5D1Izfzdoo006:-M1adTT5D1Izfzdoo007:ba9zc4k) ([raw file](https://github.com/badgertechnologies/amcl/blob/95b6eb20da05f9f418bc7ea0645e69d04bc7dd99/include/amcl/map/octomap.h#L37)):*
> ```objc
> 
> #include <octomap/OcTree.h>
> #include <octomap/OcTreeDistance.h>
> ```

Get rid of including "OcTreeDistance.h" now that you aren't using it. It isn't in the badger-develop branch of octomap, so in order to build the code, I had to remove this line (after removing, it built fine).


<!-- Sent from Reviewable.io -->

2020-03-04 17:46 UTC, c-andy-martin commented
___
*[include/amcl/map/occupancy_map.h, line 29 at r5](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M1adrJX6zy5hglWT8v8:-M1adrJY6-8bUoLIuhQZ:b-vbxpf1) ([raw file](https://github.com/badgertechnologies/amcl/blob/95b6eb20da05f9f418bc7ea0645e69d04bc7dd99/include/amcl/map/occupancy_map.h#L29)):*
> ```objc
> #define AMCL_MAP_OCCUPANCY_MAP_H
> 
> #include "map/map.h"
> ```

This include should come last, not first, as it is local. The only exception to this is in .cpp files:

https://google.github.io/styleguide/cppguide.html#Names_and_Order_of_Includes


<!-- Sent from Reviewable.io -->

2020-03-04 17:57 UTC, c-andy-martin commented
___
*[src/amcl/map/octomap.cpp, line 43 at r5](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M1agJDz46da7brK5ur9:-M1agJDz46da7brK5urA:b-pv3izc) ([raw file](https://github.com/badgertechnologies/amcl/blob/95b6eb20da05f9f418bc7ea0645e69d04bc7dd99/src/amcl/map/octomap.cpp#L43)):*
> ```cpp
>   map_max_bounds_ = std::vector<double>(2);
>   max_occ_dist_ = 0.0;
>   octree_ = std::make_shared<octomap::OcTree>(resolution_);
> ```

I'd prefer this to be:
```
octree_.reset(new octomap::OcTree(resolution_));
```
It avoids an unnecessary creation and copy of a shared_ptr, and is clearer to me how the memory got allocated that the shared_ptr is managing.


<!-- Sent from Reviewable.io -->

2020-03-04 18:06 UTC, c-andy-martin commented
___
*[include/amcl/map/octomap.h, line 67 at r3](https://reviewable.io/reviews/badgertechnologies/amcl/2#-LzIFaJu7n8X4sxlRSR-:-M1aiA6U61LFP_N--_ol:bmv1l0p) ([raw file](https://github.com/badgertechnologies/amcl/blob/770d4c63beb80b8977948e006adb7bdbc3c1d735/include/amcl/map/octomap.h#L67)):*
<details><summary><i>Previously, 12tbuchman (Tyler Buchman) wrote…</i></summary><blockquote>

I am getting errors when I try this. Lets discuss.
</blockquote></details>

Ah. So I tried this myself, and the issue is that the container these end up in need to be able to call the move constructor on the CellData. This doesn't work cleanly with references. The reason I was recommending reference here is that it prevents you from constructing a CellData with a nullptr. Another way of doing that would be to delete the default constructor, so I recommend instead just adding:
```
CellData() = delete;
```
Do the `struct CellData`.


<!-- Sent from Reviewable.io -->

2020-03-04 18:06 UTC, c-andy-martin requested changes
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/amcl/2)* status: 3 of 52 files reviewed, 35 unresolved discussions (waiting on @12tbuchman and @c-andy-martin)

___
*[include/amcl/map/octomap.h, line 67 at r3](https://reviewable.io/reviews/badgertechnologies/amcl/2#-LzIFaJu7n8X4sxlRSR-:-M1aiZuiBbkswgFtUPtP:b-serl0) ([raw file](https://github.com/badgertechnologies/amcl/blob/770d4c63beb80b8977948e006adb7bdbc3c1d735/include/amcl/map/octomap.h#L67)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

Ah. So I tried this myself, and the issue is that the container these end up in need to be able to call the move constructor on the CellData. This doesn't work cleanly with references. The reason I was recommending reference here is that it prevents you from constructing a CellData with a nullptr. Another way of doing that would be to delete the default constructor, so I recommend instead just adding:
```
CellData() = delete;
```
Do the `struct CellData`.
</blockquote></details>

Read "Do the..." as "To the..." I hate that you can't edit once you publish :D


<!-- Sent from Reviewable.io -->

2020-03-04 18:07 UTC, c-andy-martin requested changes
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/amcl/2)* status: 3 of 52 files reviewed, 34 unresolved discussions (waiting on @12tbuchman and @c-andy-martin)

___
*[include/amcl/map/octomap.h, line 122 at r3](https://reviewable.io/reviews/badgertechnologies/amcl/2#-LzIHmBZ4t5W3ia1LbkH:-M1aiggfBmgLnj0R3Bzd:bimujuk) ([raw file](https://github.com/badgertechnologies/amcl/blob/770d4c63beb80b8977948e006adb7bdbc3c1d735/include/amcl/map/octomap.h#L122)):*
<details><summary><i>Previously, 12tbuchman (Tyler Buchman) wrote…</i></summary><blockquote>

Lets discuss.
</blockquote></details>

See my comment on occupancy_grid, you should be able to do the same thing here.


<!-- Sent from Reviewable.io -->

2020-03-04 18:08 UTC, c-andy-martin commented
___
*[include/amcl/node/node.h, line 66 at r5](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M1aivoN6rNgD_77-8jo:-M1aivoOE8K65ZHVyj68:b-oy48b8) ([raw file](https://github.com/badgertechnologies/amcl/blob/95b6eb20da05f9f418bc7ea0645e69d04bc7dd99/include/amcl/node/node.h#L66)):*
> ```objc
> namespace amcl
> {
> // Pose hypothesis
> ```

This comment seems unnecessary. I would remove it.


<!-- Sent from Reviewable.io -->

2020-03-04 18:28 UTC, c-andy-martin commented
___
*[include/amcl/node/node.h, line 106 at r3](https://reviewable.io/reviews/badgertechnologies/amcl/2#-LzIJylU1tigU08JSpqr:-M1aldIl58TP90xn32OI:biq2w9o) ([raw file](https://github.com/badgertechnologies/amcl/blob/770d4c63beb80b8977948e006adb7bdbc3c1d735/include/amcl/node/node.h#L106)):*
<details><summary><i>Previously, 12tbuchman (Tyler Buchman) wrote…</i></summary><blockquote>

for some reason im getting an error when converting these to `static constexpr int` but the EPSILON worked fine from octomap.h. Lets talk about this.
</blockquote></details>

so, until C++17 you still have to define this in the CPP file b/c its part of the object. That will work, but thinking about what these indeces are, these constants are generally useful to AMCL, as it is a quick way to access the right part of a covariance. So, I suggest instead renaming these COVARIANCE_{XX,YY,AA} and putting them in the amcl namespace directly, not in the Node class. Then there will be no issue with needing a definition on top of a declaration (as you don't need that outside a class in this case). So, delete these three lines, and above, right after opening the namespace:
```
namespace amcl
{

// Convenience constants for covariance indeces.
constexpr int COVARIANCE_XX = 6 * 0 + 0;
constexpr int COVARIANCE_YY = 6 * 1 + 1;
constexpr int COVARIANCE_AA = 6 * 5 + 5;
```


<!-- Sent from Reviewable.io -->

2020-03-04 18:29 UTC, c-andy-martin commented
___
*[include/amcl/node/node.h, line 110 at r3](https://reviewable.io/reviews/badgertechnologies/amcl/2#-LzIK7vO-8X82SIDA7q4:-M1anjUc8UJDv8YvM-5C:bfks1ia) ([raw file](https://github.com/badgertechnologies/amcl/blob/770d4c63beb80b8977948e006adb7bdbc3c1d735/include/amcl/node/node.h#L110)):*
<details><summary><i>Previously, 12tbuchman (Tyler Buchman) wrote…</i></summary><blockquote>

Lets discuss this.
</blockquote></details>

I don't think this is relevant anymore.


<!-- Sent from Reviewable.io -->

2020-03-05 14:58 UTC, c-andy-martin reviewed
> Reviewed 3 of 38 files at r4.
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/amcl/2)* status: 6 of 52 files reviewed, 28 unresolved discussions (waiting on @12tbuchman and @c-andy-martin)



<!-- Sent from Reviewable.io -->

2020-03-05 15:03 UTC, c-andy-martin commented
___
*[include/amcl/map/occupancy_map.h, line 42 at r5](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M1fCuBKE6jMzF1dvXYP:-M1fCuBL55s0Jfhki4vc:buwtej8) ([raw file](https://github.com/badgertechnologies/amcl/blob/95b6eb20da05f9f418bc7ea0645e69d04bc7dd99/include/amcl/map/occupancy_map.h#L42)):*
> ```objc
> struct MapCell
> {
>   // Occupancy state (-1 = free, 0 = unknown, +1 = occ)
> ```

These constants should be defined in the amcl namespace, something like this outside the struct declaration:
```
constexpr int8_t CELL_FREE = -1;
constexpr int8_t CELL_UNKNOWN = 0;
constexpr int8_t CELL_OCCUPIED = 1;
```
Then whenever using `occ_state` use the named constants


<!-- Sent from Reviewable.io -->

2020-03-05 15:06 UTC, c-andy-martin commented
___
*[include/amcl/map/occupancy_map.h, line 61 at r5](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M1fDlWJ53jgZY2WLIhF:-M1fDlWJ53jgZY2WLIhG:bfwd1fg) ([raw file](https://github.com/badgertechnologies/amcl/blob/95b6eb20da05f9f418bc7ea0645e69d04bc7dd99/include/amcl/map/occupancy_map.h#L61)):*
> ```objc
>   void setSize(std::vector<int> size_vec);
>   // Update the cspace distance values
>   void updateCSpace(double max_occ_dist);
> ```

I really don't like the name 'cspace' we inherited from AMCL. Either rename it now to something like 'DistanceCache' or 'DistanceLUT' or take a to do by logging an issue in Jira to do this renaming soon.


<!-- Sent from Reviewable.io -->

2020-03-05 15:08 UTC, c-andy-martin commented
___
*[include/amcl/map/occupancy_map.h, line 65 at r5](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M1fE3yHEx2Y6aqYbMgG:-M1fE3yHEx2Y6aqYbMgH:btmsw07) ([raw file](https://github.com/badgertechnologies/amcl/blob/95b6eb20da05f9f418bc7ea0645e69d04bc7dd99/include/amcl/map/occupancy_map.h#L65)):*
> ```objc
>   double calcRange(double ox, double oy, double oa, double max_range);
>   // Find the distance to nearest occupied cell
>   float getOccDist(int i, int j);
> ```

I don't like AMCL abbreviating occupancy as 'occ' everywhere, its too dense. Either rename such occurrences 'Occupancy' now or take a to do on a Jira ticket to do it soon.


<!-- Sent from Reviewable.io -->

2020-03-05 15:09 UTC, c-andy-martin commented
___
*[include/amcl/map/occupancy_map.h, line 71 at r5](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M1fEO35DBH4u_15wi4u:-M1fEO35DBH4u_15wi4v:b-zblkl6) ([raw file](https://github.com/badgertechnologies/amcl/blob/95b6eb20da05f9f418bc7ea0645e69d04bc7dd99/include/amcl/map/occupancy_map.h#L71)):*
> ```objc
>   double getMaxOccDist();
>   void initCells(int num);
>   void setCellOccState(int index, int8_t state);
> ```

I would prefer the name 'setCellState' as it might get set to free or unknown or occupied, which isn't what the name implies.


<!-- Sent from Reviewable.io -->

2020-03-05 15:09 UTC, c-andy-martin reviewed
> Reviewed 1 of 38 files at r4.
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/amcl/2)* status: 7 of 52 files reviewed, 32 unresolved discussions (waiting on @12tbuchman and @c-andy-martin)



<!-- Sent from Reviewable.io -->

2020-03-05 15:31 UTC, c-andy-martin commented
___
*[include/amcl/map/occupancy_map.h, line 94 at r5](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M1fEi4t23GfeQFqgAH6:-M1fEi4t23GfeQFqgAH7:b-2vgwfk) ([raw file](https://github.com/badgertechnologies/amcl/blob/95b6eb20da05f9f418bc7ea0645e69d04bc7dd99/include/amcl/map/occupancy_map.h#L94)):*
> ```objc
>     CachedDistanceMap(double resolution, double max_dist) : resolution_(resolution), max_dist_(max_dist)
>     {
>       cell_radius_ = max_dist / resolution;
> ```

I don't like this implicit conversion to an integer. Also, I like to be explicit about which way I want to truncate/round, like this:
```
cell_radius_ = static_cast<int>(std::floor(max_dist / resolution));
```


<!-- Sent from Reviewable.io -->

2020-03-05 18:50 UTC, c-andy-martin reviewed
> Reviewed 1 of 38 files at r4.
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/amcl/2)* status: 8 of 52 files reviewed, 33 unresolved discussions (waiting on @12tbuchman and @c-andy-martin)



<!-- Sent from Reviewable.io -->

2020-03-05 18:52 UTC, c-andy-martin commented
___
*[include/amcl/map/octomap.h, line 72 at r3](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M1g1_f0AgJnSpA_6U0q:-M1g1_f0AgJnSpA_6U0r:bvtxwbg) ([raw file](https://github.com/badgertechnologies/amcl/blob/770d4c63beb80b8977948e006adb7bdbc3c1d735/include/amcl/map/octomap.h#L72)):*
> ```objc
>     }
>     int i_, j_, k_;
>     int src_i_, src_j_, src_k_;
> ```

pls put the `operator<` here, as per my comments in occupancy_map.,h


<!-- Sent from Reviewable.io -->

2020-03-05 18:56 UTC, c-andy-martin commented
___
*[include/amcl/map/octomap.h, line 100 at r5](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M1g2-KtE_klpaZbTiOD:-M1g2-KtE_klpaZbTiOE:b-d8z7zt) ([raw file](https://github.com/badgertechnologies/amcl/blob/95b6eb20da05f9f418bc7ea0645e69d04bc7dd99/include/amcl/map/octomap.h#L100)):*
> ```objc
>   bool wait_for_occupancy_map_;
>   std::unique_ptr<CachedDistanceMap> cdm_;
>   std::unique_ptr<std::priority_queue<CellData>> q_;
> ```

I'm thinking you know everything when you construct this OctoMap object that you need to construct the CachedDistanceMap and the priority_queue, so I do not think these should be wrapped in a pointer. Just make them part of the class:
```
CachedDistanceMap cdm_;
std::priority_queue<CellData> q_;
```
I'm not sure when you know the resolution for the map, as you can't contruct the octomap::OcTree without the resolution, so if you don't know resolution at construction time it makes sense to use a unique_ptr.


<!-- Sent from Reviewable.io -->

2020-03-05 18:57 UTC, c-andy-martin commented
___
*[include/amcl/node/node.h, line 19 at r5](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M1g2cq1054DmY0cNUvm:-M1g2cq1054DmY0cNUvn:b9ngg15) ([raw file](https://github.com/badgertechnologies/amcl/blob/95b6eb20da05f9f418bc7ea0645e69d04bc7dd99/include/amcl/node/node.h#L19)):*
> ```objc
>  *
>  */
> /* *************************************************************
> ```

As per my other comments, I think it would be best to just list your name in package.xml and leave it out of all the source files. Also, I don't think we need a description here. If you want to detail what Node does, do it in a doxygen comment block above the object declaration itself.


<!-- Sent from Reviewable.io -->

2020-03-05 18:58 UTC, c-andy-martin commented
___
*[include/amcl/node/node.h, line 65 at r5](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M1g2z_X7ZW7wNWPNyg_:-M1g2z_X7ZW7wNWPNyga:bisfcv5) ([raw file](https://github.com/badgertechnologies/amcl/blob/95b6eb20da05f9f418bc7ea0645e69d04bc7dd99/include/amcl/node/node.h#L65)):*
> ```objc
> 
> namespace amcl
> {
> ```

I would add a free space here, even if the clang-format might eat it, it looks prettier to me.


<!-- Sent from Reviewable.io -->

2020-03-05 19:02 UTC, c-andy-martin commented
___
*[include/amcl/node/node.h, line 86 at r5](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M1g3Z_w1CeJGoIdjGJc:-M1g3Z_w1CeJGoIdjGJd:b-h74j7n) ([raw file](https://github.com/badgertechnologies/amcl/blob/95b6eb20da05f9f418bc7ea0645e69d04bc7dd99/include/amcl/node/node.h#L86)):*
> ```objc
>   bool getOdomPose(const ros::Time& t, PFVector* map_pose);
>   std::shared_ptr<ParticleFilter> getPfPtr();
>   void publishPfCloud();
> ```

I'm not a huge fan of the 'Pf' abbreviation. I would prefer using ParticleFilter everywhere if that's what Pf means.
Or, if PF is superfluous based on context, just ditch it (like PFVector, why not just make an amcl::Vector? I doubt the vector has much to do with the particle filter itself).


<!-- Sent from Reviewable.io -->

2020-03-05 19:02 UTC, c-andy-martin requested changes
> Reviewed 1 of 3 files at r5.
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/amcl/2)* status: 9 of 52 files reviewed, 39 unresolved discussions (waiting on @12tbuchman and @c-andy-martin)

___
*[include/amcl/node/node.h, line 88 at r5](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M1g3TXP3xYPDJkN6Ei0:-M1g3TXQCYGxjSqWRPmh:b-6iwz3q) ([raw file](https://github.com/badgertechnologies/amcl/blob/95b6eb20da05f9f418bc7ea0645e69d04bc7dd99/include/amcl/node/node.h#L88)):*
> ```objc
>   void publishPfCloud();
>   void updatePose(const PFVector& max_hyp_mean, const ros::Time& stamp);
>   bool updateTf(const tf::Stamped<tf::Pose>& odom_to_map);
> ```

I'm not a huge fan of abbreviations in names. They can cause confusion. I'd prefer 'updateTransforms'


<!-- Sent from Reviewable.io -->

2020-03-05 19:03 UTC, c-andy-martin requested changes
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/amcl/2)* status: 9 of 52 files reviewed, 40 unresolved discussions (waiting on @12tbuchman and @c-andy-martin)

___
*[include/amcl/node/node.h, line 111 at r5](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M1g46DUAIg4Gh7cadeu:-M1g46DUAIg4Gh7cadev:bhp9504) ([raw file](https://github.com/badgertechnologies/amcl/blob/95b6eb20da05f9f418bc7ea0645e69d04bc7dd99/include/amcl/node/node.h#L111)):*
> ```objc
>   const int INDEX_AA_ = 6 * 5 + 5;
> 
>   void reconfigureCB(amcl::AMCLConfig& config, uint32_t level);
> ```

There is no need for the `amcl::` here, you are in the amcl namespace.


<!-- Sent from Reviewable.io -->

2020-03-05 19:06 UTC, c-andy-martin commented
___
*[include/amcl/node/node.h, line 146 at r5](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M1g4a1vE189jK2VHRrl:-M1g4a1vE189jK2VHRrm:b-q0uyey) ([raw file](https://github.com/badgertechnologies/amcl/blob/95b6eb20da05f9f418bc7ea0645e69d04bc7dd99/include/amcl/node/node.h#L146)):*
> ```objc
>   void resetOdomIntegrator();
>   void publishTransform(const ros::TimerEvent& event);
>   double normalize(double z);
> ```

let's ditch these for the `angles` package, using the `angles::normalize_angle` and `angles::shortest_angular_distance` functions. you'll need to add `angles` as a depend in package.xml and in cmake as well.


<!-- Sent from Reviewable.io -->

2020-03-05 19:10 UTC, c-andy-martin commented
___
*[include/amcl/node/node.h, line 152 at r5](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M1g5RC9EmW0G1rkP3wp:-M1g5RC9EmW0G1rkP3wq:b-7k89ac) ([raw file](https://github.com/badgertechnologies/amcl/blob/95b6eb20da05f9f418bc7ea0645e69d04bc7dd99/include/amcl/node/node.h#L152)):*
> ```objc
>   void computeDelta(const PFVector& pose, PFVector* delta);
>   void setScannersUpdateFlags(const PFVector& delta,
>                               std::shared_ptr<std::vector<bool>> scanners_update,
> ```

To save making a temporary copy of the shared_ptr for every call, I usually pass here by reference. And since you won't be changing the actual shared ptr, by const reference:
```
void setScannerUpdateFlags(const PFVector& delta, const std::shared<ptr<std::vector<bool>>& scanners_update, ...
```


<!-- Sent from Reviewable.io -->

2020-03-05 19:10 UTC, c-andy-martin commented
___
*[include/amcl/node/node.h, line 155 at r5](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M1g5nROAdJt6Lczed6j:-M1g5nROAdJt6Lczed6k:b-3yhhpz) ([raw file](https://github.com/badgertechnologies/amcl/blob/95b6eb20da05f9f418bc7ea0645e69d04bc7dd99/include/amcl/node/node.h#L155)):*
> ```objc
>                               bool* force_update);
>   void updateOdom(const PFVector& pose, const PFVector &delta);
>   void initOdom(const PFVector& pose, std::shared_ptr<std::vector<bool>> scanners_update,
> ```

same comment here about scanners_update as above


<!-- Sent from Reviewable.io -->

2020-03-05 19:15 UTC, c-andy-martin requested changes
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/amcl/2)* status: 9 of 52 files reviewed, 44 unresolved discussions (waiting on @12tbuchman and @c-andy-martin)

___
*[include/amcl/node/node.h, line 158 at r5](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M1g5vTD5sM2kRo-qBfK:-M1g5vTD5sM2kRo-qBfL:bf002w1) ([raw file](https://github.com/badgertechnologies/amcl/blob/95b6eb20da05f9f418bc7ea0645e69d04bc7dd99/include/amcl/node/node.h#L158)):*
> ```objc
>                 int* resample_count, bool* force_publication);
> 
>   std::shared_ptr<std::function<PFVector()>> uniform_pose_generator_fn_ptr_;
> ```

std::function is itself a pointer, and points to static data (it point to compiled code which doesn't change). there is no need to wrap it in a shared_ptr. I would remove wrapping any occurence of std::function w/ a shared_ptr (this will affect several files, as its in the ParticleFilter object as well).


<!-- Sent from Reviewable.io -->

2020-03-05 19:24 UTC, c-andy-martin commented
___
*[include/amcl/node/node.h, line 177 at r5](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M1g8gpU-9d-bK2nKlTD:-M1g8gpU-9d-bK2nKlTE:bl4ysas) ([raw file](https://github.com/badgertechnologies/amcl/blob/95b6eb20da05f9f418bc7ea0645e69d04bc7dd99/include/amcl/node/node.h#L177)):*
> ```objc
>   bool wait_for_occupancy_map_;
>   std::shared_ptr<Node2D> node_2d_;
>   std::shared_ptr<Node3D> node_3d_;
> ```

I would like to have a NodeBase and have Node only interact w/ the base class, store a base pointer here. You can either use a factory to build the right kind of node, or it would be fine to leave the circular dependency (broken the way you already have be pre-declaring Node) and just have NodeBase build the right kind of node instance, but only store a NodeBase pointer to it for cleanness.


<!-- Sent from Reviewable.io -->

2020-03-05 21:38 UTC, c-andy-martin commented
___
*[include/amcl/node/node.h, line 172 at r5](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M1gcVA01DBjsywxG8XY:-M1gcVA01DBjsywxG8XZ:bwo1joh) ([raw file](https://github.com/badgertechnologies/amcl/blob/95b6eb20da05f9f418bc7ea0645e69d04bc7dd99/include/amcl/node/node.h#L172)):*
> ```objc
>   ros::ServiceServer global_loc_srv_;
> 
>   // 2: 2d, 3: 3d, else: none
> ```

Per my comment in AMCL.cfg, make the dynamic configure an enumeration. That will generate constants like 'AMCL_Map2D' and 'AMCL_Map3D' (if you call the enumeration opetions 'Map2D' and 'Map3D' that encode to the integer values 2 and 3, IIRC).


<!-- Sent from Reviewable.io -->

2020-03-05 21:40 UTC, c-andy-martin commented
___
*[include/amcl/node/node.h, line 179 at r5](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M1gczKc9hzF5Lzkzsw9:-M1gczKc9hzF5LzkzswA:b-u81adu) ([raw file](https://github.com/badgertechnologies/amcl/blob/95b6eb20da05f9f418bc7ea0645e69d04bc7dd99/include/amcl/node/node.h#L179)):*
> ```objc
>   std::shared_ptr<Node3D> node_3d_;
> 
>   tf::TransformBroadcaster tfb_;
> ```

Since we are rewriting, we should go away from using tf in favor of tf2. I know this may be a lot of re-writing to get the interfaces right, so I'm OK taking a to-do in a ticket for this and getting to it in a month or two.


<!-- Sent from Reviewable.io -->

2020-03-05 21:43 UTC, c-andy-martin commented
___
*[include/amcl/node/node.h, line 233 at r5](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M1gdV-d1NXMDf2hQ-o6:-M1gdV-d1NXMDf2hQ-o7:b60edk3) ([raw file](https://github.com/badgertechnologies/amcl/blob/95b6eb20da05f9f418bc7ea0645e69d04bc7dd99/include/amcl/node/node.h#L233)):*
> ```objc
>   std::mutex tf_mutex_;
>   std::mutex latest_amcl_pose_mutex_;
>   std::unique_ptr<dynamic_reconfigure::Server<amcl::AMCLConfig>> dsrv_;
> ```

you should know everything you need to know at construction time of this object (mainly the node handle) to make this a part of this class and not need to store it in a pointer


<!-- Sent from Reviewable.io -->

2020-03-05 21:43 UTC, c-andy-martin commented
___
*[include/amcl/node/node.h, line 234 at r5](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M1gdljQBnh-vvJaXLiU:-M1gdljQBnh-vvJaXLiV:b-3s5fof) ([raw file](https://github.com/badgertechnologies/amcl/blob/95b6eb20da05f9f418bc7ea0645e69d04bc7dd99/include/amcl/node/node.h#L234)):*
> ```objc
>   std::mutex latest_amcl_pose_mutex_;
>   std::unique_ptr<dynamic_reconfigure::Server<amcl::AMCLConfig>> dsrv_;
>   amcl::AMCLConfig default_config_;
> ```

you are in the amcl namespace already, no need for `amcl::`


<!-- Sent from Reviewable.io -->

2020-03-05 21:44 UTC, c-andy-martin commented
___
*[include/amcl/node/node.h, line 243 at r5](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M1gds5n-XMFtbbP_a-r:-M1gds5n-XMFtbbP_a-s:b-ugxngy) ([raw file](https://github.com/badgertechnologies/amcl/blob/95b6eb20da05f9f418bc7ea0645e69d04bc7dd99/include/amcl/node/node.h#L243)):*
> ```objc
>   double uniform_pose_starting_weight_threshold_;
>   double uniform_pose_deweight_multiplier_;
>   std::shared_ptr<std::vector<std::pair<int, int>>> free_space_indices_;
> ```

does this need to be in a shared pointer? My guess is you can just include a straight-up vector. If you need to pass it, just pass it by reference.


<!-- Sent from Reviewable.io -->

2020-03-05 21:45 UTC, c-andy-martin commented
___
*[include/amcl/node/node.h, line 245 at r5](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M1ge43p3qgXfhwmh8GC:-M1ge43p3qgXfhwmh8GD:b8tpmqm) ([raw file](https://github.com/badgertechnologies/amcl/blob/95b6eb20da05f9f418bc7ea0645e69d04bc7dd99/include/amcl/node/node.h#L245)):*
> ```objc
>   std::shared_ptr<std::vector<std::pair<int, int>>> free_space_indices_;
> };
> }  // namespace amcl
> ```

My guess is clang-format put these two lines together, but I like having a newline between for beauty


<!-- Sent from Reviewable.io -->

2020-03-05 21:54 UTC, c-andy-martin commented
___
*[src/amcl/node/node_2d.cpp, line 354 at r5](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M1ggCBj-AplorV4UGk2:-M1ggCBj-AplorV4UGk3:b4qft3s) ([raw file](https://github.com/badgertechnologies/amcl/blob/95b6eb20da05f9f418bc7ea0645e69d04bc7dd99/src/amcl/node/node_2d.cpp#L354)):*
> ```cpp
> 
>   std::string frame_id = planar_scan->header.frame_id;
>   ros::Time stamp = planar_scan->header.stamp; 
> ```

there is an extra WS at the end of this line


<!-- Sent from Reviewable.io -->

2020-03-05 22:04 UTC, c-andy-martin commented
___
*[include/amcl/node/node_2d.h, line 55 at r5](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M1gi0_q05UwSYhdyicT:-M1gi0_q05UwSYhdyicU:bgw7sed) ([raw file](https://github.com/badgertechnologies/amcl/blob/95b6eb20da05f9f418bc7ea0645e69d04bc7dd99/include/amcl/node/node_2d.h#L55)):*
> ```objc
> {
> public:
>   Node2D(Node* node, int map_type, std::mutex& configuration_mutex);
> ```

It is odd to take a reference to another objects mutex. This is not going to break, but does mean that this object has a back-reference to another object. I don't mind you doing it this way, but we need a comment explaining why its OK. Something like: "configuration_mutex is a reference to the node's configuration mutex necessary to synchronize points between node and this node implementation and dynamic reconfigure of the node and node implementation. This is for convenience, the Node object itself could provide APIs for this, but because the purpose of this node implementation is to provide implementation specific to a particular kind of map/sensor combination, it is OK to couple the two objects".


<!-- Sent from Reviewable.io -->

2020-03-05 22:06 UTC, c-andy-martin commented
___
*[include/amcl/node/node_2d.h, line 88 at r5](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M1gizFDA7amIW3PmVKO:-M1gizFE8Oda3eh333_W:bbqq80z) ([raw file](https://github.com/badgertechnologies/amcl/blob/95b6eb20da05f9f418bc7ea0645e69d04bc7dd99/include/amcl/node/node_2d.h#L88)):*
> ```objc
>   bool resamplePf(const sensor_msgs::LaserScanConstPtr& planar_scan);
> ```

Please have only one newline here


<!-- Sent from Reviewable.io -->

2020-03-05 22:08 UTC, c-andy-martin commented
___
*[include/amcl/node/node_2d.h, line 91 at r5](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M1gj5C3E4AwQEaf8Qa9:-M1gj5C3E4AwQEaf8QaA:b-pjlg0w) ([raw file](https://github.com/badgertechnologies/amcl/blob/95b6eb20da05f9f418bc7ea0645e69d04bc7dd99/include/amcl/node/node_2d.h#L91)):*
> ```objc
>   Node* node_;
>   std::shared_ptr<OccupancyMap> map_;
>   std::unique_ptr<message_filters::Subscriber<sensor_msgs::LaserScan>> scan_sub_;
> ```

I don't think this needs to be wrapped in a pointer, just have a member for the scan_sub_ and scan_filter_. Also, if you add the base class like I was saying, you can just not instantiate this class at all in the 3D case.


<!-- Sent from Reviewable.io -->

2020-03-05 22:08 UTC, c-andy-martin commented
___
*[include/amcl/node/node_2d.h, line 101 at r5](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M1gj_G4D-O5bMLRBc_n:-M1gj_G4D-O5bMLRBc_o:b4izdmi) ([raw file](https://github.com/badgertechnologies/amcl/blob/95b6eb20da05f9f418bc7ea0645e69d04bc7dd99/include/amcl/node/node_2d.h#L101)):*
> ```objc
>   std::mutex& configuration_mutex_;
>   std::vector<std::shared_ptr<PlanarScanner>> scanners_;
>   std::shared_ptr<std::vector<bool>> scanners_update_;
> ```

can this just be a plain vector, or does it need to be a pointer?


<!-- Sent from Reviewable.io -->

2020-03-06 14:42 UTC, c-andy-martin reviewed
> Reviewed 2 of 38 files at r4.
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/amcl/2)* status: 11 of 52 files reviewed, 56 unresolved discussions (waiting on @12tbuchman and @c-andy-martin)



<!-- Sent from Reviewable.io -->

2020-03-06 14:43 UTC, c-andy-martin commented
___
*[include/amcl/node/node_3d.h, line 37 at r5](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M1kIAxc-cKiw9hkpSTP:-M1kIAxc-cKiw9hkpSTQ:b-r2opmy) ([raw file](https://github.com/badgertechnologies/amcl/blob/95b6eb20da05f9f418bc7ea0645e69d04bc7dd99/include/amcl/node/node_3d.h#L37)):*
> ```objc
> #include <tf/message_filter.h>
> 
> #include <map>
> ```

std c++ includes should come first, then libraries like ROS and octomap, and finally local includes


<!-- Sent from Reviewable.io -->

2020-03-06 14:44 UTC, c-andy-martin commented
___
*[include/amcl/node/node_2d.h, line 36 at r5](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M1kINGhBUDE83-XkJcK:-M1kINGhBUDE83-XkJcL:b-cyn6co) ([raw file](https://github.com/badgertechnologies/amcl/blob/95b6eb20da05f9f418bc7ea0645e69d04bc7dd99/include/amcl/node/node_2d.h#L36)):*
> ```objc
> #include <tf/message_filter.h>
> 
> #include <map>
> ```

std C++ includes should come first, then third party libraries. please correct this everywhere.


<!-- Sent from Reviewable.io -->

2020-03-06 14:49 UTC, c-andy-martin commented
___
*[include/amcl/node/node_3d.h, line 52 at r5](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M1kJibc1KJknB8Bp7za:-M1kJibc1KJknB8Bp7zb:b95p16i) ([raw file](https://github.com/badgertechnologies/amcl/blob/95b6eb20da05f9f418bc7ea0645e69d04bc7dd99/include/amcl/node/node_3d.h#L52)):*
> ```objc
> 
> class Node;
> struct PoseHypothesis;
> ```

This line is unnecessary, please remove it.


<!-- Sent from Reviewable.io -->

2020-03-06 14:51 UTC, c-andy-martin commented
___
*[include/amcl/node/node_3d.h, line 93 at r5](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M1kK-FF-kFPK8QYkRT2:-M1kK-FF-kFPK8QYkRT3:b742qag) ([raw file](https://github.com/badgertechnologies/amcl/blob/95b6eb20da05f9f418bc7ea0645e69d04bc7dd99/include/amcl/node/node_3d.h#L93)):*
> ```objc
>   void checkScanReceived(const ros::TimerEvent& event);
> 
>   std::shared_ptr<OctoMap> map_;
> ```

Please check each of these shared_ptr and unique_ptr to see if they can just be included in the class directly. I'm sure some of these are constructed on the fly, or generated by other classes, in which case they are fine. But esp. the unique_ptr, see if you can just construct them with the class to eliminate extra dynamic memory use.


<!-- Sent from Reviewable.io -->

2020-03-06 14:52 UTC, c-andy-martin commented
___
*[include/amcl/node/node_3d.h, line 103 at r5](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M1kKIww8tBu0jk4xh4P:-M1kKIww8tBu0jk4xh4Q:b-85m2c7) ([raw file](https://github.com/badgertechnologies/amcl/blob/95b6eb20da05f9f418bc7ea0645e69d04bc7dd99/include/amcl/node/node_3d.h#L103)):*
> ```objc
>   std::unique_ptr<tf::MessageFilter<sensor_msgs::PointCloud2>> scan_filter_;
>   std::string scan_topic_;
>   std::string odom_frame_id_;
> ```

these could probably just be accessed from the node instead of stored twice.


<!-- Sent from Reviewable.io -->

2020-03-06 14:54 UTC, c-andy-martin commented
___
*[include/amcl/node/node_3d.h, line 122 at r5](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M1kKcSj8NR86aThEKTK:-M1kKcSj8NR86aThEKTL:b-2fzeku) ([raw file](https://github.com/badgertechnologies/amcl/blob/95b6eb20da05f9f418bc7ea0645e69d04bc7dd99/include/amcl/node/node_3d.h#L122)):*
> ```objc
>   tf::TransformListener tf_;
>   tf::StampedTransform scanner_to_footprint_tf_;
>   int map_type_;
> ```

seems like you know the map_type_ is going to be 3 here no matter what? do you need to store it here?


<!-- Sent from Reviewable.io -->

2020-03-06 14:56 UTC, c-andy-martin requested changes
> Reviewed 1 of 38 files at r4.
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/amcl/2)* status: 12 of 52 files reviewed, 63 unresolved discussions (waiting on @12tbuchman and @c-andy-martin)

___
*[include/amcl/pf/eig3.h, line 22 at r5](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M1kKrMO-YYY9EGFNJhW:-M1kKrMO-YYY9EGFNJhX:b-miv8xq) ([raw file](https://github.com/badgertechnologies/amcl/blob/95b6eb20da05f9f418bc7ea0645e69d04bc7dd99/include/amcl/pf/eig3.h#L22)):*
> ```objc
> {
> public:
>   static void eigenDecomposition(const PFMatrix& A, PFMatrix* V, PFVector* d);
> ```

Please take a to-do Jira ticket to have AMCL simply use the Eigen library for all vector, matrix, quaternion, eigen decomposition, etc. TF already uses Eigen for this so its not really a new dependency. Eigen is highly optomized and there is no reason to have yet-another-vector-implementation. However, I know we inherited this from the legacy AMCL code and don't think we have to do this before the first iteration. But I want to do it sometime as part of the overall cleanup work.


<!-- Sent from Reviewable.io -->

2020-03-06 14:57 UTC, c-andy-martin commented
___
*[include/amcl/pf/particle_filter.h, line 37 at r5](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M1kLKrS4a02WTTUFvRj:-M1kLKrS4a02WTTUFvRk:b-pl5ac4) ([raw file](https://github.com/badgertechnologies/amcl/blob/95b6eb20da05f9f418bc7ea0645e69d04bc7dd99/include/amcl/pf/particle_filter.h#L37)):*
> ```objc
> namespace amcl
> {
> typedef enum {
> ```

This brace should not be cuddled


<!-- Sent from Reviewable.io -->

2020-03-06 14:58 UTC, c-andy-martin commented
___
*[include/amcl/pf/particle_filter.h, line 40 at r5](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M1kLaDGCVHIfEzR86ki:-M1kLPOUC71EnfHVM3gk:b-gggp0l) ([raw file](https://github.com/badgertechnologies/amcl/blob/95b6eb20da05f9f418bc7ea0645e69d04bc7dd99/include/amcl/pf/particle_filter.h#L40)):*
> ```objc
>   PF_RESAMPLE_MULTINOMIAL,
>   PF_RESAMPLE_SYSTEMATIC,
> } PFResampleModelType;
> ```

Lets take a Jira to-do to make these object oriented. Instead of switch/case on an enumeration, we should have a common base class for resample, and various subclasses which implement the desired behavior.


<!-- Sent from Reviewable.io -->

2020-03-06 14:59 UTC, c-andy-martin commented
___
*[include/amcl/pf/particle_filter.h, line 43 at r5](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M1kLn3s3L-w97wOWw7b:-M1kLn3s3L-w97wOWw7c:b-b9yp22) ([raw file](https://github.com/badgertechnologies/amcl/blob/95b6eb20da05f9f418bc7ea0645e69d04bc7dd99/include/amcl/pf/particle_filter.h#L43)):*
> ```objc
> 
> // Information for a single sample
> typedef struct
> ```

In c++ there is no reason for this `typedef`. Please search and make all `typedef struct` => `struct`


<!-- Sent from Reviewable.io -->

2020-03-06 14:59 UTC, c-andy-martin commented
___
*[include/amcl/pf/particle_filter.h, line 79 at r5](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M1kM0BGBcebZzB_hJ1N:-M1kM0BGBcebZzB_hJ1O:bpdorxm) ([raw file](https://github.com/badgertechnologies/amcl/blob/95b6eb20da05f9f418bc7ea0645e69d04bc7dd99/include/amcl/pf/particle_filter.h#L79)):*
> ```objc
> 
>   // A kdtree encoding the histogram
>   std::shared_ptr<PFKDTree> kdtree;
> ```

does this need to be a shared_ptr?


<!-- Sent from Reviewable.io -->

2020-03-06 15:00 UTC, c-andy-martin commented
___
*[include/amcl/pf/particle_filter.h, line 79 at r5](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M1kM0BGBcebZzB_hJ1N:-M1kM32cBVCjEWkX2V__:b-izk94v) ([raw file](https://github.com/badgertechnologies/amcl/blob/95b6eb20da05f9f418bc7ea0645e69d04bc7dd99/include/amcl/pf/particle_filter.h#L79)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

does this need to be a shared_ptr?
</blockquote></details>

(in other words, can we just include the kdtree directly as `PFKDTree kdtree`?)


<!-- Sent from Reviewable.io -->

2020-03-06 15:01 UTC, c-andy-martin commented
___
*[include/amcl/pf/particle_filter.h, line 99 at r5](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M1kMDwa9mKi8bJOuNB7:-M1kMDwa9mKi8bJOuNB8:b6l3wmk) ([raw file](https://github.com/badgertechnologies/amcl/blob/95b6eb20da05f9f418bc7ea0645e69d04bc7dd99/include/amcl/pf/particle_filter.h#L99)):*
> ```objc
>   // Create a new filter
>   ParticleFilter(int min_samples, int max_samples, double alpha_slow, double alpha_fast,
>                  std::shared_ptr<std::function<PFVector()>> random_pose_fn_ptr);
> ```

as I pointed out elsewhere, there is no need to pass the std::function in a std::pointer, its already a pointer, and doesn't need to be reference counted


<!-- Sent from Reviewable.io -->

2020-03-06 15:01 UTC, c-andy-martin commented
___
*[include/amcl/pf/particle_filter.h, line 112 at r5](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M1kMPBj0w2COsU67oCm:-M1kMPBj0w2COsU67oCn:b52nqg2) ([raw file](https://github.com/badgertechnologies/amcl/blob/95b6eb20da05f9f418bc7ea0645e69d04bc7dd99/include/amcl/pf/particle_filter.h#L112)):*
> ```objc
> 
>   // Initialize the filter using some model
>   void initModel(std::shared_ptr<std::function<PFVector()>> init_fn);
> ```

Please clean up all the places where we wrap std::function in std::shared_ptr, as it is unnecessary


<!-- Sent from Reviewable.io -->

2020-03-06 15:07 UTC, c-andy-martin commented
___
*[include/amcl/pf/particle_filter.h, line 178 at r5](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M1kMuLd2uuD-WiRy90k:-M1kMuLd2uuD-WiRy90l:b-bbsdf0) ([raw file](https://github.com/badgertechnologies/amcl/blob/95b6eb20da05f9f418bc7ea0645e69d04bc7dd99/include/amcl/pf/particle_filter.h#L178)):*
> ```objc
>   // The sample sets.  We keep two sets and use [current_set]
>   // to identify the active set.
>   int current_set_;
> ```

Maybe instead of this old way of double buffering from C, we could use the vector below as a double-ended queue. Then `push_back` new sample sets (maybe you don't even need a pointer to the sample set?) and when `size() > 2` after a `push_back` do a `pop_front`. Then all code can use the `back()` as the most recent set, and `front()` as the oldest set, or `sets_[sets_.size()-2]` as the second newest. This would make it easier to keep 3 or more sets down the road.


<!-- Sent from Reviewable.io -->

2020-03-06 15:08 UTC, c-andy-martin reviewed
> Reviewed 1 of 38 files at r4.
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/amcl/2)* status: 13 of 52 files reviewed, 70 unresolved discussions (waiting on @12tbuchman and @c-andy-martin)



<!-- Sent from Reviewable.io -->

2020-03-06 15:08 UTC, c-andy-martin reviewed
> Reviewed 1 of 38 files at r4.
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/amcl/2)* status: 14 of 52 files reviewed, 70 unresolved discussions (waiting on @12tbuchman and @c-andy-martin)



<!-- Sent from Reviewable.io -->

2020-03-06 15:09 UTC, c-andy-martin commented
___
*[include/amcl/pf/pdf_gaussian.h, line 37 at r5](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M1kO4JI7njE3akqKM44:-M1kO4JJBqHR4_WRLUIb:b7p153k) ([raw file](https://github.com/badgertechnologies/amcl/blob/95b6eb20da05f9f418bc7ea0645e69d04bc7dd99/include/amcl/pf/pdf_gaussian.h#L37)):*
> ```objc
> namespace amcl
> {
> // Gaussian PDF info
> ```

PDF is too dense, please explain here what a PDF is.


<!-- Sent from Reviewable.io -->

2020-03-06 15:12 UTC, c-andy-martin commented
___
*[include/amcl/pf/pf_kdtree.h, line 34 at r5](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M1kOndf5KzK4wUvmLGJ:-M1kOndf5KzK4wUvmLGK:b1mq9q5) ([raw file](https://github.com/badgertechnologies/amcl/blob/95b6eb20da05f9f418bc7ea0645e69d04bc7dd99/include/amcl/pf/pf_kdtree.h#L34)):*
> ```objc
> {
> // Info for a node in the tree
> typedef struct pf_kdtree_node
> ```

Let's take a Jira to-do ticket to research replacing this entire implementation w/ PCL's kdtree implementation.


<!-- Sent from Reviewable.io -->

2020-03-06 15:14 UTC, c-andy-martin reviewed
> Reviewed 1 of 47 files at r1, 2 of 38 files at r4.
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/amcl/2)* status: 17 of 52 files reviewed, 72 unresolved discussions (waiting on @12tbuchman and @c-andy-martin)



<!-- Sent from Reviewable.io -->

2020-03-06 15:17 UTC, c-andy-martin commented
___
*[include/amcl/sensors/odom.h, line 45 at r5](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M1kPzWfDU0CwL8YlcQJ:-M1kPzWfDU0CwL8YlcQK:b-q8hrst) ([raw file](https://github.com/badgertechnologies/amcl/blob/95b6eb20da05f9f418bc7ea0645e69d04bc7dd99/include/amcl/sensors/odom.h#L45)):*
> ```objc
>   ODOM_MODEL_OMNI_CORRECTED,
>   ODOM_MODEL_GAUSSIAN,
> } OdomModelType;
> ```

Let's take a todo ticket to make the odometry models object-oriented


<!-- Sent from Reviewable.io -->

2020-03-06 15:18 UTC, c-andy-martin reviewed
> Reviewed 2 of 47 files at r1, 2 of 38 files at r4.
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/amcl/2)* status: 21 of 52 files reviewed, 73 unresolved discussions (waiting on @12tbuchman and @c-andy-martin)



<!-- Sent from Reviewable.io -->

2020-03-06 15:20 UTC, c-andy-martin commented
___
*[include/amcl/sensors/planar_scanner.h, line 30 at r5](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M1kQTc_Dpc0G0ELY03o:-M1kQTc_Dpc0G0ELY03p:b-7wxqyx) ([raw file](https://github.com/badgertechnologies/amcl/blob/95b6eb20da05f9f418bc7ea0645e69d04bc7dd99/include/amcl/sensors/planar_scanner.h#L30)):*
> ```objc
> #define AMCL_SENSORS_PLANAR_SCANNER_H
> 
> #include "sensors/sensor.h"
> ```

this should come as the very last include


<!-- Sent from Reviewable.io -->

2020-03-06 15:20 UTC, c-andy-martin commented
___
*[include/amcl/sensors/planar_scanner.h, line 32 at r5](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M1kQVsc7FIh8Ld6-MKw:-M1kQVsc7FIh8Ld6-MKx:b-3qmldx) ([raw file](https://github.com/badgertechnologies/amcl/blob/95b6eb20da05f9f418bc7ea0645e69d04bc7dd99/include/amcl/sensors/planar_scanner.h#L32)):*
> ```objc
> #include "sensors/sensor.h"
> 
> #include <stddef.h>
> ```

change C headers to C++, so this should be `<cstddef>` and add `std::` where necessary, also then delete the newline below.


<!-- Sent from Reviewable.io -->

2020-03-06 15:21 UTC, c-andy-martin commented
___
*[include/amcl/sensors/planar_scanner.h, line 48 at r5](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M1kQkM51OOq16eqte-r:-M1kQkM51OOq16eqte-s:b-z5xq26) ([raw file](https://github.com/badgertechnologies/amcl/blob/95b6eb20da05f9f418bc7ea0645e69d04bc7dd99/include/amcl/sensors/planar_scanner.h#L48)):*
> ```objc
>   PLANAR_MODEL_LIKELIHOOD_FIELD_PROB,
>   PLANAR_MODEL_LIKELIHOOD_FIELD_GOMPERTZ,
> } PlanarModelType;
> ```

Let's take a to do to make this part object-oriented. So you would have a SensorModelInterface of some sort (feel free to name it to anything appropriate) and make child classes for each type. But feel free to defer this using a jira ticket.


<!-- Sent from Reviewable.io -->

2020-03-06 15:26 UTC, c-andy-martin commented
___
*[include/amcl/sensors/planar_scanner.h, line 54 at r5](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M1kR5Fu9PnaXDqbfuVW:-M1kR5Fu9PnaXDqbfuVX:b-j1o1dv) ([raw file](https://github.com/badgertechnologies/amcl/blob/95b6eb20da05f9f418bc7ea0645e69d04bc7dd99/include/amcl/sensors/planar_scanner.h#L54)):*
> ```objc
> {
> public:
>   PlanarData(){};
> ```

Either add a space here like this:
`PlanarData() {}`, or you could also do `PlanarData() = default;`. I would do the same for the destructor. The empty brace formatting follows an example here:
https://google.github.io/styleguide/cppguide.html#Horizontal_Whitespace
There is also an example there of how to do the spacing if you want to have something in the one-line body.


<!-- Sent from Reviewable.io -->

2020-03-06 15:27 UTC, c-andy-martin commented
___
*[include/amcl/sensors/planar_scanner.h, line 66 at r5](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M1kSFZ0C76P5pesD6WA:-M1kSFZ0C76P5pesD6WB:buxuvpj) ([raw file](https://github.com/badgertechnologies/amcl/blob/95b6eb20da05f9f418bc7ea0645e69d04bc7dd99/include/amcl/sensors/planar_scanner.h#L66)):*
> ```objc
> class PlanarScanner : public Sensor
> {
>   // Default constructor
> ```

I don't think this comment adds anything, just delete it


<!-- Sent from Reviewable.io -->

2020-03-06 15:29 UTC, c-andy-martin commented
___
*[include/amcl/sensors/planar_scanner.h, line 70 at r5](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M1kSW0uDirPazZ5LxCL:-M1kSW0uDirPazZ5LxCM:b-lo3rw9) ([raw file](https://github.com/badgertechnologies/amcl/blob/95b6eb20da05f9f418bc7ea0645e69d04bc7dd99/include/amcl/sensors/planar_scanner.h#L70)):*
> ```objc
>   PlanarScanner();
> 
>   void init(size_t max_beams, std::shared_ptr<OccupancyMap> map);
> ```

I would make `max_beams` an `int`. It is elsewhere, and we might want to set it to something negative to indicate to use all the data.


<!-- Sent from Reviewable.io -->

2020-03-06 15:30 UTC, c-andy-martin reviewed
> Reviewed 1 of 38 files at r4.
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/amcl/2)* status: 22 of 52 files reviewed, 79 unresolved discussions (waiting on @12tbuchman and @c-andy-martin)



<!-- Sent from Reviewable.io -->

2020-03-06 15:31 UTC, c-andy-martin commented
___
*[include/amcl/sensors/point_cloud_scanner.h, line 43 at r5](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M1kT5vi8gTUmaqE_8Uo:-M1kT5vi8gTUmaqE_8Up:b-gcin4p) ([raw file](https://github.com/badgertechnologies/amcl/blob/95b6eb20da05f9f418bc7ea0645e69d04bc7dd99/include/amcl/sensors/point_cloud_scanner.h#L43)):*
> ```objc
> typedef enum {
>   POINT_CLOUD_MODEL,
>   POINT_CLOUD_MODEL_GOMPERTZ,
> ```

and, again, let's take a to-do to make these object oriented.


<!-- Sent from Reviewable.io -->

2020-03-06 15:31 UTC, c-andy-martin commented
___
*[include/amcl/sensors/point_cloud_scanner.h, line 49 at r5](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M1kTD334SHaNPqKXsC2:-M1kTD334SHaNPqKXsC3:br5vmzh) ([raw file](https://github.com/badgertechnologies/amcl/blob/95b6eb20da05f9f418bc7ea0645e69d04bc7dd99/include/amcl/sensors/point_cloud_scanner.h#L49)):*
> ```objc
> {
> public:
>   PointCloudData(){};
> ```

Please check for spacing everywhere w/ empty braces (there should be a space before them)


<!-- Sent from Reviewable.io -->

2020-03-06 15:33 UTC, c-andy-martin commented
___
*[include/amcl/sensors/sensor.h, line 68 at r5](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M1kTkS3BpdklAMM7bxi:-M1kTkS3BpdklAMM7bxj:b-y10ead) ([raw file](https://github.com/badgertechnologies/amcl/blob/95b6eb20da05f9f418bc7ea0645e69d04bc7dd99/include/amcl/sensors/sensor.h#L68)):*
> ```objc
>   {
>   }
>   std::shared_ptr<Sensor> sensor_;
> ```

This should probably be under a `protected:`


<!-- Sent from Reviewable.io -->

2020-03-06 15:35 UTC, c-andy-martin commented
___
*[include/amcl/sensors/sensor.h, line 41 at r5](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M1kUBAP0NkoUk1_MLzx:-M1kUBAP0NkoUk1_MLzy:b-ovmlw9) ([raw file](https://github.com/badgertechnologies/amcl/blob/95b6eb20da05f9f418bc7ea0645e69d04bc7dd99/include/amcl/sensors/sensor.h#L41)):*
> ```objc
> {
> public:
>   // Default constructor
> ```

Let's ditch this comment


<!-- Sent from Reviewable.io -->

2020-03-06 15:35 UTC, c-andy-martin commented
___
*[include/amcl/sensors/sensor.h, line 44 at r5](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M1kUDPz7qpAzw98KsUM:-M1kUDPz7qpAzw98KsUN:b-ovmlw9) ([raw file](https://github.com/badgertechnologies/amcl/blob/95b6eb20da05f9f418bc7ea0645e69d04bc7dd99/include/amcl/sensors/sensor.h#L44)):*
> ```objc
>   Sensor();
> 
>   // Default destructor
> ```

Let's ditch this comment


<!-- Sent from Reviewable.io -->

2020-03-06 15:36 UTC, c-andy-martin commented
___
*[include/amcl/sensors/sensor.h, line 42 at r5](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M1kUHaL8lNY45xcEJyW:-M1kUHaL8lNY45xcEJyX:bh3czk3) ([raw file](https://github.com/badgertechnologies/amcl/blob/95b6eb20da05f9f418bc7ea0645e69d04bc7dd99/include/amcl/sensors/sensor.h#L42)):*
> ```objc
> public:
>   // Default constructor
>   Sensor();
> ```

I don't bother declaring and defining default constructors that do nothing, the compiler will already do that for you


<!-- Sent from Reviewable.io -->

2020-03-06 15:37 UTC, c-andy-martin requested changes
> Reviewed 1 of 38 files at r4.
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/amcl/2)* status: 23 of 52 files reviewed, 87 unresolved discussions (waiting on @12tbuchman and @c-andy-martin)

___
*[include/amcl/sensors/sensor.h, line 45 at r5](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M1kUVD27z984HDJquNf:-M1kUVD27z984HDJquNg:bxo9pmr) ([raw file](https://github.com/badgertechnologies/amcl/blob/95b6eb20da05f9f418bc7ea0645e69d04bc7dd99/include/amcl/sensors/sensor.h#L45)):*
> ```objc
> 
>   // Default destructor
>   virtual ~Sensor();
> ```

Go ahead and define the destructor here as either `virtual ~Sensor() = default;` or `virtual ~Sensor() {};`. Once doing this, and doing the below pure-virtual work, you can delete the sensor.cpp entirely
___
*[include/amcl/sensors/sensor.h, line 49 at r5](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M1kTx1r3nem51_v4H2_:-M1kTx1r3nem51_v4H2a:b67k891) ([raw file](https://github.com/badgertechnologies/amcl/blob/95b6eb20da05f9f418bc7ea0645e69d04bc7dd99/include/amcl/sensors/sensor.h#L49)):*
> ```objc
>   // Update the filter based on the action model.  Returns true if the filter
>   // has been updated.
>   virtual bool updateAction(std::shared_ptr<ParticleFilter> pf, std::shared_ptr<SensorData> data);
> ```

Make this and all the below methods pure virtual by adding `= 0;` and removing the definition in the .cpp file.


<!-- Sent from Reviewable.io -->

2020-03-06 15:39 UTC, c-andy-martin commented
___
*[src/main.cpp, line 57 at r5](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M1kV3EY261uihUBhw97:-M1kV3EY261uihUBhw98:b453q4i) ([raw file](https://github.com/badgertechnologies/amcl/blob/95b6eb20da05f9f418bc7ea0645e69d04bc7dd99/src/main.cpp#L57)):*
> ```cpp
>   amcl_node_ptr.reset(new Node());
> 
>   // Uncomment for single threaded
> ```

Lets delete these 4 commented lines


<!-- Sent from Reviewable.io -->

2020-03-06 15:40 UTC, c-andy-martin commented
___
*[src/main.cpp, line 19 at r5](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M1kVD8KCQV1CdnFOEm1:-M1kVD8KCQV1CdnFOEm2:b-947j12) ([raw file](https://github.com/badgertechnologies/amcl/blob/95b6eb20da05f9f418bc7ea0645e69d04bc7dd99/src/main.cpp#L19)):*
> ```cpp
>  *  Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
>  *
>  *  Maintainter: Tyler Buchman (tyler_buchman@jabil.com)
> ```

I'm for removing this line and just having you listed in package.xml


<!-- Sent from Reviewable.io -->

2020-03-06 15:40 UTC, c-andy-martin commented
___
*[src/main.cpp, line 23 at r5](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M1kVHWNEZnN51In5JgO:-M1kVHWNEZnN51In5JgP:b-evptw6) ([raw file](https://github.com/badgertechnologies/amcl/blob/95b6eb20da05f9f418bc7ea0645e69d04bc7dd99/src/main.cpp#L23)):*
> ```cpp
>  */
> 
> #include <boost/shared_ptr.hpp>
> ```

let's get rid of `boost::shared_ptr` and only use `std::shared_ptr`


<!-- Sent from Reviewable.io -->

2020-03-06 15:41 UTC, c-andy-martin commented
___
*[src/main.cpp, line 33 at r5](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M1kVQ1p6HMeVfd8ij7f:-M1kVQ1p6HMeVfd8ij7g:b-khu85c) ([raw file](https://github.com/badgertechnologies/amcl/blob/95b6eb20da05f9f418bc7ea0645e69d04bc7dd99/src/main.cpp#L33)):*
> ```cpp
> #include "node/node.h"
> 
> using namespace amcl;
> ```

I much prefer not to do this. Just add `amcl::` where necessary.


<!-- Sent from Reviewable.io -->

2020-03-06 15:41 UTC, c-andy-martin commented
___
*[src/main.cpp, line 69 at r5](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M1kVWSB4r32RTIPOynu:-M1kVWSC5kn81gMQlqdj:b-rtagwg) ([raw file](https://github.com/badgertechnologies/amcl/blob/95b6eb20da05f9f418bc7ea0645e69d04bc7dd99/src/main.cpp#L69)):*
> ```cpp
>   amcl_node_ptr.reset();
> 
>   // To quote Morgan, Hooray!
> ```

delete


<!-- Sent from Reviewable.io -->

2020-03-06 15:41 UTC, c-andy-martin commented
___
*[src/main.cpp, line 66 at r5](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M1kVZRm7R_yEgG_Xvch:-M1kVZRm7R_yEgG_Xvci:b-pys5oa) ([raw file](https://github.com/badgertechnologies/amcl/blob/95b6eb20da05f9f418bc7ea0645e69d04bc7dd99/src/main.cpp#L66)):*
> ```cpp
>   amcl_node_ptr->savePoseToFile();
> 
>   // Without this, our boost locks are not shut down nicely
> ```

Remove `boost`


<!-- Sent from Reviewable.io -->

2020-03-06 15:42 UTC, c-andy-martin commented
___
*[src/main.cpp, line 54 at r5](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M1kVgHZ1pQ9sfrw_K4Z:-M1kVgHZ1pQ9sfrw_K4_:be0zby1) ([raw file](https://github.com/badgertechnologies/amcl/blob/95b6eb20da05f9f418bc7ea0645e69d04bc7dd99/src/main.cpp#L54)):*
> ```cpp
>   signal(SIGTERM, sigHandler);
> 
>   // Make our node available to sigintHandler
> ```

This comment is misleading, it's not even correct. Remove.


<!-- Sent from Reviewable.io -->

2020-03-06 15:43 UTC, c-andy-martin commented
___
*[src/main.cpp, line 40 at r5](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M1kVxBZ8oaqsRf5eaiN:-M1kVxBZ8oaqsRf5eaiO:bw1bvbw) ([raw file](https://github.com/badgertechnologies/amcl/blob/95b6eb20da05f9f418bc7ea0645e69d04bc7dd99/src/main.cpp#L40)):*
> ```cpp
> void sigHandler(int sig)
> {
>   std::cout << "Sig int detected, ros shutting down.\n";
> ```

It is not safe to use `cout` in a signal handler. Delete this line.


<!-- Sent from Reviewable.io -->

2020-03-06 15:45 UTC, c-andy-martin commented
___
*[src/main.cpp, line 55 at r5](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M1kWKs56RFgmX6OOT-6:-M1kWKs56RFgmX6OOT-7:b-fg8n0m) ([raw file](https://github.com/badgertechnologies/amcl/blob/95b6eb20da05f9f418bc7ea0645e69d04bc7dd99/src/main.cpp#L55)):*
> ```cpp
> 
>   // Make our node available to sigintHandler
>   amcl_node_ptr.reset(new Node());
> ```

I see no reason to wrap Node in a shared pointer. Let's wrap it in a unique_ptr instead. Also, instead of the reset() below, just put the unique_ptr in a nested scope.


<!-- Sent from Reviewable.io -->

2020-03-06 15:47 UTC, c-andy-martin commented
___
*[src/main.cpp, line 35 at r5](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M1kWnl7CYpiNV8nWCAR:-M1kWnl7CYpiNV8nWCAS:bya8ydv) ([raw file](https://github.com/badgertechnologies/amcl/blob/95b6eb20da05f9f418bc7ea0645e69d04bc7dd99/src/main.cpp#L35)):*
> ```cpp
> using namespace amcl;
> 
> boost::shared_ptr<Node> amcl_node_ptr;
> ```

move this into `main()`. as i point out there, make it a unique_ptr


<!-- Sent from Reviewable.io -->

2020-03-06 15:47 UTC, c-andy-martin requested changes
> Reviewed 1 of 47 files at r1, 1 of 38 files at r4.
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/amcl/2)* status: 25 of 52 files reviewed, 99 unresolved discussions (waiting on @12tbuchman and @c-andy-martin)

___
*[src/main.cpp, line 29 at r5](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M1kVMWu5richnnvl4gC:-M1kVMWv7YDSpOct55sv:b-h437br) ([raw file](https://github.com/badgertechnologies/amcl/blob/95b6eb20da05f9f418bc7ea0645e69d04bc7dd99/src/main.cpp#L29)):*
> ```cpp
> #include <signal.h>
> 
> #include <iostream>
> ```

iostream should come first, as its a C++ std include
___
*[src/main.cpp, line 36 at r5](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M1kW2cX8M-jt8r-xnoj:-M1kW2cX8M-jt8r-xnok:b-grnejk) ([raw file](https://github.com/badgertechnologies/amcl/blob/95b6eb20da05f9f418bc7ea0645e69d04bc7dd99/src/main.cpp#L36)):*
> ```cpp
> 
> boost::shared_ptr<Node> amcl_node_ptr;
> bool sigFlag = false;
> ```

sigFlag is unused. Delete it here and below.


<!-- Sent from Reviewable.io -->

2020-03-06 15:47 UTC, c-andy-martin reviewed
> Reviewed 1 of 47 files at r1, 1 of 32 files at r3.
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/amcl/2)* status: 27 of 52 files reviewed, 99 unresolved discussions (waiting on @12tbuchman and @c-andy-martin)



<!-- Sent from Reviewable.io -->

2020-03-06 15:57 UTC, c-andy-martin reviewed
> Reviewed 6 of 47 files at r1.
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/amcl/2)* status: 33 of 52 files reviewed, 99 unresolved discussions (waiting on @12tbuchman and @c-andy-martin)



<!-- Sent from Reviewable.io -->

2020-03-06 15:58 UTC, c-andy-martin reviewed
> Reviewed 1 of 38 files at r4.
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/amcl/2)* status: 34 of 52 files reviewed, 99 unresolved discussions (waiting on @12tbuchman and @c-andy-martin)



<!-- Sent from Reviewable.io -->

2020-03-06 16:00 UTC, c-andy-martin commented
___
*[src/amcl/pf/pf_vector.cpp, line 33 at r5](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M1kZZq20MeLI0AhSGkg:-M1kZZq20MeLI0AhSGkh:bb8dv6q) ([raw file](https://github.com/badgertechnologies/amcl/blob/95b6eb20da05f9f418bc7ea0645e69d04bc7dd99/src/amcl/pf/pf_vector.cpp#L33)):*
> ```cpp
> #include "pf/eig3.h"
> 
> using namespace amcl;
> ```

I would much prefer putting this in the amcl namespace, not having a using namespace. So this would become:

```
namespace amcl
{
...
```


<!-- Sent from Reviewable.io -->

2020-03-06 16:00 UTC, c-andy-martin commented
___
*[src/amcl/pf/pf_vector.cpp, line 28 at r5](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M1kZs6gAtRKGI2POYBm:-M1kZs6gAtRKGI2POYBn:b-maz6b1) ([raw file](https://github.com/badgertechnologies/amcl/blob/95b6eb20da05f9f418bc7ea0645e69d04bc7dd99/src/amcl/pf/pf_vector.cpp#L28)):*
> ```cpp
> #include "pf/pf_vector.h"
> 
> #include <math.h>
> ```

Use `<cmath>`


<!-- Sent from Reviewable.io -->

2020-03-06 16:01 UTC, c-andy-martin commented
___
*[src/amcl/pf/pf_vector.cpp, line 35 at r5](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M1kZymJ0vdXpVe63j8v:-M1kZymJ0vdXpVe63j8w:borvo2b) ([raw file](https://github.com/badgertechnologies/amcl/blob/95b6eb20da05f9f418bc7ea0645e69d04bc7dd99/src/amcl/pf/pf_vector.cpp#L35)):*
> ```cpp
> using namespace amcl;
> 
> // Return a zero vector
> ```

Delete this incorrect comment. Constructors do not return anything


<!-- Sent from Reviewable.io -->

2020-03-06 16:05 UTC, c-andy-martin commented
___
*[src/amcl/pf/pf_vector.cpp, line 80 at r5](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M1k_g45CPw0IObUAVSi:-M1k_g45CPw0IObUAVSj:b-kbju6h) ([raw file](https://github.com/badgertechnologies/amcl/blob/95b6eb20da05f9f418bc7ea0645e69d04bc7dd99/src/amcl/pf/pf_vector.cpp#L80)):*
> ```cpp
>   c.v[1] = b.v[1] + a.v[0] * sin(b.v[2]) + a.v[1] * cos(b.v[2]);
>   c.v[2] = b.v[2] + a.v[2];
>   c.v[2] = atan2(sin(c.v[2]), cos(c.v[2]));
> ```

This is not an efficient way to normalize an angle. I would use `angles::normalize_angle`


<!-- Sent from Reviewable.io -->

2020-03-06 16:12 UTC, c-andy-martin commented
___
*[src/amcl/pf/pf_vector.cpp, line 91 at r5](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M1kb_Qg8iVXmH5GWWv0:-M1kb_Qg8iVXmH5GWWv1:bfqdgq0) ([raw file](https://github.com/badgertechnologies/amcl/blob/95b6eb20da05f9f418bc7ea0645e69d04bc7dd99/src/amcl/pf/pf_vector.cpp#L91)):*
> ```cpp
>   c.v[1] = -(a.v[0] - b.v[0]) * sin(b.v[2]) + (a.v[1] - b.v[1]) * cos(b.v[2]);
>   c.v[2] = a.v[2] - b.v[2];
>   c.v[2] = atan2(sin(c.v[2]), cos(c.v[2]));
> ```

and here too (and anywhere you spy `atan2(sin(theta), cos(theta))`)


<!-- Sent from Reviewable.io -->

2020-03-06 16:14 UTC, c-andy-martin commented
___
*[src/amcl/pf/pf_vector.cpp, line 140 at r5](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M1kbnvkBWxNqTx_mNE1:-M1kbnvkBWxNqTx_mNE2:bquudte) ([raw file](https://github.com/badgertechnologies/amcl/blob/95b6eb20da05f9f418bc7ea0645e69d04bc7dd99/src/amcl/pf/pf_vector.cpp#L140)):*
> ```cpp
>   for (i = 0; i < 3; i++)
>   {
>     d->m[i][i] = eval.v[i];
> ```

This assignment does nothing, it gets erased by the loop below. Maybe we should be assigning `v` on the left? Maybe this is one of the bugs breaking things?


<!-- Sent from Reviewable.io -->

2020-03-06 16:15 UTC, c-andy-martin commented
___
*[src/amcl/pf/pf_vector.cpp, line 140 at r5](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M1kbnvkBWxNqTx_mNE1:-M1kcArv4HI4OffA5tL1:b-cl8lrd) ([raw file](https://github.com/badgertechnologies/amcl/blob/95b6eb20da05f9f418bc7ea0645e69d04bc7dd99/src/amcl/pf/pf_vector.cpp#L140)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

This assignment does nothing, it gets erased by the loop below. Maybe we should be assigning `v` on the left? Maybe this is one of the bugs breaking things?
</blockquote></details>

Oops, this is `d`, not `r`. This looks OK.


<!-- Sent from Reviewable.io -->

2020-03-06 16:15 UTC, c-andy-martin requested changes
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/amcl/2)* status: 34 of 52 files reviewed, 108 unresolved discussions (waiting on @12tbuchman and @c-andy-martin)

___
*[src/amcl/pf/pf_vector.cpp, line 48 at r5](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M1k_6dI3y5I-smNrJPo:-M1k_6dI3y5I-smNrJPp:btgj1hv) ([raw file](https://github.com/badgertechnologies/amcl/blob/95b6eb20da05f9f418bc7ea0645e69d04bc7dd99/src/amcl/pf/pf_vector.cpp#L48)):*
> ```cpp
>   int i;
>   for (i = 0; i < 3; i++)
>     if (!isfinite(v[i]))
> ```

this will become `std::isfinite` when switching to `<cmath>` I think.
___
*[src/amcl/pf/pf_vector.cpp, line 49 at r5](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M1k_B_A8mGy9YTWccoc:-M1k_B_A8mGy9YTWccod:b4jcmsz) ([raw file](https://github.com/badgertechnologies/amcl/blob/95b6eb20da05f9f418bc7ea0645e69d04bc7dd99/src/amcl/pf/pf_vector.cpp#L49)):*
> ```cpp
>   for (i = 0; i < 3; i++)
>     if (!isfinite(v[i]))
>       return 0;
> ```

change `0` to `false`
___
*[src/amcl/pf/pf_vector.cpp, line 50 at r5](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M1k_DVC9ZRamhyouokJ:-M1k_DVC9ZRamhyouokK:bku0xuj) ([raw file](https://github.com/badgertechnologies/amcl/blob/95b6eb20da05f9f418bc7ea0645e69d04bc7dd99/src/amcl/pf/pf_vector.cpp#L50)):*
> ```cpp
>     if (!isfinite(v[i]))
>       return 0;
>   return 1;
> ```

change `1` to `true`
___
*[src/amcl/pf/pf_vector.cpp, line 54 at r5](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M1k_L5DBOPhs14GZZPY:-M1k_L5DBOPhs14GZZPZ:b-hbr100) ([raw file](https://github.com/badgertechnologies/amcl/blob/95b6eb20da05f9f418bc7ea0645e69d04bc7dd99/src/amcl/pf/pf_vector.cpp#L54)):*
> ```cpp
> 
> // Simple vector addition
> PFVector PFVector::pfVectorAdd(PFVector a, PFVector b)
> ```

comment: to make this C++ish would be `operator+`, however, I would much prefer to just delete this whole file and use Eigen vectors. Another reason to make a todo to switch this to Eigen


<!-- Sent from Reviewable.io -->

2020-03-06 16:16 UTC, c-andy-martin reviewed
> Reviewed 1 of 38 files at r4.
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/amcl/2)* status: 35 of 52 files reviewed, 108 unresolved discussions (waiting on @12tbuchman and @c-andy-martin)



<!-- Sent from Reviewable.io -->

2020-03-06 16:20 UTC, c-andy-martin commented
___
*[src/amcl/sensors/odom.cpp, line 22 at r5](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M1kdJi190VT1kE7-Hct:-M1kdJi190VT1kE7-Hcu:bbg4ivp) ([raw file](https://github.com/badgertechnologies/amcl/blob/95b6eb20da05f9f418bc7ea0645e69d04bc7dd99/src/amcl/sensors/odom.cpp#L22)):*
> ```cpp
> /************************************************************************
>  * Desc: AMCL odometry routines
>  * Author: Andrew Howard
> ```

Let's delete this whole block. The true authorship is in the copyright above, let's just have a single point of maintenance for author's etc. in package.xml


<!-- Sent from Reviewable.io -->

2020-03-06 16:20 UTC, c-andy-martin commented
___
*[src/amcl/sensors/odom.cpp, line 31 at r5](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M1kdTA8073H0qYLUft2:-M1kdTA8073H0qYLUft3:b-fl8mw2) ([raw file](https://github.com/badgertechnologies/amcl/blob/95b6eb20da05f9f418bc7ea0645e69d04bc7dd99/src/amcl/sensors/odom.cpp#L31)):*
> ```cpp
> 
> #include <algorithm>
> #include <cmath>
> ```

standard headers should come above `ros/console.h`


<!-- Sent from Reviewable.io -->

2020-03-06 16:21 UTC, c-andy-martin commented
___
*[src/amcl/sensors/odom.cpp, line 82 at r5](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M1kdiuPBlyhbhDt54fg:-M1kdiuPBlyhbhDt54fh:b-lj1oxj) ([raw file](https://github.com/badgertechnologies/amcl/blob/95b6eb20da05f9f418bc7ea0645e69d04bc7dd99/src/amcl/sensors/odom.cpp#L82)):*
> ```cpp
> }
> 
> ////////////////////////////////////////////////////////////////////////////////
> ```

This comment seems useless. Lets delete it.


<!-- Sent from Reviewable.io -->

2020-03-06 16:22 UTC, c-andy-martin requested changes
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/amcl/2)* status: 35 of 52 files reviewed, 113 unresolved discussions (waiting on @12tbuchman and @c-andy-martin)

___
*[src/amcl/sensors/amcl_odom.cpp, line 37 at r5](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M1kdWmR1vPh4El7NT0-:-M1kdWmR1vPh4El7NT00:b-aevkze) ([raw file](https://github.com/badgertechnologies/amcl/blob/8a8873533e84b3894a5f385b1d56234ebbe31d7e/src/amcl/sensors/amcl_odom.cpp#L37)):*
> ```cpp
> #include "amcl_odom.h"
> 
> using namespace amcl;
> ```

I'd rather put this inside the amcl namespace, not use it.
___
*[src/amcl/sensors/odom.cpp, line 307 at r5](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M1kdrAM32YRHjqjCFYj:-M1kdrAM32YRHjqjCFYk:bfpkkwc) ([raw file](https://github.com/badgertechnologies/amcl/blob/95b6eb20da05f9f418bc7ea0645e69d04bc7dd99/src/amcl/sensors/odom.cpp#L307)):*
> ```cpp
> double Odom::angleDiff(double a, double b)
> {
>   double d1, d2;
> ```

Make this use `angles::normalize_angle`, or better, just call `angles::normalize_angle` and get rid of this function.


<!-- Sent from Reviewable.io -->

2020-03-06 16:23 UTC, c-andy-martin commented
___
*[src/amcl/sensors/odom.cpp, line 307 at r5](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M1kdrAM32YRHjqjCFYj:-M1kdzAs2NqdOjFSdazx:bakstz7) ([raw file](https://github.com/badgertechnologies/amcl/blob/95b6eb20da05f9f418bc7ea0645e69d04bc7dd99/src/amcl/sensors/odom.cpp#L307)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

Make this use `angles::normalize_angle`, or better, just call `angles::normalize_angle` and get rid of this function.
</blockquote></details>

sorry, that comment is meant to go up on `normalize`, for this one, use the `angles::shortest_angular_distance`


<!-- Sent from Reviewable.io -->

2020-03-06 16:23 UTC, c-andy-martin commented
___
*[src/amcl/sensors/planar_scanner.cpp, line 22 at r5](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M1ke9zRDFxYUxcB7NTX:-M1ke9zRDFxYUxcB7NTY:by724ig) ([raw file](https://github.com/badgertechnologies/amcl/blob/95b6eb20da05f9f418bc7ea0645e69d04bc7dd99/src/amcl/sensors/planar_scanner.cpp#L22)):*
> ```cpp
> /***********************************************************************
>  * Desc: AMCL planar scanner routines
>  * Author: Andrew Howard
> ```

Delete this whole block please


<!-- Sent from Reviewable.io -->

2020-03-06 16:28 UTC, c-andy-martin requested changes
> Reviewed 1 of 38 files at r4.
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/amcl/2)* status: 36 of 52 files reviewed, 115 unresolved discussions (waiting on @12tbuchman and @c-andy-martin)

___
*[include/amcl/pf/eig3.h, line 25 at r5](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M1kfD_2CvEfz5DDtAf9:-M1kfD_2CvEfz5DDtAfA:b3qersu) ([raw file](https://github.com/badgertechnologies/amcl/blob/95b6eb20da05f9f418bc7ea0645e69d04bc7dd99/include/amcl/pf/eig3.h#L25)):*
> ```objc
> 
> private:
>   static const int N = 3;
> ```

make this a `constexpr` instead of `const`


<!-- Sent from Reviewable.io -->

2020-03-06 16:32 UTC, c-andy-martin commented
___
*[include/amcl/pf/eig3.h, line 27 at r5](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M1kflFt9jKNjt2hGWta:-M1kflFt9jKNjt2hGWtb:bdn0rfn) ([raw file](https://github.com/badgertechnologies/amcl/blob/95b6eb20da05f9f418bc7ea0645e69d04bc7dd99/include/amcl/pf/eig3.h#L27)):*
> ```objc
>   static const int N = 3;
>   static double hypot2(double x, double y);
>   static void tred2(PFMatrix& V, PFVector* d, PFVector* e);
> ```

Since `V` is written to, it should be passed as a pointer to follow the style guide. If this is a pain due to all the lines of code it impacts, rename the argument to `V_ptr` then in the .cpp function add a `PFMatrix& V(*V_ptr);` at the top to keep from having to touch many lines of code. This same advice applies to `tql2` below.


<!-- Sent from Reviewable.io -->

2020-03-06 16:35 UTC, c-andy-martin commented
___
*[src/amcl/pf/eig3.cpp, line 18 at r5](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M1kga-f8duCAuJwDIr2:-M1kga-f8duCAuJwDIr3:b-lqwgs6) ([raw file](https://github.com/badgertechnologies/amcl/blob/95b6eb20da05f9f418bc7ea0645e69d04bc7dd99/src/amcl/pf/eig3.cpp#L18)):*
> ```cpp
> using namespace amcl;
> 
> double EIG3::hypot2(double x, double y)
> ```

Delete this and instead use `std::hypot` from `<cmath>`


<!-- Sent from Reviewable.io -->

2020-03-06 16:44 UTC, c-andy-martin reviewed
> Reviewed 1 of 38 files at r4.
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/amcl/2)* status: 37 of 52 files reviewed, 117 unresolved discussions (waiting on @12tbuchman and @c-andy-martin)



<!-- Sent from Reviewable.io -->

2020-03-10 14:11 UTC, c-andy-martin commented
___
*[include/amcl/node/node_nd.h, line 40 at r6](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M23mA_FEl9wBMs9Xq5d:-M23mA_GD-akx6-Tj6FN:b-wujt66) ([raw file](https://github.com/badgertechnologies/amcl/blob/9df029774580bad51987f61b64a87071070f819b/include/amcl/node/node_nd.h#L40)):*
> ```objc
>   virtual double scorePose(const PFVector& p) = 0;
> };
> }  // namespace amcl
> ```

If clang-format is forcing these lines to be next to each other, I'm find with you adding back the newline. I think a newline between these braces looks better. Up to you.


<!-- Sent from Reviewable.io -->

2020-03-10 14:12 UTC, c-andy-martin commented
___
*[include/amcl/node/node_nd.h, line 36 at r6](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M23mMptCGcBUZxQ3caM:-M23mMptCGcBUZxQ3caN:bubnt4) ([raw file](https://github.com/badgertechnologies/amcl/blob/9df029774580bad51987f61b64a87071070f819b/include/amcl/node/node_nd.h#L36)):*
> ```objc
> {
> public:
>   virtual void reconfigure(amcl::AMCLConfig& config) = 0;
> ```

you must add a virtual destructor to this abstract base class. It can either be `= default` or just empty ` {}`


<!-- Sent from Reviewable.io -->

2020-03-10 14:13 UTC, c-andy-martin commented
___
*[include/amcl/node/node_nd.h, line 20 at r6](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M23mZ0V8hVgDQUa6reS:-M23mZ0V8hVgDQUa6reT:b30gm7f) ([raw file](https://github.com/badgertechnologies/amcl/blob/9df029774580bad51987f61b64a87071070f819b/include/amcl/node/node_nd.h#L20)):*
> ```objc
>  */
> /* *************************************************************
>  * Desc: AMCL Node for 3D AMCL
> ```

This comment is incorrect. As I asked elsewhere, let's remove all these block comments and maintain authorship information in the git history and in the package.xml.


<!-- Sent from Reviewable.io -->

2020-03-10 14:13 UTC, c-andy-martin requested changes
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/amcl/2)* status: 34 of 53 files reviewed, 121 unresolved discussions (waiting on @12tbuchman and @c-andy-martin)

___
*[include/amcl/node/node_nd.h, line 42 at r6](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M23mH6n63ElrN9jTdMf:-M23mH6n63ElrN9jTdMg:b-z9hfke) ([raw file](https://github.com/badgertechnologies/amcl/blob/9df029774580bad51987f61b64a87071070f819b/include/amcl/node/node_nd.h#L42)):*
> ```objc
> }  // namespace amcl
> 
> #endif // AMCL_NODE_NODE_ND_H
> ```

there are supposed to be two spaces before inline comments according to the google c++ style guide


<!-- Sent from Reviewable.io -->

2020-03-10 14:17 UTC, c-andy-martin requested changes
> Reviewed 3 of 7 files at r6.
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/amcl/2)* status: 37 of 53 files reviewed, 123 unresolved discussions (waiting on @12tbuchman and @c-andy-martin)

___
*[include/amcl/node/node_2d.h, line 27 at r6](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M23nHuqBMZhJEJA5Wzo:-M23nHuqBMZhJEJA5Wzp:b-3eaog2) ([raw file](https://github.com/badgertechnologies/amcl/blob/9df029774580bad51987f61b64a87071070f819b/include/amcl/node/node_2d.h#L27)):*
> ```objc
> #define AMCL_NODE_NODE_2D_H
> 
> #include "node/node_nd.h"
> ```

this include should come last. the "related header" rule is only for .cpp files
___
*[include/amcl/node/node_3d.h, line 27 at r6](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M23mkMw2aAeWRPeMuNw:-M23mkMx4LA6jnoMEtvj:b-97iby2) ([raw file](https://github.com/badgertechnologies/amcl/blob/9df029774580bad51987f61b64a87071070f819b/include/amcl/node/node_3d.h#L27)):*
> ```objc
> #define AMCL_NODE_NODE_3D_H
> 
> #include "node/node_nd.h"
> ```

this include should be at the end, not the beginning. the only time you put the corresponding .h first is in the .cpp file that goes with a .h file


<!-- Sent from Reviewable.io -->

2020-03-10 14:18 UTC, c-andy-martin commented
___
*[include/amcl/node/node.h, line 177 at r5](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M1g8gpU-9d-bK2nKlTD:-M23ntET-fFZso2pXWoV:bs7ptrt) ([raw file](https://github.com/badgertechnologies/amcl/blob/95b6eb20da05f9f418bc7ea0645e69d04bc7dd99/include/amcl/node/node.h#L177)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

I would like to have a NodeBase and have Node only interact w/ the base class, store a base pointer here. You can either use a factory to build the right kind of node, or it would be fine to leave the circular dependency (broken the way you already have be pre-declaring Node) and just have NodeBase build the right kind of node instance, but only store a NodeBase pointer to it for cleanness.
</blockquote></details>

This is now finished.


<!-- Sent from Reviewable.io -->

2020-03-10 14:18 UTC, c-andy-martin reviewed
> Reviewed 1 of 7 files at r6.
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/amcl/2)* status: 38 of 53 files reviewed, 122 unresolved discussions (waiting on @12tbuchman and @c-andy-martin)



<!-- Sent from Reviewable.io -->

2020-03-10 14:31 UTC, c-andy-martin commented
___
*[src/amcl/sensors/planar_scanner.cpp, line 35 at r6](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M23qlKcEqFjUwYzm49o:-M23qlKcEqFjUwYzm49p:b-rc5ow5) ([raw file](https://github.com/badgertechnologies/amcl/blob/9df029774580bad51987f61b64a87071070f819b/src/amcl/sensors/planar_scanner.cpp#L35)):*
> ```cpp
> #include <functional>
> 
> using namespace amcl;
> ```

I prefer putting the below in the amcl namespace over `using namespace amcl`


<!-- Sent from Reviewable.io -->

2020-03-10 14:38 UTC, c-andy-martin requested changes
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/amcl/2)* status: 38 of 53 files reviewed, 127 unresolved discussions (waiting on @12tbuchman and @c-andy-martin)

___
*[src/amcl/sensors/amcl_laser.cpp, line 441 at r6](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M23sGgoCKEaG-A43N99:-M23sGgoCKEaG-A43N9A:b-k23g6p) ([raw file](https://github.com/badgertechnologies/amcl/blob/8a8873533e84b3894a5f385b1d56234ebbe31d7e/src/amcl/sensors/amcl_laser.cpp#L441)):*
> ```cpp
> 
>   //we need a count the no of particles for which the beam agreed with the map 
>   int *obs_count = new int[self->max_beams]();
> ```

Let's change this to a `std::vector<int>` instead of a dynamic array.
___
*[src/amcl/sensors/planar_scanner.cpp, line 41 at r6](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M23rHMx5ukkWVi4k_3m:-M23rHMx5ukkWVi4k_3n:b5g9h9i) ([raw file](https://github.com/badgertechnologies/amcl/blob/9df029774580bad51987f61b64a87071070f819b/src/amcl/sensors/planar_scanner.cpp#L41)):*
> ```cpp
> PlanarScanner::PlanarScanner() : Sensor(), max_beams_(0), max_samples_(0), max_obs_(0)
> {
>   map_ = nullptr;
> ```

There is no need for this line, the default shared_ptr constructor will start with the shared ptr correctly initalized to be empty.
___
*[src/amcl/sensors/planar_scanner.cpp, line 47 at r6](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M23r4uaDihhslUTlHgr:-M23r4uaDihhslUTlHgs:bqa5ypi) ([raw file](https://github.com/badgertechnologies/amcl/blob/9df029774580bad51987f61b64a87071070f819b/src/amcl/sensors/planar_scanner.cpp#L47)):*
> ```cpp
>   non_free_space_radius_ = 0.0;
> 
>   if (map_vec_.size() != 2)
> ```

This if condition will never be false, you can remove the if statement. Also, I suggest making the below simply `map_vec_.resize(2)`. It will use the default value (0) when growing the vector.
___
*[src/amcl/sensors/planar_scanner.cpp, line 362 at r6](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M23sOq05IMyl51UebFu:-M23sOq05IMyl51UebFv:bp8nxyb) ([raw file](https://github.com/badgertechnologies/amcl/blob/9df029774580bad51987f61b64a87071070f819b/src/amcl/sensors/planar_scanner.cpp#L362)):*
> ```cpp
> 
>   // we also need a mask of which observations to integrate (to decide which beams to integrate to all particles)
>   bool* obs_mask = new bool[max_beams_]();
> ```

Let's change this to a std::vector<bool> instead of dynamic array


<!-- Sent from Reviewable.io -->

2020-03-10 14:40 UTC, c-andy-martin commented
___
*[src/amcl/sensors/point_cloud_scanner.cpp, line 45 at r6](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M23ssONCuCiPA2Y0Aic:-M23ssONCuCiPA2Y0Aid:biu8va4) ([raw file](https://github.com/badgertechnologies/amcl/blob/9df029774580bad51987f61b64a87071070f819b/src/amcl/sensors/point_cloud_scanner.cpp#L45)):*
> ```cpp
>   non_free_space_radius_ = 0.0;
> 
>   if(map_vec_.size() != 3)
> ```

you could replace these 4 lines with:
```
map_vec_.resize(3);
world_vec_.resize(3);
```
The if statements will always be true, in the constructor the vectors are going to have a size of zero.


<!-- Sent from Reviewable.io -->

2020-03-10 14:40 UTC, c-andy-martin commented
___
*[src/amcl/sensors/point_cloud_scanner.cpp, line 39 at r6](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M23sp1ZEJlb-4tkuz9f:-M23sp1ZEJlb-4tkuz9g:bsmdz1c) ([raw file](https://github.com/badgertechnologies/amcl/blob/9df029774580bad51987f61b64a87071070f819b/src/amcl/sensors/point_cloud_scanner.cpp#L39)):*
> ```cpp
> {
>   max_beams_ = 0;
>   map_ = nullptr;
> ```

there is no need to do this, the default constructor will already do it


<!-- Sent from Reviewable.io -->

2020-03-10 15:24 UTC, c-andy-martin commented
___
*[src/amcl/sensors/point_cloud_scanner.cpp, line 172 at r6](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M23tKeM-txJ6nAO32TI:-M23tKeN2WUc4R8PdCnu:buldp0y) ([raw file](https://github.com/badgertechnologies/amcl/blob/9df029774580bad51987f61b64a87071070f819b/src/amcl/sensors/point_cloud_scanner.cpp#L172)):*
> ```cpp
>       map_->convertWorldToMap(world_vec_, &map_vec_);
>       z = map_->getOccDist(map_vec_[0], map_vec_[1], map_vec_[2]);
>       pz = z_hit_ * exp(-(z * z) / z_hit_denom);
> ```

BTW, we could easily build a LUT for all the possible inputs to the exp function here (since its just the possible distances we can have in the cspace) and make this a LUT. This could save time if this is the hot-spot for computation. We could even build in the z_hit_ into the LUT. If the profiling data shows us spending a lot of time in `exp()` under `calcPointCloudModel` this would be worth doing (maybe take a ticket to do this later)


<!-- Sent from Reviewable.io -->

2020-03-10 15:24 UTC, c-andy-martin commented
___
*[src/amcl/sensors/point_cloud_scanner.cpp, line 172 at r6](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M23tKeM-txJ6nAO32TI:-M2422boEGaW-q07n1rr:b-mbwkqk) ([raw file](https://github.com/badgertechnologies/amcl/blob/9df029774580bad51987f61b64a87071070f819b/src/amcl/sensors/point_cloud_scanner.cpp#L172)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

BTW, we could easily build a LUT for all the possible inputs to the exp function here (since its just the possible distances we can have in the cspace) and make this a LUT. This could save time if this is the hot-spot for computation. We could even build in the z_hit_ into the LUT. If the profiling data shows us spending a lot of time in `exp()` under `calcPointCloudModel` this would be worth doing (maybe take a ticket to do this later)
</blockquote></details>

I looked at the last profile you sent me, and don't notice this being high on the profile list. so there is no need to do this


<!-- Sent from Reviewable.io -->

2020-03-10 15:39 UTC, c-andy-martin commented
___
*[src/amcl/node/node_3d.cpp, line 119 at r6](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M243RWv63W6vQ-cPhbf:-M243RWv63W6vQ-cPhbg:b2o92h2) ([raw file](https://github.com/badgertechnologies/amcl/blob/9df029774580bad51987f61b64a87071070f819b/src/amcl/node/node_3d.cpp#L119)):*
> ```cpp
>   try
>   {
>     tf_.waitForTransform("base_footprint", "top_laser", ros::Time::now(), ros::Duration(5.0));
> ```

a few things:
1) Do not hard-code frame IDs
2) We don't know the frame of the sensor data until we get it.
3) The TF from the sensor data to the footprint can change at any time (what if we recalibrate for instance)
So, given these, I propose you move updating the scanner_to_footprint_tf_ into the point cloud callback (the scanReceived method). That method can lookup the transform without waiting, since its inside a TF message filter (it should do this for every point cloud received, using the timestamp in the sensor data, the frame for the cloud might not be fixed relative to the base footprint). Then, it can immediately set the transform in the point_cloud_scanner by calling setPointCloudScannerToFootprintTF for each callback received prior to updating the sensor. Also, it should track the frame_id/timestamp from the received point cloud to the `base_frame_id_`. This proposal would remove the few lines here around TF lookup and and just add the lookupTransform (which shouldn't fail, but you can still catch exceptions just in case) in the scanReceived callback chain somewhere prior to updating the scanner. (Also, I don't think there is any need to store the scanner_to_footprint_tf_ here, just do it in the point cloud scanner class).


<!-- Sent from Reviewable.io -->

2020-03-10 15:40 UTC, c-andy-martin requested changes
> Reviewed 1 of 38 files at r4.
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/amcl/2)* status: 39 of 53 files reviewed, 132 unresolved discussions (waiting on @12tbuchman and @c-andy-martin)

___
*[src/amcl/node/node_3d.cpp, line 466 at r6](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M245-GH3z_IX8wEw5Up:-M245-GH3z_IX8wEw5Uq:b-jvt6xq) ([raw file](https://github.com/badgertechnologies/amcl/blob/9df029774580bad51987f61b64a87071070f819b/src/amcl/node/node_3d.cpp#L466)):*
> ```cpp
>   // point cloud scanner mounting angle gets computed later -> set to 0 here!
>   scanner_pose_v.v[2] = 0;
>   scanners_[scanner_index]->setPointCloudScannerPose(scanner_pose_v);
> ```

the scanner pose isn't used anywhere (not even in the scanner itself), I would delete it (and any associated functions/methods you no longer need).
___
*[src/amcl/node/node_3d.cpp, line 467 at r6](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M2452XN4fz0L__53_yx:-M2452XN4fz0L__53_yy:b-htodzm) ([raw file](https://github.com/badgertechnologies/amcl/blob/9df029774580bad51987f61b64a87071070f819b/src/amcl/node/node_3d.cpp#L467)):*
> ```cpp
>   scanner_pose_v.v[2] = 0;
>   scanners_[scanner_index]->setPointCloudScannerPose(scanner_pose_v);
>   scanners_[scanner_index]->setPointCloudScannerToFootprintTF(scanner_to_footprint_tf_);
> ```

you should be looking up the current TF before setting it (see my comment above at the lookupTransform call)


<!-- Sent from Reviewable.io -->

2020-03-10 15:49 UTC, c-andy-martin commented
___
*[src/amcl/sensors/point_cloud_scanner.cpp, line 265 at r6](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M245wTn0EA7coPIKADj:-M245wTn0EA7coPIKADk:b-lfnssv) ([raw file](https://github.com/badgertechnologies/amcl/blob/9df029774580bad51987f61b64a87071070f819b/src/amcl/sensors/point_cloud_scanner.cpp#L265)):*
> ```cpp
>   {
>     pcl_ros::transformPointCloud(data->points_, footprint_cloud, point_cloud_scanner_to_footprint_tf_);
>     pcl_ros::transformPointCloud(footprint_cloud, map_cloud, footprint_to_map_tf);
> ```

Instead of calling transformPointCloud twice, create the combined transform (which is just multiplying the quaternions and combining the translations under the hood) which makes this half the math for transforming the cloud. The last profile I have from the code shows us using 6% of our time in transformPointCloud, so this will save measurable CPU time. TF provides an easy API to do this for you by overloading the `operator*`. Create the two transforms as you already do, then combine them with one call to transformPointCloud:
```
pcl_ros::transformPointCloud(data->points_, map_cloud, point_cloud_scanner_to_footprint_tf_ * footprint_to_map_tf);
```


<!-- Sent from Reviewable.io -->

2020-03-10 15:59 UTC, c-andy-martin commented
___
*[src/amcl/sensors/point_cloud_scanner.cpp, line 267 at r6](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M24A0Tq6LqAMlCOhMkI:-M24A0TrEj4mASFGz7PB:b6q3dug) ([raw file](https://github.com/badgertechnologies/amcl/blob/9df029774580bad51987f61b64a87071070f819b/src/amcl/sensors/point_cloud_scanner.cpp#L267)):*
> ```cpp
>     pcl_ros::transformPointCloud(footprint_cloud, map_cloud, footprint_to_map_tf);
>   }
>   catch (tf::TransformException& e)
> ```

It isn't possible for transformPointCloud to throw any TF exceptions when you give it a transform. You can delete the try/catch and the whole catch block


<!-- Sent from Reviewable.io -->

2020-03-10 16:39 UTC, c-andy-martin commented
___
*[src/amcl/map/map.cpp, line 28 at r6](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M24J6uRDo7LGTVNBeif:-M24J6uRDo7LGTVNBeig:b-pbsoea) ([raw file](https://github.com/badgertechnologies/amcl/blob/9df029774580bad51987f61b64a87071070f819b/src/amcl/map/map.cpp#L28)):*
> ```cpp
> #include "map/map.h"
> 
> using namespace amcl;
> ```

I prefer to put this in the amcl namespace over using


<!-- Sent from Reviewable.io -->

2020-03-10 16:40 UTC, c-andy-martin requested changes
> Reviewed 1 of 47 files at r1, 2 of 38 files at r4.
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/amcl/2)* status: 41 of 53 files reviewed, 138 unresolved discussions (waiting on @12tbuchman and @c-andy-martin)

___
*[src/amcl/map/occupancy_map.cpp, line 28 at r6](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M24JDAb4MKDJIcDL_hf:-M24JDAb4MKDJIcDL_hg:b-pbsoea) ([raw file](https://github.com/badgertechnologies/amcl/blob/9df029774580bad51987f61b64a87071070f819b/src/amcl/map/occupancy_map.cpp#L28)):*
> ```cpp
> #include "map/occupancy_map.h"
> 
> using namespace amcl;
> ```

I prefer to put this in the amcl namespace over using
___
*[src/amcl/map/occupancy_map.cpp, line 30 at r6](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M24JFXe9fZDVvW0pH7e:-M24JFXe9fZDVvW0pH7f:bs67ad2) ([raw file](https://github.com/badgertechnologies/amcl/blob/9df029774580bad51987f61b64a87071070f819b/src/amcl/map/occupancy_map.cpp#L30)):*
> ```cpp
> using namespace amcl;
> 
> // Create a new map
> ```

This comment is a bit misleading (the map isn't created by a constructor so much as constructed, I don't think you need this comment)
___
*[src/amcl/sensors/point_cloud_scanner.cpp, line 92 at r6](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M245kMt-FYKTDTyxGIy:-M245kMt-FYKTDTyxGIz:b-od998v) ([raw file](https://github.com/badgertechnologies/amcl/blob/9df029774580bad51987f61b64a87071070f819b/src/amcl/sensors/point_cloud_scanner.cpp#L92)):*
> ```cpp
> void PointCloudScanner::setPointCloudScannerPose(PFVector& scanner_pose)
> {
>   point_cloud_scanner_pose_ = scanner_pose;
> ```

This isn't used, delete it and the API for itn


<!-- Sent from Reviewable.io -->

2020-03-10 16:40 UTC, c-andy-martin commented
___
*[src/amcl/map/occupancy_map.cpp, line 37 at r6](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M24JMvw5ezZsYmVvPFX:-M24JMvw5ezZsYmVvPFY:bq4j4y5) ([raw file](https://github.com/badgertechnologies/amcl/blob/9df029774580bad51987f61b64a87071070f819b/src/amcl/map/occupancy_map.cpp#L37)):*
> ```cpp
>   origin_y_ = 0;
> 
>   // Make the size odd
> ```

This comment doesn't make any sense to me (0 is not odd!)


<!-- Sent from Reviewable.io -->

2020-03-10 16:40 UTC, c-andy-martin commented
___
*[src/amcl/map/occupancy_map.cpp, line 43 at r6](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M24JRMWD5e2XNTvhlL6:-M24JRMWD5e2XNTvhlL7:b-droqd0) ([raw file](https://github.com/badgertechnologies/amcl/blob/9df029774580bad51987f61b64a87071070f819b/src/amcl/map/occupancy_map.cpp#L43)):*
> ```cpp
>   max_occ_dist_ = 0;
> 
>   // Allocate storage for main map
> ```

This comment doesn't make any sense, as no allocation is going on here


<!-- Sent from Reviewable.io -->

2020-03-10 16:48 UTC, c-andy-martin commented
___
*[src/amcl/map/occupancy_map.cpp, line 100 at r6](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M24Jnx1BcaNQlYvcywk:-M24Jnx280xsP5Iivepf:brbg14) ([raw file](https://github.com/badgertechnologies/amcl/blob/9df029774580bad51987f61b64a87071070f819b/src/amcl/map/occupancy_map.cpp#L100)):*
> ```cpp
>   int i = map_coords[0];
>   int j = map_coords[1];
>   (*world_coords)[0] = origin_x_ + (i - size_x_ / 2) * resolution_;
> ```

I would like to use our rewrite as an opportunity to clean this up. It doesn't make sense to me that they were adjusting the origin such that the image is centered on 0,0. I would remove all the `size_x_ / 2` part of the match in coordinate conversion, and I would just save the real world origin of the 2D map that was reported in the occupancy_grid's origin (and not adjust it by size_x_/size_y_) (that is around line 272 of node_2d.cpp, there I would just make origin the same as map_msg.info.origin). So that would make these lines here:
```
(*world_coords)[0] = origin_x_ + i * resolution_;
(*world_coords)[1] = origin_y_ + j * resolution_;
```


<!-- Sent from Reviewable.io -->

2020-03-10 16:49 UTC, c-andy-martin commented
___
*[src/amcl/map/occupancy_map.cpp, line 109 at r6](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M24LLC-6KPTxT3p5JmC:-M24LLC-6KPTxT3p5JmD:beodbug) ([raw file](https://github.com/badgertechnologies/amcl/blob/9df029774580bad51987f61b64a87071070f819b/src/amcl/map/occupancy_map.cpp#L109)):*
> ```cpp
>   double x = world_coords[0];
>   double y = world_coords[1];
>   (*map_coords)[0] = floor((x - origin_x_) / resolution_ + 0.5) + size_x_ / 2;
> ```

If you follow my advice above, get rid of adding size_x_/size_y_ here.


<!-- Sent from Reviewable.io -->

2020-03-10 16:50 UTC, c-andy-martin commented
___
*[src/amcl/map/occupancy_map.cpp, line 100 at r6](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M24Jnx1BcaNQlYvcywk:-M24LhAV4hdpT1NSja8T:bl8ssmw) ([raw file](https://github.com/badgertechnologies/amcl/blob/9df029774580bad51987f61b64a87071070f819b/src/amcl/map/occupancy_map.cpp#L100)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

I would like to use our rewrite as an opportunity to clean this up. It doesn't make sense to me that they were adjusting the origin such that the image is centered on 0,0. I would remove all the `size_x_ / 2` part of the match in coordinate conversion, and I would just save the real world origin of the 2D map that was reported in the occupancy_grid's origin (and not adjust it by size_x_/size_y_) (that is around line 272 of node_2d.cpp, there I would just make origin the same as map_msg.info.origin). So that would make these lines here:
```
(*world_coords)[0] = origin_x_ + i * resolution_;
(*world_coords)[1] = origin_y_ + j * resolution_;
```
</blockquote></details>

Also, as a part of this, we can make size_x_/size_y_ unsigned I think, which makes more sense.


<!-- Sent from Reviewable.io -->

2020-03-10 16:51 UTC, c-andy-martin requested changes
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/amcl/2)* status: 41 of 53 files reviewed, 143 unresolved discussions (waiting on @12tbuchman and @c-andy-martin)

___
*[src/amcl/map/occupancy_map.cpp, line 122 at r6](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M24LlK10PC51vsTrMh5:-M24LlK10PC51vsTrMh6:b-76kav) ([raw file](https://github.com/badgertechnologies/amcl/blob/9df029774580bad51987f61b64a87071070f819b/src/amcl/map/occupancy_map.cpp#L122)):*
> ```cpp
> unsigned int OccupancyMap::computeCellIndex(int i, int j)
> {
>   return i + j * unsigned(size_x_);
> ```

I think if you get rid of adjusting the origin by size_x_/2, you can make size_x_/size_y_ unsigned, and get rid of this static cast to unsigned here.


<!-- Sent from Reviewable.io -->

2020-03-10 16:58 UTC, c-andy-martin commented
___
*[src/amcl/map/occupancy_map_cspace.cpp, line 54 at r6](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M24NIuxAID5pCUc-Mpc:-M24NIuxAID5pCUc-Mpd:bdlzrq9) ([raw file](https://github.com/badgertechnologies/amcl/blob/9df029774580bad51987f61b64a87071070f819b/src/amcl/map/occupancy_map_cspace.cpp#L54)):*
> ```cpp
>     cdm_ = std::unique_ptr<CachedDistanceMap>(new CachedDistanceMap(resolution_, max_occ_dist_));
>   }
>   iterateObstacleCells();
> ```

it would be cleaner, I think, to pass `q_` and `marked_` into these methods and not make them member variables. Then, you could just let the unique_ptr's go out of scope to free the temporary memory. This is a minor point, so if you'd rather not its OK.


<!-- Sent from Reviewable.io -->

2020-03-10 18:12 UTC, c-andy-martin commented
___
*[src/amcl/map/occupancy_map_cspace.cpp, line 99 at r6](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M24Nio39w2OfYvfX1nq:-M24Nio39w2OfYvfX1nr:b-b75iye) ([raw file](https://github.com/badgertechnologies/amcl/blob/9df029774580bad51987f61b64a87071070f819b/src/amcl/map/occupancy_map_cspace.cpp#L99)):*
> ```cpp
>       updateNode(current_cell.i, current_cell.j - 1, current_cell);
>     }
>     if ((int)current_cell.i < size_x_ - 1)
> ```

if we make size_x_ unsigned as I ask elsewhere, we can change this to:
```
if (current_cell.i + 1 < size_x_)
```
To get rid of the cast and prevent underflow (and also the size_y_ one below)


<!-- Sent from Reviewable.io -->

2020-03-10 18:51 UTC, c-andy-martin commented
___
*[src/amcl/map/occupancy_map_cspace.cpp, line 66 at r6](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M24mOCkAb4RuqTCfZyV:-M24mOClAmbO5aLcuLzI:b1vhrkv) ([raw file](https://github.com/badgertechnologies/amcl/blob/9df029774580bad51987f61b64a87071070f819b/src/amcl/map/occupancy_map_cspace.cpp#L66)):*
> ```cpp
>   // Enqueue all the obstacle cells
>   CellData cell = CellData(this);
>   for (int i = 0; i < size_x_; i++)
> ```

if we make size_x_ unsigned, we should probably make i and j unsigned here (this may have ripple effects, but offsets in the array are never negative, so unsigned makes sense to me)


<!-- Sent from Reviewable.io -->

2020-03-10 18:51 UTC, c-andy-martin requested changes
> Reviewed 1 of 38 files at r4.
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/amcl/2)* status: 42 of 53 files reviewed, 149 unresolved discussions (waiting on @12tbuchman and @c-andy-martin)

___
*[src/amcl/map/occupancy_map_cspace.cpp, line 36 at r6](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M24M8HlEER8GJh6W_wY:-M24M8HlEER8GJh6W_wZ:b6ljuuy) ([raw file](https://github.com/badgertechnologies/amcl/blob/9df029774580bad51987f61b64a87071070f819b/src/amcl/map/occupancy_map_cspace.cpp#L36)):*
> ```cpp
> 
> // Update the cspace distance values
> void OccupancyMap::updateCSpace(double max_occ_dist)
> ```

I would prefer to put all of this .cpp file into occupancy_map.cpp and not have two separate cpp files. Generally, the rule of thumb is one cpp file for each object. This makes it easier to see all the parts of the object in one file.
___
*[src/amcl/map/occupancy_map_cspace.cpp, line 39 at r6](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M24MvoA4jHedJ6ay_Ci:-M24MvoA4jHedJ6ay_Cj:b-qkgh3x) ([raw file](https://github.com/badgertechnologies/amcl/blob/9df029774580bad51987f61b64a87071070f819b/src/amcl/map/occupancy_map_cspace.cpp#L39)):*
> ```cpp
> {
>   max_occ_dist_ = max_occ_dist;
>   if(max_occ_dist_ == 0.0)
> ```

Seems like we should also check for negative here.
___
*[src/amcl/map/occupancy_map_cspace.cpp, line 41 at r6](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M24MzCM-TAqt6VvR6oy:-M24MzCM-TAqt6VvR6oz:b-suxcms) ([raw file](https://github.com/badgertechnologies/amcl/blob/9df029774580bad51987f61b64a87071070f819b/src/amcl/map/occupancy_map_cspace.cpp#L41)):*
> ```cpp
>   if(max_occ_dist_ == 0.0)
>   {
>     ROS_DEBUG("Failed to update cspace, max occ dist is 0");
> ```

I think this should be a ROS_WARN or even ROS_ERROR


<!-- Sent from Reviewable.io -->

2020-03-10 18:53 UTC, c-andy-martin commented
___
*[src/amcl/map/occupancy_map_range.cpp, line 37 at r7](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M24mp00EIBO8VvCPhsK:-M24mp00EIBO8VvCPhsL:b-qo7xkj) ([raw file](https://github.com/badgertechnologies/amcl/blob/74db8df1672f2baaecdf854cea1efd100f551c8b/src/amcl/map/occupancy_map_range.cpp#L37)):*
> ```cpp
> double OccupancyMap::calcRange(double ox, double oy, double oa, double max_range)
> {
>   // Bresenham raytracing
> ```

I'd love to make this use OpenCV for the ray casting (which it can do w/ a function pointer to call at each ray cell). Maybe we should take a to-do on that?


<!-- Sent from Reviewable.io -->

2020-03-10 18:54 UTC, c-andy-martin commented
___
*[src/amcl/map/occupancy_map_range.cpp, line 37 at r7](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M24mp00EIBO8VvCPhsK:-M24n1eM39q7WYHvA6YR:b-6ssqh4) ([raw file](https://github.com/badgertechnologies/amcl/blob/74db8df1672f2baaecdf854cea1efd100f551c8b/src/amcl/map/occupancy_map_range.cpp#L37)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

I'd love to make this use OpenCV for the ray casting (which it can do w/ a function pointer to call at each ray cell). Maybe we should take a to-do on that?
</blockquote></details>

Then again, if it ain't broke don't fix it, I'd be OK just leaving this as is, your call


<!-- Sent from Reviewable.io -->

2020-03-10 18:55 UTC, c-andy-martin requested changes
> Reviewed 2 of 38 files at r4.
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/amcl/2)* status: 44 of 53 files reviewed, 151 unresolved discussions (waiting on @12tbuchman and @c-andy-martin)

___
*[src/amcl/map/occupancy_map_range.cpp, line 35 at r7](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M24mecq8tmdoqiVciwD:-M24mecq8tmdoqiVciwE:bghcocb) ([raw file](https://github.com/badgertechnologies/amcl/blob/74db8df1672f2baaecdf854cea1efd100f551c8b/src/amcl/map/occupancy_map_range.cpp#L35)):*
> ```cpp
> // out-of-bound cells are treated as occupied, which makes it easy to
> // use Stage bitmap files.
> double OccupancyMap::calcRange(double ox, double oy, double oa, double max_range)
> ```

again, I prefer to have this in the main occupancy_map.cpp file (my preference is one file per object)


<!-- Sent from Reviewable.io -->

2020-03-10 18:55 UTC, c-andy-martin commented
___
*[src/amcl/map/octomap.cpp, line 28 at r6](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M24nEuF34i0wrIxUEvT:-M24nEuF34i0wrIxUEvU:b94q4wd) ([raw file](https://github.com/badgertechnologies/amcl/blob/9df029774580bad51987f61b64a87071070f819b/src/amcl/map/octomap.cpp#L28)):*
> ```cpp
> #include <algorithm>
> #include <cmath>
> #include <ros/console.h>
> ```

there should be a newline between standard includes and library includes, and there should only be one newline below


<!-- Sent from Reviewable.io -->

2020-03-10 19:05 UTC, c-andy-martin commented
___
*[src/amcl/map/octomap.cpp, line 57 at r6](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M24o3SxDzeqs5n6y513:-M24o3SxDzeqs5n6y514:b4qu9mw) ([raw file](https://github.com/badgertechnologies/amcl/blob/9df029774580bad51987f61b64a87071070f819b/src/amcl/map/octomap.cpp#L57)):*
> ```cpp
>   double x_meters, y_meters, z_meters;
>   octree_->getMetricSize(x_meters, y_meters, z_meters);
>   full_cells_[0] = (int)ceil(x_meters / resolution_);
> ```

This code is assuming that the origin is 0,0,0. I think instead we should use the return of getMetricMin to be the origin. There may be some need to have negative coordinates (especially in x) to match the 2D coordinate system (think of an object up high that goes negative in x/y that wasn't on the 2D map but we want in the 3D space). Then you can use max - min to find the size (and using convertWorldToMap).


<!-- Sent from Reviewable.io -->

2020-03-10 19:07 UTC, c-andy-martin commented
___
*[src/amcl/map/octomap.cpp, line 57 at r6](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M24o3SxDzeqs5n6y513:-M24pz87ABF9hoXQsYU_:b-gxoxh3) ([raw file](https://github.com/badgertechnologies/amcl/blob/9df029774580bad51987f61b64a87071070f819b/src/amcl/map/octomap.cpp#L57)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

This code is assuming that the origin is 0,0,0. I think instead we should use the return of getMetricMin to be the origin. There may be some need to have negative coordinates (especially in x) to match the 2D coordinate system (think of an object up high that goes negative in x/y that wasn't on the 2D map but we want in the 3D space). Then you can use max - min to find the size (and using convertWorldToMap).
</blockquote></details>

Ah, I see, getMetricSize is doing that for you. Nevermind. This is OK


<!-- Sent from Reviewable.io -->

2020-03-10 19:07 UTC, c-andy-martin requested changes
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/amcl/2)* status: 44 of 53 files reviewed, 155 unresolved discussions (waiting on @12tbuchman and @c-andy-martin)

___
*[src/amcl/map/octomap.cpp, line 31 at r6](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M24nOamBEbJ_Ftx8frq:-M24nOamBEbJ_Ftx8frr:b77c9e1) ([raw file](https://github.com/badgertechnologies/amcl/blob/9df029774580bad51987f61b64a87071070f819b/src/amcl/map/octomap.cpp#L31)):*
> ```cpp
> 
> 
> using namespace amcl;
> ```

I'd prefer this to be in the amcl namespace instead of a using
___
*[src/amcl/map/octomap.cpp, line 36 at r6](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M24nXkmB1hf3npoiR86:-M24nXkmB1hf3npoiR87:bl4p0yw) ([raw file](https://github.com/badgertechnologies/amcl/blob/9df029774580bad51987f61b64a87071070f819b/src/amcl/map/octomap.cpp#L36)):*
> ```cpp
> {
>   wait_for_occupancy_map_ = wait_for_occupancy_map;
>   origin_ = std::vector<double>(3);
> ```

this could also be `origin_.resize(3)` which would save on a temporary (and all the below)
___
*[src/amcl/map/octomap.cpp, line 45 at r6](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M24neOs0MeLqRQDcGFF:-M24neOs0MeLqRQDcGFG:b-9ckiqg) ([raw file](https://github.com/badgertechnologies/amcl/blob/9df029774580bad51987f61b64a87071070f819b/src/amcl/map/octomap.cpp#L45)):*
> ```cpp
>   octree_ = std::make_shared<octomap::OcTree>(resolution_);
>   distances_ = nullptr;
>   cdm_ = nullptr;
> ```

you don't have to initialize all these to nullptr, that's done for you already by default


<!-- Sent from Reviewable.io -->

2020-03-10 19:09 UTC, c-andy-martin commented
___
*[src/amcl/map/octomap.cpp, line 57 at r6](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M24qF2j-7SRIVtwWN62:-M24qF2j-7SRIVtwWN63:b-yx6ck) ([raw file](https://github.com/badgertechnologies/amcl/blob/9df029774580bad51987f61b64a87071070f819b/src/amcl/map/octomap.cpp#L57)):*
> ```cpp
>   double x_meters, y_meters, z_meters;
>   octree_->getMetricSize(x_meters, y_meters, z_meters);
>   full_cells_[0] = (int)ceil(x_meters / resolution_);
> ```

I think you should use your convertWorldToMap function to find the integer values of full_cells_, and then add 1 to each dimension to represent the fact that the max is inclusive.


<!-- Sent from Reviewable.io -->

2020-03-10 19:10 UTC, c-andy-martin commented
___
*[src/amcl/map/octomap.cpp, line 66 at r6](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M24qXONEmOH4aK84_fC:-M24qXONEmOH4aK84_fD:b-yuow0) ([raw file](https://github.com/badgertechnologies/amcl/blob/9df029774580bad51987f61b64a87071070f819b/src/amcl/map/octomap.cpp#L66)):*
> ```cpp
>   // crop values here if required
>   convertWorldToMap({ min_x, min_y, min_z }, &cropped_min_cells_);
>   convertWorldToMap({ max_x, max_y, max_z }, &cropped_max_cells_);
> ```

Or instead of my above comment, maybe it would be easier to just set the full_cells_ by subtracing the max and min here:
```
full_cells_[0] = cropped_max_cells_[0] - cropped_max_cells_[0] + 1
```


<!-- Sent from Reviewable.io -->

2020-03-10 19:17 UTC, c-andy-martin commented
___
*[src/amcl/map/octomap.cpp, line 166 at r6](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M24rOnz7u10UaLOY-d-:-M24rOo-9B1sSY_GtjH4:b-rnptuw) ([raw file](https://github.com/badgertechnologies/amcl/blob/9df029774580bad51987f61b64a87071070f819b/src/amcl/map/octomap.cpp#L166)):*
> ```cpp
>   for (int i = 0; i < cells_min.size(); i++)
>   {
>     cropped_min_cells_[i] = std::max(cropped_min_cells_[i], cells_min[i]);
> ```

so while restricting the 3D map to the 2D bounds makes sense when restricting the pose we might come up with when localizing, we may have valid map data that we'd like to match not in those bounds. We could have two ideas of the bounds here, if we get a 2D map_min/map_max here in setMapBounds, we set a new 2D bounds that we only enforce when isValid is given a 2D vector. If isValid is given a 3D vector, just use the original 3D octomap bounds. Sound good? I think this gives us both functions at once.


<!-- Sent from Reviewable.io -->

2020-03-10 20:58 UTC, c-andy-martin commented
___
*[src/amcl/pf/pf_kdtree.cpp, line 37 at r7](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M25EKA11jZ-Wwf8VyRX:-M25EKA24svWg5LtfIso:b-ikcrfw) ([raw file](https://github.com/badgertechnologies/amcl/blob/74db8df1672f2baaecdf854cea1efd100f551c8b/src/amcl/pf/pf_kdtree.cpp#L37)):*
> ```cpp
> using namespace amcl;
> 
> ///////////////////////////////////////////////////////////////////////////////
> ```

Remove these two lines of comments


<!-- Sent from Reviewable.io -->

2020-03-10 20:58 UTC, c-andy-martin commented
___
*[src/amcl/pf/pf_kdtree.cpp, line 35 at r7](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M25EOFc9j1Wd-Sir6td:-M25EOFc9j1Wd-Sir6te:byhhdpg) ([raw file](https://github.com/badgertechnologies/amcl/blob/74db8df1672f2baaecdf854cea1efd100f551c8b/src/amcl/pf/pf_kdtree.cpp#L35)):*
> ```cpp
> #include <vector>
> 
> using namespace amcl;
> ```

I would rather put this in amcl than use using


<!-- Sent from Reviewable.io -->

2020-03-10 20:58 UTC, c-andy-martin commented
___
*[src/amcl/pf/pf_kdtree.cpp, line 29 at r7](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M25ESpJ6j684WHThd2h:-M25ESpJ6j684WHThd2i:bcc5gfd) ([raw file](https://github.com/badgertechnologies/amcl/blob/74db8df1672f2baaecdf854cea1efd100f551c8b/src/amcl/pf/pf_kdtree.cpp#L29)):*
> ```cpp
> 
> #include <math.h>
> #include <ros/assert.h>
> ```

ros headers come last


<!-- Sent from Reviewable.io -->

2020-03-10 20:58 UTC, c-andy-martin commented
___
*[src/amcl/pf/pf_kdtree.cpp, line 28 at r7](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M25EUAODSTS-RGU2OIx:-M25EUAODSTS-RGU2OIy:b5xys5n) ([raw file](https://github.com/badgertechnologies/amcl/blob/74db8df1672f2baaecdf854cea1efd100f551c8b/src/amcl/pf/pf_kdtree.cpp#L28)):*
> ```cpp
> #include "pf/pf_kdtree.h"
> 
> #include <math.h>
> ```

I'd love to move this to cmath and cstdlib


<!-- Sent from Reviewable.io -->

2020-03-10 21:12 UTC, c-andy-martin requested changes
> Reviewed 1 of 38 files at r4, 1 of 3 files at r5.
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/amcl/2)* status: 46 of 53 files reviewed, 172 unresolved discussions (waiting on @12tbuchman and @c-andy-martin)

___
*[src/amcl/map/octomap.cpp, line 82 at r6](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M24qsti0gEI001xhdeW:-M24qsti0gEI001xhdeX:bpequgo) ([raw file](https://github.com/badgertechnologies/amcl/blob/9df029774580bad51987f61b64a87071070f819b/src/amcl/map/octomap.cpp#L82)):*
> ```cpp
> // returns vector of map size in voxels
> // each voxel represents map_size_in_meters / resolution
> std::vector<int> OctoMap::getSize()
> ```

since you are returning something inside the object, you could make this return by const reference like this (and change the header to match):
`const std::vector<int>& OctoMap::getSize() const`
___
*[src/amcl/pf/pf_kdtree.cpp, line 49 at r7](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M25G7ud2l0wsCJarOcX:-M25G7ud2l0wsCJarOcY:bcnyp8m) ([raw file](https://github.com/badgertechnologies/amcl/blob/74db8df1672f2baaecdf854cea1efd100f551c8b/src/amcl/pf/pf_kdtree.cpp#L49)):*
> ```cpp
>   node_count_ = 0;
>   node_max_count_ = max_size;
>   nodes_ = (PFKDTreeNode*)calloc(node_max_count_, sizeof(PFKDTreeNode));
> ```

we need to C++ ify this. calloc is from C. Consider making this a `std::vector<PFKDTreeNode>` and making the code work with that, just need to `resize(node_max_count_)`
___
*[src/amcl/pf/pf_kdtree.cpp, line 54 at r7](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M25GOyQ1g95sd6FM8CC:-M25GOyQ1g95sd6FM8CD:blpf0mv) ([raw file](https://github.com/badgertechnologies/amcl/blob/74db8df1672f2baaecdf854cea1efd100f551c8b/src/amcl/pf/pf_kdtree.cpp#L54)):*
> ```cpp
> }
> 
> ////////////////////////////////////////////////////////////////////////////////
> ```

I don't care for these comments, I'd get rid of any of them which don't tell you something you already obviously know from the name of the function or context. Also, I'd get rid of those long `//////...` everywhere.
___
*[src/amcl/pf/pf_kdtree.cpp, line 58 at r7](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M25GN2B3tU1haAxkrDO:-M25GN2C7vhFntqOvohu:bbpz5ac) ([raw file](https://github.com/badgertechnologies/amcl/blob/74db8df1672f2baaecdf854cea1efd100f551c8b/src/amcl/pf/pf_kdtree.cpp#L58)):*
> ```cpp
> PFKDTree::~PFKDTree()
> {
>   free(nodes_);
> ```

you won't need this if you switch to std::vector
___
*[src/amcl/pf/pf_kdtree.cpp, line 76 at r7](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M25Gbtl8veYWjGHMqLW:-M25Gbtl8veYWjGHMqLX:bofkc0o) ([raw file](https://github.com/badgertechnologies/amcl/blob/74db8df1672f2baaecdf854cea1efd100f551c8b/src/amcl/pf/pf_kdtree.cpp#L76)):*
> ```cpp
>   int key[3];
> 
>   key[0] = floor(pose.v[0] / cell_size_[0]);
> ```

if you switch to cmath, this will need to be std::floor
___
*[src/amcl/pf/pf_kdtree.cpp, line 119 at r7](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M25GkUwA59RbVr_byQ8:-M25GkUwA59RbVr_byQ9:b-niogzg) ([raw file](https://github.com/badgertechnologies/amcl/blob/74db8df1672f2baaecdf854cea1efd100f551c8b/src/amcl/pf/pf_kdtree.cpp#L119)):*
> ```cpp
>     ROS_ASSERT(node_count_ < node_max_count_);
>     node = nodes_ + node_count_++;
>     memset(node, 0, sizeof(PFKDTreeNode));
> ```

this would become just an assignment to the default PFKDTreeNode on a std::vector, or you could just resize() the vector as it grows
___
*[src/amcl/pf/pf_kdtree.cpp, line 134 at r7](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M25H9rW3Psei2QHLUmj:-M25H9rW3Psei2QHLUmk:bgx549r) ([raw file](https://github.com/badgertechnologies/amcl/blob/74db8df1672f2baaecdf854cea1efd100f551c8b/src/amcl/pf/pf_kdtree.cpp#L134)):*
> ```cpp
>     leaf_count_ += 1;
>   }
> ```

i'd get rid of this newline
___
*[src/amcl/pf/pf_kdtree.cpp, line 143 at r7](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M25H8nmA9ovPmw1me9D:-M25H8nmA9ovPmw1me9E:bgx549r) ([raw file](https://github.com/badgertechnologies/amcl/blob/74db8df1672f2baaecdf854cea1efd100f551c8b/src/amcl/pf/pf_kdtree.cpp#L143)):*
> ```cpp
>       node->value += value;
>     }
> ```

i'd get rid of this newline
___
*[src/amcl/pf/pf_kdtree.cpp, line 179 at r7](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M25H6Yz0FYXYUfHUhsE:-M25H6Yz0FYXYUfHUhsF:bgx549r) ([raw file](https://github.com/badgertechnologies/amcl/blob/74db8df1672f2baaecdf854cea1efd100f551c8b/src/amcl/pf/pf_kdtree.cpp#L179)):*
> ```cpp
>     }
>   }
> ```

i'd get rid of this newline
___
*[src/amcl/pf/pf_kdtree.cpp, line 274 at r7](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M25HPqiEIz30kj7Eudf:-M25HPqiEIz30kj7Eudg:b-hbxqpo) ([raw file](https://github.com/badgertechnologies/amcl/blob/74db8df1672f2baaecdf854cea1efd100f551c8b/src/amcl/pf/pf_kdtree.cpp#L274)):*
> ```cpp
>   int i;
>   int nkey[3];
>   PFKDTreeNode* nnode;
> ```

I don't like this name, its way too similar to node. Lets make it something different that stands out (maybe found_node and make nkey search_key or something)


<!-- Sent from Reviewable.io -->

2020-03-10 21:12 UTC, c-andy-martin commented
___
*[include/amcl/map/octomap.h, line 37 at r5](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M1adTT5D1Izfzdoo006:-M25HenjCz690Yw20x4D:b-4b2jpp) ([raw file](https://github.com/badgertechnologies/amcl/blob/95b6eb20da05f9f418bc7ea0645e69d04bc7dd99/include/amcl/map/octomap.h#L37)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

Get rid of including "OcTreeDistance.h" now that you aren't using it. It isn't in the badger-develop branch of octomap, so in order to build the code, I had to remove this line (after removing, it built fine).
</blockquote></details>

This is done.


<!-- Sent from Reviewable.io -->

2020-03-10 21:12 UTC, c-andy-martin reviewed
> Reviewed 1 of 2 files at r7.
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/amcl/2)* status: 47 of 53 files reviewed, 171 unresolved discussions (waiting on @12tbuchman and @c-andy-martin)



<!-- Sent from Reviewable.io -->

2020-03-11 02:28 UTC, c-andy-martin requested changes
> Reviewed 1 of 38 files at r4.
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/amcl/2)* status: 48 of 53 files reviewed, 175 unresolved discussions (waiting on @12tbuchman and @c-andy-martin)

___
*[src/amcl/pf/pdf_gaussian.cpp, line 32 at r7](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M26P5eMD223Y7VqF_ax:-M26P5eMD223Y7VqF_ay:budzcyn) ([raw file](https://github.com/badgertechnologies/amcl/blob/74db8df1672f2baaecdf854cea1efd100f551c8b/src/amcl/pf/pdf_gaussian.cpp#L32)):*
> ```cpp
> #include <stdlib.h>
> 
> // Random number generator seed value
> ```

huh? I don't see any relevant code nearby this comment. delete it
___
*[src/amcl/pf/pdf_gaussian.cpp, line 34 at r7](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M26PBZbAJO9fK0juyG_:-M26PBZbAJO9fK0juyGa:beiuqun) ([raw file](https://github.com/badgertechnologies/amcl/blob/74db8df1672f2baaecdf854cea1efd100f551c8b/src/amcl/pf/pdf_gaussian.cpp#L34)):*
> ```cpp
> // Random number generator seed value
> 
> using namespace amcl;
> ```

I'd rather put the code in the amcl namespace than add a using
___
*[src/amcl/pf/pdf_gaussian.cpp, line 37 at r7](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M26PFwoAIyStcM4JK66:-M26PFwoAIyStcM4JK67:bul5eqq) ([raw file](https://github.com/badgertechnologies/amcl/blob/74db8df1672f2baaecdf854cea1efd100f551c8b/src/amcl/pf/pdf_gaussian.cpp#L37)):*
> ```cpp
> 
> /**************************************************************************
>  * Gaussian
> ```

This comment adds little value, I'd remove it
___
*[src/amcl/pf/pdf_gaussian.cpp, line 40 at r7](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M26PIoL3qdDvCp0dkYr:-M26PIoM4zvRMOP_kOH2:b-p5ifvd) ([raw file](https://github.com/badgertechnologies/amcl/blob/74db8df1672f2baaecdf854cea1efd100f551c8b/src/amcl/pf/pdf_gaussian.cpp#L40)):*
> ```cpp
>  *************************************************************************/
> 
> // Create a gaussian pdf
> ```

And this one too, pls remove


<!-- Sent from Reviewable.io -->

2020-03-11 02:48 UTC, c-andy-martin requested changes
> Reviewed 1 of 3 files at r5.
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/amcl/2)* status: 49 of 53 files reviewed, 186 unresolved discussions (waiting on @12tbuchman and @c-andy-martin)

___
*[src/amcl/map/octomap_cspace.cpp, line 30 at r7](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M26Q16M90YLmU1xmWQN:-M26Q16M90YLmU1xmWQO:b-pp4iwn) ([raw file](https://github.com/badgertechnologies/amcl/blob/74db8df1672f2baaecdf854cea1efd100f551c8b/src/amcl/map/octomap_cspace.cpp#L30)):*
> ```cpp
> #include <octomap/OcTreeNode.h>
> #include <ros/console.h>
> #include <stdlib.h>
> ```

lets switch to cstdlib
___
*[src/amcl/map/octomap_cspace.cpp, line 32 at r7](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M26Q3Ih4c7NsC2Ca4YN:-M26Q3Ih4c7NsC2Ca4YO:b-mnceub) ([raw file](https://github.com/badgertechnologies/amcl/blob/74db8df1672f2baaecdf854cea1efd100f551c8b/src/amcl/map/octomap_cspace.cpp#L32)):*
> ```cpp
> #include <stdlib.h>
> 
> #include <algorithm>
> ```

std libraries should come between the "map/octomap.h" and the 3rd party libraries
___
*[src/amcl/map/octomap_cspace.cpp, line 39 at r7](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M26Q9vs91fW6jDC_c8t:-M26Q9vs91fW6jDC_c8u:ba83sue) ([raw file](https://github.com/badgertechnologies/amcl/blob/74db8df1672f2baaecdf854cea1efd100f551c8b/src/amcl/map/octomap_cspace.cpp#L39)):*
> ```cpp
> // This version also updates the max_occ_dist_ variable and
> // calls the base non-parameter updateCSpace
> void OctoMap::updateMaxOccDist(double max_occ_dist)
> ```

I'd prefer to have only one octomap.cpp file and put all the OctoMap class method definitions in there, so I'd like to have these all moved into octomap.cpp
___
*[src/amcl/map/octomap_cspace.cpp, line 55 at r7](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M26QPqS1JsffgNVqKX3:-M26QPqS1JsffgNVqKX4:b-dt8rfn) ([raw file](https://github.com/badgertechnologies/amcl/blob/74db8df1672f2baaecdf854cea1efd100f551c8b/src/amcl/map/octomap_cspace.cpp#L55)):*
> ```cpp
> 
>   ROS_INFO("Updating OctoMap CSpace");
>   q_ = std::unique_ptr<std::priority_queue<CellData>>(new std::priority_queue<CellData>);
> ```

I would make `q_` and `masked_` non-member variables, then just let them go out-of-scope below
___
*[src/amcl/map/octomap_cspace.cpp, line 67 at r7](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M26QVfkBKRvOTjx2y-x:-M26QVfkBKRvOTjx2y-y:b-701mhe) ([raw file](https://github.com/badgertechnologies/amcl/blob/74db8df1672f2baaecdf854cea1efd100f551c8b/src/amcl/map/octomap_cspace.cpp#L67)):*
> ```cpp
>   cspace_created_ = true;
>   ROS_INFO("Done updating OctoMap CSpace");
>   q_ = nullptr;
> ```

I would make these non-member variables (put them on the stack) then just let them go out of scope, so you could remove these lines
___
*[src/amcl/map/octomap_cspace.cpp, line 77 at r7](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M26T5moCWHu19rjm-6c:-M26T5moCWHu19rjm-6d:b3yg9e9) ([raw file](https://github.com/badgertechnologies/amcl/blob/74db8df1672f2baaecdf854cea1efd100f551c8b/src/amcl/map/octomap_cspace.cpp#L77)):*
> ```cpp
>   std::vector<double> world_coords(3);
>   std::vector<int> map_coords(3);
> ```

You need to expand() the octree before you iterate over it, or you will not handle pruned inner leaves correctly. All you have to do is call the expand() method on it. You could do this at any point, all though the resulting tree will take slightly more RAM. Without doing this, you will not correctly handle a pruned leaf (you will only consider it as if it were at the final depth of the tree). Expand will expand any such pruned leaves back to their full form so you can iterate over all of them with the iterator below.
___
*[src/amcl/map/octomap_cspace.cpp, line 101 at r7](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M26QysL9lGcCKKgXkLn:-M26QysL9lGcCKKgXkLo:bd7e501) ([raw file](https://github.com/badgertechnologies/amcl/blob/74db8df1672f2baaecdf854cea1efd100f551c8b/src/amcl/map/octomap_cspace.cpp#L101)):*
> ```cpp
>       octomap::OcTreeKey key = it.getIndexKey();
>       int i = key[0], j = key[1], k = key[2];
>       setOccDist(i, j, k, max_occ_dist_);
> ```

I don't think you want to do anything on a non-occupied cell (free space). Note that our maps won't have any free space (we don't bother saving it, as it would take a lot of memory). I think you can just delete the else case.
___
*[src/amcl/map/octomap_cspace.cpp, line 142 at r7](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M26TXkc8bim3ciLTS_f:-M26TXkc8bim3ciLTS_g:besdewz) ([raw file](https://github.com/badgertechnologies/amcl/blob/74db8df1672f2baaecdf854cea1efd100f551c8b/src/amcl/map/octomap_cspace.cpp#L142)):*
> ```cpp
> {
>   double occThresh = octree_->getOccupancyThres();
>   octomap::OcTreeKey key(i, j, k);
> ```

your i,jk that you get from convertWorldToMap do not match the indexes used in keys (which are centered around the 'tree_max_val', not around 0). As I state below, I don't think you need to create an OcTreeKey here anyway, but should just examine the hash map (you seed the hash map w/ the values from the tree at the beginning of the algorithm, and finding the state in the hash map will be much faster than the octree).
___
*[src/amcl/map/octomap_cspace.cpp, line 143 at r7](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M26RnJC4CujJJocLtoG:-M26RnJC4CujJJocLtoH:b-bw34c4) ([raw file](https://github.com/badgertechnologies/amcl/blob/74db8df1672f2baaecdf854cea1efd100f551c8b/src/amcl/map/octomap_cspace.cpp#L143)):*
> ```cpp
>   double occThresh = octree_->getOccupancyThres();
>   octomap::OcTreeKey key(i, j, k);
>   octomap::OcTreeNode* node = marked_->search(key);
> ```

you shouldn't need to search the octomap anywhere. You should be looking at the hash map to know the current state (if you have looped back on yourself). searching the octomap here is way more inefficient than using the hash map as well. you will speed up a lot I think using the hash map to check.
___
*[src/amcl/map/octomap_cspace.cpp, line 147 at r7](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M26UCEz0v01gQC2lq-m:-M26UCEz0v01gQC2lq-n:b3je7d2) ([raw file](https://github.com/badgertechnologies/amcl/blob/74db8df1672f2baaecdf854cea1efd100f551c8b/src/amcl/map/octomap_cspace.cpp#L147)):*
> ```cpp
>   {
>     bool enqueued = enqueue(i, j, k, current_cell.src_i, current_cell.src_j, current_cell.src_k);
>     marked_->updateNode(key, enqueued);
> ```

Ah, I understand now. Marked is a new tree you are using to tell where you have been. However, this doesn't correctly handle certain cases where we can get to cells from multiple obstacles, unless we are for sure doing a breadth-first-search (which maybe we are). At any rate, if we do need to maintain this information independent of the hash map, change the data structure you are using from an octomap to a hash map. Or, if you can just use the main distance hash map for both functions, just do that.
___
*[src/amcl/map/octomap_cspace.cpp, line 181 at r7](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M26SHtV1qb9Wxvos-nM:-M26SHtV1qb9Wxvos-nN:b-23zjlk) ([raw file](https://github.com/badgertechnologies/amcl/blob/74db8df1672f2baaecdf854cea1efd100f551c8b/src/amcl/map/octomap_cspace.cpp#L181)):*
> ```cpp
> {
>   size_t hash = makeHash(i, j, k);
>   distances_->insert_or_assign(hash, d);
> ```

I don't see any logic anywhere (yet, i may be missing it) that will prevent you from assigning a further distance here than one you already had in the assign case. You will only want to assign lower distances (in fact, you'd rather prune and never even add such things to the queue, but they may have already been in there from past adds).


<!-- Sent from Reviewable.io -->

2020-03-11 21:02 UTC, c-andy-martin requested changes
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/amcl/2)* status: 49 of 53 files reviewed, 190 unresolved discussions (waiting on @12tbuchman and @c-andy-martin)

___
*[src/amcl/pf/particle_filter.cpp, line 28 at r7](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M2AOpTT02Es_O4yr6EE:-M2AOpTU4C2tS46_S1YG:bxgsmmr) ([raw file](https://github.com/badgertechnologies/amcl/blob/74db8df1672f2baaecdf854cea1efd100f551c8b/src/amcl/pf/particle_filter.cpp#L28)):*
> ```cpp
> #include "pf/particle_filter.h"
> 
> #include <math.h>
> ```

lets switch to <cmath>
___
*[src/amcl/pf/particle_filter.cpp, line 29 at r7](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M2AOrX524ExJYw3bKpS:-M2AOrX524ExJYw3bKpT:bcuz6th) ([raw file](https://github.com/badgertechnologies/amcl/blob/74db8df1672f2baaecdf854cea1efd100f551c8b/src/amcl/pf/particle_filter.cpp#L29)):*
> ```cpp
> 
> #include <math.h>
> #include <ros/assert.h>
> ```

ros includes should come last, with third party, standard includes before them
___
*[src/amcl/pf/particle_filter.cpp, line 31 at r7](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M2AP-Ca4BioWvHBvscI:-M2AP-Ca4BioWvHBvscJ:b-pp4oxj) ([raw file](https://github.com/badgertechnologies/amcl/blob/74db8df1672f2baaecdf854cea1efd100f551c8b/src/amcl/pf/particle_filter.cpp#L31)):*
> ```cpp
> #include <ros/assert.h>
> #include <ros/console.h>
> #include <stddef.h>
> ```

lets switch to cstddef
___
*[src/amcl/pf/particle_filter.cpp, line 32 at r7](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M2AOwVw9SkM1FYJK_WQ:-M2AOwVw9SkM1FYJK_WR:bsq798q) ([raw file](https://github.com/badgertechnologies/amcl/blob/74db8df1672f2baaecdf854cea1efd100f551c8b/src/amcl/pf/particle_filter.cpp#L32)):*
> ```cpp
> #include <ros/console.h>
> #include <stddef.h>
> #include <stdlib.h>
> ```

let's not  include both stdlib.h and cstdlib


<!-- Sent from Reviewable.io -->

2020-03-11 21:04 UTC, c-andy-martin requested changes
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/amcl/2)* status: 49 of 53 files reviewed, 191 unresolved discussions (waiting on @12tbuchman and @c-andy-martin)

___
*[src/amcl/pf/particle_filter.cpp, line 40 at r7](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M2APHlCCetoq11Y0B_g:-M2APHlCCetoq11Y0B_h:b-x8ncsx) ([raw file](https://github.com/badgertechnologies/amcl/blob/74db8df1672f2baaecdf854cea1efd100f551c8b/src/amcl/pf/particle_filter.cpp#L40)):*
> ```cpp
> #include "sensors/sensor.h"
> 
> using namespace amcl;
> ```

I'd prefer to make this `namespace amcl` instead of using


<!-- Sent from Reviewable.io -->

2020-03-12 12:35 UTC, 12tbuchman reviewed
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/amcl/2)* status: 49 of 53 files reviewed, 191 unresolved discussions (waiting on @12tbuchman and @c-andy-martin)

___
*[cfg/AMCL.cfg, line 10 at r1](https://reviewable.io/reviews/badgertechnologies/amcl/2#-Lz7t_Er5HJ0XmubXvj1:-M29dweMAr-hRNXezwFG:b-896fix) ([raw file](https://github.com/badgertechnologies/amcl/blob/ba6da8b7912ca1f1c7e7b5dc81bd48de469c440f/cfg/AMCL.cfg#L10)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

Because AMCL should not be specific to our robot, I'd like to change the default topics to something generic. Either remap these when we launch, or change the param in the launch file to our topics. I'd make the default here '/scan', which is a reasonable default for a ROS system.
</blockquote></details>

Done.
___
*[cfg/AMCL.cfg, line 11 at r1](https://reviewable.io/reviews/badgertechnologies/amcl/2#-Lz7uSfX-rciPm5qbAHc:-M29dwQJECFuBw5Hh5sx:b-896fix) ([raw file](https://github.com/badgertechnologies/amcl/blob/ba6da8b7912ca1f1c7e7b5dc81bd48de469c440f/cfg/AMCL.cfg#L11)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

And I'd make the default topic here "/points" or "/cloud", i've seen both as defaults for a point cloud topic.
</blockquote></details>

Done.
___
*[cfg/AMCL.cfg, line 13 at r1](https://reviewable.io/reviews/badgertechnologies/amcl/2#-Lz7uguC1MLNH1IPG7lr:-M29dw7_28TFCrN2lrUh:b-896fix) ([raw file](https://github.com/badgertechnologies/amcl/blob/ba6da8b7912ca1f1c7e7b5dc81bd48de469c440f/cfg/AMCL.cfg#L13)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

this should be an enumeration with 2 options. If you want an example, I know navigation/costmap_2d/cfg/ObstaclePlugin.cfg has an enumeration.
</blockquote></details>

Done.
___
*[cfg/AMCL.cfg, line 24 at r1](https://reviewable.io/reviews/badgertechnologies/amcl/2#-Lz7vdBQ0d-XSkoJDQQ2:-M29eTvTA6aRay4jwk1T:b-4cg8wb) ([raw file](https://github.com/badgertechnologies/amcl/blob/ba6da8b7912ca1f1c7e7b5dc81bd48de469c440f/cfg/AMCL.cfg#L24)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

why did you change the default here?
</blockquote></details>

not sure, changed it back
___
*[cfg/AMCL.cfg, line 47 at r1](https://reviewable.io/reviews/badgertechnologies/amcl/2#-Lz7vosC2rP-a_qk_q3n:-M29fvpC7XSQkR7jciMz:b-896fix) ([raw file](https://github.com/badgertechnologies/amcl/blob/ba6da8b7912ca1f1c7e7b5dc81bd48de469c440f/cfg/AMCL.cfg#L47)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

A user should be allowed to set a rate slower than 5hz I think. I'd make the minimum either 1 or something like 0.1 (so if they only want to publish every 10 seconds they can).
</blockquote></details>

Done.
___
*[cfg/AMCL.cfg, line 48 at r1](https://reviewable.io/reviews/badgertechnologies/amcl/2#-Lz7wEMr6va2YAmYmb66:-M29iuFr21sv8-3ae6WX:blg9vsw) ([raw file](https://github.com/badgertechnologies/amcl/blob/ba6da8b7912ca1f1c7e7b5dc81bd48de469c440f/cfg/AMCL.cfg#L48)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

The original desc of "-1.0 to disable" doesn't make much sense given the minimum is 0. I'd adjust the min to include -1.0 if the feature still exists.
</blockquote></details>

I changed the "disable rate" to 0.0.
___
*[cfg/AMCL.cfg, line 49 at r1](https://reviewable.io/reviews/badgertechnologies/amcl/2#-Lz7wS5j1fx_WA33amxh:-M29nHmC7FpuBW3e71-T:b-896fix) ([raw file](https://github.com/badgertechnologies/amcl/blob/ba6da8b7912ca1f1c7e7b5dc81bd48de469c440f/cfg/AMCL.cfg#L49)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

Do not mention anything specific to our robot, like BAR_COMMON. If there is a separate config for the path, mention that variable name instead. Also, same issue w/ -1.0 as above.
</blockquote></details>

Done.
___
*[cfg/AMCL.cfg, line 53 at r1](https://reviewable.io/reviews/badgertechnologies/amcl/2#-Lz7wdRKBzqqla8w-09f:-M29nHPrDsiBhxr-bJaK:b-896fix) ([raw file](https://github.com/badgertechnologies/amcl/blob/ba6da8b7912ca1f1c7e7b5dc81bd48de469c440f/cfg/AMCL.cfg#L53)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

Change 'map type is 3' to whatever you name the enumeration I asked for above.
</blockquote></details>

Done.
___
*[cfg/AMCL.cfg, line 156 at r1](https://reviewable.io/reviews/badgertechnologies/amcl/2#-Lz910OL9OtF2ULTISdW:-M29oABb6paueuzeQ9OK:bvzheqm) ([raw file](https://github.com/badgertechnologies/amcl/blob/ba6da8b7912ca1f1c7e7b5dc81bd48de469c440f/cfg/AMCL.cfg#L156)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

if you don't already have a config for the full path to the savedpose, this might be a good place to put it. Again, we don't want to hardcode any paths to robot specific locations in this code. Paths should be setup by a launch file in ant_navigation or bar_launchers.
</blockquote></details>

I actually took this feature out as we dont use it. Should I add it back in for consistency or is it okay to leave it out?


<!-- Sent from Reviewable.io -->

2020-03-12 19:17 UTC, c-andy-martin commented
___
*[src/amcl/pf/particle_filter.cpp, line 28 at r7](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M2AOpTT02Es_O4yr6EE:-M2FAYqs8c72Cxd94BN3:b-7s6cca) ([raw file](https://github.com/badgertechnologies/amcl/blob/74db8df1672f2baaecdf854cea1efd100f551c8b/src/amcl/pf/particle_filter.cpp#L28)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

lets switch to <cmath>
</blockquote></details>

cmath


<!-- Sent from Reviewable.io -->

2020-03-12 19:31 UTC, c-andy-martin commented
___
*[src/amcl/pf/particle_filter.cpp, line 86 at r7](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M2FDZ4bDdUmWV3uQmPn:-M2FDZ4bDdUmWV3uQmPo:b2ifvgu) ([raw file](https://github.com/badgertechnologies/amcl/blob/74db8df1672f2baaecdf854cea1efd100f551c8b/src/amcl/pf/particle_filter.cpp#L86)):*
> ```cpp
>     }
> 
>     // HACK: is 3 times max_samples_ enough?
> ```

If we switch kdtree to using std::vector and resizing automatically, we can get rid of setting the number of nodes a-priori and get rid of this "HACK"


<!-- Sent from Reviewable.io -->

2020-03-12 20:08 UTC, c-andy-martin requested changes
> Reviewed 1 of 38 files at r4.
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/amcl/2)* status: 50 of 53 files reviewed, 198 unresolved discussions (waiting on @12tbuchman and @c-andy-martin)

___
*[src/amcl/pf/particle_filter.cpp, line 44 at r7](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M2FAdir3XzGfJ5aXdW3:-M2FAdir3XzGfJ5aXdW4:b4010ll) ([raw file](https://github.com/badgertechnologies/amcl/blob/74db8df1672f2baaecdf854cea1efd100f551c8b/src/amcl/pf/particle_filter.cpp#L44)):*
> ```cpp
> // Create a new filter
> ParticleFilter::ParticleFilter(int min_samples, int max_samples, double alpha_slow, double alpha_fast,
>                                std::shared_ptr<std::function<PFVector()>> random_pose_fn_ptr)
> ```

as pointed out elsewhere, let's move to just passing std::function, not wrapping in shared_ptr
___
*[src/amcl/pf/particle_filter.cpp, line 50 at r7](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M2FAmVw01fdQe4rT06u:-M2FAmVw01fdQe4rT06v:b-7rgjoj) ([raw file](https://github.com/badgertechnologies/amcl/blob/74db8df1672f2baaecdf854cea1efd100f551c8b/src/amcl/pf/particle_filter.cpp#L50)):*
> ```cpp
>   PFSample* sample;
> 
>   srand48(time(NULL));
> ```

this does not belong here, but in `main()`. What if we wanted to create/destroy ParticleFilter's at some point? We don't want to be re-seeding the generator all the time. Calling srand48 affects all threads in the process, so that's why it should be in main. Move the headers we needed for `time()` to main as well.
___
*[src/amcl/pf/particle_filter.cpp, line 248 at r7](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M2FE9koEX98dtV_aZtj:-M2FE9koEX98dtV_aZtk:b-x4f1f2) ([raw file](https://github.com/badgertechnologies/amcl/blob/74db8df1672f2baaecdf854cea1efd100f551c8b/src/amcl/pf/particle_filter.cpp#L248)):*
> ```cpp
>       update_sample->weight /= total;
>     }
>     // Update running averages of likelihood of samples (Prob Rob p258)
> ```

Let's change "(Prob Rob p258)" to "(from Probabilistic Robotics 'Augmented_MCL' algorithm)"
___
*[src/amcl/pf/particle_filter.cpp, line 283 at r7](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M2FGfpW4sYZgPmD2iQN:-M2FGfpW4sYZgPmD2iQO:byqphic) ([raw file](https://github.com/badgertechnologies/amcl/blob/74db8df1672f2baaecdf854cea1efd100f551c8b/src/amcl/pf/particle_filter.cpp#L283)):*
> ```cpp
> 
>   // Build up cumulative probability table for resampling.
>   c = std::vector<double>(set_a->sample_count + 1);
> ```

It would be more efficient to not declare the vector until here (so move the declaration above here) and construct it w/ the right size right away:
```
std::vector<double> c(set_a->sample_count + 1);
```
___
*[src/amcl/pf/particle_filter.cpp, line 387 at r7](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M2FLUuu5PqfKKJKM4qv:-M2FLUuu5PqfKKJKM4qw:bdrklto) ([raw file](https://github.com/badgertechnologies/amcl/blob/74db8df1672f2baaecdf854cea1efd100f551c8b/src/amcl/pf/particle_filter.cpp#L387)):*
> ```cpp
>     sample_b = &(set_b->samples[set_b->sample_count++]);
> 
>     if (drand48() < w_diff)
> ```

Let's add curly braces here, I don't like having an if w/out braces paired w/ an else that does have braces
___
*[src/amcl/pf/particle_filter.cpp, line 580 at r7](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M2FM0Eo4bWJOo6pi8nQ:-M2FM0Eo4bWJOo6pi8nR:b-yqm047) ([raw file](https://github.com/badgertechnologies/amcl/blob/74db8df1672f2baaecdf854cea1efd100f551c8b/src/amcl/pf/particle_filter.cpp#L580)):*
> ```cpp
> 
>     // Compute covariance in linear components
>     for (j = 0; j < 2; j++)
> ```

Let's add a brace here. I don't like having the inner for w/ a brace but not the outer for


<!-- Sent from Reviewable.io -->

2020-03-12 20:10 UTC, 12tbuchman reviewed
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/amcl/2)* status: 50 of 53 files reviewed, 198 unresolved discussions (waiting on @12tbuchman and @c-andy-martin)

___
*[cfg/AMCL.cfg, line 48 at r3](https://reviewable.io/reviews/badgertechnologies/amcl/2#-LzIc_YuEpV9EO68IJYB:-M2FMjn43_8gMWydNSSO:b-896fix) ([raw file](https://github.com/badgertechnologies/amcl/blob/8a8873533e84b3894a5f385b1d56234ebbe31d7e/cfg/AMCL.cfg#L48)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

Thinking about these changes. If we want others to adopt our fork of AMCL it will be much easier if we do not change the name of existing parameters. Could we just keep these as `laser_*`? Also, why not use the same parameter names to control both the 2D and 3D matching processes where appropriate instead of having a dupilcate version of the parameter?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-03-12 20:22 UTC, c-andy-martin commented
___
*[src/amcl/node/node.cpp, line 39 at r7](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M2FPAaj1KMZOlJAEK9z:-M2FPAak7NSochHRwePU:b-wtpo60) ([raw file](https://github.com/badgertechnologies/amcl/blob/74db8df1672f2baaecdf854cea1efd100f551c8b/src/amcl/node/node.cpp#L39)):*
> ```cpp
> #include <tf/transform_datatypes.h>
> 
> #include <cstdlib>
> ```

standard includes go after the "node.h", then 3rd parties. Also, I always put 3rd party libraries ahead of any badger libraries. Then finally after all that, the local files (which are in the correct spot already at the end)


<!-- Sent from Reviewable.io -->

2020-03-12 20:30 UTC, c-andy-martin commented
___
*[src/amcl/node/node.cpp, line 198 at r7](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M2FQPRL1lubOJj3i5bp:-M2FQPRL1lubOJj3i5bq:b-p7dzh4) ([raw file](https://github.com/badgertechnologies/amcl/blob/74db8df1672f2baaecdf854cea1efd100f551c8b/src/amcl/node/node.cpp#L198)):*
> ```cpp
>   a_thresh_ = config.update_min_a;
> 
>   if (config.resample_model_type == "multinomial")
> ```

I feel like there is a lot of duplicated work here and in the constructor. In general, I think it is better to not even look at the static parameters for things that are dynamic, and on every call (including the first call) set the internal variables from the dynamic parameters. The dynamic reconfigure code already set the dynamic parameters to whatever was in the static parameter. What you can do to the locking is: first instantiate the dynamic reconfigure, then grab the lock (so after the first call), then subscribe to topics and make timers while holding the lock. This way you know everything is configured, there are no races, and you don't have to duplicate any work anywhere.


<!-- Sent from Reviewable.io -->

2020-03-12 20:41 UTC, c-andy-martin requested changes
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/amcl/2)* status: 50 of 53 files reviewed, 205 unresolved discussions (waiting on @12tbuchman and @c-andy-martin)

___
*[src/amcl/node/node.cpp, line 58 at r7](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M2FPTmw1EeM8Q4zg4hb:-M2FPTmw1EeM8Q4zg4hc:bq7efd4) ([raw file](https://github.com/badgertechnologies/amcl/blob/74db8df1672f2baaecdf854cea1efd100f551c8b/src/amcl/node/node.cpp#L58)):*
> ```cpp
>   std::lock_guard<std::mutex> cfl(configuration_mutex_);
> 
>   // 2: 2d, 3: 3d, else: none
> ```

as pointed out elsewhere, I want this to be an enum in the .cfg file and use the enum names the auto-generated code makes for us
___
*[src/amcl/node/node.cpp, line 265 at r7](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M2FQAKp8yFGEH0YpssM:-M2FQAKp8yFGEH0YpssN:ba5i4w8) ([raw file](https://github.com/badgertechnologies/amcl/blob/74db8df1672f2baaecdf854cea1efd100f551c8b/src/amcl/node/node.cpp#L265)):*
> ```cpp
>   pf_init_pose_mean.v[2] = tf::getYaw(last_published_pose_->pose.pose.orientation);
>   PFMatrix pf_init_pose_cov;
>   pf_init_pose_cov.m[0][0] = last_published_pose_->pose.covariance[6 * 0 + 0];
> ```

we should use the names for these that were defined elsewhere (whatever you make them, like COVARIANCE_XX)
___
*[src/amcl/node/node.cpp, line 373 at r7](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M2FROBQ35B2rvOyQUMn:-M2FROBQ35B2rvOyQUMo:bewtewx) ([raw file](https://github.com/badgertechnologies/amcl/blob/74db8df1672f2baaecdf854cea1efd100f551c8b/src/amcl/node/node.cpp#L373)):*
> ```cpp
>   // Report the overall filter covariance, rather than the
>   // covariance for the highest-weight cluster
>   p->pose.covariance[6 * 5 + 5] = set->cov.m[2][2];
> ```

this could be COVARIANCE_AA
___
*[src/amcl/node/node.cpp, line 727 at r7](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M2FS3ncA8K2V1_iNtk6:-M2FS3ncA8K2V1_iNtk7:ba588pu) ([raw file](https://github.com/badgertechnologies/amcl/blob/74db8df1672f2baaecdf854cea1efd100f551c8b/src/amcl/node/node.cpp#L727)):*
> ```cpp
> }
> 
> std::string Node::makeFilepathFromName(const std::string filename)
> ```

This function belong in badger_lib somewhere, not in amcl. Lets move it there (or use it if it already exists)
___
*[src/amcl/node/node_3d.cpp, line 332 at r7](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M2FSrlIBtDhVJJM-mY1:-M2FSrlIBtDhVJJM-mY2:b-nerzw4) ([raw file](https://github.com/badgertechnologies/amcl/blob/74db8df1672f2baaecdf854cea1efd100f551c8b/src/amcl/node/node_3d.cpp#L332)):*
> ```cpp
>   for (int i = min_cells[0]; i < max_cells[0]; i++)
>     for (int j = min_cells[1]; j < max_cells[1]; j++)
>       fsi->push_back(std::make_pair(i, j));
> ```

This is just putting every cell into free space. What we need to do is like 2D is doing, see how far the nearest obstacle is. But, what we need to do is test the entire column of space over the x/y since we are 3D. I suggest testing from the min_z to the max_z in the octomap. If any of the cells returns <= non_free_space_radius_ then do not set that x/y value as free space. I know this will take some time to compute, and this is another thing that is merely determined by the cspace (and the radius parameter) that we could store on disk after computing.


<!-- Sent from Reviewable.io -->

2020-03-12 21:02 UTC, 12tbuchman reviewed
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/amcl/2)* status: 50 of 53 files reviewed, 204 unresolved discussions (waiting on @12tbuchman and @c-andy-martin)

___
*[include/amcl/map/map.h, line 51 at r2](https://reviewable.io/reviews/badgertechnologies/amcl/2#-LzDKBEKBEjljFN1nK2Y:-M2FVersDc2h7BAEEJYv:b-896fix) ([raw file](https://github.com/badgertechnologies/amcl/blob/bbbafd470c81f3bf418c310bd0334bc4469d4b08/include/amcl/map/map.h#L51)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

pcl point is sufficient and used in lots of places. I'd go for that.
</blockquote></details>

Done.
___
*[include/amcl/map/map.h, line 53 at r2](https://reviewable.io/reviews/badgertechnologies/amcl/2#-LzDhL9y9aGnzNBJdOPr:-M2FW72B6Bsdw0dWcyP-:b-896fix) ([raw file](https://github.com/badgertechnologies/amcl/blob/bbbafd470c81f3bf418c310bd0334bc4469d4b08/include/amcl/map/map.h#L53)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

if something isn't used, delete it. we can always add it back later, and it makes less code to maintain.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-03-12 21:21 UTC, 12tbuchman reviewed
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/amcl/2)* status: 50 of 53 files reviewed, 204 unresolved discussions (waiting on @12tbuchman and @c-andy-martin)

___
*[include/amcl/map/occupancy_map.h, line 24 at r2](https://reviewable.io/reviews/badgertechnologies/amcl/2#-LzDfbH93_CR3EQnC6pc:-M2F_UlN4BQ-dVKIV-1x:b-896fix) ([raw file](https://github.com/badgertechnologies/amcl/blob/bbbafd470c81f3bf418c310bd0334bc4469d4b08/include/amcl/map/occupancy_map.h#L24)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

Lets remove your name from every source file, and just put it in the package.xml.
</blockquote></details>

Done.
___
*[include/amcl/map/occupancy_map.h, line 29 at r5](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M1adrJX6zy5hglWT8v8:-M2FbgGT05-8_yb-RW8s:b-896fix) ([raw file](https://github.com/badgertechnologies/amcl/blob/95b6eb20da05f9f418bc7ea0645e69d04bc7dd99/include/amcl/map/occupancy_map.h#L29)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

This include should come last, not first, as it is local. The only exception to this is in .cpp files:

https://google.github.io/styleguide/cppguide.html#Names_and_Order_of_Includes
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-03-12 21:21 UTC, 12tbuchman reviewed
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/amcl/2)* status: 50 of 53 files reviewed, 204 unresolved discussions (waiting on @12tbuchman and @c-andy-martin)

___
*[include/amcl/map/occupancy_map.h, line 33 at r2](https://reviewable.io/reviews/badgertechnologies/amcl/2#-LzDg0kP8nS6GFpgpHpM:-M2FbvSr4Ywe-1Y7oEIv:b-6pee2i) ([raw file](https://github.com/badgertechnologies/amcl/blob/bbbafd470c81f3bf418c310bd0334bc4469d4b08/include/amcl/map/occupancy_map.h#L33)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

oh, but now this is a c++ header, so you can remove the line
</blockquote></details>

i should remove the cmath include?


<!-- Sent from Reviewable.io -->

2020-03-12 21:22 UTC, 12tbuchman reviewed
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/amcl/2)* status: 50 of 53 files reviewed, 204 unresolved discussions (waiting on @12tbuchman and @c-andy-martin)

___
*[include/amcl/map/map.h, line 24 at r1](https://reviewable.io/reviews/badgertechnologies/amcl/2#-Lz926KZ7Hj0JbyTRpXg:-M2Fc37m3QO00tj6x48L:b-896fix) ([raw file](https://github.com/badgertechnologies/amcl/blob/ba6da8b7912ca1f1c7e7b5dc81bd48de469c440f/include/amcl/map/map.h#L24)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

FWIW, I think we can get rid of all 'Maintainer: ' from every file, and just use the one listed in package.xml.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-03-12 21:24 UTC, 12tbuchman reviewed
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/amcl/2)* status: 50 of 53 files reviewed, 204 unresolved discussions (waiting on @12tbuchman and @c-andy-martin)

___
*[include/amcl/map/map.h, line 39 at r3](https://reviewable.io/reviews/badgertechnologies/amcl/2#-LzIE4XhC9vxHQQwBWyT:-M2FcXZXAw6QuXP-gS98:bb6un1j) ([raw file](https://github.com/badgertechnologies/amcl/blob/770d4c63beb80b8977948e006adb7bdbc3c1d735/include/amcl/map/map.h#L39)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

This still isn't fixed. I don't think removing the destructor will not make it virtual. You should make a virtual destructor that does nothing.
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2020-03-13 15:37 UTC, 12tbuchman reviewed
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/amcl/2)* status: 50 of 53 files reviewed, 204 unresolved discussions (waiting on @12tbuchman and @c-andy-martin)

___
*[include/amcl/map/occupancy_map.h, line 42 at r5](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M1fCuBKE6jMzF1dvXYP:-M2JXPNh4EQZz4X7QM7r:b-896fix) ([raw file](https://github.com/badgertechnologies/amcl/blob/95b6eb20da05f9f418bc7ea0645e69d04bc7dd99/include/amcl/map/occupancy_map.h#L42)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

These constants should be defined in the amcl namespace, something like this outside the struct declaration:
```
constexpr int8_t CELL_FREE = -1;
constexpr int8_t CELL_UNKNOWN = 0;
constexpr int8_t CELL_OCCUPIED = 1;
```
Then whenever using `occ_state` use the named constants
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-03-16 18:52 UTC, c-andy-martin commented
___
*[src/amcl/node/node_3d.cpp, line 332 at r7](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M2FSrlIBtDhVJJM-mY1:-M2ZfncP5pJ1wk3axaTK:b-d8xz79) ([raw file](https://github.com/badgertechnologies/amcl/blob/74db8df1672f2baaecdf854cea1efd100f551c8b/src/amcl/node/node_3d.cpp#L332)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

This is just putting every cell into free space. What we need to do is like 2D is doing, see how far the nearest obstacle is. But, what we need to do is test the entire column of space over the x/y since we are 3D. I suggest testing from the min_z to the max_z in the octomap. If any of the cells returns <= non_free_space_radius_ then do not set that x/y value as free space. I know this will take some time to compute, and this is another thing that is merely determined by the cspace (and the radius parameter) that we could store on disk after computing.
</blockquote></details>

Actually, an even better idea is to use the *2D* map for free space indices. In other words, do the same thing as the 2D node for free space indices. This way, the noise on the 3D map won't matter (as it gets cleaned up for the 2D nav map). And you won't have to worry about robot height.


<!-- Sent from Reviewable.io -->

2020-03-16 19:14 UTC, c-andy-martin requested changes
> Reviewed 1 of 2 files at r7.
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/amcl/2)* status: 51 of 53 files reviewed, 214 unresolved discussions (waiting on @12tbuchman and @c-andy-martin)

___
*[src/amcl/node/node.cpp, line 117 at r7](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M2ZgEUlBnNgcMFALR9j:-M2ZgEUlBnNgcMFALR9k:b-fyvt89) ([raw file](https://github.com/badgertechnologies/amcl/blob/74db8df1672f2baaecdf854cea1efd100f551c8b/src/amcl/node/node.cpp#L117)):*
> ```cpp
>   else
>   {
>     ROS_WARN("Unknown resample model type \"%s\"; defaulting to multinomial model", tmp_model_type.c_str());
> ```

I greatly prefer to avoid c_str() whenever possible. Here I would do:
```
ROS_WARN_STREAM("Unknown resample model type " << tmp_model_type << "; defaulting to multinomial model");
```
___
*[src/amcl/node/node.cpp, line 170 at r7](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M2ZgkBr3MLm9gJDlwTY:-M2ZgkBr3MLm9gJDlwTZ:b-lsw91t) ([raw file](https://github.com/badgertechnologies/amcl/blob/74db8df1672f2baaecdf854cea1efd100f551c8b/src/amcl/node/node.cpp#L170)):*
> ```cpp
>             new dynamic_reconfigure::Server<amcl::AMCLConfig>(ros::NodeHandle("~")));
>   dynamic_reconfigure::Server<amcl::AMCLConfig>::CallbackType cb = boost::bind(&Node::reconfigureCB, this, _1, _2);
>   dsrv_->setCallback(cb);
> ```

you might want to have the dynamic reconfigure happen before you have subscribed for other callbacks. that way the first call will have already happened (although you may need to make the other changes I suggested around dynamic reconfigure first, such as not duplicating work between static/dynamic, see my other comments).
___
*[src/amcl/node/node.cpp, line 567 at r7](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M2Zi8xQ6EuPZVtJOo8_:-M2Zi8xQ6EuPZVtJOo8a:b4otiqx) ([raw file](https://github.com/badgertechnologies/amcl/blob/74db8df1672f2baaecdf854cea1efd100f551c8b/src/amcl/node/node.cpp#L567)):*
> ```cpp
>   catch (std::exception& e)
>   {
>     ROS_WARN("exception: %s", e.what());
> ```

this can be `ROS_WARN_STREAM("exception: " << e.what());`
also, we should print more than just 'exception' I think, describe where you are:
`ROS_WARN_STREAM("Exception in loadPoseFromFile: " << e.what());`
Last, this should probably be ROS_INFO actually
___
*[src/amcl/node/node.cpp, line 568 at r7](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M2ZiOmo43MXTjORF0Du:-M2ZiOmp45w0PjjiB2LM:b-fmzwql) ([raw file](https://github.com/badgertechnologies/amcl/blob/74db8df1672f2baaecdf854cea1efd100f551c8b/src/amcl/node/node.cpp#L568)):*
> ```cpp
>   {
>     ROS_WARN("exception: %s", e.what());
>     ROS_DEBUG("Failed to parse saved YAML pose.");
> ```

Doesn't seem like this should be DEBUG probably should be ROS_WARN
___
*[src/amcl/node/node.cpp, line 649 at r7](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M2ZivBr97feK6_Mz8jL:-M2ZivBr97feK6_Mz8jM:bhslmo3) ([raw file](https://github.com/badgertechnologies/amcl/blob/74db8df1672f2baaecdf854cea1efd100f551c8b/src/amcl/node/node.cpp#L649)):*
> ```cpp
>   // We need to apply the last transform to the latest odom pose to get
>   // the latest map pose to store.  We'll take the covariance from
>   // last_published_pose_.
> ```

don't you need the tf_mutex_ held for the below line? Also, I didn't analyze the order you are grabbing the other locks, you might want to only hold the tf_mutex_ while you need it to get the map_pose.
___
*[src/amcl/node/node.cpp, line 834 at r7](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M2Zjf9z09R-Y2sneiLk:-M2Zjf9z09R-Y2sneiLl:bjc2a8v) ([raw file](https://github.com/badgertechnologies/amcl/blob/74db8df1672f2baaecdf854cea1efd100f551c8b/src/amcl/node/node.cpp#L834)):*
> ```cpp
>   else
>   {
>     delta_bearing = angleDiff(atan2(delta.v[1], delta.v[0]), odom_integrator_last_pose_.v[2] + delta_rot / 2);
> ```

as pointed out elsewhere, we should switch to the angles package
___
*[src/amcl/node/node.cpp, line 881 at r7](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M2ZjuLv4FvhkCwZt1Rv:-M2ZjuLv4FvhkCwZt1Rw:b8lavy3) ([raw file](https://github.com/badgertechnologies/amcl/blob/74db8df1672f2baaecdf854cea1efd100f551c8b/src/amcl/node/node.cpp#L881)):*
> ```cpp
>   }
>   unsigned int rand_index = drand48() * free_space_indices_->size();
>   std::pair<int, int> free_point = free_space_indices_->at(rand_index);
> ```

seems like there should be a loop here to retry if we draw a non-free space pose. the loop must have some limit so we don't wait forever trying to get one.
___
*[src/amcl/node/node.cpp, line 1055 at r7](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M2ZkXyZ4Ar5OXI2gnof:-M2ZkXyZ4Ar5OXI2gnog:b7wujfh) ([raw file](https://github.com/badgertechnologies/amcl/blob/74db8df1672f2baaecdf854cea1efd100f551c8b/src/amcl/node/node.cpp#L1055)):*
> ```cpp
>     *force_update = false;
> 
>     // Set the planar scanner update flags
> ```

this comment needs tweaking, we aren't in the planar scanner code
___
*[src/amcl/node/node.cpp, line 1122 at r7](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M2ZksxV-SE6pZamVrww:-M2ZksxV-SE6pZamVrwx:b-2wg5va) ([raw file](https://github.com/badgertechnologies/amcl/blob/74db8df1672f2baaecdf854cea1efd100f551c8b/src/amcl/node/node.cpp#L1122)):*
> ```cpp
>   else if (tf_.resolve(msg.header.frame_id) != tf_.resolve(global_frame_id_))
>   {
>     ROS_WARN("Ignoring initial pose in frame \"%s\"; initial poses must be in the global frame, \"%s\"",
> ```

let's make this a ROS_WARN_STREAM and not use c_str()
___
*[src/amcl/node/node.cpp, line 1220 at r7](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M2Zl6yi3gW84OOzX65N:-M2Zl6yi3gW84OOzX65O:bfq5h50) ([raw file](https://github.com/badgertechnologies/amcl/blob/74db8df1672f2baaecdf854cea1efd100f551c8b/src/amcl/node/node.cpp#L1220)):*
> ```cpp
> }
> 
> double Node::normalize(double z)
> ```

we should be using the angles package. we *could* just call that package here and below instead of having to clean up every call to this function and the function below.


<!-- Sent from Reviewable.io -->

2020-03-16 19:30 UTC, c-andy-martin requested changes
> Reviewed 2 of 7 files at r6.
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/amcl/2)* status: all files reviewed, 222 unresolved discussions (waiting on @12tbuchman and @c-andy-martin)

___
*[src/amcl/node/node_2d.cpp, line 458 at r7](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M2ZlfF84guTs211_rnt:-M2ZlfF84guTs211_rnu:bausg7t) ([raw file](https://github.com/badgertechnologies/amcl/blob/74db8df1672f2baaecdf854cea1efd100f551c8b/src/amcl/node/node_2d.cpp#L458)):*
> ```cpp
>   {
>     ROS_ERROR("Couldn't transform from %s to %s, even though the message notifier is in use",
>               frame_id.c_str(), base_frame_id_.c_str());
> ```

let's clean up these c_str() and use ROS_ERROR_STREAM
___
*[src/amcl/node/node_2d.cpp, line 512 at r7](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M2ZlkihDAYdw49Hsen2:-M2ZlkihDAYdw49Hsen3:b-2n3chl) ([raw file](https://github.com/badgertechnologies/amcl/blob/74db8df1672f2baaecdf854cea1efd100f551c8b/src/amcl/node/node_2d.cpp#L512)):*
> ```cpp
>     *angle_increment = tf::getYaw(inc_q) - *angle_min;
>     // wrapping angle to [-pi .. pi]
>     *angle_increment = fmod(*angle_increment + 5 * M_PI, 2 * M_PI) - M_PI;
> ```

this should be a call to angles normalize right?
___
*[src/amcl/node/node_2d.cpp, line 637 at r7](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M2ZluSe0LFo4ape_YhQ:-M2ZluSe0LFo4ape_YhR:b-8mydji) ([raw file](https://github.com/badgertechnologies/amcl/blob/74db8df1672f2baaecdf854cea1efd100f551c8b/src/amcl/node/node_2d.cpp#L637)):*
> ```cpp
>     ROS_WARN("No planar scan received (and thus no pose updates have been published) for %f seconds."
>              "Verify that data is being published on the %s topic.",
>              d.toSec(), ros::names::resolve(scan_topic_).c_str());
> ```

let's clean up this c_str() and use ROS_WARN_STREAM
___
*[src/amcl/node/node_3d.cpp, line 99 at r7](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M2Zm2kHBlus_VakcNsl:-M2Zm2kHBlus_VakcNsm:b-k1iq01) ([raw file](https://github.com/badgertechnologies/amcl/blob/74db8df1672f2baaecdf854cea1efd100f551c8b/src/amcl/node/node_3d.cpp#L99)):*
> ```cpp
>   {
>     ROS_WARN("Unknown point cloud scanner model type \"%s\"; defaulting to point cloud scanner model",
>              tmp_model_type.c_str());
> ```

let's use ROS_WARN_STREAM and get rid of the `c_str()`
___
*[src/amcl/node/node_3d.cpp, line 281 at r7](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M2ZnLv-9Pq9-NlHPiJe:-M2ZnLv-9Pq9-NlHPiJf:b-y4bxkb) ([raw file](https://github.com/badgertechnologies/amcl/blob/74db8df1672f2baaecdf854cea1efd100f551c8b/src/amcl/node/node_3d.cpp#L281)):*
> ```cpp
>   std::shared_ptr<OctoMap> octomap = std::make_shared<OctoMap>(wait_for_occupancy_map_);
>   ROS_ASSERT(octomap);
>   octomap::AbstractOcTree* absoctree;
> ```

it might be more maintainable to initialize this to `nullptr` in case in the future there is more complex logic below where we set `absoctree` (right now, there is no path it would stay uninitialized, but for stack variables, it is often a good idea to initialize them since they are not initialized automatically).
___
*[src/amcl/node/node_3d.cpp, line 453 at r7](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M2ZoNOE4gOxfWAPqrAN:-M2ZoNOE4gOxfWAPqrAO:bd1mh7t) ([raw file](https://github.com/badgertechnologies/amcl/blob/74db8df1672f2baaecdf854cea1efd100f551c8b/src/amcl/node/node_3d.cpp#L453)):*
> ```cpp
>     ROS_ERROR("Couldn't transform from %s to %s, "
>               "even though the message notifier is in use",
>               frame_id.c_str(), base_frame_id_.c_str());
> ```

let's get rid of the c_str() and use ROS_ERROR_STREAM
___
*[src/amcl/node/node_3d.cpp, line 596 at r7](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M2Zom5J2vk7jte7NYge:-M2Zom5J2vk7jte7NYgf:bj9qrn0) ([raw file](https://github.com/badgertechnologies/amcl/blob/74db8df1672f2baaecdf854cea1efd100f551c8b/src/amcl/node/node_3d.cpp#L596)):*
> ```cpp
>     ROS_DEBUG("No point cloud scan received (and thus no pose updates have been published) for %f seconds. "
>               "Verify that data is being published on the %s topic.",
>               d.toSec(), ros::names::resolve(scan_topic_).c_str());
> ```

let's clean this up to be ROS_DEBUG_STREAM and not use c_str()
___
*[src/amcl/node/node_3d.cpp, line 603 at r7](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M2ZoqERBf2hfweQGYBw:-M2ZoqERBf2hfweQGYBx:b-bzqat9) ([raw file](https://github.com/badgertechnologies/amcl/blob/74db8df1672f2baaecdf854cea1efd100f551c8b/src/amcl/node/node_3d.cpp#L603)):*
> ```cpp
> {
>   scanner_.setMapFactors(global_localization_off_map_factor_, global_localization_non_free_space_factor_,
>                                      non_free_space_radius_);
> ```

the white space doesn't line up well here, seems like this should be lined up near the `(`?


<!-- Sent from Reviewable.io -->

2020-03-16 19:48 UTC, 12tbuchman reviewed
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/amcl/2)* status: all files reviewed, 221 unresolved discussions (waiting on @12tbuchman and @c-andy-martin)

___
*[include/amcl/map/occupancy_map.h, line 53 at r2](https://reviewable.io/reviews/badgertechnologies/amcl/2#-LzDgDfk7cnU4Gwm0Gqx:-M2JpEmO0RiI08W-K8Os:bb7f2mf) ([raw file](https://github.com/badgertechnologies/amcl/blob/bbbafd470c81f3bf418c310bd0334bc4469d4b08/include/amcl/map/occupancy_map.h#L53)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

I disagree with the style guide a bit here. You should mark these all virtual, as you don't know if sometime down the road you will want to inherit from this class. Also, I mark everything protected for that reason too, unless there is some reason a child class must not use a private variable. Such cases are rare. I'm all the time running into code upstream where they only make a few things virtual, or they make the data I need to change the behavior of private. The style guide makes sense if you are writing closed source code you are sure is never going to get reused, but I tend to think the more flexible the better. The only exception I make to this in new code for myself is when I have performance critical code paths. Those I might make inline and not virtual. Or if I'm writing a class or struct that I'm pretty sure will never be inherited from, in such cases I would not mark anything virtual (but I wouldn't bother with the 'final' keyword).
</blockquote></details>

done
___
*[include/amcl/map/occupancy_map.h, line 123 at r3](https://reviewable.io/reviews/badgertechnologies/amcl/2#-LzDxJjy67TeH2eNSHib:-M2KIuW68_2HzRoaQlTS:b-896fix) ([raw file](https://github.com/badgertechnologies/amcl/blob/770d4c63beb80b8977948e006adb7bdbc3c1d735/include/amcl/map/occupancy_map.h#L123)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

Here is exactly what you need to do. Delete this line, and the `operator<` below. Then back up around line 82 (inside `struct CellData` add:

```
    inline bool operator<(const CellData& rhs) const                                                                             
    {                                                                                                                            
      return occ_map->getOccDist(i, j) > rhs.occ_map->getOccDist(rhs.i, rhs.j);                                                  
    }                                                                                                                            
```
I tested this and it compiles fine.
       
</blockquote></details>

Done.
___
*[include/amcl/map/occupancy_map.h, line 61 at r5](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M1fDlWJ53jgZY2WLIhF:-M2K5wYw2p-BHEHDpPE0:b-elyu9s) ([raw file](https://github.com/badgertechnologies/amcl/blob/95b6eb20da05f9f418bc7ea0645e69d04bc7dd99/include/amcl/map/occupancy_map.h#L61)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

I really don't like the name 'cspace' we inherited from AMCL. Either rename it now to something like 'DistanceCache' or 'DistanceLUT' or take a to do by logging an issue in Jira to do this renaming soon.
</blockquote></details>

Done. Created a story in Jira.
___
*[include/amcl/map/occupancy_map.h, line 65 at r5](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M1fE3yHEx2Y6aqYbMgG:-M2K5wqr-GAozxhw7b1N:b-elyu9s) ([raw file](https://github.com/badgertechnologies/amcl/blob/95b6eb20da05f9f418bc7ea0645e69d04bc7dd99/include/amcl/map/occupancy_map.h#L65)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

I don't like AMCL abbreviating occupancy as 'occ' everywhere, its too dense. Either rename such occurrences 'Occupancy' now or take a to do on a Jira ticket to do it soon.
</blockquote></details>

Done. Created a story in Jira.
___
*[include/amcl/map/occupancy_map.h, line 71 at r5](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M1fEO35DBH4u_15wi4u:-M2K8Ld9BIrD2kNwRZZy:b-896fix) ([raw file](https://github.com/badgertechnologies/amcl/blob/95b6eb20da05f9f418bc7ea0645e69d04bc7dd99/include/amcl/map/occupancy_map.h#L71)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

I would prefer the name 'setCellState' as it might get set to free or unknown or occupied, which isn't what the name implies.
</blockquote></details>

Done.
___
*[include/amcl/map/occupancy_map.h, line 94 at r5](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M1fEi4t23GfeQFqgAH6:-M2KInnvDb0Aq5TCxE8r:b-896fix) ([raw file](https://github.com/badgertechnologies/amcl/blob/95b6eb20da05f9f418bc7ea0645e69d04bc7dd99/include/amcl/map/occupancy_map.h#L94)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

I don't like this implicit conversion to an integer. Also, I like to be explicit about which way I want to truncate/round, like this:
```
cell_radius_ = static_cast<int>(std::floor(max_dist / resolution));
```
</blockquote></details>

Done.
___
*[include/amcl/map/octomap.h, line 27 at r3](https://reviewable.io/reviews/badgertechnologies/amcl/2#-LzID2YS1c2-S9z5rjc_:-M2ZsxMUCgiP89CzIR2d:b-896fix) ([raw file](https://github.com/badgertechnologies/amcl/blob/770d4c63beb80b8977948e006adb7bdbc3c1d735/include/amcl/map/octomap.h#L27)):*
<details><summary><i>Previously, 12tbuchman (Tyler Buchman) wrote…</i></summary><blockquote>

Lets discuss this.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-03-16 19:55 UTC, 12tbuchman reviewed
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/amcl/2)* status: all files reviewed, 221 unresolved discussions (waiting on @12tbuchman and @c-andy-martin)

___
*[include/amcl/map/octomap.h, line 67 at r3](https://reviewable.io/reviews/badgertechnologies/amcl/2#-LzIFaJu7n8X4sxlRSR-:-M2ZuSaw4iKs5MuorZOu:b-896fix) ([raw file](https://github.com/badgertechnologies/amcl/blob/770d4c63beb80b8977948e006adb7bdbc3c1d735/include/amcl/map/octomap.h#L67)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

Read "Do the..." as "To the..." I hate that you can't edit once you publish :D
</blockquote></details>

Done.
___
*[include/amcl/map/octomap.h, line 72 at r3](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M1g1_f0AgJnSpA_6U0q:-M2ZuUMx0XfVirAq6BfL:b-896fix) ([raw file](https://github.com/badgertechnologies/amcl/blob/770d4c63beb80b8977948e006adb7bdbc3c1d735/include/amcl/map/octomap.h#L72)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

pls put the `operator<` here, as per my comments in occupancy_map.,h
</blockquote></details>

Done.
___
*[include/amcl/map/octomap.h, line 122 at r3](https://reviewable.io/reviews/badgertechnologies/amcl/2#-LzIHmBZ4t5W3ia1LbkH:-M2ZuZgg-ki-zNyDidga:b-896fix) ([raw file](https://github.com/badgertechnologies/amcl/blob/770d4c63beb80b8977948e006adb7bdbc3c1d735/include/amcl/map/octomap.h#L122)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

See my comment on occupancy_grid, you should be able to do the same thing here.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-03-17 17:17 UTC, c-andy-martin requested changes
> Reviewed 1 of 35 files at r8.
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/amcl/2)* status: 19 of 53 files reviewed, 212 unresolved discussions (waiting on @12tbuchman and @c-andy-martin)

___
*[cfg/AMCL.cfg, line 156 at r1](https://reviewable.io/reviews/badgertechnologies/amcl/2#-Lz910OL9OtF2ULTISdW:-M2dUuuTB6ZBKxBFcJq-:bf8sesz) ([raw file](https://github.com/badgertechnologies/amcl/blob/ba6da8b7912ca1f1c7e7b5dc81bd48de469c440f/cfg/AMCL.cfg#L156)):*
<details><summary><i>Previously, 12tbuchman (Tyler Buchman) wrote…</i></summary><blockquote>

I actually took this feature out as we dont use it. Should I add it back in for consistency or is it okay to leave it out?
</blockquote></details>

I'm confused, because the feature seems to be there, and I thought we did use the save pose to file, so Control doesn't have to worry with the pose at all.


<!-- Sent from Reviewable.io -->

2020-03-17 17:18 UTC, c-andy-martin requested changes
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/amcl/2)* status: 19 of 53 files reviewed, 212 unresolved discussions (waiting on @12tbuchman and @c-andy-martin)

___
*[include/amcl/map/map.h, line 28 at r8](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M2dV5K12piaxQXSnT-i:-M2dV5K12piaxQXSnT-j:b-slvmhm) ([raw file](https://github.com/badgertechnologies/amcl/blob/7cb58c9d2aa3041f7f54502c6088113283cd12f6/include/amcl/map/map.h#L28)):*
> ```objc
> #define AMCL_MAP_MAP_H
> 
> #include <pcl/point_types.h>
> ```

This include should come after the standard includes below.


<!-- Sent from Reviewable.io -->

2020-03-17 17:28 UTC, 12tbuchman reviewed
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/amcl/2)* status: 19 of 53 files reviewed, 212 unresolved discussions (waiting on @12tbuchman and @c-andy-martin)

___
*[include/amcl/map/octomap.h, line 100 at r5](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M1g2-KtE_klpaZbTiOD:-M2dXYN80hcMg2go8CSU:b-896fix) ([raw file](https://github.com/badgertechnologies/amcl/blob/95b6eb20da05f9f418bc7ea0645e69d04bc7dd99/include/amcl/map/octomap.h#L100)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

I'm thinking you know everything when you construct this OctoMap object that you need to construct the CachedDistanceMap and the priority_queue, so I do not think these should be wrapped in a pointer. Just make them part of the class:
```
CachedDistanceMap cdm_;
std::priority_queue<CellData> q_;
```
I'm not sure when you know the resolution for the map, as you can't contruct the octomap::OcTree without the resolution, so if you don't know resolution at construction time it makes sense to use a unique_ptr.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-03-17 20:48 UTC, c-andy-martin commented
___
*[include/amcl/map/occupancy_map.h, line 33 at r2](https://reviewable.io/reviews/badgertechnologies/amcl/2#-LzDg0kP8nS6GFpgpHpM:-M2eFGOQ2XvOR8vdjfXD:bkrp7sa) ([raw file](https://github.com/badgertechnologies/amcl/blob/bbbafd470c81f3bf418c310bd0334bc4469d4b08/include/amcl/map/occupancy_map.h#L33)):*
<details><summary><i>Previously, 12tbuchman (Tyler Buchman) wrote…</i></summary><blockquote>

i should remove the cmath include?
</blockquote></details>

at some point, there was an extra newline in here b/c it was math.h. I think that's cleaned up, so this is OK


<!-- Sent from Reviewable.io -->

2020-03-17 20:55 UTC, c-andy-martin commented
___
*[src/amcl/map/occupancy_map.cpp, line 112 at r9](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M2eGWdY4VSfutNgZKAy:-M2eGWdY4VSfutNgZKAz:b-lfle1l) ([raw file](https://github.com/badgertechnologies/amcl/blob/b28c573d53c54b2904a0c476e86e7f24b8cd83ff/src/amcl/map/occupancy_map.cpp#L112)):*
> ```cpp
>     : resolution_(resolution), max_dist_(max_dist)
> {
>   cell_radius_ = (int)floor(max_dist / resolution);
> ```

I prefer using C++ style casts in C++ code:
```
cell_radius_ = static_cast<int>(std::floor(max_dist / resolution));
```
Also, unless someone pulls in math.h or someone does a `using namespace std` you won't have floor in your namespace, you need to make the namespace explicit to prevent future breakage (so floor should be `std::floor` everywhere)


<!-- Sent from Reviewable.io -->

2020-03-17 20:56 UTC, c-andy-martin requested changes
> Reviewed 1 of 10 files at r9.
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/amcl/2)* status: 20 of 53 files reviewed, 204 unresolved discussions (waiting on @12tbuchman and @c-andy-martin)

___
*[src/amcl/map/octomap.cpp, line 161 at r9](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M2eGxGc7XoHYqK5PoZS:-M2eGxGc7XoHYqK5PoZT:b-ort4tt) ([raw file](https://github.com/badgertechnologies/amcl/blob/b28c573d53c54b2904a0c476e86e7f24b8cd83ff/src/amcl/map/octomap.cpp#L161)):*
> ```cpp
>     : resolution_(resolution), max_dist_(max_dist)
> {
>   cell_radius_ = (int)floor(max_dist / resolution);
> ```

I prefer using C++ style casts in C++ code:

```
cell_radius_ = static_cast<int>(std::floor(max_dist / resolution));
```

Also, unless someone pulls in math.h or someone does a using namespace std you won't have floor in your namespace, you need to make the namespace explicit to prevent future breakage (so `floor` should be `std::floor` everywhere)


<!-- Sent from Reviewable.io -->

2020-03-17 20:59 UTC, c-andy-martin commented
___
*[include/amcl/map/occupancy_map.h, line 109 at r9](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M2eHh8H09SCfT9WCY9z:-M2eHh8H09SCfT9WCYA-:bgdd415) ([raw file](https://github.com/badgertechnologies/amcl/blob/b28c573d53c54b2904a0c476e86e7f24b8cd83ff/include/amcl/map/occupancy_map.h#L109)):*
> ```objc
> };
> 
> struct OccupancyMapCellData
> ```

I'm curious why you pulled OccupancyMapCellData out of OccupancyMap. If this struct is only used internally to OccupancyMap, I like it better inside the OccupancyMap object under `protected`.


<!-- Sent from Reviewable.io -->

2020-03-17 21:09 UTC, c-andy-martin requested changes
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/amcl/2)* status: 20 of 53 files reviewed, 204 unresolved discussions (waiting on @12tbuchman and @c-andy-martin)

___
*[include/amcl/map/occupancy_map.h, line 89 at r9](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M2eHvjz6ZgkGC5ysSX2:-M2eHvjz6ZgkGC5ysSX3:b-ekw24i) ([raw file](https://github.com/badgertechnologies/amcl/blob/b28c573d53c54b2904a0c476e86e7f24b8cd83ff/include/amcl/map/occupancy_map.h#L89)):*
> ```objc
> 
> protected:
>   void setMapOccDist(int i, int j, float d);
> ```

These should either be `virtual` or under `private`. My logic is this: either this method is internal to OccupancyMap and should never be used by child classes (therefore should be `private`) or, there is some reason why a child class might want to override the behavior of these methods, in which case they should also be marked as `virtual`. If you decide to make them `private`, please leave the internal variables `protected` unless you are sure they are only ever used by the `private` methods and there is no reason why a child class would ever want to override. My vote would be to just add `virtual` to all of them except for setMapOccDist (because of performance concerns). (In fact, you might want setMapOccDist to be inline and private)


<!-- Sent from Reviewable.io -->

2020-03-17 21:12 UTC, c-andy-martin commented
___
*[include/amcl/map/octomap.h, line 79 at r9](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M2eKjgR1p59bvz9o3NE:-M2eKjgR1p59bvz9o3NF:b-6hw9lj) ([raw file](https://github.com/badgertechnologies/amcl/blob/b28c573d53c54b2904a0c476e86e7f24b8cd83ff/include/amcl/map/octomap.h#L79)):*
> ```objc
>   static constexpr double EPSILON = std::numeric_limits<double>::epsilon();
> 
>   void iterateObstacleCells();
> ```

Same comment here as I made in occupancy_map.h


<!-- Sent from Reviewable.io -->

2020-03-17 21:14 UTC, c-andy-martin commented
___
*[include/amcl/map/octomap.h, line 67 at r3](https://reviewable.io/reviews/badgertechnologies/amcl/2#-LzIFaJu7n8X4sxlRSR-:-M2eL6wBC-ETGB5YPaC2:b1encd6) ([raw file](https://github.com/badgertechnologies/amcl/blob/770d4c63beb80b8977948e006adb7bdbc3c1d735/include/amcl/map/octomap.h#L67)):*
<details><summary><i>Previously, 12tbuchman (Tyler Buchman) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I don't see the default constructor deleted. If you don't explicitly delete it, the compiler will make one for you. So, down below, in OctoMapCellData, do:
```
OctoMapCellData() = delete;
```


<!-- Sent from Reviewable.io -->

2020-03-17 21:15 UTC, c-andy-martin reviewed
> Reviewed 2 of 10 files at r9.
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/amcl/2)* status: 22 of 53 files reviewed, 201 unresolved discussions (waiting on @12tbuchman and @c-andy-martin)



<!-- Sent from Reviewable.io -->

2020-03-18 14:33 UTC, 12tbuchman reviewed
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/amcl/2)* status: 22 of 53 files reviewed, 201 unresolved discussions (waiting on @12tbuchman and @c-andy-martin)

___
*[include/amcl/node/node.h, line 19 at r5](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M1g2cq1054DmY0cNUvm:-M2dilRHAWU9zZe7Wxde:b-896fix) ([raw file](https://github.com/badgertechnologies/amcl/blob/95b6eb20da05f9f418bc7ea0645e69d04bc7dd99/include/amcl/node/node.h#L19)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

As per my other comments, I think it would be best to just list your name in package.xml and leave it out of all the source files. Also, I don't think we need a description here. If you want to detail what Node does, do it in a doxygen comment block above the object declaration itself.
</blockquote></details>

Done.
___
*[include/amcl/node/node.h, line 66 at r5](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M1aivoN6rNgD_77-8jo:-M2dixxR7pQgn0lKXu18:b-896fix) ([raw file](https://github.com/badgertechnologies/amcl/blob/95b6eb20da05f9f418bc7ea0645e69d04bc7dd99/include/amcl/node/node.h#L66)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

This comment seems unnecessary. I would remove it.
</blockquote></details>

Done.
___
*[include/amcl/node/node.h, line 86 at r5](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M1g3Z_w1CeJGoIdjGJc:-M2i2oXz3vGt--Td9-gN:b4zrsic) ([raw file](https://github.com/badgertechnologies/amcl/blob/95b6eb20da05f9f418bc7ea0645e69d04bc7dd99/include/amcl/node/node.h#L86)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

I'm not a huge fan of the 'Pf' abbreviation. I would prefer using ParticleFilter everywhere if that's what Pf means.
Or, if PF is superfluous based on context, just ditch it (like PFVector, why not just make an amcl::Vector? I doubt the vector has much to do with the particle filter itself).
</blockquote></details>

the additional information from PFVector is that the vector is of size 3, so its a Vector3 really. We could name it amcl::Vector3,but I think amcl::Vector is confusing given that I use std::vector a lot.


<!-- Sent from Reviewable.io -->

2020-03-18 14:35 UTC, c-andy-martin reviewed
> Reviewed 1 of 35 files at r8.
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/amcl/2)* status: 23 of 53 files reviewed, 200 unresolved discussions (waiting on @12tbuchman and @c-andy-martin)



<!-- Sent from Reviewable.io -->

2020-03-18 14:36 UTC, c-andy-martin commented
___
*[include/amcl/node/node.h, line 86 at r5](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M1g3Z_w1CeJGoIdjGJc:-M2i3ijD3jLeyDe20uww:b9puhqz) ([raw file](https://github.com/badgertechnologies/amcl/blob/95b6eb20da05f9f418bc7ea0645e69d04bc7dd99/include/amcl/node/node.h#L86)):*
<details><summary><i>Previously, 12tbuchman (Tyler Buchman) wrote…</i></summary><blockquote>

the additional information from PFVector is that the vector is of size 3, so its a Vector3 really. We could name it amcl::Vector3,but I think amcl::Vector is confusing given that I use std::vector a lot.
</blockquote></details>

Let's name it amcl::Vector3 then (or take a todo to do that)


<!-- Sent from Reviewable.io -->

2020-03-18 14:37 UTC, 12tbuchman reviewed
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/amcl/2)* status: 23 of 53 files reviewed, 199 unresolved discussions (waiting on @12tbuchman and @c-andy-martin)

___
*[include/amcl/node/node.h, line 86 at r5](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M1g3Z_w1CeJGoIdjGJc:-M2i3rB23YoEv0qY9KoJ:b-o8opi4) ([raw file](https://github.com/badgertechnologies/amcl/blob/95b6eb20da05f9f418bc7ea0645e69d04bc7dd99/include/amcl/node/node.h#L86)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

Let's name it amcl::Vector3 then (or take a todo to do that)
</blockquote></details>

Ill make it a Todo


<!-- Sent from Reviewable.io -->

2020-03-18 14:37 UTC, c-andy-martin reviewed
> Reviewed 2 of 35 files at r8.
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/amcl/2)* status: 25 of 53 files reviewed, 198 unresolved discussions (waiting on @12tbuchman and @c-andy-martin)



<!-- Sent from Reviewable.io -->

2020-03-18 14:38 UTC, c-andy-martin reviewed
> Reviewed 1 of 35 files at r8.
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/amcl/2)* status: 26 of 53 files reviewed, 197 unresolved discussions (waiting on @12tbuchman and @c-andy-martin)



<!-- Sent from Reviewable.io -->

2020-03-18 14:39 UTC, c-andy-martin reviewed
> Reviewed 10 of 35 files at r8.
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/amcl/2)* status: 36 of 53 files reviewed, 196 unresolved discussions (waiting on @12tbuchman and @c-andy-martin)



<!-- Sent from Reviewable.io -->

2020-03-18 14:40 UTC, 12tbuchman reviewed
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/amcl/2)* status: 36 of 53 files reviewed, 196 unresolved discussions (waiting on @12tbuchman and @c-andy-martin)

___
*[include/amcl/node/node.h, line 86 at r5](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M1g3Z_w1CeJGoIdjGJc:-M2i4Y9rEGEqGj976Oax:bvv8zm2) ([raw file](https://github.com/badgertechnologies/amcl/blob/95b6eb20da05f9f418bc7ea0645e69d04bc7dd99/include/amcl/node/node.h#L86)):*
<details><summary><i>Previously, 12tbuchman (Tyler Buchman) wrote…</i></summary><blockquote>

Ill make it a Todo
</blockquote></details>

Ive improved the publishPfCloud name to publishParticleCloud


<!-- Sent from Reviewable.io -->

2020-03-18 14:40 UTC, c-andy-martin reviewed
> Reviewed 2 of 10 files at r9.
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/amcl/2)* status: 38 of 53 files reviewed, 196 unresolved discussions (waiting on @12tbuchman and @c-andy-martin)



<!-- Sent from Reviewable.io -->

2020-03-18 14:42 UTC, c-andy-martin commented
___
*[src/amcl/map/octomap.cpp, line 32 at r9](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M2i5-Vr-mOPAvqwVlp4:-M2i5-Vs9wKMVO5LpFkH:b-aojgbw) ([raw file](https://github.com/badgertechnologies/amcl/blob/b28c573d53c54b2904a0c476e86e7f24b8cd83ff/src/amcl/map/octomap.cpp#L32)):*
> ```cpp
> using namespace amcl;
> 
> OctoMap::OctoMap(double resolution, bool wait_for_occupancy_map) :
> ```

I think the spacing for the `:` is to have it on the next line, see:
https://google.github.io/styleguide/cppguide.html#Constructor_Initializer_Lists


<!-- Sent from Reviewable.io -->

2020-03-18 14:42 UTC, c-andy-martin requested changes
> Reviewed 1 of 35 files at r8, 1 of 10 files at r9.
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/amcl/2)* status: 40 of 53 files reviewed, 198 unresolved discussions (waiting on @12tbuchman and @c-andy-martin)

___
*[src/amcl/map/octomap.cpp, line 28 at r9](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M2i4uIc5NxBrnw6Cmep:-M2i4uIc5NxBrnw6Cmeq:bl4degu) ([raw file](https://github.com/badgertechnologies/amcl/blob/b28c573d53c54b2904a0c476e86e7f24b8cd83ff/src/amcl/map/octomap.cpp#L28)):*
> ```cpp
> 
> #include <algorithm>
> #include <cmath>
> ```

These includes are in the wrong order. Standard goes before ros


<!-- Sent from Reviewable.io -->

2020-03-18 14:44 UTC, c-andy-martin reviewed
> Reviewed 1 of 10 files at r9.
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/amcl/2)* status: 41 of 53 files reviewed, 196 unresolved discussions (waiting on @12tbuchman and @c-andy-martin)



<!-- Sent from Reviewable.io -->

2020-03-18 14:44 UTC, c-andy-martin commented
___
*[src/amcl/map/octomap_cspace.cpp, line 67 at r7](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M26QVfkBKRvOTjx2y-x:-M2i5ck1AFLh6O1RxFU7:bn9uzhv) ([raw file](https://github.com/badgertechnologies/amcl/blob/74db8df1672f2baaecdf854cea1efd100f551c8b/src/amcl/map/octomap_cspace.cpp#L67)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

I would make these non-member variables (put them on the stack) then just let them go out of scope, so you could remove these lines
</blockquote></details>

these are no longer pointers, so this part is OK


<!-- Sent from Reviewable.io -->

2020-03-18 14:45 UTC, c-andy-martin requested changes
> Reviewed 1 of 10 files at r9.
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/amcl/2)* status: 42 of 53 files reviewed, 195 unresolved discussions (waiting on @12tbuchman and @c-andy-martin)

___
*[src/amcl/map/octomap_cspace.cpp, line 55 at r7](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M26QPqS1JsffgNVqKX3:-M2i5hEF4vOa68JVbEi4:by06b3b) ([raw file](https://github.com/badgertechnologies/amcl/blob/74db8df1672f2baaecdf854cea1efd100f551c8b/src/amcl/map/octomap_cspace.cpp#L55)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

I would make `q_` and `masked_` non-member variables, then just let them go out-of-scope below
</blockquote></details>

These are no longer pointers, but I still think you don't need them to be part of the class, just put them on the stack here.


<!-- Sent from Reviewable.io -->

2020-03-18 14:46 UTC, c-andy-martin reviewed
> Reviewed 2 of 35 files at r8, 2 of 10 files at r9.
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/amcl/2)* status: 46 of 53 files reviewed, 195 unresolved discussions (waiting on @12tbuchman and @c-andy-martin)



<!-- Sent from Reviewable.io -->

2020-03-18 14:47 UTC, c-andy-martin reviewed
> Reviewed 7 of 35 files at r8.
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/amcl/2)* status: all files reviewed, 193 unresolved discussions (waiting on @12tbuchman and @c-andy-martin)



<!-- Sent from Reviewable.io -->

2020-03-18 17:53 UTC, 12tbuchman reviewed
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/amcl/2)* status: all files reviewed, 193 unresolved discussions (waiting on @12tbuchman and @c-andy-martin)

___
*[include/amcl/node/node.h, line 106 at r3](https://reviewable.io/reviews/badgertechnologies/amcl/2#-LzIJylU1tigU08JSpqr:-M2il_1wANBVnXbmUUYK:b-896fix) ([raw file](https://github.com/badgertechnologies/amcl/blob/770d4c63beb80b8977948e006adb7bdbc3c1d735/include/amcl/node/node.h#L106)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

so, until C++17 you still have to define this in the CPP file b/c its part of the object. That will work, but thinking about what these indeces are, these constants are generally useful to AMCL, as it is a quick way to access the right part of a covariance. So, I suggest instead renaming these COVARIANCE_{XX,YY,AA} and putting them in the amcl namespace directly, not in the Node class. Then there will be no issue with needing a definition on top of a declaration (as you don't need that outside a class in this case). So, delete these three lines, and above, right after opening the namespace:
```
namespace amcl
{

// Convenience constants for covariance indeces.
constexpr int COVARIANCE_XX = 6 * 0 + 0;
constexpr int COVARIANCE_YY = 6 * 1 + 1;
constexpr int COVARIANCE_AA = 6 * 5 + 5;
```
</blockquote></details>

Done.
___
*[include/amcl/node/node.h, line 88 at r5](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M1g3TXP3xYPDJkN6Ei0:-M2i5B5T5NGeFz8FgiNi:b-896fix) ([raw file](https://github.com/badgertechnologies/amcl/blob/95b6eb20da05f9f418bc7ea0645e69d04bc7dd99/include/amcl/node/node.h#L88)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

I'm not a huge fan of abbreviations in names. They can cause confusion. I'd prefer 'updateTransforms'
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-03-20 15:01 UTC, 12tbuchman reviewed
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/amcl/2)* status: 43 of 53 files reviewed, 193 unresolved discussions (waiting on @12tbuchman and @c-andy-martin)

___
*[include/amcl/node/node.h, line 111 at r5](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M1g46DUAIg4Gh7cadeu:-M2ipHEu9065W4jYywdc:b-896fix) ([raw file](https://github.com/badgertechnologies/amcl/blob/95b6eb20da05f9f418bc7ea0645e69d04bc7dd99/include/amcl/node/node.h#L111)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

There is no need for the `amcl::` here, you are in the amcl namespace.
</blockquote></details>

Done.
___
*[include/amcl/node/node.h, line 146 at r5](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M1g4a1vE189jK2VHRrl:-M2sS_PY7yisWu9IN9k9:b-896fix) ([raw file](https://github.com/badgertechnologies/amcl/blob/95b6eb20da05f9f418bc7ea0645e69d04bc7dd99/include/amcl/node/node.h#L146)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

let's ditch these for the `angles` package, using the `angles::normalize_angle` and `angles::shortest_angular_distance` functions. you'll need to add `angles` as a depend in package.xml and in cmake as well.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-03-20 18:34 UTC, 12tbuchman reviewed
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/amcl/2)* status: 43 of 53 files reviewed, 193 unresolved discussions (waiting on @12tbuchman and @c-andy-martin)

___
*[include/amcl/node/node.h, line 152 at r5](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M1g5RC9EmW0G1rkP3wp:-M2sbtnh7iTDo9-L_y7P:b-896fix) ([raw file](https://github.com/badgertechnologies/amcl/blob/95b6eb20da05f9f418bc7ea0645e69d04bc7dd99/include/amcl/node/node.h#L152)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

To save making a temporary copy of the shared_ptr for every call, I usually pass here by reference. And since you won't be changing the actual shared ptr, by const reference:
```
void setScannerUpdateFlags(const PFVector& delta, const std::shared<ptr<std::vector<bool>>& scanners_update, ...
```
</blockquote></details>

Done.
___
*[include/amcl/node/node.h, line 155 at r5](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M1g5nROAdJt6Lczed6j:-M2sdtSPEos28H6v4N-0:b-896fix) ([raw file](https://github.com/badgertechnologies/amcl/blob/95b6eb20da05f9f418bc7ea0645e69d04bc7dd99/include/amcl/node/node.h#L155)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

same comment here about scanners_update as above
</blockquote></details>

Done.
___
*[include/amcl/node/node.h, line 158 at r5](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M1g5vTD5sM2kRo-qBfK:-M2sokLS67fRebhyEN8t:b-896fix) ([raw file](https://github.com/badgertechnologies/amcl/blob/95b6eb20da05f9f418bc7ea0645e69d04bc7dd99/include/amcl/node/node.h#L158)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

std::function is itself a pointer, and points to static data (it point to compiled code which doesn't change). there is no need to wrap it in a shared_ptr. I would remove wrapping any occurence of std::function w/ a shared_ptr (this will affect several files, as its in the ParticleFilter object as well).
</blockquote></details>

Done.
___
*[include/amcl/node/node.h, line 172 at r5](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M1gcVA01DBjsywxG8XY:-M2tDMU53-ZCV7lTlE9N:bsp5gqx) ([raw file](https://github.com/badgertechnologies/amcl/blob/95b6eb20da05f9f418bc7ea0645e69d04bc7dd99/include/amcl/node/node.h#L172)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

Per my comment in AMCL.cfg, make the dynamic configure an enumeration. That will generate constants like 'AMCL_Map2D' and 'AMCL_Map3D' (if you call the enumeration opetions 'Map2D' and 'Map3D' that encode to the integer values 2 and 3, IIRC).
</blockquote></details>

the type of 'map_type_' will stay an int, correct?


<!-- Sent from Reviewable.io -->

2020-03-20 18:37 UTC, 12tbuchman reviewed
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/amcl/2)* status: 43 of 53 files reviewed, 193 unresolved discussions (waiting on @12tbuchman and @c-andy-martin)

___
*[include/amcl/node/node.h, line 179 at r5](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M1gczKc9hzF5Lzkzsw9:-M2tE00t4FF8Jw9UnGIz:bgsasp7) ([raw file](https://github.com/badgertechnologies/amcl/blob/95b6eb20da05f9f418bc7ea0645e69d04bc7dd99/include/amcl/node/node.h#L179)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

Since we are rewriting, we should go away from using tf in favor of tf2. I know this may be a lot of re-writing to get the interfaces right, so I'm OK taking a to-do in a ticket for this and getting to it in a month or two.
</blockquote></details>

Made a todo


<!-- Sent from Reviewable.io -->

2020-03-22 00:20 UTC, 12tbuchman reviewed
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/amcl/2)* status: 43 of 53 files reviewed, 193 unresolved discussions (waiting on @12tbuchman and @c-andy-martin)

___
*[include/amcl/node/node.h, line 233 at r5](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M1gdV-d1NXMDf2hQ-o6:-M2zY6C453dJFYXBJcf_:b-896fix) ([raw file](https://github.com/badgertechnologies/amcl/blob/95b6eb20da05f9f418bc7ea0645e69d04bc7dd99/include/amcl/node/node.h#L233)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

you should know everything you need to know at construction time of this object (mainly the node handle) to make this a part of this class and not need to store it in a pointer
</blockquote></details>

Done.
___
*[include/amcl/node/node.h, line 234 at r5](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M1gdljQBnh-vvJaXLiU:-M2zY6a2CEuPnLEIINOH:b-896fix) ([raw file](https://github.com/badgertechnologies/amcl/blob/95b6eb20da05f9f418bc7ea0645e69d04bc7dd99/include/amcl/node/node.h#L234)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

you are in the amcl namespace already, no need for `amcl::`
</blockquote></details>

Done.
___
*[include/amcl/node/node.h, line 243 at r5](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M1gds5n-XMFtbbP_a-r:-M2zaTW55zhcRRLW6iyT:b-896fix) ([raw file](https://github.com/badgertechnologies/amcl/blob/95b6eb20da05f9f418bc7ea0645e69d04bc7dd99/include/amcl/node/node.h#L243)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

does this need to be in a shared pointer? My guess is you can just include a straight-up vector. If you need to pass it, just pass it by reference.
</blockquote></details>

Done.
___
*[include/amcl/node/node.h, line 245 at r5](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M1ge43p3qgXfhwmh8GC:-M2zbCM2A9yvH1N6l8bb:b-896fix) ([raw file](https://github.com/badgertechnologies/amcl/blob/95b6eb20da05f9f418bc7ea0645e69d04bc7dd99/include/amcl/node/node.h#L245)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

My guess is clang-format put these two lines together, but I like having a newline between for beauty
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-03-22 00:22 UTC, 12tbuchman reviewed
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/amcl/2)* status: 43 of 53 files reviewed, 193 unresolved discussions (waiting on @12tbuchman and @c-andy-martin)

___
*[include/amcl/node/node_2d.h, line 36 at r5](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M1kINGhBUDE83-XkJcK:-M2zbeoVEW7nNGuDXang:bc48xdn) ([raw file](https://github.com/badgertechnologies/amcl/blob/95b6eb20da05f9f418bc7ea0645e69d04bc7dd99/include/amcl/node/node_2d.h#L36)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

std C++ includes should come first, then third party libraries. please correct this everywhere.
</blockquote></details>

Order is C style headers and then C++ style headers
https://google.github.io/styleguide/cppguide.html#Names_and_Order_of_Includes


<!-- Sent from Reviewable.io -->

2020-03-22 00:53 UTC, 12tbuchman reviewed
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/amcl/2)* status: 31 of 53 files reviewed, 193 unresolved discussions (waiting on @12tbuchman and @c-andy-martin)

___
*[include/amcl/node/node_2d.h, line 55 at r5](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M1gi0_q05UwSYhdyicT:-M2zgUpc5S9PslolmMu6:b-896fix) ([raw file](https://github.com/badgertechnologies/amcl/blob/95b6eb20da05f9f418bc7ea0645e69d04bc7dd99/include/amcl/node/node_2d.h#L55)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

It is odd to take a reference to another objects mutex. This is not going to break, but does mean that this object has a back-reference to another object. I don't mind you doing it this way, but we need a comment explaining why its OK. Something like: "configuration_mutex is a reference to the node's configuration mutex necessary to synchronize points between node and this node implementation and dynamic reconfigure of the node and node implementation. This is for convenience, the Node object itself could provide APIs for this, but because the purpose of this node implementation is to provide implementation specific to a particular kind of map/sensor combination, it is OK to couple the two objects".
</blockquote></details>

Done.
___
*[include/amcl/node/node_2d.h, line 88 at r5](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M1gizFDA7amIW3PmVKO:-M2zbyDD8P5H-mvXtx6p:b-896fix) ([raw file](https://github.com/badgertechnologies/amcl/blob/95b6eb20da05f9f418bc7ea0645e69d04bc7dd99/include/amcl/node/node_2d.h#L88)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

Please have only one newline here
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-03-22 01:15 UTC, 12tbuchman reviewed
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/amcl/2)* status: 31 of 53 files reviewed, 193 unresolved discussions (waiting on @12tbuchman and @c-andy-martin)

___
*[include/amcl/node/node_2d.h, line 91 at r5](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M1gj5C3E4AwQEaf8Qa9:-M2znafW-a6mp0bb59Wu:bman8ke) ([raw file](https://github.com/badgertechnologies/amcl/blob/95b6eb20da05f9f418bc7ea0645e69d04bc7dd99/include/amcl/node/node_2d.h#L91)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

I don't think this needs to be wrapped in a pointer, just have a member for the scan_sub_ and scan_filter_. Also, if you add the base class like I was saying, you can just not instantiate this class at all in the 3D case.
</blockquote></details>

Node2D is not being instantiated in the 3D case


<!-- Sent from Reviewable.io -->

2020-03-22 01:26 UTC, 12tbuchman reviewed
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/amcl/2)* status: 31 of 53 files reviewed, 193 unresolved discussions (waiting on @12tbuchman and @c-andy-martin)

___
*[include/amcl/node/node_2d.h, line 91 at r5](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M1gj5C3E4AwQEaf8Qa9:-M2zpBaX8f61_HEINArP:b4pd163) ([raw file](https://github.com/badgertechnologies/amcl/blob/95b6eb20da05f9f418bc7ea0645e69d04bc7dd99/include/amcl/node/node_2d.h#L91)):*
<details><summary><i>Previously, 12tbuchman (Tyler Buchman) wrote…</i></summary><blockquote>

Node2D is not being instantiated in the 3D case
</blockquote></details>

There may be an easy way to do this that I am not familiar with, but when I make these class objects instead of smart pointers, I need to give a base class construction, which requires the scan topic that I get from the parameter server within the constructor.


<!-- Sent from Reviewable.io -->

2020-03-23 14:09 UTC, 12tbuchman reviewed
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/amcl/2)* status: 31 of 53 files reviewed, 193 unresolved discussions (waiting on @12tbuchman and @c-andy-martin)

___
*[include/amcl/node/node_2d.h, line 101 at r5](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M1gj_G4D-O5bMLRBc_n:-M36iSN73HtlmX2RuKCV:b-896fix) ([raw file](https://github.com/badgertechnologies/amcl/blob/95b6eb20da05f9f418bc7ea0645e69d04bc7dd99/include/amcl/node/node_2d.h#L101)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

can this just be a plain vector, or does it need to be a pointer?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-03-23 14:11 UTC, 12tbuchman reviewed
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/amcl/2)* status: 31 of 53 files reviewed, 193 unresolved discussions (waiting on @12tbuchman and @c-andy-martin)

___
*[include/amcl/node/node_3d.h, line 37 at r5](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M1kIAxc-cKiw9hkpSTP:-M36igkz8ArNgZo7nbaO:bnewsm3) ([raw file](https://github.com/badgertechnologies/amcl/blob/95b6eb20da05f9f418bc7ea0645e69d04bc7dd99/include/amcl/node/node_3d.h#L37)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

std c++ includes should come first, then libraries like ROS and octomap, and finally local includes
</blockquote></details>

https://google.github.io/styleguide/cppguide.html#Names_and_Order_of_Includes
According to the C++ Style Guide, the order is C system headers ending in .h/.hpp, then C++ standard library headers.


<!-- Sent from Reviewable.io -->

2020-03-23 15:43 UTC, 12tbuchman reviewed
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/amcl/2)* status: 31 of 53 files reviewed, 193 unresolved discussions (waiting on @12tbuchman and @c-andy-martin)

___
*[include/amcl/node/node_3d.h, line 52 at r5](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M1kJibc1KJknB8Bp7za:-M36md9I1qZBgPrvNLd-:b-896fix) ([raw file](https://github.com/badgertechnologies/amcl/blob/95b6eb20da05f9f418bc7ea0645e69d04bc7dd99/include/amcl/node/node_3d.h#L52)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

This line is unnecessary, please remove it.
</blockquote></details>

Done.
___
*[include/amcl/node/node_3d.h, line 103 at r5](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M1kKIww8tBu0jk4xh4P:-M37306C196L8KHH_ggT:b-896fix) ([raw file](https://github.com/badgertechnologies/amcl/blob/95b6eb20da05f9f418bc7ea0645e69d04bc7dd99/include/amcl/node/node_3d.h#L103)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

these could probably just be accessed from the node instead of stored twice.
</blockquote></details>

Done.
___
*[include/amcl/node/node_3d.h, line 122 at r5](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M1kKcSj8NR86aThEKTK:-M36sUGK1BnfAGuVN_25:b-896fix) ([raw file](https://github.com/badgertechnologies/amcl/blob/95b6eb20da05f9f418bc7ea0645e69d04bc7dd99/include/amcl/node/node_3d.h#L122)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

seems like you know the map_type_ is going to be 3 here no matter what? do you need to store it here?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-03-23 19:50 UTC, 12tbuchman reviewed
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/amcl/2)* status: 31 of 53 files reviewed, 193 unresolved discussions (waiting on @12tbuchman and @c-andy-martin)

___
*[include/amcl/node/node_3d.h, line 93 at r5](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M1kK-FF-kFPK8QYkRT2:-M37wJ5Z-So1Ye_L4pde:b-55jn4w) ([raw file](https://github.com/badgertechnologies/amcl/blob/95b6eb20da05f9f418bc7ea0645e69d04bc7dd99/include/amcl/node/node_3d.h#L93)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

Please check each of these shared_ptr and unique_ptr to see if they can just be included in the class directly. I'm sure some of these are constructed on the fly, or generated by other classes, in which case they are fine. But esp. the unique_ptr, see if you can just construct them with the class to eliminate extra dynamic memory use.
</blockquote></details>

The unique pointers cannot be made class variables because I dont have everything I need to call the base class constructor on startup. I will do some refactoring to remove some unnecessary shared pointers that can be passed by reference instead.


<!-- Sent from Reviewable.io -->

2020-03-24 15:02 UTC, 12tbuchman reviewed
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/amcl/2)* status: 31 of 53 files reviewed, 193 unresolved discussions (waiting on @12tbuchman and @c-andy-martin)

___
*[include/amcl/node/node_3d.h, line 93 at r5](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M1kK-FF-kFPK8QYkRT2:-M3C38VD-InTcARarDYh:b-896fix) ([raw file](https://github.com/badgertechnologies/amcl/blob/95b6eb20da05f9f418bc7ea0645e69d04bc7dd99/include/amcl/node/node_3d.h#L93)):*
<details><summary><i>Previously, 12tbuchman (Tyler Buchman) wrote…</i></summary><blockquote>

The unique pointers cannot be made class variables because I dont have everything I need to call the base class constructor on startup. I will do some refactoring to remove some unnecessary shared pointers that can be passed by reference instead.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-03-24 15:06 UTC, 12tbuchman reviewed
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/amcl/2)* status: 31 of 53 files reviewed, 193 unresolved discussions (waiting on @12tbuchman and @c-andy-martin)

___
*[include/amcl/node/node_nd.h, line 20 at r6](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M23mZ0V8hVgDQUa6reS:-M3C3BEm5egwMBCXslS7:b-896fix) ([raw file](https://github.com/badgertechnologies/amcl/blob/9df029774580bad51987f61b64a87071070f819b/include/amcl/node/node_nd.h#L20)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

This comment is incorrect. As I asked elsewhere, let's remove all these block comments and maintain authorship information in the git history and in the package.xml.
</blockquote></details>

Done.
___
*[include/amcl/node/node_nd.h, line 36 at r6](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M23mMptCGcBUZxQ3caM:-M3C3TA_7--VxITwU0wI:b-896fix) ([raw file](https://github.com/badgertechnologies/amcl/blob/9df029774580bad51987f61b64a87071070f819b/include/amcl/node/node_nd.h#L36)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

you must add a virtual destructor to this abstract base class. It can either be `= default` or just empty ` {}`
</blockquote></details>

Done.
___
*[include/amcl/node/node_nd.h, line 40 at r6](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M23mA_FEl9wBMs9Xq5d:-M3C3VUr6FsMuUgpW0Ov:b-896fix) ([raw file](https://github.com/badgertechnologies/amcl/blob/9df029774580bad51987f61b64a87071070f819b/include/amcl/node/node_nd.h#L40)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

If clang-format is forcing these lines to be next to each other, I'm find with you adding back the newline. I think a newline between these braces looks better. Up to you.
</blockquote></details>

Done.
___
*[include/amcl/node/node_nd.h, line 42 at r6](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M23mH6n63ElrN9jTdMf:-M3C43CXBwg0_FJj52S9:b-896fix) ([raw file](https://github.com/badgertechnologies/amcl/blob/9df029774580bad51987f61b64a87071070f819b/include/amcl/node/node_nd.h#L42)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

there are supposed to be two spaces before inline comments according to the google c++ style guide
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-03-24 15:08 UTC, 12tbuchman reviewed
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/amcl/2)* status: 31 of 53 files reviewed, 193 unresolved discussions (waiting on @12tbuchman and @c-andy-martin)

___
*[include/amcl/pf/eig3.h, line 22 at r5](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M1kKrMO-YYY9EGFNJhW:-M3C4cJYDLEGrUWMhOIC:bjcelyo) ([raw file](https://github.com/badgertechnologies/amcl/blob/95b6eb20da05f9f418bc7ea0645e69d04bc7dd99/include/amcl/pf/eig3.h#L22)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

Please take a to-do Jira ticket to have AMCL simply use the Eigen library for all vector, matrix, quaternion, eigen decomposition, etc. TF already uses Eigen for this so its not really a new dependency. Eigen is highly optomized and there is no reason to have yet-another-vector-implementation. However, I know we inherited this from the legacy AMCL code and don't think we have to do this before the first iteration. But I want to do it sometime as part of the overall cleanup work.
</blockquote></details>

Added to Jira ticket.


<!-- Sent from Reviewable.io -->

2020-03-24 15:39 UTC, 12tbuchman reviewed
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/amcl/2)* status: 31 of 53 files reviewed, 193 unresolved discussions (waiting on @12tbuchman and @c-andy-martin)

___
*[include/amcl/pf/eig3.h, line 25 at r5](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M1kfD_2CvEfz5DDtAf9:-M3CAPsBD0GJEw_wC3rX:b-896fix) ([raw file](https://github.com/badgertechnologies/amcl/blob/95b6eb20da05f9f418bc7ea0645e69d04bc7dd99/include/amcl/pf/eig3.h#L25)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

make this a `constexpr` instead of `const`
</blockquote></details>

Done.
___
*[include/amcl/pf/eig3.h, line 27 at r5](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M1kflFt9jKNjt2hGWta:-M3CAnab01dFMFNTd8Ic:b-1k68h5) ([raw file](https://github.com/badgertechnologies/amcl/blob/95b6eb20da05f9f418bc7ea0645e69d04bc7dd99/include/amcl/pf/eig3.h#L27)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

Since `V` is written to, it should be passed as a pointer to follow the style guide. If this is a pain due to all the lines of code it impacts, rename the argument to `V_ptr` then in the .cpp function add a `PFMatrix& V(*V_ptr);` at the top to keep from having to touch many lines of code. This same advice applies to `tql2` below.
</blockquote></details>

V is passed into the eigenDecomposition function as a pointer because it is not intended to be filled already. It is only receiving data from that point, not contributing data. However by tred2 and tql2 it is expected to be contributing as well as being updated. Therefore I think it would be incorrect to pass it as a pointer, which would not guarantee that it has any information because it could be passed as nullptr. I will improve the eigenDecomposition function to handle V coming in as a nullptr though because that case should be handled.


<!-- Sent from Reviewable.io -->

2020-03-24 16:49 UTC, 12tbuchman reviewed
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/amcl/2)* status: 31 of 53 files reviewed, 193 unresolved discussions (waiting on @12tbuchman and @c-andy-martin)

___
*[include/amcl/pf/eig3.h, line 27 at r5](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M1kflFt9jKNjt2hGWta:-M3CRbcR5e1AZaXcf1uC:b-896fix) ([raw file](https://github.com/badgertechnologies/amcl/blob/95b6eb20da05f9f418bc7ea0645e69d04bc7dd99/include/amcl/pf/eig3.h#L27)):*
<details><summary><i>Previously, 12tbuchman (Tyler Buchman) wrote…</i></summary><blockquote>

V is passed into the eigenDecomposition function as a pointer because it is not intended to be filled already. It is only receiving data from that point, not contributing data. However by tred2 and tql2 it is expected to be contributing as well as being updated. Therefore I think it would be incorrect to pass it as a pointer, which would not guarantee that it has any information because it could be passed as nullptr. I will improve the eigenDecomposition function to handle V coming in as a nullptr though because that case should be handled.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-03-24 17:56 UTC, 12tbuchman reviewed
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/amcl/2)* status: 31 of 53 files reviewed, 193 unresolved discussions (waiting on @12tbuchman and @c-andy-martin)

___
*[include/amcl/pf/particle_filter.h, line 37 at r5](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M1kLKrS4a02WTTUFvRj:-M3CRlowAnFX2rJgPQ5T:b-896fix) ([raw file](https://github.com/badgertechnologies/amcl/blob/95b6eb20da05f9f418bc7ea0645e69d04bc7dd99/include/amcl/pf/particle_filter.h#L37)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

This brace should not be cuddled
</blockquote></details>

Done.
___
*[include/amcl/pf/particle_filter.h, line 40 at r5](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M1kLaDGCVHIfEzR86ki:-M3CS4Pe-6ih4-4a5I9B:b-896fix) ([raw file](https://github.com/badgertechnologies/amcl/blob/95b6eb20da05f9f418bc7ea0645e69d04bc7dd99/include/amcl/pf/particle_filter.h#L40)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

Lets take a Jira to-do to make these object oriented. Instead of switch/case on an enumeration, we should have a common base class for resample, and various subclasses which implement the desired behavior.
</blockquote></details>

Done.
___
*[include/amcl/pf/particle_filter.h, line 43 at r5](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M1kLn3s3L-w97wOWw7b:-M3CTe2YBlA7W8kE6h3W:b-896fix) ([raw file](https://github.com/badgertechnologies/amcl/blob/95b6eb20da05f9f418bc7ea0645e69d04bc7dd99/include/amcl/pf/particle_filter.h#L43)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

In c++ there is no reason for this `typedef`. Please search and make all `typedef struct` => `struct`
</blockquote></details>

Done.
___
*[include/amcl/pf/particle_filter.h, line 79 at r5](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M1kM0BGBcebZzB_hJ1N:-M3Cd8B35Ty3_dOuG3J_:bopjj79) ([raw file](https://github.com/badgertechnologies/amcl/blob/95b6eb20da05f9f418bc7ea0645e69d04bc7dd99/include/amcl/pf/particle_filter.h#L79)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

(in other words, can we just include the kdtree directly as `PFKDTree kdtree`?)
</blockquote></details>

To do that we would need to make a constructor for PFSampleSet with a kdtree size to pass to kdtree's base constructor, but that requires knowing the size at the time of creating the PFSampleSet which is not always true. I would prefer to leave this but I am open to more suggestions.


<!-- Sent from Reviewable.io -->

2020-03-24 18:31 UTC, 12tbuchman reviewed
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/amcl/2)* status: 31 of 53 files reviewed, 193 unresolved discussions (waiting on @12tbuchman and @c-andy-martin)

___
*[include/amcl/pf/particle_filter.h, line 99 at r5](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M1kMDwa9mKi8bJOuNB7:-M3Co7NKCxM4orHzWpUI:b-896fix) ([raw file](https://github.com/badgertechnologies/amcl/blob/95b6eb20da05f9f418bc7ea0645e69d04bc7dd99/include/amcl/pf/particle_filter.h#L99)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

as I pointed out elsewhere, there is no need to pass the std::function in a std::pointer, its already a pointer, and doesn't need to be reference counted
</blockquote></details>

Done.
___
*[include/amcl/pf/particle_filter.h, line 112 at r5](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M1kMPBj0w2COsU67oCm:-M3Co8Wc0JVcNkzygMyG:b-896fix) ([raw file](https://github.com/badgertechnologies/amcl/blob/95b6eb20da05f9f418bc7ea0645e69d04bc7dd99/include/amcl/pf/particle_filter.h#L112)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

Please clean up all the places where we wrap std::function in std::shared_ptr, as it is unnecessary
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-03-24 18:44 UTC, 12tbuchman reviewed
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/amcl/2)* status: 31 of 53 files reviewed, 193 unresolved discussions (waiting on @12tbuchman and @c-andy-martin)

___
*[include/amcl/pf/particle_filter.h, line 178 at r5](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M1kMuLd2uuD-WiRy90k:-M3CqSV2EmhhkyBdLCyQ:bvwafwt) ([raw file](https://github.com/badgertechnologies/amcl/blob/95b6eb20da05f9f418bc7ea0645e69d04bc7dd99/include/amcl/pf/particle_filter.h#L178)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

Maybe instead of this old way of double buffering from C, we could use the vector below as a double-ended queue. Then `push_back` new sample sets (maybe you don't even need a pointer to the sample set?) and when `size() > 2` after a `push_back` do a `pop_front`. Then all code can use the `back()` as the most recent set, and `front()` as the oldest set, or `sets_[sets_.size()-2]` as the second newest. This would make it easier to keep 3 or more sets down the road.
</blockquote></details>

The reason for having the 2 sets is so we can create the new set from the old set. We dont ever use the old set outside of creating the new set. What we could do instead is create the sets as smart pointers and then only remember the current set, but I think the current implementation is actually cleaner. I dont know why we would want more than 2 sets. We can discuss this further.


<!-- Sent from Reviewable.io -->

2020-03-24 18:50 UTC, 12tbuchman reviewed
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/amcl/2)* status: 31 of 53 files reviewed, 193 unresolved discussions (waiting on @12tbuchman and @c-andy-martin)

___
*[include/amcl/pf/pdf_gaussian.h, line 37 at r5](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M1kO4JI7njE3akqKM44:-M3CsRPi6ujlkZpKM25P:b-896fix) ([raw file](https://github.com/badgertechnologies/amcl/blob/95b6eb20da05f9f418bc7ea0645e69d04bc7dd99/include/amcl/pf/pdf_gaussian.h#L37)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

PDF is too dense, please explain here what a PDF is.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-03-24 18:51 UTC, 12tbuchman reviewed
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/amcl/2)* status: 31 of 53 files reviewed, 193 unresolved discussions (waiting on @12tbuchman and @c-andy-martin)

___
*[include/amcl/pf/pf_kdtree.h, line 34 at r5](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M1kOndf5KzK4wUvmLGJ:-M3CsjzE3Mnm3xyo-pFu:b-896fix) ([raw file](https://github.com/badgertechnologies/amcl/blob/95b6eb20da05f9f418bc7ea0645e69d04bc7dd99/include/amcl/pf/pf_kdtree.h#L34)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

Let's take a Jira to-do ticket to research replacing this entire implementation w/ PCL's kdtree implementation.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-03-24 18:55 UTC, 12tbuchman reviewed
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/amcl/2)* status: 31 of 53 files reviewed, 193 unresolved discussions (waiting on @12tbuchman and @c-andy-martin)

___
*[include/amcl/sensors/odom.h, line 45 at r5](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M1kPzWfDU0CwL8YlcQJ:-M3CtL327GFpFs-Upoy1:b-896fix) ([raw file](https://github.com/badgertechnologies/amcl/blob/95b6eb20da05f9f418bc7ea0645e69d04bc7dd99/include/amcl/sensors/odom.h#L45)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

Let's take a todo ticket to make the odometry models object-oriented
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-03-25 15:11 UTC, 12tbuchman reviewed
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/amcl/2)* status: 31 of 53 files reviewed, 193 unresolved discussions (waiting on @12tbuchman and @c-andy-martin)

___
*[include/amcl/sensors/planar_scanner.h, line 30 at r5](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M1kQTc_Dpc0G0ELY03o:-M3EbYKqBXQU8ew1c9kv:b-896fix) ([raw file](https://github.com/badgertechnologies/amcl/blob/95b6eb20da05f9f418bc7ea0645e69d04bc7dd99/include/amcl/sensors/planar_scanner.h#L30)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

this should come as the very last include
</blockquote></details>

Done.
___
*[include/amcl/sensors/planar_scanner.h, line 32 at r5](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M1kQVsc7FIh8Ld6-MKw:-M3HEk6F-BNOeKPaALlv:b-a4m407) ([raw file](https://github.com/badgertechnologies/amcl/blob/95b6eb20da05f9f418bc7ea0645e69d04bc7dd99/include/amcl/sensors/planar_scanner.h#L32)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

change C headers to C++, so this should be `<cstddef>` and add `std::` where necessary, also then delete the newline below.
</blockquote></details>

Done throughout entire package.


<!-- Sent from Reviewable.io -->

2020-03-25 15:17 UTC, 12tbuchman reviewed
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/amcl/2)* status: 18 of 53 files reviewed, 193 unresolved discussions (waiting on @12tbuchman and @c-andy-martin)

___
*[include/amcl/sensors/planar_scanner.h, line 48 at r5](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M1kQkM51OOq16eqte-r:-M3HF8Zu5Q9cHWmdqR3e:b-896fix) ([raw file](https://github.com/badgertechnologies/amcl/blob/95b6eb20da05f9f418bc7ea0645e69d04bc7dd99/include/amcl/sensors/planar_scanner.h#L48)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

Let's take a to do to make this part object-oriented. So you would have a SensorModelInterface of some sort (feel free to name it to anything appropriate) and make child classes for each type. But feel free to defer this using a jira ticket.
</blockquote></details>

Done.
___
*[include/amcl/sensors/planar_scanner.h, line 54 at r5](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M1kR5Fu9PnaXDqbfuVW:-M3HG5Mf4TYxdIMZ61wS:b-h1so1b) ([raw file](https://github.com/badgertechnologies/amcl/blob/95b6eb20da05f9f418bc7ea0645e69d04bc7dd99/include/amcl/sensors/planar_scanner.h#L54)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

Either add a space here like this:
`PlanarData() {}`, or you could also do `PlanarData() = default;`. I would do the same for the destructor. The empty brace formatting follows an example here:
https://google.github.io/styleguide/cppguide.html#Horizontal_Whitespace
There is also an example there of how to do the spacing if you want to have something in the one-line body.
</blockquote></details>

Done throughout package. Thanks for the link.


<!-- Sent from Reviewable.io -->

2020-03-25 16:25 UTC, 12tbuchman reviewed
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/amcl/2)* status: 18 of 53 files reviewed, 193 unresolved discussions (waiting on @12tbuchman and @c-andy-martin)

___
*[include/amcl/sensors/planar_scanner.h, line 66 at r5](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M1kSFZ0C76P5pesD6WA:-M3HUdZH0yNa0_ib5eQX:b-896fix) ([raw file](https://github.com/badgertechnologies/amcl/blob/95b6eb20da05f9f418bc7ea0645e69d04bc7dd99/include/amcl/sensors/planar_scanner.h#L66)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

I don't think this comment adds anything, just delete it
</blockquote></details>

Done.
___
*[include/amcl/sensors/planar_scanner.h, line 70 at r5](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M1kSW0uDirPazZ5LxCL:-M3HVgGO65DTLUFq8Tlh:b-fos6be) ([raw file](https://github.com/badgertechnologies/amcl/blob/95b6eb20da05f9f418bc7ea0645e69d04bc7dd99/include/amcl/sensors/planar_scanner.h#L70)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

I would make `max_beams` an `int`. It is elsewhere, and we might want to set it to something negative to indicate to use all the data.
</blockquote></details>

Done throughout package.


<!-- Sent from Reviewable.io -->

2020-03-25 16:26 UTC, 12tbuchman reviewed
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/amcl/2)* status: 18 of 53 files reviewed, 193 unresolved discussions (waiting on @12tbuchman and @c-andy-martin)

___
*[include/amcl/sensors/point_cloud_scanner.h, line 43 at r5](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M1kT5vi8gTUmaqE_8Uo:-M3HW1rD2vZpYcZ1QOA3:b-896fix) ([raw file](https://github.com/badgertechnologies/amcl/blob/95b6eb20da05f9f418bc7ea0645e69d04bc7dd99/include/amcl/sensors/point_cloud_scanner.h#L43)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

and, again, let's take a to-do to make these object oriented.
</blockquote></details>

Done.
___
*[include/amcl/sensors/point_cloud_scanner.h, line 49 at r5](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M1kTD334SHaNPqKXsC2:-M3HW2rB0IOkR3FXbqHh:b-896fix) ([raw file](https://github.com/badgertechnologies/amcl/blob/95b6eb20da05f9f418bc7ea0645e69d04bc7dd99/include/amcl/sensors/point_cloud_scanner.h#L49)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

Please check for spacing everywhere w/ empty braces (there should be a space before them)
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-03-25 16:29 UTC, 12tbuchman reviewed
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/amcl/2)* status: 18 of 53 files reviewed, 193 unresolved discussions (waiting on @12tbuchman and @c-andy-martin)

___
*[include/amcl/sensors/sensor.h, line 41 at r5](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M1kUBAP0NkoUk1_MLzx:-M3HWNU49xAkO4-HV40j:b-896fix) ([raw file](https://github.com/badgertechnologies/amcl/blob/95b6eb20da05f9f418bc7ea0645e69d04bc7dd99/include/amcl/sensors/sensor.h#L41)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

Let's ditch this comment
</blockquote></details>

Done.
___
*[include/amcl/sensors/sensor.h, line 42 at r5](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M1kUHaL8lNY45xcEJyW:-M3HWcsy-iDSp1y1rdni:b-896fix) ([raw file](https://github.com/badgertechnologies/amcl/blob/95b6eb20da05f9f418bc7ea0645e69d04bc7dd99/include/amcl/sensors/sensor.h#L42)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

I don't bother declaring and defining default constructors that do nothing, the compiler will already do that for you
</blockquote></details>

Done.
___
*[include/amcl/sensors/sensor.h, line 44 at r5](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M1kUDPz7qpAzw98KsUM:-M3HWdHl257cIJArkLOC:b-896fix) ([raw file](https://github.com/badgertechnologies/amcl/blob/95b6eb20da05f9f418bc7ea0645e69d04bc7dd99/include/amcl/sensors/sensor.h#L44)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

Let's ditch this comment
</blockquote></details>

Done.
___
*[include/amcl/sensors/sensor.h, line 45 at r5](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M1kUVD27z984HDJquNf:-M3HWeJU3TiE0QMJ9P7i:b-896fix) ([raw file](https://github.com/badgertechnologies/amcl/blob/95b6eb20da05f9f418bc7ea0645e69d04bc7dd99/include/amcl/sensors/sensor.h#L45)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

Go ahead and define the destructor here as either `virtual ~Sensor() = default;` or `virtual ~Sensor() {};`. Once doing this, and doing the below pure-virtual work, you can delete the sensor.cpp entirely
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-03-25 16:45 UTC, 12tbuchman reviewed
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/amcl/2)* status: 18 of 53 files reviewed, 193 unresolved discussions (waiting on @12tbuchman and @c-andy-martin)

___
*[include/amcl/sensors/sensor.h, line 49 at r5](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M1kTx1r3nem51_v4H2_:-M3HX23NDkbQLyyYB0AK:bgbyqa2) ([raw file](https://github.com/badgertechnologies/amcl/blob/95b6eb20da05f9f418bc7ea0645e69d04bc7dd99/include/amcl/sensors/sensor.h#L49)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

Make this and all the below methods pure virtual by adding `= 0;` and removing the definition in the .cpp file.
</blockquote></details>

Id prefer not to make these pure virtual because that requires all child classes to implement the functions, which is not the case. Odom currently implements updateAction() while PlanarScanner and PointCloudScanner implement updateSensor(). I have moved their trivial implementation into the .h file and removed the .cpp file. If you still want these functions to be pure virtual we can discuss this further.
___
*[include/amcl/sensors/sensor.h, line 68 at r5](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M1kTkS3BpdklAMM7bxi:-M3HXLLW3AMCoIoblz2A:b-l3fgtv) ([raw file](https://github.com/badgertechnologies/amcl/blob/95b6eb20da05f9f418bc7ea0645e69d04bc7dd99/include/amcl/sensors/sensor.h#L68)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

This should probably be under a `protected:`
</blockquote></details>

I made a getSensor() method and hid the object itself.


<!-- Sent from Reviewable.io -->

2020-03-25 16:54 UTC, 12tbuchman reviewed
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/amcl/2)* status: 18 of 53 files reviewed, 193 unresolved discussions (waiting on @12tbuchman and @c-andy-martin)

___
*[include/amcl/sensors/sensor.h, line 68 at r5](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M1kTkS3BpdklAMM7bxi:-M3HbLGG94L_Yo8rU2Q0:bxqwnm9) ([raw file](https://github.com/badgertechnologies/amcl/blob/95b6eb20da05f9f418bc7ea0645e69d04bc7dd99/include/amcl/sensors/sensor.h#L68)):*
<details><summary><i>Previously, 12tbuchman (Tyler Buchman) wrote…</i></summary><blockquote>

I made a getSensor() method and hid the object itself.
</blockquote></details>

Actually I am removing the sensor_ object from SensorData altogether because it is not needed.


<!-- Sent from Reviewable.io -->

2020-03-25 20:55 UTC, 12tbuchman reviewed
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/amcl/2)* status: 17 of 53 files reviewed, 193 unresolved discussions (waiting on @12tbuchman and @c-andy-martin)

___
*[cfg/AMCL.cfg, line 156 at r1](https://reviewable.io/reviews/badgertechnologies/amcl/2#-Lz910OL9OtF2ULTISdW:-M3ITPo_EdJZg28c2BTK:b87hlfq) ([raw file](https://github.com/badgertechnologies/amcl/blob/ba6da8b7912ca1f1c7e7b5dc81bd48de469c440f/cfg/AMCL.cfg#L156)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

I'm confused, because the feature seems to be there, and I thought we did use the save pose to file, so Control doesn't have to worry with the pose at all.
</blockquote></details>

Sorry, my comment actually referred to the line above, the save_pose boolean


<!-- Sent from Reviewable.io -->

2020-03-25 22:03 UTC, 12tbuchman reviewed
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/amcl/2)* status: 16 of 53 files reviewed, 193 unresolved discussions (waiting on @12tbuchman and @c-andy-martin)

___
*[cfg/AMCL.cfg, line 156 at r1](https://reviewable.io/reviews/badgertechnologies/amcl/2#-Lz910OL9OtF2ULTISdW:-M3Ii61e2HTWk93T_JBj:b-d8kmga) ([raw file](https://github.com/badgertechnologies/amcl/blob/ba6da8b7912ca1f1c7e7b5dc81bd48de469c440f/cfg/AMCL.cfg#L156)):*
<details><summary><i>Previously, 12tbuchman (Tyler Buchman) wrote…</i></summary><blockquote>

Sorry, my comment actually referred to the line above, the save_pose boolean
</blockquote></details>

Done with saved_pose_filepath


<!-- Sent from Reviewable.io -->

2020-03-25 22:04 UTC, 12tbuchman reviewed
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/amcl/2)* status: 16 of 53 files reviewed, 193 unresolved discussions (waiting on @12tbuchman and @c-andy-martin)

___
*[include/amcl/map/map.h, line 28 at r8](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M2dV5K12piaxQXSnT-i:-M3IiG5S-DzyTS210kyQ:b-cht3z5) ([raw file](https://github.com/badgertechnologies/amcl/blob/7cb58c9d2aa3041f7f54502c6088113283cd12f6/include/amcl/map/map.h#L28)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

This include should come after the standard includes below.
</blockquote></details>

see previous similar discussions


<!-- Sent from Reviewable.io -->

2020-03-25 22:37 UTC, 12tbuchman reviewed
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/amcl/2)* status: 16 of 53 files reviewed, 193 unresolved discussions (waiting on @12tbuchman and @c-andy-martin)

___
*[include/amcl/map/occupancy_map.h, line 89 at r9](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M2eHvjz6ZgkGC5ysSX2:-M3IpQjLByxyI9C0OfJP:b-cndjls) ([raw file](https://github.com/badgertechnologies/amcl/blob/b28c573d53c54b2904a0c476e86e7f24b8cd83ff/include/amcl/map/occupancy_map.h#L89)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

These should either be `virtual` or under `private`. My logic is this: either this method is internal to OccupancyMap and should never be used by child classes (therefore should be `private`) or, there is some reason why a child class might want to override the behavior of these methods, in which case they should also be marked as `virtual`. If you decide to make them `private`, please leave the internal variables `protected` unless you are sure they are only ever used by the `private` methods and there is no reason why a child class would ever want to override. My vote would be to just add `virtual` to all of them except for setMapOccDist (because of performance concerns). (In fact, you might want setMapOccDist to be inline and private)
</blockquote></details>

Ive made the functions called for every voxel in updateCSpace to be private inline for performance. I was thinking though, should the public function getOccDist really be virtual? This is a huge performance cost considering we already spend so much time in that function from calling it for every iterated point in a data scan.


<!-- Sent from Reviewable.io -->

2020-03-25 23:09 UTC, 12tbuchman reviewed
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/amcl/2)* status: 16 of 53 files reviewed, 193 unresolved discussions (waiting on @12tbuchman and @c-andy-martin)

___
*[include/amcl/map/occupancy_map.h, line 109 at r9](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M2eHh8H09SCfT9WCY9z:-M3Ix-n-AHtyjOThwFxi:buhjg11) ([raw file](https://github.com/badgertechnologies/amcl/blob/b28c573d53c54b2904a0c476e86e7f24b8cd83ff/include/amcl/map/occupancy_map.h#L109)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

I'm curious why you pulled OccupancyMapCellData out of OccupancyMap. If this struct is only used internally to OccupancyMap, I like it better inside the OccupancyMap object under `protected`.
</blockquote></details>

I took it out so I could put the constructor implementation in OccupancyMap.cpp for readability but I realize now I can have the struct within the class and still have the constructor in the .cpp file so I have fixed this.


<!-- Sent from Reviewable.io -->

2020-03-25 23:20 UTC, 12tbuchman reviewed
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/amcl/2)* status: 16 of 53 files reviewed, 193 unresolved discussions (waiting on @12tbuchman and @c-andy-martin)

___
*[include/amcl/map/occupancy_map.h, line 109 at r9](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M2eHh8H09SCfT9WCY9z:-M3IzUB60LKhe9OMaNYB:be4rtzr) ([raw file](https://github.com/badgertechnologies/amcl/blob/b28c573d53c54b2904a0c476e86e7f24b8cd83ff/include/amcl/map/occupancy_map.h#L109)):*
<details><summary><i>Previously, 12tbuchman (Tyler Buchman) wrote…</i></summary><blockquote>

I took it out so I could put the constructor implementation in OccupancyMap.cpp for readability but I realize now I can have the struct within the class and still have the constructor in the .cpp file so I have fixed this.
</blockquote></details>

wait nevermind, that was the CachedDistanceMap and I dont think I can put that in the class and have the constructor in the .cpp file. Anyway I just took out the CellData struct when I was trying to refactor the friend override function for readability, but I put the struct back in the main class now.


<!-- Sent from Reviewable.io -->

2020-03-26 14:41 UTC, 12tbuchman reviewed
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/amcl/2)* status: 16 of 53 files reviewed, 193 unresolved discussions (waiting on @12tbuchman and @c-andy-martin)

___
*[include/amcl/map/octomap.h, line 67 at r3](https://reviewable.io/reviews/badgertechnologies/amcl/2#-LzIFaJu7n8X4sxlRSR-:-M3MHT6l9or02O_lxToD:bj6drha) ([raw file](https://github.com/badgertechnologies/amcl/blob/770d4c63beb80b8977948e006adb7bdbc3c1d735/include/amcl/map/octomap.h#L67)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

I don't see the default constructor deleted. If you don't explicitly delete it, the compiler will make one for you. So, down below, in OctoMapCellData, do:
```
OctoMapCellData() = delete;
```
</blockquote></details>

Sorry, now its done.


<!-- Sent from Reviewable.io -->

2020-03-26 14:41 UTC, 12tbuchman reviewed
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/amcl/2)* status: 16 of 53 files reviewed, 193 unresolved discussions (waiting on @12tbuchman and @c-andy-martin)

___
*[include/amcl/map/octomap.h, line 79 at r9](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M2eKjgR1p59bvz9o3NE:-M3MHcSDChAYmjM65idW:b-896fix) ([raw file](https://github.com/badgertechnologies/amcl/blob/b28c573d53c54b2904a0c476e86e7f24b8cd83ff/include/amcl/map/octomap.h#L79)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

Same comment here as I made in occupancy_map.h
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-03-26 14:57 UTC, 12tbuchman reviewed
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/amcl/2)* status: 16 of 53 files reviewed, 193 unresolved discussions (waiting on @12tbuchman and @c-andy-martin)

___
*[include/amcl/node/node.h, line 65 at r5](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M1g2z_X7ZW7wNWPNyg_:-M3MKmpV0-oVNf15Wjv2:b-896fix) ([raw file](https://github.com/badgertechnologies/amcl/blob/95b6eb20da05f9f418bc7ea0645e69d04bc7dd99/include/amcl/node/node.h#L65)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

I would add a free space here, even if the clang-format might eat it, it looks prettier to me.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-03-26 15:08 UTC, 12tbuchman reviewed
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/amcl/2)* status: 16 of 53 files reviewed, 193 unresolved discussions (waiting on @12tbuchman and @c-andy-martin)

___
*[src/main.cpp, line 23 at r5](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M1kVHWNEZnN51In5JgO:-M3MNfRpAdoBhOpe5FQX:b-896fix) ([raw file](https://github.com/badgertechnologies/amcl/blob/95b6eb20da05f9f418bc7ea0645e69d04bc7dd99/src/main.cpp#L23)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

let's get rid of `boost::shared_ptr` and only use `std::shared_ptr`
</blockquote></details>

Done.
___
*[src/main.cpp, line 29 at r5](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M1kVMWu5richnnvl4gC:-M3MNgmI6NHc_RzEDtc2:bgm2s8j) ([raw file](https://github.com/badgertechnologies/amcl/blob/95b6eb20da05f9f418bc7ea0645e69d04bc7dd99/src/main.cpp#L29)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

iostream should come first, as its a C++ std include
</blockquote></details>

see previous discussions on this
___
*[src/main.cpp, line 33 at r5](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M1kVQ1p6HMeVfd8ij7f:-M3MNksl69AJ9OeubuQH:bnug35m) ([raw file](https://github.com/badgertechnologies/amcl/blob/95b6eb20da05f9f418bc7ea0645e69d04bc7dd99/src/main.cpp#L33)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

I much prefer not to do this. Just add `amcl::` where necessary.
</blockquote></details>

whats the reason we want to not use amcl here?


<!-- Sent from Reviewable.io -->

2020-03-26 15:58 UTC, 12tbuchman reviewed
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/amcl/2)* status: 16 of 53 files reviewed, 193 unresolved discussions (waiting on @12tbuchman and @c-andy-martin)

___
*[src/main.cpp, line 35 at r5](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M1kWnl7CYpiNV8nWCAR:-M3MXblTAqX0_Y4ruhkT:b-9xaney) ([raw file](https://github.com/badgertechnologies/amcl/blob/95b6eb20da05f9f418bc7ea0645e69d04bc7dd99/src/main.cpp#L35)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

move this into `main()`. as i point out there, make it a unique_ptr
</blockquote></details>

Done. I was looking into if we need this to be a pointer at all. I think we do but i don't really understand why. Can you help me on this?
___
*[src/main.cpp, line 36 at r5](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M1kW2cX8M-jt8r-xnoj:-M3MXnQZ3K7sjPzu0EtM:b-896fix) ([raw file](https://github.com/badgertechnologies/amcl/blob/95b6eb20da05f9f418bc7ea0645e69d04bc7dd99/src/main.cpp#L36)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

sigFlag is unused. Delete it here and below.
</blockquote></details>

Done.
___
*[src/main.cpp, line 40 at r5](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M1kVxBZ8oaqsRf5eaiN:-M3MXrbV-30O85qYkt_L:b-896fix) ([raw file](https://github.com/badgertechnologies/amcl/blob/95b6eb20da05f9f418bc7ea0645e69d04bc7dd99/src/main.cpp#L40)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

It is not safe to use `cout` in a signal handler. Delete this line.
</blockquote></details>

Done.
___
*[src/main.cpp, line 54 at r5](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M1kVgHZ1pQ9sfrw_K4Z:-M3MXtXp37HbonZUuEuX:b-896fix) ([raw file](https://github.com/badgertechnologies/amcl/blob/95b6eb20da05f9f418bc7ea0645e69d04bc7dd99/src/main.cpp#L54)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

This comment is misleading, it's not even correct. Remove.
</blockquote></details>

Done.
___
*[src/main.cpp, line 55 at r5](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M1kWKs56RFgmX6OOT-6:-M3MXx1YE9D65xpM8Uzi:b-896fix) ([raw file](https://github.com/badgertechnologies/amcl/blob/95b6eb20da05f9f418bc7ea0645e69d04bc7dd99/src/main.cpp#L55)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

I see no reason to wrap Node in a shared pointer. Let's wrap it in a unique_ptr instead. Also, instead of the reset() below, just put the unique_ptr in a nested scope.
</blockquote></details>

Done.
___
*[src/main.cpp, line 57 at r5](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M1kV3EY261uihUBhw97:-M3MY2nVC9JPFA92JY3w:b-896fix) ([raw file](https://github.com/badgertechnologies/amcl/blob/95b6eb20da05f9f418bc7ea0645e69d04bc7dd99/src/main.cpp#L57)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

Lets delete these 4 commented lines
</blockquote></details>

Done.
___
*[src/main.cpp, line 66 at r5](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M1kVZRm7R_yEgG_Xvch:-M3MYDdB4VWwEOwsiwCu:b-896fix) ([raw file](https://github.com/badgertechnologies/amcl/blob/95b6eb20da05f9f418bc7ea0645e69d04bc7dd99/src/main.cpp#L66)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

Remove `boost`
</blockquote></details>

Done.
___
*[src/main.cpp, line 69 at r5](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M1kVWSB4r32RTIPOynu:-M3MYDwz4C-ftqt2tjnK:b-896fix) ([raw file](https://github.com/badgertechnologies/amcl/blob/95b6eb20da05f9f418bc7ea0645e69d04bc7dd99/src/main.cpp#L69)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

delete
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-03-26 17:16 UTC, 12tbuchman reviewed
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/amcl/2)* status: 16 of 53 files reviewed, 193 unresolved discussions (waiting on @12tbuchman and @c-andy-martin)

___
*[src/amcl/map/map.cpp, line 28 at r6](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M24J6uRDo7LGTVNBeif:-M3MmKY-4Z76iLX-etSH:b-lw2zgl) ([raw file](https://github.com/badgertechnologies/amcl/blob/9df029774580bad51987f61b64a87071070f819b/src/amcl/map/map.cpp#L28)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

I prefer to put this in the amcl namespace over using
</blockquote></details>

Done for all .cpp files


<!-- Sent from Reviewable.io -->

2020-03-26 17:18 UTC, 12tbuchman reviewed
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/amcl/2)* status: 16 of 53 files reviewed, 193 unresolved discussions (waiting on @12tbuchman and @c-andy-martin)

___
*[src/amcl/map/occupancy_map.cpp, line 28 at r6](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M24JDAb4MKDJIcDL_hf:-M3Mq1yPEkC2Ch7OaYEf:b-896fix) ([raw file](https://github.com/badgertechnologies/amcl/blob/9df029774580bad51987f61b64a87071070f819b/src/amcl/map/occupancy_map.cpp#L28)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

I prefer to put this in the amcl namespace over using
</blockquote></details>

Done.
___
*[src/amcl/map/occupancy_map.cpp, line 30 at r6](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M24JFXe9fZDVvW0pH7e:-M3MqEmy34MfmKFD5EHS:b-896fix) ([raw file](https://github.com/badgertechnologies/amcl/blob/9df029774580bad51987f61b64a87071070f819b/src/amcl/map/occupancy_map.cpp#L30)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

This comment is a bit misleading (the map isn't created by a constructor so much as constructed, I don't think you need this comment)
</blockquote></details>

Done.
___
*[src/amcl/map/occupancy_map.cpp, line 37 at r6](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M24JMvw5ezZsYmVvPFX:-M3MqM9G8kaJ2GtOsvMB:bmc5gxa) ([raw file](https://github.com/badgertechnologies/amcl/blob/9df029774580bad51987f61b64a87071070f819b/src/amcl/map/occupancy_map.cpp#L37)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

This comment doesn't make any sense to me (0 is not odd!)
</blockquote></details>

yeah I saw that too when I was refactoring this from a previous comment
___
*[src/amcl/map/occupancy_map.cpp, line 43 at r6](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M24JRMWD5e2XNTvhlL6:-M3MqSp3ALqKq81INeo-:b9iq4wn) ([raw file](https://github.com/badgertechnologies/amcl/blob/9df029774580bad51987f61b64a87071070f819b/src/amcl/map/occupancy_map.cpp#L43)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

This comment doesn't make any sense, as no allocation is going on here
</blockquote></details>

this has already been removed


<!-- Sent from Reviewable.io -->

2020-03-26 17:36 UTC, 12tbuchman reviewed
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/amcl/2)* status: 16 of 53 files reviewed, 193 unresolved discussions (waiting on @12tbuchman and @c-andy-martin)

___
*[src/amcl/map/occupancy_map.cpp, line 109 at r6](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M24LLC-6KPTxT3p5JmC:-M3MuDvV2ntcenvyFKLH:bae78fq) ([raw file](https://github.com/badgertechnologies/amcl/blob/9df029774580bad51987f61b64a87071070f819b/src/amcl/map/occupancy_map.cpp#L109)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

If you follow my advice above, get rid of adding size_x_/size_y_ here.
</blockquote></details>

Is this really important? This is how the legacy code is written, and changing it introduces the possibility of breaking something. I dont see how the benefit outweighs the cost here but I am willing to discuss it.


<!-- Sent from Reviewable.io -->

2020-03-26 17:40 UTC, 12tbuchman reviewed
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/amcl/2)* status: 16 of 53 files reviewed, 193 unresolved discussions (waiting on @12tbuchman and @c-andy-martin)

___
*[src/amcl/map/occupancy_map.cpp, line 122 at r6](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M24LlK10PC51vsTrMh5:-M3MvUpzDqjEENRctNg3:byr4ffv) ([raw file](https://github.com/badgertechnologies/amcl/blob/9df029774580bad51987f61b64a87071070f819b/src/amcl/map/occupancy_map.cpp#L122)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

I think if you get rid of adjusting the origin by size_x_/2, you can make size_x_/size_y_ unsigned, and get rid of this static cast to unsigned here.
</blockquote></details>

see above
___
*[src/amcl/map/occupancy_map.cpp, line 112 at r9](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M2eGWdY4VSfutNgZKAy:-M3Mv-Ju3uX43IszxL8y:bplhxcm) ([raw file](https://github.com/badgertechnologies/amcl/blob/b28c573d53c54b2904a0c476e86e7f24b8cd83ff/src/amcl/map/occupancy_map.cpp#L112)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

I prefer using C++ style casts in C++ code:
```
cell_radius_ = static_cast<int>(std::floor(max_dist / resolution));
```
Also, unless someone pulls in math.h or someone does a `using namespace std` you won't have floor in your namespace, you need to make the namespace explicit to prevent future breakage (so floor should be `std::floor` everywhere)
</blockquote></details>

Ive made the std::namespace explicit throughout the code now.


<!-- Sent from Reviewable.io -->

2020-03-26 17:42 UTC, 12tbuchman reviewed
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/amcl/2)* status: 16 of 53 files reviewed, 193 unresolved discussions (waiting on @12tbuchman and @c-andy-martin)

___
*[src/amcl/map/occupancy_map.cpp, line 112 at r9](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M2eGWdY4VSfutNgZKAy:-M3Mw0jo2T517PAX7P6-:b-896fix) ([raw file](https://github.com/badgertechnologies/amcl/blob/b28c573d53c54b2904a0c476e86e7f24b8cd83ff/src/amcl/map/occupancy_map.cpp#L112)):*
<details><summary><i>Previously, 12tbuchman (Tyler Buchman) wrote…</i></summary><blockquote>

Ive made the std::namespace explicit throughout the code now.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-03-26 21:30 UTC, 12tbuchman reviewed
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/amcl/2)* status: 16 of 53 files reviewed, 193 unresolved discussions (waiting on @12tbuchman and @c-andy-martin)

___
*[src/amcl/map/occupancy_map.cpp, line 109 at r6](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M24LLC-6KPTxT3p5JmC:-M3Nk5SN-fOj_gZsUQ_8:b-arved7) ([raw file](https://github.com/badgertechnologies/amcl/blob/9df029774580bad51987f61b64a87071070f819b/src/amcl/map/occupancy_map.cpp#L109)):*
<details><summary><i>Previously, 12tbuchman (Tyler Buchman) wrote…</i></summary><blockquote>

Is this really important? This is how the legacy code is written, and changing it introduces the possibility of breaking something. I dont see how the benefit outweighs the cost here but I am willing to discuss it.
</blockquote></details>

whoops meant to write this above...


<!-- Sent from Reviewable.io -->

2020-03-26 21:30 UTC, 12tbuchman reviewed
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/amcl/2)* status: 16 of 53 files reviewed, 193 unresolved discussions (waiting on @12tbuchman and @c-andy-martin)

___
*[src/amcl/map/occupancy_map.cpp, line 100 at r6](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M24Jnx1BcaNQlYvcywk:-M3Nk8sW1BMfF_xUkaOv:bg9tqgg) ([raw file](https://github.com/badgertechnologies/amcl/blob/9df029774580bad51987f61b64a87071070f819b/src/amcl/map/occupancy_map.cpp#L100)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

Also, as a part of this, we can make size_x_/size_y_ unsigned I think, which makes more sense.
</blockquote></details>

see comment below.


<!-- Sent from Reviewable.io -->

2020-03-26 21:32 UTC, 12tbuchman reviewed
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/amcl/2)* status: 16 of 53 files reviewed, 193 unresolved discussions (waiting on @12tbuchman and @c-andy-martin)

___
*[src/amcl/map/occupancy_map_cspace.cpp, line 36 at r6](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M24M8HlEER8GJh6W_wY:-M3NkCwj6hd5cHSYtmEC:b-896fix) ([raw file](https://github.com/badgertechnologies/amcl/blob/9df029774580bad51987f61b64a87071070f819b/src/amcl/map/occupancy_map_cspace.cpp#L36)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

I would prefer to put all of this .cpp file into occupancy_map.cpp and not have two separate cpp files. Generally, the rule of thumb is one cpp file for each object. This makes it easier to see all the parts of the object in one file.
</blockquote></details>

Done.
___
*[src/amcl/map/occupancy_map_cspace.cpp, line 41 at r6](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M24MzCM-TAqt6VvR6oy:-M3NkIma5JIP8jKUJFit:b-c87ft5) ([raw file](https://github.com/badgertechnologies/amcl/blob/9df029774580bad51987f61b64a87071070f819b/src/amcl/map/occupancy_map_cspace.cpp#L41)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

I think this should be a ROS_WARN or even ROS_ERROR
</blockquote></details>

In the current implementation this function is called at the creation of the map, but quickly exits because we havent set max_occ_dist yet. Later, it is called again once max_occ_dist has been properly set. So making this a warning or error would create a false-positive flag that we don't need. 


<!-- Sent from Reviewable.io -->

2020-03-26 21:35 UTC, 12tbuchman reviewed
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/amcl/2)* status: 16 of 53 files reviewed, 193 unresolved discussions (waiting on @12tbuchman and @c-andy-martin)

___
*[src/amcl/map/occupancy_map_cspace.cpp, line 39 at r6](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M24MvoA4jHedJ6ay_Ci:-M3Nl0di3-IhjpbiP68l:b-fio9n0) ([raw file](https://github.com/badgertechnologies/amcl/blob/9df029774580bad51987f61b64a87071070f819b/src/amcl/map/occupancy_map_cspace.cpp#L39)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

Seems like we should also check for negative here.
</blockquote></details>

This is really meant to catch when max_occ_dist hasnt been set yet, not an error check.


<!-- Sent from Reviewable.io -->

2020-03-26 21:37 UTC, 12tbuchman reviewed
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/amcl/2)* status: 16 of 53 files reviewed, 193 unresolved discussions (waiting on @12tbuchman and @c-andy-martin)

___
*[src/amcl/map/occupancy_map_cspace.cpp, line 54 at r6](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M24NIuxAID5pCUc-Mpc:-M3NlYA-6dJQKBiIHYGs:b-az6s09) ([raw file](https://github.com/badgertechnologies/amcl/blob/9df029774580bad51987f61b64a87071070f819b/src/amcl/map/occupancy_map_cspace.cpp#L54)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

it would be cleaner, I think, to pass `q_` and `marked_` into these methods and not make them member variables. Then, you could just let the unique_ptr's go out of scope to free the temporary memory. This is a minor point, so if you'd rather not its OK.
</blockquote></details>

Considering we have followed the rule of adding an underscore after a class variable I prefer to keep the functions parameter-less.


<!-- Sent from Reviewable.io -->

2020-03-26 21:38 UTC, 12tbuchman reviewed
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/amcl/2)* status: 16 of 53 files reviewed, 193 unresolved discussions (waiting on @12tbuchman and @c-andy-martin)

___
*[src/amcl/map/occupancy_map_cspace.cpp, line 66 at r6](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M24mOCkAb4RuqTCfZyV:-M3Nlweo3EbnEehIHUsP:b-jlszh) ([raw file](https://github.com/badgertechnologies/amcl/blob/9df029774580bad51987f61b64a87071070f819b/src/amcl/map/occupancy_map_cspace.cpp#L66)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

if we make size_x_ unsigned, we should probably make i and j unsigned here (this may have ripple effects, but offsets in the array are never negative, so unsigned makes sense to me)
</blockquote></details>

see previous comments.
___
*[src/amcl/map/occupancy_map_cspace.cpp, line 99 at r6](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M24Nio39w2OfYvfX1nq:-M3NlyjKAn5G9v8oOE7b:b-jlszh) ([raw file](https://github.com/badgertechnologies/amcl/blob/9df029774580bad51987f61b64a87071070f819b/src/amcl/map/occupancy_map_cspace.cpp#L99)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

if we make size_x_ unsigned as I ask elsewhere, we can change this to:
```
if (current_cell.i + 1 < size_x_)
```
To get rid of the cast and prevent underflow (and also the size_y_ one below)
</blockquote></details>

see previous comments.


<!-- Sent from Reviewable.io -->

2020-03-26 21:38 UTC, 12tbuchman reviewed
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/amcl/2)* status: 16 of 53 files reviewed, 193 unresolved discussions (waiting on @12tbuchman and @c-andy-martin)

___
*[src/amcl/map/occupancy_map_range.cpp, line 35 at r7](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M24mecq8tmdoqiVciwD:-M3Nm0zD4k3RtKPil66R:b-896fix) ([raw file](https://github.com/badgertechnologies/amcl/blob/74db8df1672f2baaecdf854cea1efd100f551c8b/src/amcl/map/occupancy_map_range.cpp#L35)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

again, I prefer to have this in the main occupancy_map.cpp file (my preference is one file per object)
</blockquote></details>

Done.
___
*[src/amcl/map/occupancy_map_range.cpp, line 37 at r7](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M24mp00EIBO8VvCPhsK:-M3Nm3W21XXd5nAqixfc:bz9sd52) ([raw file](https://github.com/badgertechnologies/amcl/blob/74db8df1672f2baaecdf854cea1efd100f551c8b/src/amcl/map/occupancy_map_range.cpp#L37)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

Then again, if it ain't broke don't fix it, I'd be OK just leaving this as is, your call
</blockquote></details>

Ill make a to-do.


<!-- Sent from Reviewable.io -->

2020-03-27 14:05 UTC, 12tbuchman reviewed
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/amcl/2)* status: 16 of 53 files reviewed, 193 unresolved discussions (waiting on @12tbuchman and @c-andy-martin)

___
*[src/amcl/map/octomap.cpp, line 43 at r5](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M1agJDz46da7brK5ur9:-M3NqbOV3ajlMufDti6K:b5yc0zv) ([raw file](https://github.com/badgertechnologies/amcl/blob/95b6eb20da05f9f418bc7ea0645e69d04bc7dd99/src/amcl/map/octomap.cpp#L43)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

I'd prefer this to be:
```
octree_.reset(new octomap::OcTree(resolution_));
```
It avoids an unnecessary creation and copy of a shared_ptr, and is clearer to me how the memory got allocated that the shared_ptr is managing.
</blockquote></details>

The reason I am using make_shared is that it is an optimization over .reset or shared_ptr because it allocates the reference counter and shared pointer together.
___
*[src/amcl/map/octomap.cpp, line 28 at r6](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M24nEuF34i0wrIxUEvT:-M3NmTIP8Akow593MRZx:b-896fix) ([raw file](https://github.com/badgertechnologies/amcl/blob/9df029774580bad51987f61b64a87071070f819b/src/amcl/map/octomap.cpp#L28)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

there should be a newline between standard includes and library includes, and there should only be one newline below
</blockquote></details>

Done.
___
*[src/amcl/map/octomap.cpp, line 31 at r6](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M24nOamBEbJ_Ftx8frq:-M3NmWqi7SJICFN2Cdhx:b-896fix) ([raw file](https://github.com/badgertechnologies/amcl/blob/9df029774580bad51987f61b64a87071070f819b/src/amcl/map/octomap.cpp#L31)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

I'd prefer this to be in the amcl namespace instead of a using
</blockquote></details>

Done.
___
*[src/amcl/map/octomap.cpp, line 28 at r9](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M2i4uIc5NxBrnw6Cmep:-M3NmUWd1RLZbveYT-K-:b-mrn9) ([raw file](https://github.com/badgertechnologies/amcl/blob/b28c573d53c54b2904a0c476e86e7f24b8cd83ff/src/amcl/map/octomap.cpp#L28)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

These includes are in the wrong order. Standard goes before ros
</blockquote></details>

see previous comments
___
*[src/amcl/map/octomap.cpp, line 32 at r9](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M2i5-Vr-mOPAvqwVlp4:-M3NnjYTB_JcmpxZhvbH:b-896fix) ([raw file](https://github.com/badgertechnologies/amcl/blob/b28c573d53c54b2904a0c476e86e7f24b8cd83ff/src/amcl/map/octomap.cpp#L32)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

I think the spacing for the `:` is to have it on the next line, see:
https://google.github.io/styleguide/cppguide.html#Constructor_Initializer_Lists
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-03-27 14:44 UTC, 12tbuchman reviewed
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/amcl/2)* status: 15 of 51 files reviewed, 193 unresolved discussions (waiting on @12tbuchman and @c-andy-martin)

___
*[src/amcl/map/octomap.cpp, line 57 at r6](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M24qF2j-7SRIVtwWN62:-M3RRgT_7qjHn39vANjp:b-itt7h4) ([raw file](https://github.com/badgertechnologies/amcl/blob/9df029774580bad51987f61b64a87071070f819b/src/amcl/map/octomap.cpp#L57)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

I think you should use your convertWorldToMap function to find the integer values of full_cells_, and then add 1 to each dimension to represent the fact that the max is inclusive.
</blockquote></details>

that seems more complicated and less intuitive than what i have now, no?


<!-- Sent from Reviewable.io -->

2020-03-27 16:07 UTC, 12tbuchman reviewed
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/amcl/2)* status: 15 of 51 files reviewed, 193 unresolved discussions (waiting on @12tbuchman and @c-andy-martin)

___
*[src/amcl/map/octomap.cpp, line 66 at r6](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M24qXONEmOH4aK84_fC:-M3RjqBk0EW0APXS_g1i:b-896fix) ([raw file](https://github.com/badgertechnologies/amcl/blob/9df029774580bad51987f61b64a87071070f819b/src/amcl/map/octomap.cpp#L66)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

Or instead of my above comment, maybe it would be easier to just set the full_cells_ by subtracing the max and min here:
```
full_cells_[0] = cropped_max_cells_[0] - cropped_max_cells_[0] + 1
```
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-03-27 16:28 UTC, 12tbuchman reviewed
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/amcl/2)* status: 15 of 51 files reviewed, 193 unresolved discussions (waiting on @12tbuchman and @c-andy-martin)

___
*[src/amcl/map/octomap.cpp, line 66 at r6](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M24qXONEmOH4aK84_fC:-M3RohtEB5tGzHyKhsRI:blxl2sk) ([raw file](https://github.com/badgertechnologies/amcl/blob/9df029774580bad51987f61b64a87071070f819b/src/amcl/map/octomap.cpp#L66)):*
<details><summary><i>Previously, 12tbuchman (Tyler Buchman) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

actually this is unused.
___
*[src/amcl/map/octomap.cpp, line 82 at r6](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M24qsti0gEI001xhdeW:-M3RochB9E7zIMP1cdvs:b-1m8qzd) ([raw file](https://github.com/badgertechnologies/amcl/blob/9df029774580bad51987f61b64a87071070f819b/src/amcl/map/octomap.cpp#L82)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

since you are returning something inside the object, you could make this return by const reference like this (and change the header to match):
`const std::vector<int>& OctoMap::getSize() const`
</blockquote></details>

actually this is an unused function, and thus full_cells_ is unused as well. Removing them now.


<!-- Sent from Reviewable.io -->

2020-03-27 16:44 UTC, 12tbuchman reviewed
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/amcl/2)* status: 15 of 51 files reviewed, 193 unresolved discussions (waiting on @12tbuchman and @c-andy-martin)

___
*[src/amcl/map/octomap.cpp, line 161 at r9](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M2eGxGc7XoHYqK5PoZS:-M3RsOjy4ifCMTBvFyah:b-1bclgj) ([raw file](https://github.com/badgertechnologies/amcl/blob/b28c573d53c54b2904a0c476e86e7f24b8cd83ff/src/amcl/map/octomap.cpp#L161)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

I prefer using C++ style casts in C++ code:

```
cell_radius_ = static_cast<int>(std::floor(max_dist / resolution));
```

Also, unless someone pulls in math.h or someone does a using namespace std you won't have floor in your namespace, you need to make the namespace explicit to prevent future breakage (so `floor` should be `std::floor` everywhere)
</blockquote></details>

fixed for all c style casting i could find in the package


<!-- Sent from Reviewable.io -->

2020-03-27 16:55 UTC, 12tbuchman reviewed
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/amcl/2)* status: 15 of 51 files reviewed, 193 unresolved discussions (waiting on @12tbuchman and @c-andy-martin)

___
*[src/amcl/map/octomap.cpp, line 166 at r6](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M24rOnz7u10UaLOY-d-:-M3Ru2Cc3B-I1W6M592u:b7i498d) ([raw file](https://github.com/badgertechnologies/amcl/blob/9df029774580bad51987f61b64a87071070f819b/src/amcl/map/octomap.cpp#L166)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

so while restricting the 3D map to the 2D bounds makes sense when restricting the pose we might come up with when localizing, we may have valid map data that we'd like to match not in those bounds. We could have two ideas of the bounds here, if we get a 2D map_min/map_max here in setMapBounds, we set a new 2D bounds that we only enforce when isValid is given a 2D vector. If isValid is given a 3D vector, just use the original 3D octomap bounds. Sound good? I think this gives us both functions at once.
</blockquote></details>

So I think what you are referring to is getting data points at the edge of the map, right? I factored max_occ_dist into the cropped cells so that we can evaluate data points at the edges of the map. I changed isValid to isPoseValid in OctoMap to better reflect that isValid is only called to evaluate the validity of a pose, not of a data point as is true in OccupancyMap. Lets discuss this further.


<!-- Sent from Reviewable.io -->

2020-03-27 17:11 UTC, 12tbuchman reviewed
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/amcl/2)* status: 15 of 51 files reviewed, 193 unresolved discussions (waiting on @12tbuchman and @c-andy-martin)

___
*[src/amcl/map/octomap_cspace.cpp, line 30 at r7](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M26Q16M90YLmU1xmWQN:-M3RyToT-_p9MW98d2GG:b-896fix) ([raw file](https://github.com/badgertechnologies/amcl/blob/74db8df1672f2baaecdf854cea1efd100f551c8b/src/amcl/map/octomap_cspace.cpp#L30)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

lets switch to cstdlib
</blockquote></details>

Done.
___
*[src/amcl/map/octomap_cspace.cpp, line 32 at r7](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M26Q3Ih4c7NsC2Ca4YN:-M3RyWJVC6ZdBN-i2dU7:b-k27tvl) ([raw file](https://github.com/badgertechnologies/amcl/blob/74db8df1672f2baaecdf854cea1efd100f551c8b/src/amcl/map/octomap_cspace.cpp#L32)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

std libraries should come between the "map/octomap.h" and the 3rd party libraries
</blockquote></details>

see previous discussion
___
*[src/amcl/map/octomap_cspace.cpp, line 39 at r7](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M26Q9vs91fW6jDC_c8t:-M3RyYuoCG3XlQQ_Tu-4:b-896fix) ([raw file](https://github.com/badgertechnologies/amcl/blob/74db8df1672f2baaecdf854cea1efd100f551c8b/src/amcl/map/octomap_cspace.cpp#L39)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

I'd prefer to have only one octomap.cpp file and put all the OctoMap class method definitions in there, so I'd like to have these all moved into octomap.cpp
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-03-30 15:38 UTC, 12tbuchman reviewed
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/amcl/2)* status: 15 of 51 files reviewed, 193 unresolved discussions (waiting on @12tbuchman and @c-andy-martin)

___
*[src/amcl/map/octomap_cspace.cpp, line 55 at r7](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M26QPqS1JsffgNVqKX3:-M3g4ei006bMiroJb6EV:b-9ebhqs) ([raw file](https://github.com/badgertechnologies/amcl/blob/74db8df1672f2baaecdf854cea1efd100f551c8b/src/amcl/map/octomap_cspace.cpp#L55)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

These are no longer pointers, but I still think you don't need them to be part of the class, just put them on the stack here.
</blockquote></details>

done, though I think it makes the code less clean to have 2 more parameters with long types added to 4 functions.


<!-- Sent from Reviewable.io -->

2020-03-30 19:35 UTC, 12tbuchman reviewed
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/amcl/2)* status: 15 of 51 files reviewed, 193 unresolved discussions (waiting on @12tbuchman and @c-andy-martin)

___
*[src/amcl/map/octomap_cspace.cpp, line 77 at r7](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M26T5moCWHu19rjm-6c:-M3g71YFBcI4IwCwMCTr:b-896fix) ([raw file](https://github.com/badgertechnologies/amcl/blob/74db8df1672f2baaecdf854cea1efd100f551c8b/src/amcl/map/octomap_cspace.cpp#L77)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

You need to expand() the octree before you iterate over it, or you will not handle pruned inner leaves correctly. All you have to do is call the expand() method on it. You could do this at any point, all though the resulting tree will take slightly more RAM. Without doing this, you will not correctly handle a pruned leaf (you will only consider it as if it were at the final depth of the tree). Expand will expand any such pruned leaves back to their full form so you can iterate over all of them with the iterator below.
</blockquote></details>

Done.
___
*[src/amcl/map/octomap_cspace.cpp, line 101 at r7](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M26QysL9lGcCKKgXkLn:-M3gA7l-C3XJs3JFuqF_:b-896fix) ([raw file](https://github.com/badgertechnologies/amcl/blob/74db8df1672f2baaecdf854cea1efd100f551c8b/src/amcl/map/octomap_cspace.cpp#L101)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

I don't think you want to do anything on a non-occupied cell (free space). Note that our maps won't have any free space (we don't bother saving it, as it would take a lot of memory). I think you can just delete the else case.
</blockquote></details>

Done.
___
*[src/amcl/map/octomap_cspace.cpp, line 147 at r7](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M26UCEz0v01gQC2lq-m:-M3gw3Ml4y3_l0-p4Qyz:b-hnanzs) ([raw file](https://github.com/badgertechnologies/amcl/blob/74db8df1672f2baaecdf854cea1efd100f551c8b/src/amcl/map/octomap_cspace.cpp#L147)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

Ah, I understand now. Marked is a new tree you are using to tell where you have been. However, this doesn't correctly handle certain cases where we can get to cells from multiple obstacles, unless we are for sure doing a breadth-first-search (which maybe we are). At any rate, if we do need to maintain this information independent of the hash map, change the data structure you are using from an octomap to a hash map. Or, if you can just use the main distance hash map for both functions, just do that.
</blockquote></details>

The purpose of using a priority queue is to achieve a breadth first search.


<!-- Sent from Reviewable.io -->

2020-03-30 19:35 UTC, 12tbuchman reviewed
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/amcl/2)* status: 15 of 51 files reviewed, 193 unresolved discussions (waiting on @12tbuchman and @c-andy-martin)

___
*[src/amcl/map/octomap_cspace.cpp, line 142 at r7](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M26TXkc8bim3ciLTS_f:-M3gwBonC4phML9AMbT1:byrq2m7) ([raw file](https://github.com/badgertechnologies/amcl/blob/74db8df1672f2baaecdf854cea1efd100f551c8b/src/amcl/map/octomap_cspace.cpp#L142)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

your i,jk that you get from convertWorldToMap do not match the indexes used in keys (which are centered around the 'tree_max_val', not around 0). As I state below, I don't think you need to create an OcTreeKey here anyway, but should just examine the hash map (you seed the hash map w/ the values from the tree at the beginning of the algorithm, and finding the state in the hash map will be much faster than the octree).
</blockquote></details>

see below
___
*[src/amcl/map/octomap_cspace.cpp, line 143 at r7](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M26RnJC4CujJJocLtoG:-M3gwD9FBazt_EDclP1K:byrq2m7) ([raw file](https://github.com/badgertechnologies/amcl/blob/74db8df1672f2baaecdf854cea1efd100f551c8b/src/amcl/map/octomap_cspace.cpp#L143)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

you shouldn't need to search the octomap anywhere. You should be looking at the hash map to know the current state (if you have looped back on yourself). searching the octomap here is way more inefficient than using the hash map as well. you will speed up a lot I think using the hash map to check.
</blockquote></details>

see below


<!-- Sent from Reviewable.io -->

2020-03-30 20:10 UTC, 12tbuchman reviewed
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/amcl/2)* status: 15 of 51 files reviewed, 193 unresolved discussions (waiting on @12tbuchman and @c-andy-martin)

___
*[src/amcl/map/octomap_cspace.cpp, line 181 at r7](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M26SHtV1qb9Wxvos-nM:-M3h2okH9tLgrrydcnS5:bucmqlv) ([raw file](https://github.com/badgertechnologies/amcl/blob/74db8df1672f2baaecdf854cea1efd100f551c8b/src/amcl/map/octomap_cspace.cpp#L181)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

I don't see any logic anywhere (yet, i may be missing it) that will prevent you from assigning a further distance here than one you already had in the assign case. You will only want to assign lower distances (in fact, you'd rather prune and never even add such things to the queue, but they may have already been in there from past adds).
</blockquote></details>

In the updateNode function, we only enter the if statement if the node is null or not occupied. If the node is occupied that means it has already been reached, and since we use a priority queue, it already has the minimum distance. I will update the marked variable to be a tsl::sparse_map instead of an OcTree.


<!-- Sent from Reviewable.io -->

2020-03-30 21:43 UTC, 12tbuchman reviewed
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/amcl/2)* status: 15 of 51 files reviewed, 193 unresolved discussions (waiting on @12tbuchman and @c-andy-martin)

___
*[src/amcl/map/octomap_cspace.cpp, line 181 at r7](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M26SHtV1qb9Wxvos-nM:-M3hOXYS5xJoeQImbk4r:b-4b2jpp) ([raw file](https://github.com/badgertechnologies/amcl/blob/74db8df1672f2baaecdf854cea1efd100f551c8b/src/amcl/map/octomap_cspace.cpp#L181)):*
<details><summary><i>Previously, 12tbuchman (Tyler Buchman) wrote…</i></summary><blockquote>

In the updateNode function, we only enter the if statement if the node is null or not occupied. If the node is occupied that means it has already been reached, and since we use a priority queue, it already has the minimum distance. I will update the marked variable to be a tsl::sparse_map instead of an OcTree.
</blockquote></details>

This is done.


<!-- Sent from Reviewable.io -->

2020-03-30 21:44 UTC, 12tbuchman reviewed
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/amcl/2)* status: 15 of 51 files reviewed, 193 unresolved discussions (waiting on @12tbuchman and @c-andy-martin)

___
*[src/amcl/node/node.cpp, line 39 at r7](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M2FPAaj1KMZOlJAEK9z:-M3hOeSi4pu1QxC324qB:b-mrn9) ([raw file](https://github.com/badgertechnologies/amcl/blob/74db8df1672f2baaecdf854cea1efd100f551c8b/src/amcl/node/node.cpp#L39)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

standard includes go after the "node.h", then 3rd parties. Also, I always put 3rd party libraries ahead of any badger libraries. Then finally after all that, the local files (which are in the correct spot already at the end)
</blockquote></details>

see previous comments


<!-- Sent from Reviewable.io -->

2020-04-01 01:17 UTC, 12tbuchman reviewed
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/amcl/2)* status: 15 of 51 files reviewed, 193 unresolved discussions (waiting on @12tbuchman and @c-andy-martin)

___
*[src/amcl/node/node.cpp, line 58 at r7](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M2FPTmw1EeM8Q4zg4hb:-M3nIU672tqqw5HVlbAR:b-896fix) ([raw file](https://github.com/badgertechnologies/amcl/blob/74db8df1672f2baaecdf854cea1efd100f551c8b/src/amcl/node/node.cpp#L58)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

as pointed out elsewhere, I want this to be an enum in the .cfg file and use the enum names the auto-generated code makes for us
</blockquote></details>

Done.
___
*[src/amcl/node/node.cpp, line 117 at r7](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M2ZgEUlBnNgcMFALR9j:-M3nItil2u6anBNOVpRw:b4yy8lb) ([raw file](https://github.com/badgertechnologies/amcl/blob/74db8df1672f2baaecdf854cea1efd100f551c8b/src/amcl/node/node.cpp#L117)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

I greatly prefer to avoid c_str() whenever possible. Here I would do:
```
ROS_WARN_STREAM("Unknown resample model type " << tmp_model_type << "; defaulting to multinomial model");
```
</blockquote></details>

Whats the reason this is significantly better than using a c_str?


<!-- Sent from Reviewable.io -->

2020-04-01 01:31 UTC, 12tbuchman reviewed
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/amcl/2)* status: 15 of 51 files reviewed, 193 unresolved discussions (waiting on @12tbuchman and @c-andy-martin)

___
*[src/amcl/node/node.cpp, line 265 at r7](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M2FQAKp8yFGEH0YpssM:-M3nKq3o1zKYLtDTd_C5:b-896fix) ([raw file](https://github.com/badgertechnologies/amcl/blob/74db8df1672f2baaecdf854cea1efd100f551c8b/src/amcl/node/node.cpp#L265)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

we should use the names for these that were defined elsewhere (whatever you make them, like COVARIANCE_XX)
</blockquote></details>

Done.
___
*[src/amcl/node/node.cpp, line 373 at r7](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M2FROBQ35B2rvOyQUMn:-M3nLBeH-H5yvokAcE8Y:b-896fix) ([raw file](https://github.com/badgertechnologies/amcl/blob/74db8df1672f2baaecdf854cea1efd100f551c8b/src/amcl/node/node.cpp#L373)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

this could be COVARIANCE_AA
</blockquote></details>

Done.
___
*[src/amcl/node/node.cpp, line 834 at r7](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M2Zjf9z09R-Y2sneiLk:-M3nMOC49g8XXZ1vvTKz:b-rywu4a) ([raw file](https://github.com/badgertechnologies/amcl/blob/74db8df1672f2baaecdf854cea1efd100f551c8b/src/amcl/node/node.cpp#L834)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

as pointed out elsewhere, we should switch to the angles package
</blockquote></details>

This is already a TODO


<!-- Sent from Reviewable.io -->

2020-04-01 01:33 UTC, 12tbuchman reviewed
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/amcl/2)* status: 15 of 51 files reviewed, 193 unresolved discussions (waiting on @12tbuchman and @c-andy-martin)

___
*[src/amcl/node/node.cpp, line 727 at r7](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M2FS3ncA8K2V1_iNtk6:-M3nMYC0BAyeBzJevO72:b-qtawld) ([raw file](https://github.com/badgertechnologies/amcl/blob/74db8df1672f2baaecdf854cea1efd100f551c8b/src/amcl/node/node.cpp#L727)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

This function belong in badger_lib somewhere, not in amcl. Lets move it there (or use it if it already exists)
</blockquote></details>

Im not understanding why this wouldnt be in AMCL. We are initializing many key parts of the algorithm in this function.


<!-- Sent from Reviewable.io -->

2020-04-01 01:34 UTC, 12tbuchman reviewed
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/amcl/2)* status: 15 of 51 files reviewed, 193 unresolved discussions (waiting on @12tbuchman and @c-andy-martin)

___
*[src/amcl/node/node.cpp, line 881 at r7](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M2ZjuLv4FvhkCwZt1Rv:-M3nMp3jC21gjc0uN4J5:b17s5v8) ([raw file](https://github.com/badgertechnologies/amcl/blob/74db8df1672f2baaecdf854cea1efd100f551c8b/src/amcl/node/node.cpp#L881)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

seems like there should be a loop here to retry if we draw a non-free space pose. the loop must have some limit so we don't wait forever trying to get one.
</blockquote></details>

free_space_indices only stores points that are free space


<!-- Sent from Reviewable.io -->

2020-04-01 01:36 UTC, 12tbuchman reviewed
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/amcl/2)* status: 15 of 51 files reviewed, 193 unresolved discussions (waiting on @12tbuchman and @c-andy-martin)

___
*[src/amcl/node/node.cpp, line 1055 at r7](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M2ZkXyZ4Ar5OXI2gnof:-M3nNH558GBmPWkhpd33:b-896fix) ([raw file](https://github.com/badgertechnologies/amcl/blob/74db8df1672f2baaecdf854cea1efd100f551c8b/src/amcl/node/node.cpp#L1055)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

this comment needs tweaking, we aren't in the planar scanner code
</blockquote></details>

Done.
___
*[src/amcl/node/node.cpp, line 1122 at r7](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M2ZksxV-SE6pZamVrww:-M3nNI5K5RVNCVVWouH1:bhd9rm7) ([raw file](https://github.com/badgertechnologies/amcl/blob/74db8df1672f2baaecdf854cea1efd100f551c8b/src/amcl/node/node.cpp#L1122)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

let's make this a ROS_WARN_STREAM and not use c_str()
</blockquote></details>

see previous discussion.
___
*[src/amcl/node/node.cpp, line 1220 at r7](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M2Zl6yi3gW84OOzX65N:-M3nNMpt4Ut6OKoH2ZiL:b-w4lb6e) ([raw file](https://github.com/badgertechnologies/amcl/blob/74db8df1672f2baaecdf854cea1efd100f551c8b/src/amcl/node/node.cpp#L1220)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

we should be using the angles package. we *could* just call that package here and below instead of having to clean up every call to this function and the function below.
</blockquote></details>

Theres a TODO for this.


<!-- Sent from Reviewable.io -->

2020-04-01 01:56 UTC, 12tbuchman reviewed
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/amcl/2)* status: 15 of 51 files reviewed, 193 unresolved discussions (waiting on @12tbuchman and @c-andy-martin)

___
*[src/amcl/node/node.cpp, line 649 at r7](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M2ZivBr97feK6_Mz8jL:-M3nRcU4Ebmj6SopRg2T:b-1v9nms) ([raw file](https://github.com/badgertechnologies/amcl/blob/74db8df1672f2baaecdf854cea1efd100f551c8b/src/amcl/node/node.cpp#L649)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

don't you need the tf_mutex_ held for the below line? Also, I didn't analyze the order you are grabbing the other locks, you might want to only hold the tf_mutex_ while you need it to get the map_pose.
</blockquote></details>

Im currently using the mutex anytime I access latest_tf_ or latest_tf_valid_. If I only use it in this place, wouldn't it be trivial? I have added the mutex to the general save_pose function which is the sole function that calls this function, so this should now be covered.


<!-- Sent from Reviewable.io -->

2020-04-01 02:06 UTC, 12tbuchman reviewed
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/amcl/2)* status: 15 of 51 files reviewed, 193 unresolved discussions (waiting on @12tbuchman and @c-andy-martin)

___
*[src/amcl/node/node.cpp, line 567 at r7](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M2Zi8xQ6EuPZVtJOo8_:-M3nTz3B-41fu7CqBZrU:byyvcio) ([raw file](https://github.com/badgertechnologies/amcl/blob/74db8df1672f2baaecdf854cea1efd100f551c8b/src/amcl/node/node.cpp#L567)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

this can be `ROS_WARN_STREAM("exception: " << e.what());`
also, we should print more than just 'exception' I think, describe where you are:
`ROS_WARN_STREAM("Exception in loadPoseFromFile: " << e.what());`
Last, this should probably be ROS_INFO actually
</blockquote></details>

I know ive asked this before but this is slightly different, what is the benefit of ROS_WARN_STREAM over ROS_WARN? I like putting exceptions in ROS_WARN unless you have a reason not to. i will combine this with the debug below to give context.
___
*[src/amcl/node/node.cpp, line 568 at r7](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M2ZiOmo43MXTjORF0Du:-M3nUK5REt6KKY378oUv:b-896fix) ([raw file](https://github.com/badgertechnologies/amcl/blob/74db8df1672f2baaecdf854cea1efd100f551c8b/src/amcl/node/node.cpp#L568)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

Doesn't seem like this should be DEBUG probably should be ROS_WARN
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-04-01 02:17 UTC, 12tbuchman reviewed
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/amcl/2)* status: 15 of 51 files reviewed, 193 unresolved discussions (waiting on @12tbuchman and @c-andy-martin)

___
*[src/amcl/node/node.cpp, line 170 at r7](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M2ZgkBr3MLm9gJDlwTY:-M3nWjh908QD2MRhPE8J:bg9tqgg) ([raw file](https://github.com/badgertechnologies/amcl/blob/74db8df1672f2baaecdf854cea1efd100f551c8b/src/amcl/node/node.cpp#L170)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

you might want to have the dynamic reconfigure happen before you have subscribed for other callbacks. that way the first call will have already happened (although you may need to make the other changes I suggested around dynamic reconfigure first, such as not duplicating work between static/dynamic, see my other comments).
</blockquote></details>

see comment below.
___
*[src/amcl/node/node.cpp, line 198 at r7](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M2FQPRL1lubOJj3i5bp:-M3nWdbX0d9u-QdUvUZI:b-82qmal) ([raw file](https://github.com/badgertechnologies/amcl/blob/74db8df1672f2baaecdf854cea1efd100f551c8b/src/amcl/node/node.cpp#L198)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

I feel like there is a lot of duplicated work here and in the constructor. In general, I think it is better to not even look at the static parameters for things that are dynamic, and on every call (including the first call) set the internal variables from the dynamic parameters. The dynamic reconfigure code already set the dynamic parameters to whatever was in the static parameter. What you can do to the locking is: first instantiate the dynamic reconfigure, then grab the lock (so after the first call), then subscribe to topics and make timers while holding the lock. This way you know everything is configured, there are no races, and you don't have to duplicate any work anywhere.
</blockquote></details>

If we are going to do that Id like to talk about which parameters should be static and which should be dynamic.


<!-- Sent from Reviewable.io -->

2020-04-01 03:02 UTC, 12tbuchman reviewed
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/amcl/2)* status: 15 of 51 files reviewed, 193 unresolved discussions (waiting on @12tbuchman and @c-andy-martin)

___
*[src/amcl/node/node_2d.cpp, line 354 at r5](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M1ggCBj-AplorV4UGk2:-M3ng6eo5D1q78HoM4wt:b-896fix) ([raw file](https://github.com/badgertechnologies/amcl/blob/95b6eb20da05f9f418bc7ea0645e69d04bc7dd99/src/amcl/node/node_2d.cpp#L354)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

there is an extra WS at the end of this line
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-04-01 03:02 UTC, 12tbuchman reviewed
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/amcl/2)* status: 15 of 51 files reviewed, 193 unresolved discussions (waiting on @12tbuchman and @c-andy-martin)

___
*[src/amcl/node/node_2d.cpp, line 458 at r7](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M2ZlfF84guTs211_rnt:-M3ng7ed-nv8IJWltLLa:b-em24ba) ([raw file](https://github.com/badgertechnologies/amcl/blob/74db8df1672f2baaecdf854cea1efd100f551c8b/src/amcl/node/node_2d.cpp#L458)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

let's clean up these c_str() and use ROS_ERROR_STREAM
</blockquote></details>

see previous comments on this


<!-- Sent from Reviewable.io -->

2020-04-01 03:02 UTC, 12tbuchman reviewed
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/amcl/2)* status: 15 of 51 files reviewed, 193 unresolved discussions (waiting on @12tbuchman and @c-andy-martin)

___
*[src/amcl/node/node_2d.cpp, line 512 at r7](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M2ZlkihDAYdw49Hsen2:-M3ngAU72ol4MpBU0uub:bddik1n) ([raw file](https://github.com/badgertechnologies/amcl/blob/74db8df1672f2baaecdf854cea1efd100f551c8b/src/amcl/node/node_2d.cpp#L512)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

this should be a call to angles normalize right?
</blockquote></details>

there is a TODO for this


<!-- Sent from Reviewable.io -->

2020-04-01 03:03 UTC, 12tbuchman reviewed
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/amcl/2)* status: 15 of 51 files reviewed, 193 unresolved discussions (waiting on @12tbuchman and @c-andy-martin)

___
*[src/amcl/node/node_2d.cpp, line 637 at r7](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M2ZluSe0LFo4ape_YhQ:-M3ngFgVEoTdfItl4Gjr:b-mrn9) ([raw file](https://github.com/badgertechnologies/amcl/blob/74db8df1672f2baaecdf854cea1efd100f551c8b/src/amcl/node/node_2d.cpp#L637)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

let's clean up this c_str() and use ROS_WARN_STREAM
</blockquote></details>

see previous comments


<!-- Sent from Reviewable.io -->

2020-04-01 03:03 UTC, 12tbuchman reviewed
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/amcl/2)* status: 15 of 51 files reviewed, 193 unresolved discussions (waiting on @12tbuchman and @c-andy-martin)

___
*[src/amcl/node/node_3d.cpp, line 99 at r7](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M2Zm2kHBlus_VakcNsl:-M3ngJ8x4I2SVYm7EH7o:b-mrn9) ([raw file](https://github.com/badgertechnologies/amcl/blob/74db8df1672f2baaecdf854cea1efd100f551c8b/src/amcl/node/node_3d.cpp#L99)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

let's use ROS_WARN_STREAM and get rid of the `c_str()`
</blockquote></details>

see previous comments


<!-- Sent from Reviewable.io -->

2020-04-01 03:04 UTC, 12tbuchman reviewed
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/amcl/2)* status: 15 of 51 files reviewed, 193 unresolved discussions (waiting on @12tbuchman and @c-andy-martin)

___
*[src/amcl/node/node_3d.cpp, line 603 at r7](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M2ZoqERBf2hfweQGYBw:-M3ngTXR5_MHjp854feK:b-7udcw1) ([raw file](https://github.com/badgertechnologies/amcl/blob/74db8df1672f2baaecdf854cea1efd100f551c8b/src/amcl/node/node_3d.cpp#L603)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

the white space doesn't line up well here, seems like this should be lined up near the `(`?
</blockquote></details>

maybe this changed since you wrote your comment, but if not im not really understanding what you would like


<!-- Sent from Reviewable.io -->

2020-04-01 03:04 UTC, 12tbuchman reviewed
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/amcl/2)* status: 15 of 51 files reviewed, 193 unresolved discussions (waiting on @12tbuchman and @c-andy-martin)

___
*[src/amcl/node/node_3d.cpp, line 596 at r7](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M2Zom5J2vk7jte7NYge:-M3ng_wV9Xytgq5tS7IC:bhd9ro4) ([raw file](https://github.com/badgertechnologies/amcl/blob/74db8df1672f2baaecdf854cea1efd100f551c8b/src/amcl/node/node_3d.cpp#L596)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

let's clean this up to be ROS_DEBUG_STREAM and not use c_str()
</blockquote></details>

see previous discussions


<!-- Sent from Reviewable.io -->

2020-04-01 03:04 UTC, 12tbuchman reviewed
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/amcl/2)* status: 15 of 51 files reviewed, 193 unresolved discussions (waiting on @12tbuchman and @c-andy-martin)

___
*[src/amcl/node/node_3d.cpp, line 453 at r7](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M2ZoNOE4gOxfWAPqrAN:-M3ngeL22fhlxUHDTGp9:bhd9ro4) ([raw file](https://github.com/badgertechnologies/amcl/blob/74db8df1672f2baaecdf854cea1efd100f551c8b/src/amcl/node/node_3d.cpp#L453)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

let's get rid of the c_str() and use ROS_ERROR_STREAM
</blockquote></details>

see previous discussions


<!-- Sent from Reviewable.io -->

2020-04-01 18:16 UTC, 12tbuchman reviewed
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/amcl/2)* status: 15 of 51 files reviewed, 193 unresolved discussions (waiting on @12tbuchman and @c-andy-martin)

___
*[src/amcl/node/node_3d.cpp, line 466 at r6](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M245-GH3z_IX8wEw5Up:-M3nmNI_8JvM1sZRk8d6:b-896fix) ([raw file](https://github.com/badgertechnologies/amcl/blob/9df029774580bad51987f61b64a87071070f819b/src/amcl/node/node_3d.cpp#L466)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

the scanner pose isn't used anywhere (not even in the scanner itself), I would delete it (and any associated functions/methods you no longer need).
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-04-06 20:55 UTC, 12tbuchman reviewed
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/amcl/2)* status: 15 of 51 files reviewed, 193 unresolved discussions (waiting on @12tbuchman and @c-andy-martin)

___
*[src/amcl/node/node_3d.cpp, line 281 at r7](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M2ZnLv-9Pq9-NlHPiJe:-M4GGaHj9_iSs2N5orF-:b-896fix) ([raw file](https://github.com/badgertechnologies/amcl/blob/74db8df1672f2baaecdf854cea1efd100f551c8b/src/amcl/node/node_3d.cpp#L281)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

it might be more maintainable to initialize this to `nullptr` in case in the future there is more complex logic below where we set `absoctree` (right now, there is no path it would stay uninitialized, but for stack variables, it is often a good idea to initialize them since they are not initialized automatically).
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-04-06 22:06 UTC, 12tbuchman reviewed
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/amcl/2)* status: 15 of 51 files reviewed, 193 unresolved discussions (waiting on @12tbuchman and @c-andy-martin)

___
*[src/amcl/node/node_3d.cpp, line 119 at r6](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M243RWv63W6vQ-cPhbf:-M4GWxyd0uILJ-gdbHfN:b-896fix) ([raw file](https://github.com/badgertechnologies/amcl/blob/9df029774580bad51987f61b64a87071070f819b/src/amcl/node/node_3d.cpp#L119)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

a few things:
1) Do not hard-code frame IDs
2) We don't know the frame of the sensor data until we get it.
3) The TF from the sensor data to the footprint can change at any time (what if we recalibrate for instance)
So, given these, I propose you move updating the scanner_to_footprint_tf_ into the point cloud callback (the scanReceived method). That method can lookup the transform without waiting, since its inside a TF message filter (it should do this for every point cloud received, using the timestamp in the sensor data, the frame for the cloud might not be fixed relative to the base footprint). Then, it can immediately set the transform in the point_cloud_scanner by calling setPointCloudScannerToFootprintTF for each callback received prior to updating the sensor. Also, it should track the frame_id/timestamp from the received point cloud to the `base_frame_id_`. This proposal would remove the few lines here around TF lookup and and just add the lookupTransform (which shouldn't fail, but you can still catch exceptions just in case) in the scanReceived callback chain somewhere prior to updating the scanner. (Also, I don't think there is any need to store the scanner_to_footprint_tf_ here, just do it in the point cloud scanner class).
</blockquote></details>

Done.
___
*[src/amcl/node/node_3d.cpp, line 467 at r6](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M2452XN4fz0L__53_yx:-M4GWzEg545QE-UlnZKJ:b-896fix) ([raw file](https://github.com/badgertechnologies/amcl/blob/9df029774580bad51987f61b64a87071070f819b/src/amcl/node/node_3d.cpp#L467)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

you should be looking up the current TF before setting it (see my comment above at the lookupTransform call)
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-04-06 22:09 UTC, 12tbuchman reviewed
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/amcl/2)* status: 15 of 51 files reviewed, 193 unresolved discussions (waiting on @12tbuchman and @c-andy-martin)

___
*[src/amcl/node/node_3d.cpp, line 332 at r7](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M2FSrlIBtDhVJJM-mY1:-M4GXBge096UkN4BCXBO:bjvcqql) ([raw file](https://github.com/badgertechnologies/amcl/blob/74db8df1672f2baaecdf854cea1efd100f551c8b/src/amcl/node/node_3d.cpp#L332)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

Actually, an even better idea is to use the *2D* map for free space indices. In other words, do the same thing as the 2D node for free space indices. This way, the noise on the 3D map won't matter (as it gets cleaned up for the 2D nav map). And you won't have to worry about robot height.
</blockquote></details>

The reason I am adding all cells to the free space list is exactly that, there are too many false-positive objects on the 3d map. Currently we only use the 2d map if we are specified to do so in the parameters. What I can do is update the free space indices with the 2d map if we are specified to get a 2d map and when that 2d map arrives. If we are not expected to get the 2d map or if it hasnt arrived yet, we use this list which of all cells.


<!-- Sent from Reviewable.io -->

2020-04-06 22:25 UTC, 12tbuchman reviewed
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/amcl/2)* status: 15 of 51 files reviewed, 193 unresolved discussions (waiting on @12tbuchman and @c-andy-martin)

___
*[src/amcl/node/node_3d.cpp, line 332 at r7](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M2FSrlIBtDhVJJM-mY1:-M4G_mgyBQJTftDFN7ox:b4fgjy3) ([raw file](https://github.com/badgertechnologies/amcl/blob/74db8df1672f2baaecdf854cea1efd100f551c8b/src/amcl/node/node_3d.cpp#L332)):*
<details><summary><i>Previously, 12tbuchman (Tyler Buchman) wrote…</i></summary><blockquote>

The reason I am adding all cells to the free space list is exactly that, there are too many false-positive objects on the 3d map. Currently we only use the 2d map if we are specified to do so in the parameters. What I can do is update the free space indices with the 2d map if we are specified to get a 2d map and when that 2d map arrives. If we are not expected to get the 2d map or if it hasnt arrived yet, we use this list which of all cells.
</blockquote></details>

So having looked more into this, I will correct myself that we already wait for the Occupancy Map to arrive before setting the free space indices. However, to use the Occupancy Map means we need to fully initialize that map, which currently we don't do. Do you think it is worth initializing the 2D map to be able to reduce the free space indices here? My reasoning for saying maybe not is that I would think we will be cleaning the 3D maps like we do the 2D maps, and then we can improve this section to use only free spaces. However maybe my assumption is not true. Even if my assumption isnt true, the question remains if it is worth it to initialize the 2D map.


<!-- Sent from Reviewable.io -->

2020-04-07 15:09 UTC, 12tbuchman reviewed
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/amcl/2)* status: 15 of 51 files reviewed, 193 unresolved discussions (waiting on @12tbuchman and @c-andy-martin)

___
*[src/amcl/pf/eig3.cpp, line 18 at r5](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M1kga-f8duCAuJwDIr2:-M4KB7kN2cfUcJZok3j_:b-896fix) ([raw file](https://github.com/badgertechnologies/amcl/blob/95b6eb20da05f9f418bc7ea0645e69d04bc7dd99/src/amcl/pf/eig3.cpp#L18)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

Delete this and instead use `std::hypot` from `<cmath>`
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-04-07 15:11 UTC, 12tbuchman reviewed
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/amcl/2)* status: 15 of 51 files reviewed, 193 unresolved discussions (waiting on @12tbuchman and @c-andy-martin)

___
*[src/amcl/pf/particle_filter.cpp, line 28 at r7](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M2AOpTT02Es_O4yr6EE:-M4KBF8A0orzAIj9SiGS:b-896fix) ([raw file](https://github.com/badgertechnologies/amcl/blob/74db8df1672f2baaecdf854cea1efd100f551c8b/src/amcl/pf/particle_filter.cpp#L28)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

cmath
</blockquote></details>

Done.
___
*[src/amcl/pf/particle_filter.cpp, line 29 at r7](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M2AOrX524ExJYw3bKpS:-M4KBG4BEhPFcFrSewD9:bhd9ro4) ([raw file](https://github.com/badgertechnologies/amcl/blob/74db8df1672f2baaecdf854cea1efd100f551c8b/src/amcl/pf/particle_filter.cpp#L29)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

ros includes should come last, with third party, standard includes before them
</blockquote></details>

see previous discussions
___
*[src/amcl/pf/particle_filter.cpp, line 31 at r7](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M2AP-Ca4BioWvHBvscI:-M4KBN_25n2B-cecyazl:b-896fix) ([raw file](https://github.com/badgertechnologies/amcl/blob/74db8df1672f2baaecdf854cea1efd100f551c8b/src/amcl/pf/particle_filter.cpp#L31)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

lets switch to cstddef
</blockquote></details>

Done.
___
*[src/amcl/pf/particle_filter.cpp, line 32 at r7](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M2AOwVw9SkM1FYJK_WQ:-M4KBMjs0gsUlOvq3W7s:b-896fix) ([raw file](https://github.com/badgertechnologies/amcl/blob/74db8df1672f2baaecdf854cea1efd100f551c8b/src/amcl/pf/particle_filter.cpp#L32)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

let's not  include both stdlib.h and cstdlib
</blockquote></details>

Done.
___
*[src/amcl/pf/particle_filter.cpp, line 40 at r7](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M2APHlCCetoq11Y0B_g:-M4KBPGf4HbgpuTMfy9j:b-896fix) ([raw file](https://github.com/badgertechnologies/amcl/blob/74db8df1672f2baaecdf854cea1efd100f551c8b/src/amcl/pf/particle_filter.cpp#L40)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

I'd prefer to make this `namespace amcl` instead of using
</blockquote></details>

Done.
___
*[src/amcl/pf/particle_filter.cpp, line 44 at r7](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M2FAdir3XzGfJ5aXdW3:-M4KBQEvErtpB9DCcX9h:b-896fix) ([raw file](https://github.com/badgertechnologies/amcl/blob/74db8df1672f2baaecdf854cea1efd100f551c8b/src/amcl/pf/particle_filter.cpp#L44)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

as pointed out elsewhere, let's move to just passing std::function, not wrapping in shared_ptr
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-04-07 15:45 UTC, 12tbuchman reviewed
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/amcl/2)* status: 15 of 51 files reviewed, 193 unresolved discussions (waiting on @12tbuchman and @c-andy-martin)

___
*[src/amcl/pf/particle_filter.cpp, line 50 at r7](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M2FAmVw01fdQe4rT06u:-M4KFjGb4LEis9SQaWNp:b-896fix) ([raw file](https://github.com/badgertechnologies/amcl/blob/74db8df1672f2baaecdf854cea1efd100f551c8b/src/amcl/pf/particle_filter.cpp#L50)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

this does not belong here, but in `main()`. What if we wanted to create/destroy ParticleFilter's at some point? We don't want to be re-seeding the generator all the time. Calling srand48 affects all threads in the process, so that's why it should be in main. Move the headers we needed for `time()` to main as well.
</blockquote></details>

Done.
___
*[src/amcl/pf/particle_filter.cpp, line 248 at r7](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M2FE9koEX98dtV_aZtj:-M4KIIvf1Y-1CSy1F399:b-896fix) ([raw file](https://github.com/badgertechnologies/amcl/blob/74db8df1672f2baaecdf854cea1efd100f551c8b/src/amcl/pf/particle_filter.cpp#L248)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

Let's change "(Prob Rob p258)" to "(from Probabilistic Robotics 'Augmented_MCL' algorithm)"
</blockquote></details>

Done.
___
*[src/amcl/pf/particle_filter.cpp, line 283 at r7](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M2FGfpW4sYZgPmD2iQN:-M4KIdWhENHVfatpR45f:b-896fix) ([raw file](https://github.com/badgertechnologies/amcl/blob/74db8df1672f2baaecdf854cea1efd100f551c8b/src/amcl/pf/particle_filter.cpp#L283)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

It would be more efficient to not declare the vector until here (so move the declaration above here) and construct it w/ the right size right away:
```
std::vector<double> c(set_a->sample_count + 1);
```
</blockquote></details>

Done.
___
*[src/amcl/pf/particle_filter.cpp, line 387 at r7](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M2FLUuu5PqfKKJKM4qv:-M4KIr_P4nqzr4sn0ECX:b-896fix) ([raw file](https://github.com/badgertechnologies/amcl/blob/74db8df1672f2baaecdf854cea1efd100f551c8b/src/amcl/pf/particle_filter.cpp#L387)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

Let's add curly braces here, I don't like having an if w/out braces paired w/ an else that does have braces
</blockquote></details>

Done.
___
*[src/amcl/pf/particle_filter.cpp, line 580 at r7](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M2FM0Eo4bWJOo6pi8nQ:-M4KJPDQ0fe7RTmiV-wH:b-896fix) ([raw file](https://github.com/badgertechnologies/amcl/blob/74db8df1672f2baaecdf854cea1efd100f551c8b/src/amcl/pf/particle_filter.cpp#L580)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

Let's add a brace here. I don't like having the inner for w/ a brace but not the outer for
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-04-07 15:47 UTC, 12tbuchman reviewed
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/amcl/2)* status: 15 of 51 files reviewed, 193 unresolved discussions (waiting on @12tbuchman and @c-andy-martin)

___
*[src/amcl/pf/pdf_gaussian.cpp, line 32 at r7](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M26P5eMD223Y7VqF_ax:-M4KJXKo3VBmLNoKEy1p:b-8ysqpq) ([raw file](https://github.com/badgertechnologies/amcl/blob/74db8df1672f2baaecdf854cea1efd100f551c8b/src/amcl/pf/pdf_gaussian.cpp#L32)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

huh? I don't see any relevant code nearby this comment. delete it
</blockquote></details>

I think this was already deleted
___
*[src/amcl/pf/pdf_gaussian.cpp, line 34 at r7](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M26PBZbAJO9fK0juyG_:-M4KJZL014JVnoZpab7z:b-896fix) ([raw file](https://github.com/badgertechnologies/amcl/blob/74db8df1672f2baaecdf854cea1efd100f551c8b/src/amcl/pf/pdf_gaussian.cpp#L34)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

I'd rather put the code in the amcl namespace than add a using
</blockquote></details>

Done.
___
*[src/amcl/pf/pdf_gaussian.cpp, line 37 at r7](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M26PFwoAIyStcM4JK66:-M4KJc968SN8hgSmfYqj:b-896fix) ([raw file](https://github.com/badgertechnologies/amcl/blob/74db8df1672f2baaecdf854cea1efd100f551c8b/src/amcl/pf/pdf_gaussian.cpp#L37)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

This comment adds little value, I'd remove it
</blockquote></details>

Done.
___
*[src/amcl/pf/pdf_gaussian.cpp, line 40 at r7](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M26PIoL3qdDvCp0dkYr:-M4KJfiX3s2-IdGzoV9l:b-896fix) ([raw file](https://github.com/badgertechnologies/amcl/blob/74db8df1672f2baaecdf854cea1efd100f551c8b/src/amcl/pf/pdf_gaussian.cpp#L40)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

And this one too, pls remove
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-04-07 15:53 UTC, 12tbuchman reviewed
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/amcl/2)* status: 15 of 51 files reviewed, 193 unresolved discussions (waiting on @12tbuchman and @c-andy-martin)

___
*[src/amcl/pf/pf_kdtree.cpp, line 28 at r7](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M25EUAODSTS-RGU2OIx:-M4KJuzp40_7wz0_TaYW:b-896fix) ([raw file](https://github.com/badgertechnologies/amcl/blob/74db8df1672f2baaecdf854cea1efd100f551c8b/src/amcl/pf/pf_kdtree.cpp#L28)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

I'd love to move this to cmath and cstdlib
</blockquote></details>

Done.
___
*[src/amcl/pf/pf_kdtree.cpp, line 29 at r7](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M25ESpJ6j684WHThd2h:-M4KJvyh-QrCw7BoiS7P:b-mrn9) ([raw file](https://github.com/badgertechnologies/amcl/blob/74db8df1672f2baaecdf854cea1efd100f551c8b/src/amcl/pf/pf_kdtree.cpp#L29)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

ros headers come last
</blockquote></details>

see previous comments
___
*[src/amcl/pf/pf_kdtree.cpp, line 35 at r7](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M25EOFc9j1Wd-Sir6td:-M4KK3oFAOiNUZSD4Lvu:b-896fix) ([raw file](https://github.com/badgertechnologies/amcl/blob/74db8df1672f2baaecdf854cea1efd100f551c8b/src/amcl/pf/pf_kdtree.cpp#L35)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

I would rather put this in amcl than use using
</blockquote></details>

Done.
___
*[src/amcl/pf/pf_kdtree.cpp, line 37 at r7](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M25EKA11jZ-Wwf8VyRX:-M4KK8rbCbPuD0C1fs3P:b-896fix) ([raw file](https://github.com/badgertechnologies/amcl/blob/74db8df1672f2baaecdf854cea1efd100f551c8b/src/amcl/pf/pf_kdtree.cpp#L37)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

Remove these two lines of comments
</blockquote></details>

Done.
___
*[src/amcl/pf/pf_kdtree.cpp, line 76 at r7](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M25Gbtl8veYWjGHMqLW:-M4KKiiYE3TW0iKyX1Ql:b-896fix) ([raw file](https://github.com/badgertechnologies/amcl/blob/74db8df1672f2baaecdf854cea1efd100f551c8b/src/amcl/pf/pf_kdtree.cpp#L76)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

if you switch to cmath, this will need to be std::floor
</blockquote></details>

Done.
___
*[src/amcl/pf/pf_kdtree.cpp, line 134 at r7](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M25H9rW3Psei2QHLUmj:-M4KLBzT60pEFZn4SmkM:b-896fix) ([raw file](https://github.com/badgertechnologies/amcl/blob/74db8df1672f2baaecdf854cea1efd100f551c8b/src/amcl/pf/pf_kdtree.cpp#L134)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

i'd get rid of this newline
</blockquote></details>

Done.
___
*[src/amcl/pf/pf_kdtree.cpp, line 143 at r7](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M25H8nmA9ovPmw1me9D:-M4KLCUL8JKO1qmHDAFp:b-896fix) ([raw file](https://github.com/badgertechnologies/amcl/blob/74db8df1672f2baaecdf854cea1efd100f551c8b/src/amcl/pf/pf_kdtree.cpp#L143)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

i'd get rid of this newline
</blockquote></details>

Done.
___
*[src/amcl/pf/pf_kdtree.cpp, line 179 at r7](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M25H6Yz0FYXYUfHUhsE:-M4KLCxG4FlzyTnqa_RU:b-896fix) ([raw file](https://github.com/badgertechnologies/amcl/blob/74db8df1672f2baaecdf854cea1efd100f551c8b/src/amcl/pf/pf_kdtree.cpp#L179)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

i'd get rid of this newline
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-04-07 17:35 UTC, 12tbuchman reviewed
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/amcl/2)* status: 15 of 51 files reviewed, 193 unresolved discussions (waiting on @12tbuchman and @c-andy-martin)

___
*[src/amcl/pf/pf_kdtree.cpp, line 49 at r7](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M25G7ud2l0wsCJarOcX:-M4KbVlo1rg-LGegzUR2:b-896fix) ([raw file](https://github.com/badgertechnologies/amcl/blob/74db8df1672f2baaecdf854cea1efd100f551c8b/src/amcl/pf/pf_kdtree.cpp#L49)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

we need to C++ ify this. calloc is from C. Consider making this a `std::vector<PFKDTreeNode>` and making the code work with that, just need to `resize(node_max_count_)`
</blockquote></details>

Done.
___
*[src/amcl/pf/pf_kdtree.cpp, line 54 at r7](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M25GOyQ1g95sd6FM8CC:-M4KbTY2EZ9FAu29zBTb:b-896fix) ([raw file](https://github.com/badgertechnologies/amcl/blob/74db8df1672f2baaecdf854cea1efd100f551c8b/src/amcl/pf/pf_kdtree.cpp#L54)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

I don't care for these comments, I'd get rid of any of them which don't tell you something you already obviously know from the name of the function or context. Also, I'd get rid of those long `//////...` everywhere.
</blockquote></details>

Done.
___
*[src/amcl/pf/pf_kdtree.cpp, line 58 at r7](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M25GN2B3tU1haAxkrDO:-M4KhL7R8VrJpbTWUTL2:b-896fix) ([raw file](https://github.com/badgertechnologies/amcl/blob/74db8df1672f2baaecdf854cea1efd100f551c8b/src/amcl/pf/pf_kdtree.cpp#L58)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

you won't need this if you switch to std::vector
</blockquote></details>

Done.
___
*[src/amcl/pf/pf_kdtree.cpp, line 119 at r7](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M25GkUwA59RbVr_byQ8:-M4KhMnz4Ou_XqtAG1nl:b-896fix) ([raw file](https://github.com/badgertechnologies/amcl/blob/74db8df1672f2baaecdf854cea1efd100f551c8b/src/amcl/pf/pf_kdtree.cpp#L119)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

this would become just an assignment to the default PFKDTreeNode on a std::vector, or you could just resize() the vector as it grows
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-04-07 17:37 UTC, 12tbuchman reviewed
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/amcl/2)* status: 15 of 51 files reviewed, 193 unresolved discussions (waiting on @12tbuchman and @c-andy-martin)

___
*[src/amcl/pf/pf_kdtree.cpp, line 274 at r7](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M25HPqiEIz30kj7Eudf:-M4Ki2xyCVolgHv2jMIr:b-896fix) ([raw file](https://github.com/badgertechnologies/amcl/blob/74db8df1672f2baaecdf854cea1efd100f551c8b/src/amcl/pf/pf_kdtree.cpp#L274)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

I don't like this name, its way too similar to node. Lets make it something different that stands out (maybe found_node and make nkey search_key or something)
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-04-07 17:39 UTC, 12tbuchman reviewed
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/amcl/2)* status: 15 of 51 files reviewed, 193 unresolved discussions (waiting on @12tbuchman and @c-andy-martin)

___
*[src/amcl/pf/pf_vector.cpp, line 28 at r5](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M1kZs6gAtRKGI2POYBm:-M4Ki57Q7Rn7emx-xjCQ:b-896fix) ([raw file](https://github.com/badgertechnologies/amcl/blob/95b6eb20da05f9f418bc7ea0645e69d04bc7dd99/src/amcl/pf/pf_vector.cpp#L28)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

Use `<cmath>`
</blockquote></details>

Done.
___
*[src/amcl/pf/pf_vector.cpp, line 33 at r5](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M1kZZq20MeLI0AhSGkg:-M4Ki5ga8UZyecJtMBfe:b-896fix) ([raw file](https://github.com/badgertechnologies/amcl/blob/95b6eb20da05f9f418bc7ea0645e69d04bc7dd99/src/amcl/pf/pf_vector.cpp#L33)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

I would much prefer putting this in the amcl namespace, not having a using namespace. So this would become:

```
namespace amcl
{
...
```
</blockquote></details>

Done.
___
*[src/amcl/pf/pf_vector.cpp, line 35 at r5](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M1kZymJ0vdXpVe63j8v:-M4KiB2J3lhHd485la0M:b-896fix) ([raw file](https://github.com/badgertechnologies/amcl/blob/95b6eb20da05f9f418bc7ea0645e69d04bc7dd99/src/amcl/pf/pf_vector.cpp#L35)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

Delete this incorrect comment. Constructors do not return anything
</blockquote></details>

Done.
___
*[src/amcl/pf/pf_vector.cpp, line 48 at r5](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M1k_6dI3y5I-smNrJPo:-M4KiC7LEJJlZ12TLTcu:b-896fix) ([raw file](https://github.com/badgertechnologies/amcl/blob/95b6eb20da05f9f418bc7ea0645e69d04bc7dd99/src/amcl/pf/pf_vector.cpp#L48)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

this will become `std::isfinite` when switching to `<cmath>` I think.
</blockquote></details>

Done.
___
*[src/amcl/pf/pf_vector.cpp, line 49 at r5](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M1k_B_A8mGy9YTWccoc:-M4KiGUi17GKbC7pqJRJ:b-896fix) ([raw file](https://github.com/badgertechnologies/amcl/blob/95b6eb20da05f9f418bc7ea0645e69d04bc7dd99/src/amcl/pf/pf_vector.cpp#L49)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

change `0` to `false`
</blockquote></details>

Done.
___
*[src/amcl/pf/pf_vector.cpp, line 50 at r5](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M1k_DVC9ZRamhyouokJ:-M4KiHEN8EGO-GOhbu42:b-896fix) ([raw file](https://github.com/badgertechnologies/amcl/blob/95b6eb20da05f9f418bc7ea0645e69d04bc7dd99/src/amcl/pf/pf_vector.cpp#L50)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

change `1` to `true`
</blockquote></details>

Done.
___
*[src/amcl/pf/pf_vector.cpp, line 54 at r5](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M1k_L5DBOPhs14GZZPY:-M4KiJPL4znbj_mDdi-2:b-385o9b) ([raw file](https://github.com/badgertechnologies/amcl/blob/95b6eb20da05f9f418bc7ea0645e69d04bc7dd99/src/amcl/pf/pf_vector.cpp#L54)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

comment: to make this C++ish would be `operator+`, however, I would much prefer to just delete this whole file and use Eigen vectors. Another reason to make a todo to switch this to Eigen
</blockquote></details>

This is already a TODO. Ill leave this pfVectorAdd for now.
___
*[src/amcl/pf/pf_vector.cpp, line 80 at r5](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M1k_g45CPw0IObUAVSi:-M4KiPXpDvl5yAlpUwHk:b-ujs72o) ([raw file](https://github.com/badgertechnologies/amcl/blob/95b6eb20da05f9f418bc7ea0645e69d04bc7dd99/src/amcl/pf/pf_vector.cpp#L80)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

This is not an efficient way to normalize an angle. I would use `angles::normalize_angle`
</blockquote></details>

This is a TODO.
___
*[src/amcl/pf/pf_vector.cpp, line 91 at r5](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M1kb_Qg8iVXmH5GWWv0:-M4KiRJD83GdRqY2mHvf:bu6xv8r) ([raw file](https://github.com/badgertechnologies/amcl/blob/95b6eb20da05f9f418bc7ea0645e69d04bc7dd99/src/amcl/pf/pf_vector.cpp#L91)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

and here too (and anywhere you spy `atan2(sin(theta), cos(theta))`)
</blockquote></details>

See previous comments


<!-- Sent from Reviewable.io -->

2020-04-07 17:42 UTC, 12tbuchman reviewed
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/amcl/2)* status: 15 of 51 files reviewed, 193 unresolved discussions (waiting on @12tbuchman and @c-andy-martin)

___
*[src/amcl/sensors/amcl_odom.cpp, line 37 at r5](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M1kdWmR1vPh4El7NT0-:-M4Kj4fi-KWrZnYn1GNd:b-896fix) ([raw file](https://github.com/badgertechnologies/amcl/blob/8a8873533e84b3894a5f385b1d56234ebbe31d7e/src/amcl/sensors/amcl_odom.cpp#L37)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

I'd rather put this inside the amcl namespace, not use it.
</blockquote></details>

Done.
___
*[src/amcl/sensors/odom.cpp, line 31 at r5](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M1kdTA8073H0qYLUft2:-M4Kj2_24mTsGbCZKDdJ:b-mrn9) ([raw file](https://github.com/badgertechnologies/amcl/blob/95b6eb20da05f9f418bc7ea0645e69d04bc7dd99/src/amcl/sensors/odom.cpp#L31)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

standard headers should come above `ros/console.h`
</blockquote></details>

see previous comments


<!-- Sent from Reviewable.io -->

2020-04-07 17:43 UTC, 12tbuchman reviewed
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/amcl/2)* status: 15 of 51 files reviewed, 193 unresolved discussions (waiting on @12tbuchman and @c-andy-martin)

___
*[src/amcl/sensors/odom.cpp, line 307 at r5](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M1kdrAM32YRHjqjCFYj:-M4KjMj9DOTQG5eMzKvm:bf03pms) ([raw file](https://github.com/badgertechnologies/amcl/blob/95b6eb20da05f9f418bc7ea0645e69d04bc7dd99/src/amcl/sensors/odom.cpp#L307)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

sorry, that comment is meant to go up on `normalize`, for this one, use the `angles::shortest_angular_distance`
</blockquote></details>

Theres a TODO for this


<!-- Sent from Reviewable.io -->

2020-04-07 17:54 UTC, 12tbuchman reviewed
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/amcl/2)* status: 15 of 51 files reviewed, 193 unresolved discussions (waiting on @12tbuchman and @c-andy-martin)

___
*[src/amcl/sensors/planar_scanner.cpp, line 35 at r6](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M23qlKcEqFjUwYzm49o:-M4KjTXH-9dGaSvjIF6o:b-896fix) ([raw file](https://github.com/badgertechnologies/amcl/blob/9df029774580bad51987f61b64a87071070f819b/src/amcl/sensors/planar_scanner.cpp#L35)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

I prefer putting the below in the amcl namespace over `using namespace amcl`
</blockquote></details>

Done.
___
*[src/amcl/sensors/planar_scanner.cpp, line 41 at r6](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M23rHMx5ukkWVi4k_3m:-M4Kjuf_8cGgN8C6O-0R:b-896fix) ([raw file](https://github.com/badgertechnologies/amcl/blob/9df029774580bad51987f61b64a87071070f819b/src/amcl/sensors/planar_scanner.cpp#L41)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

There is no need for this line, the default shared_ptr constructor will start with the shared ptr correctly initalized to be empty.
</blockquote></details>

Done.
___
*[src/amcl/sensors/planar_scanner.cpp, line 47 at r6](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M23r4uaDihhslUTlHgr:-M4Kk4OfCP3BLrUja9Wr:b-896fix) ([raw file](https://github.com/badgertechnologies/amcl/blob/9df029774580bad51987f61b64a87071070f819b/src/amcl/sensors/planar_scanner.cpp#L47)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

This if condition will never be false, you can remove the if statement. Also, I suggest making the below simply `map_vec_.resize(2)`. It will use the default value (0) when growing the vector.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-04-07 17:59 UTC, 12tbuchman reviewed
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/amcl/2)* status: 15 of 51 files reviewed, 193 unresolved discussions (waiting on @12tbuchman and @c-andy-martin)

___
*[src/amcl/sensors/amcl_laser.cpp, line 441 at r6](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M23sGgoCKEaG-A43N99:-M4KmpLbERL0ley0NyCV:b-896fix) ([raw file](https://github.com/badgertechnologies/amcl/blob/8a8873533e84b3894a5f385b1d56234ebbe31d7e/src/amcl/sensors/amcl_laser.cpp#L441)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

Let's change this to a `std::vector<int>` instead of a dynamic array.
</blockquote></details>

Done.
___
*[src/amcl/sensors/planar_scanner.cpp, line 362 at r6](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M23sOq05IMyl51UebFu:-M4KmpdZ8R-kn3XKYH84:b-896fix) ([raw file](https://github.com/badgertechnologies/amcl/blob/9df029774580bad51987f61b64a87071070f819b/src/amcl/sensors/planar_scanner.cpp#L362)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

Let's change this to a std::vector<bool> instead of dynamic array
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-04-07 18:04 UTC, 12tbuchman reviewed
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/amcl/2)* status: 15 of 51 files reviewed, 193 unresolved discussions (waiting on @12tbuchman and @c-andy-martin)

___
*[src/amcl/sensors/point_cloud_scanner.cpp, line 39 at r6](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M23sp1ZEJlb-4tkuz9f:-M4KnDfa-Dif3sBkQlCL:b-896fix) ([raw file](https://github.com/badgertechnologies/amcl/blob/9df029774580bad51987f61b64a87071070f819b/src/amcl/sensors/point_cloud_scanner.cpp#L39)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

there is no need to do this, the default constructor will already do it
</blockquote></details>

Done.
___
*[src/amcl/sensors/point_cloud_scanner.cpp, line 45 at r6](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M23ssONCuCiPA2Y0Aic:-M4KnE4v0i2mKsZGSChn:b-896fix) ([raw file](https://github.com/badgertechnologies/amcl/blob/9df029774580bad51987f61b64a87071070f819b/src/amcl/sensors/point_cloud_scanner.cpp#L45)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

you could replace these 4 lines with:
```
map_vec_.resize(3);
world_vec_.resize(3);
```
The if statements will always be true, in the constructor the vectors are going to have a size of zero.
</blockquote></details>

Done.
___
*[src/amcl/sensors/point_cloud_scanner.cpp, line 92 at r6](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M245kMt-FYKTDTyxGIy:-M4KnQgP1FJY5-8UKtfO:b-896fix) ([raw file](https://github.com/badgertechnologies/amcl/blob/9df029774580bad51987f61b64a87071070f819b/src/amcl/sensors/point_cloud_scanner.cpp#L92)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

This isn't used, delete it and the API for itn
</blockquote></details>

Done.
___
*[src/amcl/sensors/point_cloud_scanner.cpp, line 172 at r6](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M23tKeM-txJ6nAO32TI:-M4KnyJZC6h6X-bGyZ7Q:b-mot8r5) ([raw file](https://github.com/badgertechnologies/amcl/blob/9df029774580bad51987f61b64a87071070f819b/src/amcl/sensors/point_cloud_scanner.cpp#L172)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

I looked at the last profile you sent me, and don't notice this being high on the profile list. so there is no need to do this
</blockquote></details>

I think it was 3.7%, right? What % would you consider important enough?


<!-- Sent from Reviewable.io -->

2020-04-07 18:54 UTC, 12tbuchman reviewed
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/amcl/2)* status: 15 of 51 files reviewed, 193 unresolved discussions (waiting on @12tbuchman and @c-andy-martin)

___
*[src/amcl/sensors/point_cloud_scanner.cpp, line 265 at r6](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M245wTn0EA7coPIKADj:-M4KzXRfDiw7mUqiRKEu:b-896fix) ([raw file](https://github.com/badgertechnologies/amcl/blob/9df029774580bad51987f61b64a87071070f819b/src/amcl/sensors/point_cloud_scanner.cpp#L265)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

Instead of calling transformPointCloud twice, create the combined transform (which is just multiplying the quaternions and combining the translations under the hood) which makes this half the math for transforming the cloud. The last profile I have from the code shows us using 6% of our time in transformPointCloud, so this will save measurable CPU time. TF provides an easy API to do this for you by overloading the `operator*`. Create the two transforms as you already do, then combine them with one call to transformPointCloud:
```
pcl_ros::transformPointCloud(data->points_, map_cloud, point_cloud_scanner_to_footprint_tf_ * footprint_to_map_tf);
```
</blockquote></details>

Done.
___
*[src/amcl/sensors/point_cloud_scanner.cpp, line 267 at r6](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M24A0Tq6LqAMlCOhMkI:-M4KzXJG0kmsyB5bF-8Z:b-896fix) ([raw file](https://github.com/badgertechnologies/amcl/blob/9df029774580bad51987f61b64a87071070f819b/src/amcl/sensors/point_cloud_scanner.cpp#L267)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

It isn't possible for transformPointCloud to throw any TF exceptions when you give it a transform. You can delete the try/catch and the whole catch block
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-04-07 19:24 UTC, 12tbuchman reviewed
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/amcl/2)* status: 15 of 51 files reviewed, 193 unresolved discussions (waiting on @12tbuchman and @c-andy-martin)

___
*[src/amcl/pf/particle_filter.cpp, line 86 at r7](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M2FDZ4bDdUmWV3uQmPn:-M4L4mks8AnnKUM7h76L:b-896fix) ([raw file](https://github.com/badgertechnologies/amcl/blob/74db8df1672f2baaecdf854cea1efd100f551c8b/src/amcl/pf/particle_filter.cpp#L86)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

If we switch kdtree to using std::vector and resizing automatically, we can get rid of setting the number of nodes a-priori and get rid of this "HACK"
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-04-07 19:31 UTC, 12tbuchman reviewed
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/amcl/2)* status: 15 of 51 files reviewed, 193 unresolved discussions (waiting on @12tbuchman and @c-andy-martin)

___
*[src/amcl/sensors/odom.cpp, line 22 at r5](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M1kdJi190VT1kE7-Hct:-M4L7-Zj3ws3muzTNZ8h:b-u9xezd) ([raw file](https://github.com/badgertechnologies/amcl/blob/95b6eb20da05f9f418bc7ea0645e69d04bc7dd99/src/amcl/sensors/odom.cpp#L22)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

Let's delete this whole block. The true authorship is in the copyright above, let's just have a single point of maintenance for author's etc. in package.xml
</blockquote></details>

Who should we have as the author in package.xml?


<!-- Sent from Reviewable.io -->

2020-04-07 19:38 UTC, 12tbuchman reviewed
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/amcl/2)* status: 15 of 51 files reviewed, 193 unresolved discussions (waiting on @c-andy-martin)

___
*[src/amcl/sensors/odom.cpp, line 82 at r5](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M1kdiuPBlyhbhDt54fg:-M4L8e-WBuC_gYt_sC1L:b-896fix) ([raw file](https://github.com/badgertechnologies/amcl/blob/95b6eb20da05f9f418bc7ea0645e69d04bc7dd99/src/amcl/sensors/odom.cpp#L82)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

This comment seems useless. Lets delete it.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-04-09 00:29 UTC, c-andy-martin commented
___
*[include/amcl/node/node.h, line 172 at r5](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M1gcVA01DBjsywxG8XY:-M4RKqkG7h-I2pKbsTq3:b-yrdcp5) ([raw file](https://github.com/badgertechnologies/amcl/blob/95b6eb20da05f9f418bc7ea0645e69d04bc7dd99/include/amcl/node/node.h#L172)):*
<details><summary><i>Previously, 12tbuchman (Tyler Buchman) wrote…</i></summary><blockquote>

the type of 'map_type_' will stay an int, correct?
</blockquote></details>

yes, I think so


<!-- Sent from Reviewable.io -->

2020-04-09 00:33 UTC, c-andy-martin commented
___
*[include/amcl/node/node_2d.h, line 36 at r5](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M1kINGhBUDE83-XkJcK:-M4RLPDVCUzujSvGfsTf:b-fp4gm7) ([raw file](https://github.com/badgertechnologies/amcl/blob/95b6eb20da05f9f418bc7ea0645e69d04bc7dd99/include/amcl/node/node_2d.h#L36)):*
<details><summary><i>Previously, 12tbuchman (Tyler Buchman) wrote…</i></summary><blockquote>

Order is C style headers and then C++ style headers
https://google.github.io/styleguide/cppguide.html#Names_and_Order_of_Includes
</blockquote></details>

"Include headers in the following order: Related header, C system headers, C++ standard library headers, other libraries' headers, your project's headers." All of the ROS headers fall under "other libraries' headers", so should come after all standard headers. C system headers would be things like `#include <unistd.h>`. C++ standard headers, are `<memory>` etc. like you have below. So the `<memory>` etc. go above all the ROS headers


<!-- Sent from Reviewable.io -->

2020-04-09 00:34 UTC, c-andy-martin commented
___
*[include/amcl/node/node_2d.h, line 91 at r5](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M1gj5C3E4AwQEaf8Qa9:-M4RM2aN-_0sCYK9gFn9:bvs82a5) ([raw file](https://github.com/badgertechnologies/amcl/blob/95b6eb20da05f9f418bc7ea0645e69d04bc7dd99/include/amcl/node/node_2d.h#L91)):*
<details><summary><i>Previously, 12tbuchman (Tyler Buchman) wrote…</i></summary><blockquote>

There may be an easy way to do this that I am not familiar with, but when I make these class objects instead of smart pointers, I need to give a base class construction, which requires the scan topic that I get from the parameter server within the constructor.
</blockquote></details>

Its OK, even if there is a way, this isn't a big deal. Its OK for now


<!-- Sent from Reviewable.io -->

2020-04-09 00:36 UTC, c-andy-martin commented
___
*[include/amcl/node/node_3d.h, line 37 at r5](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M1kIAxc-cKiw9hkpSTP:-M4RMBqF8pVJUhrwY3qs:byed54f) ([raw file](https://github.com/badgertechnologies/amcl/blob/95b6eb20da05f9f418bc7ea0645e69d04bc7dd99/include/amcl/node/node_3d.h#L37)):*
<details><summary><i>Previously, 12tbuchman (Tyler Buchman) wrote…</i></summary><blockquote>

https://google.github.io/styleguide/cppguide.html#Names_and_Order_of_Includes
According to the C++ Style Guide, the order is C system headers ending in .h/.hpp, then C++ standard library headers.
</blockquote></details>

No, by C system headers, it means things like "<unistd.h>" or "<system.h>". All the ros headers are third-party library headers, and go after all standard headers.


<!-- Sent from Reviewable.io -->

2020-04-09 00:41 UTC, c-andy-martin commented
___
*[include/amcl/pf/eig3.h, line 27 at r5](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M1kflFt9jKNjt2hGWta:-M4RNDsa20Ps_tBV1XS2:blay1ex) ([raw file](https://github.com/badgertechnologies/amcl/blob/95b6eb20da05f9f418bc7ea0645e69d04bc7dd99/include/amcl/pf/eig3.h#L27)):*
<details><summary><i>Previously, 12tbuchman (Tyler Buchman) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

The google C++ style guide suggests that any parameter that is an output (even if it is also an input) should be passed by a pointer, not be a reference:

https://google.github.io/styleguide/cppguide.html#Output_Parameters

Basically, the rule of thumb then is to only ever have const references.


<!-- Sent from Reviewable.io -->

2020-04-09 00:51 UTC, c-andy-martin commented
___
*[include/amcl/pf/particle_filter.h, line 178 at r5](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M1kMuLd2uuD-WiRy90k:-M4RPluO33oQPLKa6qTp:b-74l0nj) ([raw file](https://github.com/badgertechnologies/amcl/blob/95b6eb20da05f9f418bc7ea0645e69d04bc7dd99/include/amcl/pf/particle_filter.h#L178)):*
<details><summary><i>Previously, 12tbuchman (Tyler Buchman) wrote…</i></summary><blockquote>

The reason for having the 2 sets is so we can create the new set from the old set. We dont ever use the old set outside of creating the new set. What we could do instead is create the sets as smart pointers and then only remember the current set, but I think the current implementation is actually cleaner. I dont know why we would want more than 2 sets. We can discuss this further.
</blockquote></details>

I'm OK just leaving this as is. It is better to not use dynamic memory for this.


<!-- Sent from Reviewable.io -->

2020-04-09 00:54 UTC, c-andy-martin commented
___
*[include/amcl/sensors/sensor.h, line 49 at r5](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M1kTx1r3nem51_v4H2_:-M4RQQdBBkasWlL7pttv:b-wc1u98) ([raw file](https://github.com/badgertechnologies/amcl/blob/95b6eb20da05f9f418bc7ea0645e69d04bc7dd99/include/amcl/sensors/sensor.h#L49)):*
<details><summary><i>Previously, 12tbuchman (Tyler Buchman) wrote…</i></summary><blockquote>

Id prefer not to make these pure virtual because that requires all child classes to implement the functions, which is not the case. Odom currently implements updateAction() while PlanarScanner and PointCloudScanner implement updateSensor(). I have moved their trivial implementation into the .h file and removed the .cpp file. If you still want these functions to be pure virtual we can discuss this further.
</blockquote></details>

No, they do not have to be pure virtual. I mainly just wanted them all virtual or none virtual (not piecemeal)


<!-- Sent from Reviewable.io -->

2020-04-09 01:18 UTC, c-andy-martin commented
___
*[src/main.cpp, line 29 at r5](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M1kVMWu5richnnvl4gC:-M4RW2O9Aa70ZfFyC-nf:bmscs58) ([raw file](https://github.com/badgertechnologies/amcl/blob/95b6eb20da05f9f418bc7ea0645e69d04bc7dd99/src/main.cpp#L29)):*
<details><summary><i>Previously, 12tbuchman (Tyler Buchman) wrote…</i></summary><blockquote>

see previous discussions on this
</blockquote></details>

See my previous responses :smiley: 


<!-- Sent from Reviewable.io -->

2020-04-09 01:22 UTC, c-andy-martin commented
___
*[src/main.cpp, line 35 at r5](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M1kWnl7CYpiNV8nWCAR:-M4RWrT1CGC8ZfciFQg9:bfysqwr) ([raw file](https://github.com/badgertechnologies/amcl/blob/95b6eb20da05f9f418bc7ea0645e69d04bc7dd99/src/main.cpp#L35)):*
<details><summary><i>Previously, 12tbuchman (Tyler Buchman) wrote…</i></summary><blockquote>

Done. I was looking into if we need this to be a pointer at all. I think we do but i don't really understand why. Can you help me on this?
</blockquote></details>

You can probably just put in on the stack after the NodeHandle and things will be fine, unless you need to cast the pointer somewhere.


<!-- Sent from Reviewable.io -->

2020-04-09 01:27 UTC, c-andy-martin commented
___
*[src/main.cpp, line 24 at r11](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M4RX6OK4oq6WyOZJ5Wv:-M4RX6OK4oq6WyOZJ5Ww:b4cgypn) ([raw file](https://github.com/badgertechnologies/amcl/blob/c42088b651491b70cb4ce0f5431dbf0a908d5ea7/src/main.cpp#L24)):*
> ```cpp
> #include <ros/node_handle.h>
> #include <ros/spinner.h>
> #include <signal.h>
> ```

so here you do have one "system header" which should go first, but the ros headers are "third party libraries" and go at the end. so the order should be:
```
#include <signal.h>

#include <ctime>
#include <iostream>

#include <ros/init.h>
#include <ros/node_handle.h>
#include <ros/spinner.h>
#include "node/node.h"
```

I think what is confusing you is in https://google.github.io/styleguide/cppguide.html#Names_and_Order_of_Includes it has this line:

`C system headers (more precisely: headers in angle brackets with the .h extension), e.g. <unistd.h>, <stdlib.h>.`

But they clearly mean 'system' headers, i.e., ones from the operating system. The 'more precisely' I think is to try and distinguish it from C++ standard includes, which generally do not have a `.h`. But third party libaries might follow all kinds of naming conventions of their header files. ROS uses `.h`, which is also what Google recommends


<!-- Sent from Reviewable.io -->

2020-04-09 01:28 UTC, c-andy-martin commented
___
*[src/main.cpp, line 33 at r5](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M1kVQ1p6HMeVfd8ij7f:-M4RW9udDbw_FeJJStDu:bsjsner) ([raw file](https://github.com/badgertechnologies/amcl/blob/95b6eb20da05f9f418bc7ea0645e69d04bc7dd99/src/main.cpp#L33)):*
<details><summary><i>Previously, 12tbuchman (Tyler Buchman) wrote…</i></summary><blockquote>

whats the reason we want to not use amcl here?
</blockquote></details>

In general, I do not like `using namespace...` as it makes it easy to make accidental mistakes. For instance, if there were an `amcl::read` and a `ros::read` and just a `::read` it gets confusing. That's why in new code I prefer to never have a `using namespace` and just refer to the namespaces when I need them. Now, in this case, these names below are *in* the amcl namespace, so what I always do is:
```
namespace amcl
{
```
and at the end
```
}  // namespace amcl
```
This way you aren't pulling in amcl everywhere, but are actually inside it (which is different, in the case where there are top-level or global name conflicts, like `::read`).


<!-- Sent from Reviewable.io -->

2020-04-09 01:29 UTC, c-andy-martin commented
___
*[src/main.cpp, line 33 at r5](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M1kVQ1p6HMeVfd8ij7f:-M4RYPox-Jjk03S1HSEk:b2wl4mk) ([raw file](https://github.com/badgertechnologies/amcl/blob/95b6eb20da05f9f418bc7ea0645e69d04bc7dd99/src/main.cpp#L33)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

In general, I do not like `using namespace...` as it makes it easy to make accidental mistakes. For instance, if there were an `amcl::read` and a `ros::read` and just a `::read` it gets confusing. That's why in new code I prefer to never have a `using namespace` and just refer to the namespaces when I need them. Now, in this case, these names below are *in* the amcl namespace, so what I always do is:
```
namespace amcl
{
```
and at the end
```
}  // namespace amcl
```
This way you aren't pulling in amcl everywhere, but are actually inside it (which is different, in the case where there are top-level or global name conflicts, like `::read`).
</blockquote></details>

Oh, i wasn't looking at what file we are in here, this is main.cpp, and main() must be in the global namespace. So, no, do not do what I said above. You did this in your C++ files. I would prefer instead to remove the `using namespace amcl;` and instead just add `amcl::` where necessary.


<!-- Sent from Reviewable.io -->

2020-04-09 01:39 UTC, c-andy-martin commented
___
*[src/amcl/map/octomap_cspace.cpp, line 55 at r7](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M26QPqS1JsffgNVqKX3:-M4R_coY1geFI7RIIHtd:b-ga7es5) ([raw file](https://github.com/badgertechnologies/amcl/blob/74db8df1672f2baaecdf854cea1efd100f551c8b/src/amcl/map/octomap_cspace.cpp#L55)):*
<details><summary><i>Previously, 12tbuchman (Tyler Buchman) wrote…</i></summary><blockquote>

done, though I think it makes the code less clean to have 2 more parameters with long types added to 4 functions.
</blockquote></details>

In general, it is cleaner to me to have fewer things in the class which is state shared everywhere by the class. Now q and masked come off the stack, which is a cheap and easy way to allocate temporaries. So I like this better.


<!-- Sent from Reviewable.io -->

2020-04-09 01:41 UTC, c-andy-martin commented
___
*[src/amcl/node/node.cpp, line 117 at r7](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M2ZgEUlBnNgcMFALR9j:-M4Ra6BI5XFtqmhqscb4:bs8zyx0) ([raw file](https://github.com/badgertechnologies/amcl/blob/74db8df1672f2baaecdf854cea1efd100f551c8b/src/amcl/node/node.cpp#L117)):*
<details><summary><i>Previously, 12tbuchman (Tyler Buchman) wrote…</i></summary><blockquote>

Whats the reason this is significantly better than using a c_str?
</blockquote></details>

c_str, depending on the implementation, may have to allocate a temporary buffer, it requires adding a '\0' at the end of the string, and `%s` is a known vector for security vulnerabilities. Since we already have a std::string and an iostream, just use `<<` and avoid all of that


<!-- Sent from Reviewable.io -->

2020-04-09 01:44 UTC, c-andy-martin commented
___
*[src/amcl/node/node.cpp, line 567 at r7](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M2Zi8xQ6EuPZVtJOo8_:-M4RaknD9KIHwqlVsRlD:bca5zwb) ([raw file](https://github.com/badgertechnologies/amcl/blob/74db8df1672f2baaecdf854cea1efd100f551c8b/src/amcl/node/node.cpp#L567)):*
<details><summary><i>Previously, 12tbuchman (Tyler Buchman) wrote…</i></summary><blockquote>

I know ive asked this before but this is slightly different, what is the benefit of ROS_WARN_STREAM over ROS_WARN? I like putting exceptions in ROS_WARN unless you have a reason not to. i will combine this with the debug below to give context.
</blockquote></details>

See my comment above about avoiding `%s` and `c_str()`. C-style strings in general should be avoided in C++ code as they are easy to get wrong. Adding `_STREAM` makes ROS_ console use an `iostream` C++ object to do the formatting instead of a printf style function.


<!-- Sent from Reviewable.io -->

2020-04-09 13:53 UTC, 12tbuchman reviewed
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/amcl/2)* status: 15 of 49 files reviewed, 110 unresolved discussions (waiting on @12tbuchman and @c-andy-martin)

___
*[include/amcl/node/node.h, line 172 at r5](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M1gcVA01DBjsywxG8XY:-M4UClPSEu58BnniY4yf:b-896fix) ([raw file](https://github.com/badgertechnologies/amcl/blob/95b6eb20da05f9f418bc7ea0645e69d04bc7dd99/include/amcl/node/node.h#L172)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

yes, I think so
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-04-09 13:54 UTC, 12tbuchman reviewed
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/amcl/2)* status: 15 of 49 files reviewed, 110 unresolved discussions (waiting on @12tbuchman and @c-andy-martin)

___
*[include/amcl/node/node_2d.h, line 91 at r5](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M1gj5C3E4AwQEaf8Qa9:-M4UCqE01EDaUHqANWDU:b-896fix) ([raw file](https://github.com/badgertechnologies/amcl/blob/95b6eb20da05f9f418bc7ea0645e69d04bc7dd99/include/amcl/node/node_2d.h#L91)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

Its OK, even if there is a way, this isn't a big deal. Its OK for now
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-04-09 14:34 UTC, 12tbuchman reviewed
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/amcl/2)* status: 15 of 49 files reviewed, 110 unresolved discussions (waiting on @12tbuchman and @c-andy-martin)

___
*[include/amcl/node/node_3d.h, line 37 at r5](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M1kIAxc-cKiw9hkpSTP:-M4UMC4S9bqmSbOHyxor:b-896fix) ([raw file](https://github.com/badgertechnologies/amcl/blob/95b6eb20da05f9f418bc7ea0645e69d04bc7dd99/include/amcl/node/node_3d.h#L37)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

No, by C system headers, it means things like "<unistd.h>" or "<system.h>". All the ros headers are third-party library headers, and go after all standard headers.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-04-09 14:37 UTC, 12tbuchman reviewed
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/amcl/2)* status: 15 of 49 files reviewed, 110 unresolved discussions (waiting on @12tbuchman and @c-andy-martin)

___
*[include/amcl/pf/particle_filter.h, line 178 at r5](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M1kMuLd2uuD-WiRy90k:-M4UMpvT0ehSfUBP45u0:b-896fix) ([raw file](https://github.com/badgertechnologies/amcl/blob/95b6eb20da05f9f418bc7ea0645e69d04bc7dd99/include/amcl/pf/particle_filter.h#L178)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

I'm OK just leaving this as is. It is better to not use dynamic memory for this.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-04-09 14:40 UTC, 12tbuchman reviewed
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/amcl/2)* status: 15 of 49 files reviewed, 110 unresolved discussions (waiting on @12tbuchman and @c-andy-martin)

___
*[include/amcl/node/node_2d.h, line 36 at r5](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M1kINGhBUDE83-XkJcK:-M4UNC9bAiut_Asp1ok0:b-896fix) ([raw file](https://github.com/badgertechnologies/amcl/blob/95b6eb20da05f9f418bc7ea0645e69d04bc7dd99/include/amcl/node/node_2d.h#L36)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

"Include headers in the following order: Related header, C system headers, C++ standard library headers, other libraries' headers, your project's headers." All of the ROS headers fall under "other libraries' headers", so should come after all standard headers. C system headers would be things like `#include <unistd.h>`. C++ standard headers, are `<memory>` etc. like you have below. So the `<memory>` etc. go above all the ROS headers
</blockquote></details>

Done.
___
*[src/main.cpp, line 29 at r5](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M1kVMWu5richnnvl4gC:-M4UNIO03nv9TCYp7mPX:b-896fix) ([raw file](https://github.com/badgertechnologies/amcl/blob/95b6eb20da05f9f418bc7ea0645e69d04bc7dd99/src/main.cpp#L29)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

See my previous responses :smiley: 
</blockquote></details>

Done.
___
*[src/main.cpp, line 24 at r11](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M4RX6OK4oq6WyOZJ5Wv:-M4UNHiICd5VFsEYdGKZ:b-896fix) ([raw file](https://github.com/badgertechnologies/amcl/blob/c42088b651491b70cb4ce0f5431dbf0a908d5ea7/src/main.cpp#L24)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

so here you do have one "system header" which should go first, but the ros headers are "third party libraries" and go at the end. so the order should be:
```
#include <signal.h>

#include <ctime>
#include <iostream>

#include <ros/init.h>
#include <ros/node_handle.h>
#include <ros/spinner.h>
#include "node/node.h"
```

I think what is confusing you is in https://google.github.io/styleguide/cppguide.html#Names_and_Order_of_Includes it has this line:

`C system headers (more precisely: headers in angle brackets with the .h extension), e.g. <unistd.h>, <stdlib.h>.`

But they clearly mean 'system' headers, i.e., ones from the operating system. The 'more precisely' I think is to try and distinguish it from C++ standard includes, which generally do not have a `.h`. But third party libaries might follow all kinds of naming conventions of their header files. ROS uses `.h`, which is also what Google recommends

</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-04-09 14:48 UTC, 12tbuchman reviewed
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/amcl/2)* status: 15 of 49 files reviewed, 110 unresolved discussions (waiting on @12tbuchman and @c-andy-martin)

___
*[src/main.cpp, line 33 at r5](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M1kVQ1p6HMeVfd8ij7f:-M4UPOeoBOpNv_k9zJMi:b-896fix) ([raw file](https://github.com/badgertechnologies/amcl/blob/95b6eb20da05f9f418bc7ea0645e69d04bc7dd99/src/main.cpp#L33)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

Oh, i wasn't looking at what file we are in here, this is main.cpp, and main() must be in the global namespace. So, no, do not do what I said above. You did this in your C++ files. I would prefer instead to remove the `using namespace amcl;` and instead just add `amcl::` where necessary.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-04-09 16:09 UTC, 12tbuchman reviewed
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/amcl/2)* status: 15 of 49 files reviewed, 110 unresolved discussions (waiting on @c-andy-martin)

___
*[src/amcl/node/node.cpp, line 117 at r7](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M2ZgEUlBnNgcMFALR9j:-M4UgwiYBh1pzO3JhJd_:b-896fix) ([raw file](https://github.com/badgertechnologies/amcl/blob/74db8df1672f2baaecdf854cea1efd100f551c8b/src/amcl/node/node.cpp#L117)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

c_str, depending on the implementation, may have to allocate a temporary buffer, it requires adding a '\0' at the end of the string, and `%s` is a known vector for security vulnerabilities. Since we already have a std::string and an iostream, just use `<<` and avoid all of that
</blockquote></details>

Done.
___
*[src/amcl/node/node.cpp, line 567 at r7](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M2Zi8xQ6EuPZVtJOo8_:-M4Ugxu--__PSM4qZP8z:b-896fix) ([raw file](https://github.com/badgertechnologies/amcl/blob/74db8df1672f2baaecdf854cea1efd100f551c8b/src/amcl/node/node.cpp#L567)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

See my comment above about avoiding `%s` and `c_str()`. C-style strings in general should be avoided in C++ code as they are easy to get wrong. Adding `_STREAM` makes ROS_ console use an `iostream` C++ object to do the formatting instead of a printf style function.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-04-09 17:10 UTC, c-andy-martin commented
___
*[include/amcl/map/occupancy_map.h, line 89 at r9](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M2eHvjz6ZgkGC5ysSX2:-M4Uuk6944JjGcUA5-pE:b2he1s4) ([raw file](https://github.com/badgertechnologies/amcl/blob/b28c573d53c54b2904a0c476e86e7f24b8cd83ff/include/amcl/map/occupancy_map.h#L89)):*
<details><summary><i>Previously, 12tbuchman (Tyler Buchman) wrote…</i></summary><blockquote>

Ive made the functions called for every voxel in updateCSpace to be private inline for performance. I was thinking though, should the public function getOccDist really be virtual? This is a huge performance cost considering we already spend so much time in that function from calling it for every iterated point in a data scan.
</blockquote></details>

Since there is no map getOccDist, its OK to not have it be virtual. Please document why (something like, `do not make this virtual as getOccDist is called many times when scoring a pose`)


<!-- Sent from Reviewable.io -->

2020-04-09 17:11 UTC, c-andy-martin commented
___
*[include/amcl/map/occupancy_map.h, line 80 at r9](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M4Uv9YkC9Cae7Mi8UpY:-M4Uv9YkC9Cae7Mi8UpZ:b-e41vn6) ([raw file](https://github.com/badgertechnologies/amcl/blob/b28c573d53c54b2904a0c476e86e7f24b8cd83ff/include/amcl/map/occupancy_map.h#L80)):*
> ```objc
>   virtual double calcRange(double ox, double oy, double oa, double max_range);
>   // Find the distance to nearest occupied cell
>   virtual float getOccDist(int i, int j);
> ```

if you choose (as commented below) to make this non-virtual and add the comment, you might want to also inline this and add the definition of the function right here. This would give you the maximum performance gain.


<!-- Sent from Reviewable.io -->

2020-04-09 17:12 UTC, c-andy-martin commented
___
*[include/amcl/map/octomap.h, line 73 at r9](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M4UvLY_20012YjyzA-T:-M4UvLY_20012YjyzA-U:b-rx6uzu) ([raw file](https://github.com/badgertechnologies/amcl/blob/b28c573d53c54b2904a0c476e86e7f24b8cd83ff/include/amcl/map/octomap.h#L73)):*
> ```objc
>   virtual void updateMaxOccDist(double max_occ_dist);
>   virtual void initFromOctree(std::shared_ptr<octomap::OcTree> octree);
>   virtual double getOccDist(int i, int j, int k);
> ```

same comment here as on occupancy_map's getOccDist


<!-- Sent from Reviewable.io -->

2020-04-09 17:17 UTC, c-andy-martin requested changes
> Reviewed 1 of 38 files at r10, 2 of 19 files at r12.
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/amcl/2)* status: 18 of 49 files reviewed, 101 unresolved discussions (waiting on @12tbuchman and @c-andy-martin)

___
*[src/main.cpp, line 47 at r12](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M4Uw6FP7-3v1Uup8QPG:-M4Uw6FP7-3v1Uup8QPH:b-dnsq8z) ([raw file](https://github.com/badgertechnologies/amcl/blob/69e2d9799639a29b8b666212f628f28b703e35ef/src/main.cpp#L47)):*
> ```cpp
>   signal(SIGTERM, sigHandler);
> 
>   std::unique_ptr<amcl::Node> amcl_node_ptr(new amcl::Node());
> ```

There is no reason for this to be a pointer. I would just make this:
```
amcl::Node node;
```
___
*[src/main.cpp, line 52 at r12](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M4UwTfzDUPkUlNtEllS:-M4UwTfzDUPkUlNtEllT:by0l2jf) ([raw file](https://github.com/badgertechnologies/amcl/blob/69e2d9799639a29b8b666212f628f28b703e35ef/src/main.cpp#L52)):*
> ```cpp
>   spinner.spin();
> 
>   amcl_node_ptr->savePoseToFile();
> ```

once this is not a pointer, node.savePoseToFile()
___
*[src/main.cpp, line 55 at r12](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M4Uw2AwD7519EGvPvlJ:-M4Uw2Ax3q9GC0L9qC5d:b-pflxvb) ([raw file](https://github.com/badgertechnologies/amcl/blob/69e2d9799639a29b8b666212f628f28b703e35ef/src/main.cpp#L55)):*
> ```cpp
> 
>   // Without this, our locks are not shut down nicely
>   amcl_node_ptr.reset();
> ```

This line is no longer necessar, or the comment. The pointer will go out-of-scope above in the order they were put in scope.


<!-- Sent from Reviewable.io -->

2020-04-09 17:19 UTC, c-andy-martin commented
___
*[src/main.cpp, line 34 at r12](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M4UwkEfBRoqLKQjuNXF:-M4UwkEfBRoqLKQjuNXG:b193gs7) ([raw file](https://github.com/badgertechnologies/amcl/blob/69e2d9799639a29b8b666212f628f28b703e35ef/src/main.cpp#L34)):*
> ```cpp
> void sigHandler(int sig)
> {
>   ros::shutdown();
> ```

we should change this to `ros::requestShutdown()` which is signal-handler safe. It isn't safe to call `ros::shutdown()` in a signal handler. AFAIK this is not documented behavior, but I've learned this by inspection of the source.


<!-- Sent from Reviewable.io -->

2020-04-09 17:20 UTC, c-andy-martin requested changes
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/amcl/2)* status: 18 of 49 files reviewed, 103 unresolved discussions (waiting on @12tbuchman and @c-andy-martin)

___
*[src/main.cpp, line 49 at r12](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M4Ux5Pk3PjWaSD4CVOO:-M4Ux5Pk3PjWaSD4CVOP:b-1s5nml) ([raw file](https://github.com/badgertechnologies/amcl/blob/69e2d9799639a29b8b666212f628f28b703e35ef/src/main.cpp#L49)):*
> ```cpp
>   std::unique_ptr<amcl::Node> amcl_node_ptr(new amcl::Node());
> 
>   ros::MultiThreadedSpinner spinner(4);
> ```

I'd say its probably better to remove the argument to spinner. It will default to the number of cores you have. We don't have a specific need for a specific number of threads, so I'd remove the constructor argument of `4`:
```
ros::MultiThreadedSpinner spinner;
```


<!-- Sent from Reviewable.io -->

2020-04-09 17:25 UTC, c-andy-martin commented
___
*[src/main.cpp, line 39 at r12](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M4UxiKdBFgSH3FrgqOW:-M4UxiKdBFgSH3FrgqOX:b-p3c9i1) ([raw file](https://github.com/badgertechnologies/amcl/blob/69e2d9799639a29b8b666212f628f28b703e35ef/src/main.cpp#L39)):*
> ```cpp
> int main(int argc, char** argv)
> {
>   srand48(std::time(NULL));
> ```

this function comes from `<stdlib.h>` which is a Linux/POSIX system header. Please add this header as the first header included. Also, it is slightly more C++ish to use `nullptr` than NULL.


<!-- Sent from Reviewable.io -->

2020-04-09 17:25 UTC, c-andy-martin reviewed
> Reviewed 1 of 19 files at r12.
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/amcl/2)* status: 19 of 49 files reviewed, 104 unresolved discussions (waiting on @12tbuchman and @c-andy-martin)



<!-- Sent from Reviewable.io -->

2020-04-09 17:27 UTC, c-andy-martin commented
___
*[src/amcl/map/occupancy_map.cpp, line 100 at r6](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M24Jnx1BcaNQlYvcywk:-M4UyVQu6SUr5B5SxOWI:b-3rydr) ([raw file](https://github.com/badgertechnologies/amcl/blob/9df029774580bad51987f61b64a87071070f819b/src/amcl/map/occupancy_map.cpp#L100)):*
<details><summary><i>Previously, 12tbuchman (Tyler Buchman) wrote…</i></summary><blockquote>

see comment below.
</blockquote></details>

I'm OK leaving this as is, as long as we add a comment like this here:
```
/*
 *This legacy code centers the map at 0, 0.
 *It could be made to have the origin at the bottom left similar to nav_msgs/OccupancyGrid.
 * However, the potential for breaking the code is there, so this is left as-is.
 */
```


<!-- Sent from Reviewable.io -->

2020-04-09 17:28 UTC, c-andy-martin reviewed
> Reviewed 1 of 30 files at r11, 1 of 19 files at r12.
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/amcl/2)* status: 21 of 49 files reviewed, 102 unresolved discussions (waiting on @12tbuchman and @c-andy-martin)



<!-- Sent from Reviewable.io -->

2020-04-09 17:31 UTC, c-andy-martin commented
___
*[src/amcl/node/node.cpp, line 567 at r7](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M2Zi8xQ6EuPZVtJOo8_:-M4Uzbjb2TXA94LcHaNr:by1okpw) ([raw file](https://github.com/badgertechnologies/amcl/blob/74db8df1672f2baaecdf854cea1efd100f551c8b/src/amcl/node/node.cpp#L567)):*
<details><summary><i>Previously, 12tbuchman (Tyler Buchman) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I still see `%s`, lets change this to ROS_WARN_STREAM and use `<<`


<!-- Sent from Reviewable.io -->

2020-04-09 17:33 UTC, c-andy-martin commented
___
*[src/amcl/node/node.cpp, line 649 at r7](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M2ZivBr97feK6_Mz8jL:-M4Uzs-N5gUIDMmXjYOz:bpu3sgv) ([raw file](https://github.com/badgertechnologies/amcl/blob/74db8df1672f2baaecdf854cea1efd100f551c8b/src/amcl/node/node.cpp#L649)):*
<details><summary><i>Previously, 12tbuchman (Tyler Buchman) wrote…</i></summary><blockquote>

Im currently using the mutex anytime I access latest_tf_ or latest_tf_valid_. If I only use it in this place, wouldn't it be trivial? I have added the mutex to the general save_pose function which is the sole function that calls this function, so this should now be covered.
</blockquote></details>

no, its not trivial to call `.inverse()`, the matrix needs to stay the same during the entire computation or you could get incorrect results. Matrices are not atomic. If you require the caller to hold a lock, you should document that in the header something like `// caller must be holding tf_mutex_`, but if the tf_mutex_ isn't needed anywhere else in save_pose, you should only hold it here. You want to hold a mutex for the minimum required time.


<!-- Sent from Reviewable.io -->

2020-04-09 17:34 UTC, 12tbuchman reviewed
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/amcl/2)* status: 21 of 49 files reviewed, 98 unresolved discussions (waiting on @12tbuchman and @c-andy-martin)

___
*[include/amcl/map/occupancy_map.h, line 80 at r9](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M4Uv9YkC9Cae7Mi8UpY:-M4V-C7F8rcG3CaKZW5-:b5a02n2) ([raw file](https://github.com/badgertechnologies/amcl/blob/b28c573d53c54b2904a0c476e86e7f24b8cd83ff/include/amcl/map/occupancy_map.h#L80)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

if you choose (as commented below) to make this non-virtual and add the comment, you might want to also inline this and add the definition of the function right here. This would give you the maximum performance gain.
</blockquote></details>

Is the reason we should inline this function because it is part of the bottleneck?
___
*[include/amcl/map/occupancy_map.h, line 89 at r9](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M2eHvjz6ZgkGC5ysSX2:-M4UyfVA5oYT0VRmMRB_:b-896fix) ([raw file](https://github.com/badgertechnologies/amcl/blob/b28c573d53c54b2904a0c476e86e7f24b8cd83ff/include/amcl/map/occupancy_map.h#L89)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

Since there is no map getOccDist, its OK to not have it be virtual. Please document why (something like, `do not make this virtual as getOccDist is called many times when scoring a pose`)
</blockquote></details>

Done.
___
*[include/amcl/map/octomap.h, line 73 at r9](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M4UvLY_20012YjyzA-T:-M4Uyv84-tMd9DTYmSGA:b-896fix) ([raw file](https://github.com/badgertechnologies/amcl/blob/b28c573d53c54b2904a0c476e86e7f24b8cd83ff/include/amcl/map/octomap.h#L73)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

same comment here as on occupancy_map's getOccDist
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-04-09 17:37 UTC, 12tbuchman reviewed
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/amcl/2)* status: 21 of 49 files reviewed, 98 unresolved discussions (waiting on @12tbuchman and @c-andy-martin)

___
*[src/main.cpp, line 34 at r12](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M4UwkEfBRoqLKQjuNXF:-M4V03CC8Sn46QIy_iQ6:b-896fix) ([raw file](https://github.com/badgertechnologies/amcl/blob/69e2d9799639a29b8b666212f628f28b703e35ef/src/main.cpp#L34)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

we should change this to `ros::requestShutdown()` which is signal-handler safe. It isn't safe to call `ros::shutdown()` in a signal handler. AFAIK this is not documented behavior, but I've learned this by inspection of the source.
</blockquote></details>

Done.
___
*[src/main.cpp, line 39 at r12](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M4UxiKdBFgSH3FrgqOW:-M4V03c81GGXhsfyOczp:b-896fix) ([raw file](https://github.com/badgertechnologies/amcl/blob/69e2d9799639a29b8b666212f628f28b703e35ef/src/main.cpp#L39)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

this function comes from `<stdlib.h>` which is a Linux/POSIX system header. Please add this header as the first header included. Also, it is slightly more C++ish to use `nullptr` than NULL.
</blockquote></details>

Done.
___
*[src/main.cpp, line 47 at r12](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M4Uw6FP7-3v1Uup8QPG:-M4V06Dy2ty_FERaA8N5:b-vw5lnw) ([raw file](https://github.com/badgertechnologies/amcl/blob/69e2d9799639a29b8b666212f628f28b703e35ef/src/main.cpp#L47)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

There is no reason for this to be a pointer. I would just make this:
```
amcl::Node node;
```
</blockquote></details>

If I do that, would I remove the line amcl_node_ptr.reset() or would I replace it with something?


<!-- Sent from Reviewable.io -->

2020-04-09 17:42 UTC, c-andy-martin commented
___
*[src/amcl/node/node.cpp, line 727 at r7](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M2FS3ncA8K2V1_iNtk6:-M4V1ADyAePlwPxXeS54:b-dfg0io) ([raw file](https://github.com/badgertechnologies/amcl/blob/74db8df1672f2baaecdf854cea1efd100f551c8b/src/amcl/node/node.cpp#L727)):*
<details><summary><i>Previously, 12tbuchman (Tyler Buchman) wrote…</i></summary><blockquote>

Im not understanding why this wouldnt be in AMCL. We are initializing many key parts of the algorithm in this function.
</blockquote></details>

It shouldn't be here because AMCL should have no knowledge about how system paths are organized, or any references to badger-specific environment variables. Those things belong at the system integration layer, as the system may have need to put them in different places depending on how/where the code is run. I see you already removed this, so this is now OK.


<!-- Sent from Reviewable.io -->

2020-04-09 17:43 UTC, c-andy-martin reviewed
> Reviewed 2 of 38 files at r10, 1 of 19 files at r12.
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/amcl/2)* status: 22 of 49 files reviewed, 93 unresolved discussions (waiting on @12tbuchman and @c-andy-martin)



<!-- Sent from Reviewable.io -->

2020-04-09 17:45 UTC, c-andy-martin commented
___
*[src/amcl/node/node.cpp, line 863 at r12](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M4V1vt68fyy2wKR6ltX:-M4V1vt68fyy2wKR6ltY:bs9zzl1) ([raw file](https://github.com/badgertechnologies/amcl/blob/69e2d9799639a29b8b666212f628f28b703e35ef/src/amcl/node/node.cpp#L863)):*
> ```cpp
>     return p;
>   }
>   unsigned int rand_index = drand48() * free_space_indices_.size();
> ```

drand48 comes from `<stdlib.h>` (POSIX) and should be the first include in the file (as a system header)


<!-- Sent from Reviewable.io -->

2020-04-09 17:46 UTC, c-andy-martin requested changes
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/amcl/2)* status: 22 of 49 files reviewed, 95 unresolved discussions (waiting on @12tbuchman and @c-andy-martin)

___
*[src/amcl/pf/particle_filter.cpp, line 20 at r12](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M4V2AGB1sQwqbKV_Hng:-M4V2AGB1sQwqbKV_Hnh:bh03gil) ([raw file](https://github.com/badgertechnologies/amcl/blob/69e2d9799639a29b8b666212f628f28b703e35ef/src/amcl/pf/particle_filter.cpp#L20)):*
> ```cpp
>  *
>  */
> ```

we need to add `<stdlib.h>` for `drand48`


<!-- Sent from Reviewable.io -->

2020-04-09 17:46 UTC, c-andy-martin requested changes
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/amcl/2)* status: 22 of 49 files reviewed, 96 unresolved discussions (waiting on @12tbuchman and @c-andy-martin)

___
*[src/amcl/pf/pdf_gaussian.cpp, line 20 at r12](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M4V2HRvES0zllhpAfDo:-M4V2HRvES0zllhpAfDp:b-kxjhex) ([raw file](https://github.com/badgertechnologies/amcl/blob/69e2d9799639a29b8b666212f628f28b703e35ef/src/amcl/pf/pdf_gaussian.cpp#L20)):*
> ```cpp
>  *
>  */
> ```

we need to add `<stdlib.h>` for drand48


<!-- Sent from Reviewable.io -->

2020-04-09 17:50 UTC, c-andy-martin commented
___
*[include/amcl/pf/pf_kdtree.h, line 97 at r12](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M4V2wrO1ah_yMRKgKKX:-M4V2wrO1ah_yMRKgKKY:b8o8fin) ([raw file](https://github.com/badgertechnologies/amcl/blob/69e2d9799639a29b8b666212f628f28b703e35ef/include/amcl/pf/pf_kdtree.h#L97)):*
> ```objc
> 
>   // The maximum number of nodes in the tree
>   int node_count_;
> ```

node_count_ is now redundant with nodes_.size(). Remove node_count_ in favor of various calls in std::vector (for instance, if you need the address of the last node, use `.back()`


<!-- Sent from Reviewable.io -->

2020-04-09 18:05 UTC, c-andy-martin commented
___
*[src/amcl/pf/pf_kdtree.cpp, line 195 at r12](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M4V3hMn84eTOwekrSqt:-M4V3hMn84eTOwekrSqu:b-20ns7i) ([raw file](https://github.com/badgertechnologies/amcl/blob/69e2d9799639a29b8b666212f628f28b703e35ef/src/amcl/pf/pf_kdtree.cpp#L195)):*
> ```cpp
> {
>   int i;
>   int queue_count, cluster_count;
> ```

I would like to rewrite this function to be (assuming you make the vector directly hold nodes and not unique_ptr):
```
// Cluster the leaves in the tree
void PFKDTree::cluster()
{ 
  int cluster_count = 0;

  for (auto node : nodes_)
  {
    node.cluster = -1;
  }
  
  // Do connected components for each node
  for (auto node : nodes_)
  {
    // If this node has already been labelled, skip it
    if (node.cluster < 0)
    {
      // Assign a label to this cluster 
      node.cluster = cluster_count++;
      // Recursively label nodes in this cluster
      clusterNode(&node, 0);
    }
  }
}
```


<!-- Sent from Reviewable.io -->

2020-04-09 18:06 UTC, c-andy-martin requested changes
> Reviewed 1 of 19 files at r12.
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/amcl/2)* status: 23 of 49 files reviewed, 94 unresolved discussions (waiting on @12tbuchman and @c-andy-martin)

___
*[include/amcl/pf/pf_kdtree.h, line 98 at r12](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M4V35w0CdWpP8Y9qu1J:-M4V35w0CdWpP8Y9qu1K:bct0wff) ([raw file](https://github.com/badgertechnologies/amcl/blob/69e2d9799639a29b8b666212f628f28b703e35ef/include/amcl/pf/pf_kdtree.h#L98)):*
> ```objc
>   // The maximum number of nodes in the tree
>   int node_count_;
>   std::vector<std::unique_ptr<PFKDTreeNode>> nodes_;
> ```

I don't think the vector needs to store pointers. Just make this a vector of `PFKDTreeNode`
___
*[src/amcl/pf/pf_kdtree.cpp, line 41 at r12](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M4V6YDV9fi7uumlW82D:-M4V6YDV9fi7uumlW82E:bca04nn) ([raw file](https://github.com/badgertechnologies/amcl/blob/69e2d9799639a29b8b666212f628f28b703e35ef/src/amcl/pf/pf_kdtree.cpp#L41)):*
> ```cpp
>   root_ = NULL;
> 
>   node_count_ = 0;
> ```

this goes away when you remove node_count_
___
*[src/amcl/pf/pf_kdtree.cpp, line 50 at r12](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M4V6_nYDqSAU7RK5TuK:-M4V6_nYDqSAU7RK5TuL:b-7uujtd) ([raw file](https://github.com/badgertechnologies/amcl/blob/69e2d9799639a29b8b666212f628f28b703e35ef/src/amcl/pf/pf_kdtree.cpp#L50)):*
> ```cpp
>   root_ = NULL;
>   leaf_count_ = 0;
>   node_count_ = 0;
> ```

this goes away too
___
*[src/amcl/pf/pf_kdtree.cpp, line 94 at r12](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M4V6cF46TJdIM3oP-qm:-M4V6cF46TJdIM3oP-qn:b89rccz) ([raw file](https://github.com/badgertechnologies/amcl/blob/69e2d9799639a29b8b666212f628f28b703e35ef/src/amcl/pf/pf_kdtree.cpp#L94)):*
> ```cpp
>   if (node == NULL)
>   {
>     nodes_.push_back(std::unique_ptr<PFKDTreeNode>(new PFKDTreeNode()));
> ```

these two lines become:
```
    nodes_.resize(nodes_.size() + 1);
    node = &nodes_.back();
```
when you get rid of node_count and switch to directly holding the nodes in the vector
 


<!-- Sent from Reviewable.io -->

2020-04-09 18:06 UTC, 12tbuchman reviewed
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/amcl/2)* status: 23 of 49 files reviewed, 94 unresolved discussions (waiting on @12tbuchman and @c-andy-martin)

___
*[src/main.cpp, line 47 at r12](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M4Uw6FP7-3v1Uup8QPG:-M4V6oij1znJ9A9ITZjg:bas8z63) ([raw file](https://github.com/badgertechnologies/amcl/blob/69e2d9799639a29b8b666212f628f28b703e35ef/src/main.cpp#L47)):*
<details><summary><i>Previously, 12tbuchman (Tyler Buchman) wrote…</i></summary><blockquote>

If I do that, would I remove the line amcl_node_ptr.reset() or would I replace it with something?
</blockquote></details>

nevermind, I see your comment.
___
*[src/main.cpp, line 49 at r12](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M4Ux5Pk3PjWaSD4CVOO:-M4V6fHx5JdpbTXWIfl_:b-896fix) ([raw file](https://github.com/badgertechnologies/amcl/blob/69e2d9799639a29b8b666212f628f28b703e35ef/src/main.cpp#L49)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

I'd say its probably better to remove the argument to spinner. It will default to the number of cores you have. We don't have a specific need for a specific number of threads, so I'd remove the constructor argument of `4`:
```
ros::MultiThreadedSpinner spinner;
```
</blockquote></details>

Done.
___
*[src/main.cpp, line 52 at r12](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M4UwTfzDUPkUlNtEllS:-M4V6nvo-Wf2wS6SfwuW:b-896fix) ([raw file](https://github.com/badgertechnologies/amcl/blob/69e2d9799639a29b8b666212f628f28b703e35ef/src/main.cpp#L52)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

once this is not a pointer, node.savePoseToFile()
</blockquote></details>

Done.
___
*[src/main.cpp, line 55 at r12](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M4Uw2AwD7519EGvPvlJ:-M4V6nkjBDZpmeqAyYNn:b-896fix) ([raw file](https://github.com/badgertechnologies/amcl/blob/69e2d9799639a29b8b666212f628f28b703e35ef/src/main.cpp#L55)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

This line is no longer necessar, or the comment. The pointer will go out-of-scope above in the order they were put in scope.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-04-09 18:09 UTC, c-andy-martin commented
___
*[src/amcl/sensors/odom.cpp, line 22 at r5](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M1kdJi190VT1kE7-Hct:-M4V7UKOAxv0T1Ne1WxU:b-gd8x9a) ([raw file](https://github.com/badgertechnologies/amcl/blob/95b6eb20da05f9f418bc7ea0645e69d04bc7dd99/src/amcl/sensors/odom.cpp#L22)):*
<details><summary><i>Previously, 12tbuchman (Tyler Buchman) wrote…</i></summary><blockquote>

Who should we have as the author in package.xml?
</blockquote></details>

whomever was listed previously in the original package.xml and you


<!-- Sent from Reviewable.io -->

2020-04-09 18:12 UTC, c-andy-martin commented
___
*[src/amcl/sensors/odom.cpp, line 307 at r5](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M1kdrAM32YRHjqjCFYj:-M4V7eEeCHnajIB4Kx_k:b2p9nyw) ([raw file](https://github.com/badgertechnologies/amcl/blob/95b6eb20da05f9f418bc7ea0645e69d04bc7dd99/src/amcl/sensors/odom.cpp#L307)):*
<details><summary><i>Previously, 12tbuchman (Tyler Buchman) wrote…</i></summary><blockquote>

Theres a TODO for this
</blockquote></details>

I'm not convinced that this code is even correct.  for instance, if the angles passed in are > 4pi I think this gets the wrong answer. You are already using `shortest_angular_distance` elsewhere, just change this whole function to `return angles::shortest_angular_distance(a, b);`


<!-- Sent from Reviewable.io -->

2020-04-09 18:12 UTC, c-andy-martin commented
___
*[src/amcl/sensors/odom.cpp, line 315 at r12](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M4V88sy7EwzoSlADTgW:-M4V88sy7EwzoSlADTgX:bf0lxu7) ([raw file](https://github.com/badgertechnologies/amcl/blob/69e2d9799639a29b8b666212f628f28b703e35ef/src/amcl/sensors/odom.cpp#L315)):*
> ```cpp
> double Odom::normalize(double z)
> {
>   return std::atan2(std::sin(z), std::cos(z));
> ```

Just change this to `return angles::normalize_angle(z);`


<!-- Sent from Reviewable.io -->

2020-04-09 18:13 UTC, c-andy-martin reviewed
> Reviewed 1 of 30 files at r11, 1 of 19 files at r12.
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/amcl/2)* status: 25 of 49 files reviewed, 74 unresolved discussions (waiting on @12tbuchman and @c-andy-martin)



<!-- Sent from Reviewable.io -->

2020-04-09 18:18 UTC, c-andy-martin commented
___
*[src/amcl/pf/pf_vector.cpp, line 75 at r12](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M4V8WMu8pWFrREGm112:-M4V8WMu8pWFrREGm113:b-gf8gep) ([raw file](https://github.com/badgertechnologies/amcl/blob/69e2d9799639a29b8b666212f628f28b703e35ef/src/amcl/pf/pf_vector.cpp#L75)):*
> ```cpp
>   c.v[1] = b.v[1] + a.v[0] * std::sin(b.v[2]) + a.v[1] * std::cos(b.v[2]);
>   c.v[2] = b.v[2] + a.v[2];
>   c.v[2] = std::atan2(std::sin(c.v[2]), std::cos(c.v[2]));
> ```

I'd like to go ahead and fix this now. Just make it `c.v[2] = angles::normalize(c.v[2]);`


<!-- Sent from Reviewable.io -->

2020-04-09 18:19 UTC, c-andy-martin commented
___
*[src/amcl/pf/pf_vector.cpp, line 91 at r5](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M1kb_Qg8iVXmH5GWWv0:-M4V9aMhBF0HtqYhvtew:b-oqeb07) ([raw file](https://github.com/badgertechnologies/amcl/blob/95b6eb20da05f9f418bc7ea0645e69d04bc7dd99/src/amcl/pf/pf_vector.cpp#L91)):*
<details><summary><i>Previously, 12tbuchman (Tyler Buchman) wrote…</i></summary><blockquote>

See previous comments
</blockquote></details>

lets go ahead and fix this now, just make it `c.v[2] = angles::normalize(c.v[2]);`


<!-- Sent from Reviewable.io -->

2020-04-09 18:22 UTC, c-andy-martin commented
___
*[src/amcl/sensors/point_cloud_scanner.cpp, line 172 at r6](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M23tKeM-txJ6nAO32TI:-M4VAIYS7BLh1rR1GL9r:b-ia24bx) ([raw file](https://github.com/badgertechnologies/amcl/blob/9df029774580bad51987f61b64a87071070f819b/src/amcl/sensors/point_cloud_scanner.cpp#L172)):*
<details><summary><i>Previously, 12tbuchman (Tyler Buchman) wrote…</i></summary><blockquote>

I think it was 3.7%, right? What % would you consider important enough?
</blockquote></details>

certainly >10%. depends too on how much total CPU a process is using. If you are using an entire core, any amount is good as it frees up cycles for other things. But I don't think AMCL is taking nearly that much normally. I'd say take a TODO on this


<!-- Sent from Reviewable.io -->

2020-04-09 18:24 UTC, c-andy-martin requested changes
> Reviewed 1 of 19 files at r12.
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/amcl/2)* status: 26 of 49 files reviewed, 66 unresolved discussions (waiting on @12tbuchman and @c-andy-martin)



<!-- Sent from Reviewable.io -->

2020-04-09 18:25 UTC, c-andy-martin commented
___
*[include/amcl/map/occupancy_map.h, line 80 at r9](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M4Uv9YkC9Cae7Mi8UpY:-M4VAuWX3KpDjRIEQNcH:bi1iy2h) ([raw file](https://github.com/badgertechnologies/amcl/blob/b28c573d53c54b2904a0c476e86e7f24b8cd83ff/include/amcl/map/occupancy_map.h#L80)):*
<details><summary><i>Previously, 12tbuchman (Tyler Buchman) wrote…</i></summary><blockquote>

Is the reason we should inline this function because it is part of the bottleneck?
</blockquote></details>

well, you mentioned elsewhere to not make it virtual b/c you were worried about performance. I haven't checked the profile to see. But if this is a bottle-neck, yes, mark it `inline` and provide the definition here w/ the declaration so it can actually be inlined.


<!-- Sent from Reviewable.io -->

2020-04-09 18:26 UTC, 12tbuchman reviewed
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/amcl/2)* status: 26 of 49 files reviewed, 66 unresolved discussions (waiting on @12tbuchman and @c-andy-martin)

___
*[src/amcl/map/occupancy_map.cpp, line 100 at r6](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M24Jnx1BcaNQlYvcywk:-M4VBBLh3sDHdRypf_gQ:b-896fix) ([raw file](https://github.com/badgertechnologies/amcl/blob/9df029774580bad51987f61b64a87071070f819b/src/amcl/map/occupancy_map.cpp#L100)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

I'm OK leaving this as is, as long as we add a comment like this here:
```
/*
 *This legacy code centers the map at 0, 0.
 *It could be made to have the origin at the bottom left similar to nav_msgs/OccupancyGrid.
 * However, the potential for breaking the code is there, so this is left as-is.
 */
```
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-04-09 18:27 UTC, c-andy-martin commented
___
*[include/amcl/map/occupancy_map.h, line 109 at r9](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M2eHh8H09SCfT9WCY9z:-M4VBK-K6uPRGtwQRZiK:bkb7u4t) ([raw file](https://github.com/badgertechnologies/amcl/blob/b28c573d53c54b2904a0c476e86e7f24b8cd83ff/include/amcl/map/occupancy_map.h#L109)):*
<details><summary><i>Previously, 12tbuchman (Tyler Buchman) wrote…</i></summary><blockquote>

wait nevermind, that was the CachedDistanceMap and I dont think I can put that in the class and have the constructor in the .cpp file. Anyway I just took out the CellData struct when I was trying to refactor the friend override function for readability, but I put the struct back in the main class now.
</blockquote></details>

If you want the constructor, or any inner classes implementation in the .cpp file, it works fine, you just have to keep qualifying the name, like this, in the cpp file:
```
OccupancyMap::OccupancyMapCellData::OccupancyMapCellData()
{
  ...
```
I think this is OK now


<!-- Sent from Reviewable.io -->

2020-04-09 18:31 UTC, 12tbuchman reviewed
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/amcl/2)* status: 26 of 49 files reviewed, 66 unresolved discussions (waiting on @12tbuchman and @c-andy-martin)

___
*[src/amcl/node/node.cpp, line 649 at r7](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M2ZivBr97feK6_Mz8jL:-M4VCKjTAoWhSRR_pxFQ:b-axp0nb) ([raw file](https://github.com/badgertechnologies/amcl/blob/74db8df1672f2baaecdf854cea1efd100f551c8b/src/amcl/node/node.cpp#L649)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

no, its not trivial to call `.inverse()`, the matrix needs to stay the same during the entire computation or you could get incorrect results. Matrices are not atomic. If you require the caller to hold a lock, you should document that in the header something like `// caller must be holding tf_mutex_`, but if the tf_mutex_ isn't needed anywhere else in save_pose, you should only hold it here. You want to hold a mutex for the minimum required time.
</blockquote></details>

It is needed throughout save_pose. Done.


<!-- Sent from Reviewable.io -->

2020-04-09 18:34 UTC, 12tbuchman reviewed
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/amcl/2)* status: 26 of 49 files reviewed, 66 unresolved discussions (waiting on @12tbuchman and @c-andy-martin)

___
*[src/amcl/node/node.cpp, line 649 at r7](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M2ZivBr97feK6_Mz8jL:-M4VD4b841fRBFy8xNeJ:b-p2bwve) ([raw file](https://github.com/badgertechnologies/amcl/blob/74db8df1672f2baaecdf854cea1efd100f551c8b/src/amcl/node/node.cpp#L649)):*
<details><summary><i>Previously, 12tbuchman (Tyler Buchman) wrote…</i></summary><blockquote>

It is needed throughout save_pose. Done.
</blockquote></details>

I am holding the lock in savePoseToFile because that gets called from main.cpp. I will also hold the lock in savePoseToServer.


<!-- Sent from Reviewable.io -->

2020-04-09 18:36 UTC, 12tbuchman reviewed
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/amcl/2)* status: 26 of 49 files reviewed, 66 unresolved discussions (waiting on @12tbuchman and @c-andy-martin)

___
*[src/amcl/node/node.cpp, line 727 at r7](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M2FS3ncA8K2V1_iNtk6:-M4VDZml0Y-a4Ah2sVMG:bv1jg11) ([raw file](https://github.com/badgertechnologies/amcl/blob/74db8df1672f2baaecdf854cea1efd100f551c8b/src/amcl/node/node.cpp#L727)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

It shouldn't be here because AMCL should have no knowledge about how system paths are organized, or any references to badger-specific environment variables. Those things belong at the system integration layer, as the system may have need to put them in different places depending on how/where the code is run. I see you already removed this, so this is now OK.
</blockquote></details>

sorry, when I was looking at this earlier I thought you were referring to initFromNewMap


<!-- Sent from Reviewable.io -->

2020-04-09 18:37 UTC, 12tbuchman reviewed
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/amcl/2)* status: 26 of 49 files reviewed, 66 unresolved discussions (waiting on @12tbuchman and @c-andy-martin)

___
*[src/amcl/node/node.cpp, line 727 at r7](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M2FS3ncA8K2V1_iNtk6:-M4VDo-UE8lwfbFI4KDM:b-9lv1qk) ([raw file](https://github.com/badgertechnologies/amcl/blob/74db8df1672f2baaecdf854cea1efd100f551c8b/src/amcl/node/node.cpp#L727)):*
<details><summary><i>Previously, 12tbuchman (Tyler Buchman) wrote…</i></summary><blockquote>

sorry, when I was looking at this earlier I thought you were referring to initFromNewMap
</blockquote></details>

I think thats because I had already deleted the function.


<!-- Sent from Reviewable.io -->

2020-04-09 18:38 UTC, 12tbuchman reviewed
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/amcl/2)* status: 26 of 49 files reviewed, 66 unresolved discussions (waiting on @12tbuchman and @c-andy-martin)

___
*[src/amcl/node/node.cpp, line 863 at r12](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M4V1vt68fyy2wKR6ltX:-M4VE7Ti--Y7BMdfjr2q:b-896fix) ([raw file](https://github.com/badgertechnologies/amcl/blob/69e2d9799639a29b8b666212f628f28b703e35ef/src/amcl/node/node.cpp#L863)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

drand48 comes from `<stdlib.h>` (POSIX) and should be the first include in the file (as a system header)
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-04-09 18:45 UTC, c-andy-martin commented
___
*[src/amcl/node/node_3d.cpp, line 332 at r7](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M2FSrlIBtDhVJJM-mY1:-M4VFF5pBdFgHIrD22HM:b-ystfzu) ([raw file](https://github.com/badgertechnologies/amcl/blob/74db8df1672f2baaecdf854cea1efd100f551c8b/src/amcl/node/node_3d.cpp#L332)):*
<details><summary><i>Previously, 12tbuchman (Tyler Buchman) wrote…</i></summary><blockquote>

So having looked more into this, I will correct myself that we already wait for the Occupancy Map to arrive before setting the free space indices. However, to use the Occupancy Map means we need to fully initialize that map, which currently we don't do. Do you think it is worth initializing the 2D map to be able to reduce the free space indices here? My reasoning for saying maybe not is that I would think we will be cleaning the 3D maps like we do the 2D maps, and then we can improve this section to use only free spaces. However maybe my assumption is not true. Even if my assumption isnt true, the question remains if it is worth it to initialize the 2D map.
</blockquote></details>

I would assume we will never clean the 3D map. It is too much work. Yes, I think it is worth it to initialize the 2D map to get the free space indices from 2D. However, it is only really worth it when doing global localization and allowing the robot to move so that it can down-score poses that move through occupied things on the 2D map. So, I think what we should do, is make a comment here that we consider every space free for 3D because 3D maps often have too much noise when they are collected, and that it would be better to use the 2D map, which is often cleaned up, for figuring out if the pose is valid. Then, also take a TODO to initializing the 2D map (and seeing how expensive that is) and using it for the free space pose stuff.


<!-- Sent from Reviewable.io -->

2020-04-09 18:45 UTC, c-andy-martin reviewed
> Reviewed 3 of 38 files at r10.
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/amcl/2)* status: 28 of 49 files reviewed, 63 unresolved discussions (waiting on @12tbuchman and @c-andy-martin)



<!-- Sent from Reviewable.io -->

2020-04-09 18:47 UTC, 12tbuchman reviewed
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/amcl/2)* status: 28 of 49 files reviewed, 60 unresolved discussions (waiting on @12tbuchman and @c-andy-martin)

___
*[src/amcl/node/node.cpp, line 649 at r7](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M2ZivBr97feK6_Mz8jL:-M4VFh4d9p7yHyO547ac:bhj5gvh) ([raw file](https://github.com/badgertechnologies/amcl/blob/74db8df1672f2baaecdf854cea1efd100f551c8b/src/amcl/node/node.cpp#L649)):*
<details><summary><i>Previously, 12tbuchman (Tyler Buchman) wrote…</i></summary><blockquote>

I am holding the lock in savePoseToFile because that gets called from main.cpp. I will also hold the lock in savePoseToServer.
</blockquote></details>

Ignore that, they are different locks.


<!-- Sent from Reviewable.io -->

2020-04-09 18:52 UTC, c-andy-martin commented
___
*[src/amcl/node/node_3d.cpp, line 559 at r12](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M4VGIRNDc-JV070KO7t:-M4VGIRNDc-JV070KO7u:b-ok0783) ([raw file](https://github.com/badgertechnologies/amcl/blob/69e2d9799639a29b8b666212f628f28b703e35ef/src/amcl/node/node_3d.cpp#L559)):*
> ```cpp
>   if (d > scanner_check_interval_)
>   {
>     ROS_DEBUG_STREAM("No point cloud scan received (and thus no pose updates have been published) for " << d.toSec()
> ```

the `.toSec()` is unnecessary here, I would delete it. ROS's CPP library provides an `operator<<` for `ros::Duration`.


<!-- Sent from Reviewable.io -->

2020-04-09 18:53 UTC, c-andy-martin commented
___
*[src/amcl/pf/particle_filter.cpp, line 32 at r7](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M2AOwVw9SkM1FYJK_WQ:-M4VHbKX0s0Oaf0WmzjM:b-uazs9o) ([raw file](https://github.com/badgertechnologies/amcl/blob/74db8df1672f2baaecdf854cea1efd100f551c8b/src/amcl/pf/particle_filter.cpp#L32)):*
<details><summary><i>Previously, 12tbuchman (Tyler Buchman) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I'm wrong about this, as we need stdlib.h for drand48.


<!-- Sent from Reviewable.io -->

2020-04-09 18:55 UTC, c-andy-martin reviewed
> Reviewed 5 of 19 files at r12.
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/amcl/2)* status: 33 of 49 files reviewed, 46 unresolved discussions (waiting on @12tbuchman and @c-andy-martin)



<!-- Sent from Reviewable.io -->

2020-04-09 19:02 UTC, 12tbuchman reviewed
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/amcl/2)* status: 33 of 49 files reviewed, 46 unresolved discussions (waiting on @12tbuchman and @c-andy-martin)

___
*[src/amcl/pf/pdf_gaussian.cpp, line 20 at r12](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M4V2HRvES0zllhpAfDo:-M4VJcJEDJElmDD4edaE:b-896fix) ([raw file](https://github.com/badgertechnologies/amcl/blob/69e2d9799639a29b8b666212f628f28b703e35ef/src/amcl/pf/pdf_gaussian.cpp#L20)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

we need to add `<stdlib.h>` for drand48
</blockquote></details>

Done.
___
*[src/amcl/pf/particle_filter.cpp, line 20 at r12](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M4V2AGB1sQwqbKV_Hng:-M4VJbHZ76hcfTt4jFGt:b-896fix) ([raw file](https://github.com/badgertechnologies/amcl/blob/69e2d9799639a29b8b666212f628f28b703e35ef/src/amcl/pf/particle_filter.cpp#L20)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

we need to add `<stdlib.h>` for `drand48`
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-04-09 19:03 UTC, c-andy-martin commented
___
*[src/amcl/node/node.cpp, line 198 at r7](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M2FQPRL1lubOJj3i5bp:-M4VJs3Y8uJy--jXsqLQ:blbr4ni) ([raw file](https://github.com/badgertechnologies/amcl/blob/74db8df1672f2baaecdf854cea1efd100f551c8b/src/amcl/node/node.cpp#L198)):*
<details><summary><i>Previously, 12tbuchman (Tyler Buchman) wrote…</i></summary><blockquote>

If we are going to do that Id like to talk about which parameters should be static and which should be dynamic.
</blockquote></details>

Let's leave this as is for now. I'm OK with it.


<!-- Sent from Reviewable.io -->

2020-04-09 19:03 UTC, c-andy-martin reviewed
> Reviewed 2 of 38 files at r10, 9 of 30 files at r11, 4 of 19 files at r12.
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/amcl/2)* status: 47 of 49 files reviewed, 40 unresolved discussions (waiting on @12tbuchman and @c-andy-martin)



<!-- Sent from Reviewable.io -->

2020-04-09 19:05 UTC, c-andy-martin commented
___
*[src/amcl/node/node_2d.cpp, line 512 at r7](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M2ZlkihDAYdw49Hsen2:-M4VKHgD-kRNvbLpMJeX:bsx65vy) ([raw file](https://github.com/badgertechnologies/amcl/blob/74db8df1672f2baaecdf854cea1efd100f551c8b/src/amcl/node/node_2d.cpp#L512)):*
<details><summary><i>Previously, 12tbuchman (Tyler Buchman) wrote…</i></summary><blockquote>

there is a TODO for this
</blockquote></details>

let's just go ahead and do it, its easy enough, just `angles::normalize(*angle_increment);`


<!-- Sent from Reviewable.io -->

2020-04-09 19:06 UTC, c-andy-martin requested changes
> Reviewed 2 of 19 files at r12.
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/amcl/2)* status: all files reviewed, 35 unresolved discussions (waiting on @12tbuchman and @c-andy-martin)

___
*[src/amcl/node/node_2d.cpp, line 620 at r12](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M4VKOhY61pKUW-hR4rE:-M4VKOhY61pKUW-hR4rF:b65ga14) ([raw file](https://github.com/badgertechnologies/amcl/blob/69e2d9799639a29b8b666212f628f28b703e35ef/src/amcl/node/node_2d.cpp#L620)):*
> ```cpp
>   if (d > check_scanner_interval_)
>   {
>     ROS_WARN_STREAM("No planar scan received (and thus no pose updates have been published) for " << d.toSec()
> ```

this `.toSec()` is unnecessary, I'd delete it.


<!-- Sent from Reviewable.io -->

2020-04-09 19:55 UTC, 12tbuchman reviewed
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/amcl/2)* status: all files reviewed, 30 unresolved discussions (waiting on @12tbuchman and @c-andy-martin)

___
*[include/amcl/pf/pf_kdtree.h, line 97 at r12](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M4V2wrO1ah_yMRKgKKX:-M4VLpukAlDp9K94aH2U:b-896fix) ([raw file](https://github.com/badgertechnologies/amcl/blob/69e2d9799639a29b8b666212f628f28b703e35ef/include/amcl/pf/pf_kdtree.h#L97)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

node_count_ is now redundant with nodes_.size(). Remove node_count_ in favor of various calls in std::vector (for instance, if you need the address of the last node, use `.back()`
</blockquote></details>

Done.
___
*[include/amcl/pf/pf_kdtree.h, line 98 at r12](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M4V35w0CdWpP8Y9qu1J:-M4VLySq4zdmcqanSUtk:b-896fix) ([raw file](https://github.com/badgertechnologies/amcl/blob/69e2d9799639a29b8b666212f628f28b703e35ef/include/amcl/pf/pf_kdtree.h#L98)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

I don't think the vector needs to store pointers. Just make this a vector of `PFKDTreeNode`
</blockquote></details>

Done.
___
*[src/amcl/pf/pf_kdtree.cpp, line 41 at r12](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M4V6YDV9fi7uumlW82D:-M4VMD6x0bY3J1QzIyBe:b-896fix) ([raw file](https://github.com/badgertechnologies/amcl/blob/69e2d9799639a29b8b666212f628f28b703e35ef/src/amcl/pf/pf_kdtree.cpp#L41)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

this goes away when you remove node_count_
</blockquote></details>

Done.
___
*[src/amcl/pf/pf_kdtree.cpp, line 50 at r12](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M4V6_nYDqSAU7RK5TuK:-M4VMDSB6b0tbbQ0ZaZz:b-896fix) ([raw file](https://github.com/badgertechnologies/amcl/blob/69e2d9799639a29b8b666212f628f28b703e35ef/src/amcl/pf/pf_kdtree.cpp#L50)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

this goes away too
</blockquote></details>

Done.
___
*[src/amcl/pf/pf_kdtree.cpp, line 94 at r12](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M4V6cF46TJdIM3oP-qm:-M4VMFEX2I8jV--ikwXJ:b-896fix) ([raw file](https://github.com/badgertechnologies/amcl/blob/69e2d9799639a29b8b666212f628f28b703e35ef/src/amcl/pf/pf_kdtree.cpp#L94)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

these two lines become:
```
    nodes_.resize(nodes_.size() + 1);
    node = &nodes_.back();
```
when you get rid of node_count and switch to directly holding the nodes in the vector
 
</blockquote></details>

Done.
___
*[src/amcl/pf/pf_kdtree.cpp, line 195 at r12](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M4V3hMn84eTOwekrSqt:-M4VUQazDpcXN4XQJPKe:b-896fix) ([raw file](https://github.com/badgertechnologies/amcl/blob/69e2d9799639a29b8b666212f628f28b703e35ef/src/amcl/pf/pf_kdtree.cpp#L195)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

I would like to rewrite this function to be (assuming you make the vector directly hold nodes and not unique_ptr):
```
// Cluster the leaves in the tree
void PFKDTree::cluster()
{ 
  int cluster_count = 0;

  for (auto node : nodes_)
  {
    node.cluster = -1;
  }
  
  // Do connected components for each node
  for (auto node : nodes_)
  {
    // If this node has already been labelled, skip it
    if (node.cluster < 0)
    {
      // Assign a label to this cluster 
      node.cluster = cluster_count++;
      // Recursively label nodes in this cluster
      clusterNode(&node, 0);
    }
  }
}
```
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-04-09 19:59 UTC, 12tbuchman reviewed
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/amcl/2)* status: all files reviewed, 30 unresolved discussions (waiting on @12tbuchman and @c-andy-martin)

___
*[src/amcl/sensors/point_cloud_scanner.cpp, line 172 at r6](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M23tKeM-txJ6nAO32TI:-M4VWPsf03ioWTdoZRwH:b-tsdsxq) ([raw file](https://github.com/badgertechnologies/amcl/blob/9df029774580bad51987f61b64a87071070f819b/src/amcl/sensors/point_cloud_scanner.cpp#L172)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

certainly >10%. depends too on how much total CPU a process is using. If you are using an entire core, any amount is good as it frees up cycles for other things. But I don't think AMCL is taking nearly that much normally. I'd say take a TODO on this
</blockquote></details>

What kind of resolution would you want on the LUT? z can be an infinite number of values with infinite precision. Therefore, the LUT would be infinite with infinite precision as well, no?


<!-- Sent from Reviewable.io -->

2020-04-09 20:00 UTC, 12tbuchman reviewed
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/amcl/2)* status: all files reviewed, 30 unresolved discussions (waiting on @12tbuchman and @c-andy-martin)

___
*[include/amcl/map/occupancy_map.h, line 80 at r9](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M4Uv9YkC9Cae7Mi8UpY:-M4VWjH67Ph6XoHFu4Po:b-pcwgp0) ([raw file](https://github.com/badgertechnologies/amcl/blob/b28c573d53c54b2904a0c476e86e7f24b8cd83ff/include/amcl/map/occupancy_map.h#L80)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

well, you mentioned elsewhere to not make it virtual b/c you were worried about performance. I haven't checked the profile to see. But if this is a bottle-neck, yes, mark it `inline` and provide the definition here w/ the declaration so it can actually be inlined.
</blockquote></details>

I guess it was a general question about the improvement made by inlining


<!-- Sent from Reviewable.io -->

2020-04-09 21:19 UTC, 12tbuchman reviewed
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/amcl/2)* status: all files reviewed, 30 unresolved discussions (waiting on @12tbuchman and @c-andy-martin)

___
*[src/amcl/node/node_3d.cpp, line 332 at r7](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M2FSrlIBtDhVJJM-mY1:-M4VnEs6DMsPwMPpvqa6:b-896fix) ([raw file](https://github.com/badgertechnologies/amcl/blob/74db8df1672f2baaecdf854cea1efd100f551c8b/src/amcl/node/node_3d.cpp#L332)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

I would assume we will never clean the 3D map. It is too much work. Yes, I think it is worth it to initialize the 2D map to get the free space indices from 2D. However, it is only really worth it when doing global localization and allowing the robot to move so that it can down-score poses that move through occupied things on the 2D map. So, I think what we should do, is make a comment here that we consider every space free for 3D because 3D maps often have too much noise when they are collected, and that it would be better to use the 2D map, which is often cleaned up, for figuring out if the pose is valid. Then, also take a TODO to initializing the 2D map (and seeing how expensive that is) and using it for the free space pose stuff.
</blockquote></details>

Done.
___
*[src/amcl/node/node_3d.cpp, line 559 at r12](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M4VGIRNDc-JV070KO7t:-M4VnrYwEYMikJMNyRok:b-896fix) ([raw file](https://github.com/badgertechnologies/amcl/blob/69e2d9799639a29b8b666212f628f28b703e35ef/src/amcl/node/node_3d.cpp#L559)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

the `.toSec()` is unnecessary here, I would delete it. ROS's CPP library provides an `operator<<` for `ros::Duration`.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-04-09 21:20 UTC, 12tbuchman reviewed
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/amcl/2)* status: all files reviewed, 30 unresolved discussions (waiting on @12tbuchman and @c-andy-martin)

___
*[src/amcl/node/node_2d.cpp, line 620 at r12](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M4VKOhY61pKUW-hR4rE:-M4Vo6iXDyS24JQUzxec:b-896fix) ([raw file](https://github.com/badgertechnologies/amcl/blob/69e2d9799639a29b8b666212f628f28b703e35ef/src/amcl/node/node_2d.cpp#L620)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

this `.toSec()` is unnecessary, I'd delete it.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-04-10 18:09 UTC, 12tbuchman reviewed
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/amcl/2)* status: all files reviewed, 30 unresolved discussions (waiting on @12tbuchman and @c-andy-martin)

___
*[src/amcl/pf/pf_vector.cpp, line 75 at r12](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M4V8WMu8pWFrREGm112:-M4_GXcL4GdTMRBx2Imv:b-896fix) ([raw file](https://github.com/badgertechnologies/amcl/blob/69e2d9799639a29b8b666212f628f28b703e35ef/src/amcl/pf/pf_vector.cpp#L75)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

I'd like to go ahead and fix this now. Just make it `c.v[2] = angles::normalize(c.v[2]);`
</blockquote></details>

Done.
___
*[src/amcl/sensors/odom.cpp, line 307 at r5](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M1kdrAM32YRHjqjCFYj:-M4_H2UzDpFXBz7rcZ0h:b-896fix) ([raw file](https://github.com/badgertechnologies/amcl/blob/95b6eb20da05f9f418bc7ea0645e69d04bc7dd99/src/amcl/sensors/odom.cpp#L307)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

I'm not convinced that this code is even correct.  for instance, if the angles passed in are > 4pi I think this gets the wrong answer. You are already using `shortest_angular_distance` elsewhere, just change this whole function to `return angles::shortest_angular_distance(a, b);`
</blockquote></details>

Done.
___
*[src/amcl/sensors/odom.cpp, line 315 at r12](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M4V88sy7EwzoSlADTgW:-M4_H2m9631eZHxPpTzb:b-896fix) ([raw file](https://github.com/badgertechnologies/amcl/blob/69e2d9799639a29b8b666212f628f28b703e35ef/src/amcl/sensors/odom.cpp#L315)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

Just change this to `return angles::normalize_angle(z);`
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-04-10 19:10 UTC, 12tbuchman reviewed
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/amcl/2)* status: 34 of 49 files reviewed, 30 unresolved discussions (waiting on @c-andy-martin)

___
*[src/amcl/node/node_2d.cpp, line 512 at r7](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M2ZlkihDAYdw49Hsen2:-M4_V-HCBhZ8HPdp3vWh:b-896fix) ([raw file](https://github.com/badgertechnologies/amcl/blob/74db8df1672f2baaecdf854cea1efd100f551c8b/src/amcl/node/node_2d.cpp#L512)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

let's just go ahead and do it, its easy enough, just `angles::normalize(*angle_increment);`
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-04-10 19:18 UTC, c-andy-martin commented
___
*[include/amcl/pf/pf_kdtree.h, line 98 at r12](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M4V35w0CdWpP8Y9qu1J:-M4_WTBM2E5DSsDskSmw:b3829n5) ([raw file](https://github.com/badgertechnologies/amcl/blob/69e2d9799639a29b8b666212f628f28b703e35ef/include/amcl/pf/pf_kdtree.h#L98)):*
<details><summary><i>Previously, 12tbuchman (Tyler Buchman) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

After looking at how this class is used, I think it would be good to make this a `std::deque<PFKDTreeNode>` as per my suggestion before so we don't have to new/delete a bunch of memory on every particle filter update cycle. The code should be the same as I suggested before, except making this a `std::deque` so the memory is never invalidated.


<!-- Sent from Reviewable.io -->

2020-04-10 19:19 UTC, c-andy-martin commented
___
*[src/amcl/map/occupancy_map.cpp, line 77 at r13](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M4_X9qSBmsDfDZtXXUM:-M4_X3uBEcahXPV7KRNV:b-s7hfvm) ([raw file](https://github.com/badgertechnologies/amcl/blob/2e69b6c66cf8f5689d0038e906fe7b8368d334c7/src/amcl/map/occupancy_map.cpp#L77)):*
> ```cpp
>   int j = map_coords[1];
>   /*
>   * This legacy code centers the map at 0, 0.
> ```

I think the `*` should line up with the `*` above it by adding one whitespace in front of each of these lines.


<!-- Sent from Reviewable.io -->

2020-04-10 19:23 UTC, c-andy-martin commented
___
*[src/amcl/node/node_2d.cpp, line 23 at r13](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M4_XmKd7PVDRz2T8I6C:-M4_XmKd7PVDRz2T8I6D:b-wtf9c3) ([raw file](https://github.com/badgertechnologies/amcl/blob/2e69b6c66cf8f5689d0038e906fe7b8368d334c7/src/amcl/node/node_2d.cpp#L23)):*
> ```cpp
> 
> #include <angles/angles.h>
> #include <boost/bind.hpp>
> ```

lets remove boost bind everywhere in favor of std::bind. We are using both in various places, std::bind is the current correct best practice way to do this since we are using C++11.


<!-- Sent from Reviewable.io -->

2020-04-10 19:25 UTC, c-andy-martin commented
___
*[src/amcl/pf/pf_kdtree.cpp, line 195 at r12](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M4V3hMn84eTOwekrSqt:-M4_YFJB64-VtrY0RiJB:boymm7u) ([raw file](https://github.com/badgertechnologies/amcl/blob/69e2d9799639a29b8b666212f628f28b703e35ef/src/amcl/pf/pf_kdtree.cpp#L195)):*
<details><summary><i>Previously, 12tbuchman (Tyler Buchman) wrote…</i></summary><blockquote>

Done.
</blockquote></details>


as i mentioned in a separate comment, lets make this `std::deque<PFKDTreeNode>`to avoid the dynamic memory. I also would like to use the `for (auto node : nodes_)` as its faster than using `operator[]`


<!-- Sent from Reviewable.io -->

2020-04-10 19:29 UTC, c-andy-martin commented
___
*[src/amcl/sensors/point_cloud_scanner.cpp, line 172 at r6](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M23tKeM-txJ6nAO32TI:-M4_Yc2M8-cMscupgQlq:b-g0wvh1) ([raw file](https://github.com/badgertechnologies/amcl/blob/9df029774580bad51987f61b64a87071070f819b/src/amcl/sensors/point_cloud_scanner.cpp#L172)):*
<details><summary><i>Previously, 12tbuchman (Tyler Buchman) wrote…</i></summary><blockquote>

What kind of resolution would you want on the LUT? z can be an infinite number of values with infinite precision. Therefore, the LUT would be infinite with infinite precision as well, no?
</blockquote></details>

no, the z comes from one of the finite values from getOccDist, it can only have one of the values from the `distances_` array (or the max dist) in the Octomap or OccupancyMap class. there are only a handful of distinct values, depending on what max dist is.


<!-- Sent from Reviewable.io -->

2020-04-10 19:29 UTC, c-andy-martin reviewed
> Reviewed 15 of 15 files at r13.
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/amcl/2)* status: all files reviewed, 5 unresolved discussions (waiting on @12tbuchman)



<!-- Sent from Reviewable.io -->

2020-04-12 15:59 UTC, 12tbuchman reviewed
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/amcl/2)* status: all files reviewed, 5 unresolved discussions (waiting on @12tbuchman and @c-andy-martin)

___
*[src/amcl/sensors/point_cloud_scanner.cpp, line 172 at r6](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M23tKeM-txJ6nAO32TI:-M4j4y1nDyvK8bOXyNb9:b-s0iebf) ([raw file](https://github.com/badgertechnologies/amcl/blob/9df029774580bad51987f61b64a87071070f819b/src/amcl/sensors/point_cloud_scanner.cpp#L172)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

no, the z comes from one of the finite values from getOccDist, it can only have one of the values from the `distances_` array (or the max dist) in the Octomap or OccupancyMap class. there are only a handful of distinct values, depending on what max dist is.
</blockquote></details>

so basically replace the distances lut with an lut of the result of this exp? or would you want to have both? If we wanted only 1 we would have to pass in sigma hit to the map class and create the z_hit_denom there. The function would have to be renamed to something like getOccGaussInt and then in the CellData class within operator< overload we would refactor that to:
```
inline bool operator<(const OctoMapCellData& b) const
    {
      return octo_map->getOccGaussInt(i, j, k) < b.octo_map->getOccGaussInt(b.i, b.j, b.k);
    }
```


<!-- Sent from Reviewable.io -->

2020-04-13 14:47 UTC, 12tbuchman reviewed
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/amcl/2)* status: all files reviewed, 5 unresolved discussions (waiting on @c-andy-martin)

___
*[src/amcl/map/occupancy_map.cpp, line 77 at r13](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M4_X9qSBmsDfDZtXXUM:-M4nrvdT5FM7dGB3a2z_:b-896fix) ([raw file](https://github.com/badgertechnologies/amcl/blob/2e69b6c66cf8f5689d0038e906fe7b8368d334c7/src/amcl/map/occupancy_map.cpp#L77)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

I think the `*` should line up with the `*` above it by adding one whitespace in front of each of these lines.
</blockquote></details>

Done.
___
*[src/amcl/node/node_2d.cpp, line 23 at r13](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M4_XmKd7PVDRz2T8I6C:-M4nvpb99FnsHr3xD-h8:b-896fix) ([raw file](https://github.com/badgertechnologies/amcl/blob/2e69b6c66cf8f5689d0038e906fe7b8368d334c7/src/amcl/node/node_2d.cpp#L23)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

lets remove boost bind everywhere in favor of std::bind. We are using both in various places, std::bind is the current correct best practice way to do this since we are using C++11.
</blockquote></details>

Done.
___
*[src/amcl/pf/pf_kdtree.cpp, line 195 at r12](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M4V3hMn84eTOwekrSqt:-M4nvtU01PqbuEm6uiHh:b5ui5j0) ([raw file](https://github.com/badgertechnologies/amcl/blob/69e2d9799639a29b8b666212f628f28b703e35ef/src/amcl/pf/pf_kdtree.cpp#L195)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

as i mentioned in a separate comment, lets make this `std::deque<PFKDTreeNode>`to avoid the dynamic memory. I also would like to use the `for (auto node : nodes_)` as its faster than using `operator[]`
</blockquote></details>

With a unique_ptr it isnt possible to do a for each loop because the copy constructor is blocked. Ive converted it to a deque though so now it can use the for each loop.


<!-- Sent from Reviewable.io -->

2020-04-13 15:45 UTC, c-andy-martin commented
___
*[src/amcl/sensors/point_cloud_scanner.cpp, line 172 at r6](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M23tKeM-txJ6nAO32TI:-M4oB3kYBXj2FyTVoqzn:bls0xki) ([raw file](https://github.com/badgertechnologies/amcl/blob/9df029774580bad51987f61b64a87071070f819b/src/amcl/sensors/point_cloud_scanner.cpp#L172)):*
<details><summary><i>Previously, 12tbuchman (Tyler Buchman) wrote…</i></summary><blockquote>

so basically replace the distances lut with an lut of the result of this exp? or would you want to have both? If we wanted only 1 we would have to pass in sigma hit to the map class and create the z_hit_denom there. The function would have to be renamed to something like getOccGaussInt and then in the CellData class within operator< overload we would refactor that to:
```
inline bool operator<(const OctoMapCellData& b) const
    {
      return octo_map->getOccGaussInt(i, j, k) < b.octo_map->getOccGaussInt(b.i, b.j, b.k);
    }
```
</blockquote></details>

I don't want to replace the normal distance LUT, as there may be times we want the distance itself (such as weighting poses for global localization). There may not be such a use yet, but I'd rather not make it overly complicated. If we change the distance lut to store 3 uint8_t values which is the absolute i, j, k from the looked up cell to the nearest obstacle cell, we could then lookup the distance value using the LUT that already exists for that by i, j, k, or if we want the sigma lut (which we are inventing here) we would lookup using the simga lut (which would be precalcualted to be the possible exp values). Does that make sense? Would you rather table this for now as a TODO and copy all this info somewhere?


<!-- Sent from Reviewable.io -->

2020-04-13 15:46 UTC, c-andy-martin reviewed
> Reviewed 7 of 7 files at r14.
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/amcl/2)* status: all files reviewed, 1 unresolved discussion (waiting on @12tbuchman)



<!-- Sent from Reviewable.io -->

2020-04-13 16:04 UTC, 12tbuchman reviewed
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/amcl/2)* status: all files reviewed, 1 unresolved discussion (waiting on @c-andy-martin)

___
*[src/amcl/sensors/point_cloud_scanner.cpp, line 172 at r6](https://reviewable.io/reviews/badgertechnologies/amcl/2#-M23tKeM-txJ6nAO32TI:-M4oHGoy5j622H28MgQ-:bm63mhk) ([raw file](https://github.com/badgertechnologies/amcl/blob/9df029774580bad51987f61b64a87071070f819b/src/amcl/sensors/point_cloud_scanner.cpp#L172)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

I don't want to replace the normal distance LUT, as there may be times we want the distance itself (such as weighting poses for global localization). There may not be such a use yet, but I'd rather not make it overly complicated. If we change the distance lut to store 3 uint8_t values which is the absolute i, j, k from the looked up cell to the nearest obstacle cell, we could then lookup the distance value using the LUT that already exists for that by i, j, k, or if we want the sigma lut (which we are inventing here) we would lookup using the simga lut (which would be precalcualted to be the possible exp values). Does that make sense? Would you rather table this for now as a TODO and copy all this info somewhere?
</blockquote></details>

Lets make this a TODO


<!-- Sent from Reviewable.io -->

2020-04-13 17:26 UTC, c-andy-martin approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> Great work Tyler!

> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/amcl/2#-:-M4oZtg_CQgewrRnzukv:bggzcze)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2020-04-13 17:31 UTC, merged