Setting global localization active to true
BadgerTechnologies/badger_amcl pull request #21
Opened 2022-03-02 20:11 UTC by Ibrahim-Apata

Added Succes and Failure percentage logs
Adding convergence test after weighing particles
Changing success threshold to a node

Creating an adjustable node that allows us the set a threshold that we use to define and determine when the particles have converged

2022-03-03 17:08 UTC, 12tbuchman requested changes
"Setting global localization active to true" sounds like you are switching a parameter. I would suggest "Adding threshold to global localization convergence"

> Reviewed 2 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/badger_amcl/21#-:-MxFUsJRCgOHJR0TLy5o:bhp4rla)* status: 2 of 3 files reviewed, 9 unresolved discussions (waiting on @12tbuchman and @Ibrahim-Apata)

___
*[src/amcl/node/node_3d.cpp, line 489 at r1](https://reviewable.io/reviews/badgertechnologies/badger_amcl/21#-MxFVJuZ1Hsmnh2ccoDV:-MxFVJuZ1Hsmnh2ccoDW:b-okx9zu) ([raw file](https://github.com/badgertechnologies/badger_amcl/blob/954c1e519bc7f1d57490c8ff6c9497a68104f16b/src/amcl/node/node_3d.cpp#L489)):*
> ```cpp
> {
>   pf_->updateResample();
>   bool isconverged = pf_->isConverged();
> ```

"isconverged" should be "is_converged"

please see https://google.github.io/styleguide/cppguide.html for this and other comments I make regarding style.
___
*[src/amcl/node/node_3d.cpp, line 490 at r1](https://reviewable.io/reviews/badgertechnologies/badger_amcl/21#-MxFVa00DKgQXtjxxvCB:-MxFVa00DKgQXtjxxvCC:b-ccz6v6) ([raw file](https://github.com/badgertechnologies/badger_amcl/blob/954c1e519bc7f1d57490c8ff6c9497a68104f16b/src/amcl/node/node_3d.cpp#L490)):*
> ```cpp
>   pf_->updateResample();
>   bool isconverged = pf_->isConverged();
>   ROS_INFO_STREAM("converged: " << isconverged << ", localization active: " << global_localization_active_);
> ```

Lets change the text to "Global localization convergence:" and we only want to publish this if `global_localization_active_` is true
___
*[src/amcl/pf/particle_filter.cpp, line 22 at r1](https://reviewable.io/reviews/badgertechnologies/badger_amcl/21#-MxFVpbx-jB7NFua-E_h:-MxFVpbyDlvw2lS6Fb6X:bmugpks) ([raw file](https://github.com/badgertechnologies/badger_amcl/blob/954c1e519bc7f1d57490c8ff6c9497a68104f16b/src/amcl/pf/particle_filter.cpp#L22)):*
> ```cpp
> 
> #include "pf/particle_filter.h"
> #include "ros/ros.h"
> ```

what is the reason for each of these includes you are adding? Please make sure the include statements follow the google c++ style guide (should have line space in between sections).
___
*[src/amcl/pf/particle_filter.cpp, line 170 at r1](https://reviewable.io/reviews/badgertechnologies/badger_amcl/21#-MxFW0U28QqVlTxpvCEW:-MxFW0U28QqVlTxpvCEX:bfdnbpo) ([raw file](https://github.com/badgertechnologies/badger_amcl/blob/954c1e519bc7f1d57490c8ff6c9497a68104f16b/src/amcl/pf/particle_filter.cpp#L170)):*
> ```cpp
> void ParticleFilter::updateConverged()
> {
>   ROS_INFO("Looking for Particle Convergence");
> ```

this should be deleted
___
*[src/amcl/pf/particle_filter.cpp, line 173 at r1](https://reviewable.io/reviews/badgertechnologies/badger_amcl/21#-MxFW9Kb3gmN6EF2gAwf:-MxFW9Kb3gmN6EF2gAwg:bhcbkkk) ([raw file](https://github.com/badgertechnologies/badger_amcl/blob/954c1e519bc7f1d57490c8ff6c9497a68104f16b/src/amcl/pf/particle_filter.cpp#L173)):*
> ```cpp
>   int i;
>   // Counting what particles succeed and fail
>   float success;
> ```

Whats the reason you are using floats? I would suggest using ints for counting and doubles for decimal values as this is what we use for other variables
___
*[src/amcl/pf/particle_filter.cpp, line 180 at r1](https://reviewable.io/reviews/badgertechnologies/badger_amcl/21#-MxFWV6o2Y6tUpdmeQQM:-MxFWV6o2Y6tUpdmeQQN:brbyztr) ([raw file](https://github.com/badgertechnologies/badger_amcl/blob/954c1e519bc7f1d57490c8ff6c9497a68104f16b/src/amcl/pf/particle_filter.cpp#L180)):*
> ```cpp
>   ros::NodeHandle node("~");
>   node.getParam("particle_success_threshold", success_threshold);
>   success = 0;
> ```

instead of "success" and "failure", which sound like variables related to the overall convergence, Id suggest "particles_converged" or "particles_not_converged" be counted, and the other value can be inferred by the total number of particles minus the value collected.
___
*[src/amcl/pf/particle_filter.cpp, line 201 at r1](https://reviewable.io/reviews/badgertechnologies/badger_amcl/21#-MxFWJREBjAXmQKlXX_s:-MxFWJREBjAXmQKlXX_t:br3aezl) ([raw file](https://github.com/badgertechnologies/badger_amcl/blob/954c1e519bc7f1d57490c8ff6c9497a68104f16b/src/amcl/pf/particle_filter.cpp#L201)):*
> ```cpp
>   set->converged = true;
>   converged_ = true;
>   ROS_INFO_STREAM("Testing: " << set->sample_count << " Particles");
> ```

Do you need this info message?
___
*[src/amcl/pf/particle_filter.cpp, line 218 at r1](https://reviewable.io/reviews/badgertechnologies/badger_amcl/21#-MxFk8y7CmtudNbsVWem:-MxFk8y7CmtudNbsVWen:b-rdsvhl) ([raw file](https://github.com/badgertechnologies/badger_amcl/blob/954c1e519bc7f1d57490c8ff6c9497a68104f16b/src/amcl/pf/particle_filter.cpp#L218)):*
> ```cpp
>   success_percent = ((success/(failure + success)) * 100);
>   failure_percent = ((failure/(failure + success)) * 100);
>   ROS_INFO_STREAM("Printing Success Percentage: " << success_percent << " %");
> ```

If you want to keep this, please clean up the message to be more understandable when published in the journal
___
*[src/amcl/pf/particle_filter.cpp, line 230 at r1](https://reviewable.io/reviews/badgertechnologies/badger_amcl/21#-MxFkHcxBNOoJCH5hhLm:-MxFkHcxBNOoJCH5hhLn:bxcdlbm) ([raw file](https://github.com/badgertechnologies/badger_amcl/blob/954c1e519bc7f1d57490c8ff6c9497a68104f16b/src/amcl/pf/particle_filter.cpp#L230)):*
> ```cpp
>     set->converged = false;
>     converged_ = false;
>     ROS_INFO("The Particles have NOT converged!");
> ```

Do we need this message?


<!-- Sent from Reviewable.io -->

2022-03-04 14:50 UTC, 12tbuchman requested changes
> Reviewed 2 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/badger_amcl/21)* status: 1 of 3 files reviewed, 9 unresolved discussions (waiting on @12tbuchman and @Ibrahim-Apata)



<!-- Sent from Reviewable.io -->

2022-03-04 14:53 UTC, 12tbuchman requested changes
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/badger_amcl/21)* status: 1 of 3 files reviewed, 4 unresolved discussions (waiting on @12tbuchman and @Ibrahim-Apata)

___
*[-- commits, line 10 at r3](https://reviewable.io/reviews/badgertechnologies/badger_amcl/21#-MxKPrRD0eQm8S7d26In):*
please add the ticket number
___
*[src/amcl/pf/particle_filter.cpp, line 173 at r3](https://reviewable.io/reviews/badgertechnologies/badger_amcl/21#-MxKPg4N9fu5sWWtoztv:-MxKPg4N9fu5sWWtoztw:b-7p4vdj) ([raw file](https://github.com/badgertechnologies/badger_amcl/blob/b18eb323751be188900c4c0042f0978184bc7fe3/src/amcl/pf/particle_filter.cpp#L173)):*
> ```cpp
> void ParticleFilter::updateConverged()
> {
>   double particles_converged;
> ```

this should be an int


<!-- Sent from Reviewable.io -->

2022-03-04 15:08 UTC, 12tbuchman requested changes
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/badger_amcl/21)* status: 1 of 3 files reviewed, 6 unresolved discussions (waiting on @12tbuchman and @Ibrahim-Apata)

___
*[src/amcl/pf/particle_filter.cpp, line 21 at r3](https://reviewable.io/reviews/badgertechnologies/badger_amcl/21#-MxKSpZq4ghBb7doh2yy:-MxKSpZq4ghBb7doh2yz:b-uf1d9a) ([raw file](https://github.com/badgertechnologies/badger_amcl/blob/b18eb323751be188900c4c0042f0978184bc7fe3/src/amcl/pf/particle_filter.cpp#L21)):*
> ```cpp
>  */
> 
> #include "sensors/sensor.h" 
> ```

please review the includes section changes you made.
1. dont re-arrange the include statements, they are in a specific order justified by the C++ style guide
2. please justify the include statements you added. why are they required? make sure to check if the include is already in this .h file. If you need the include and its not in the .h file of this class then you can include it here, but if its not needed or already in the .h file then you should not add it here.
___
*[src/amcl/pf/particle_filter.cpp, line 203 at r3](https://reviewable.io/reviews/badgertechnologies/badger_amcl/21#-MxKSTUf8xSQZb9oL2NT:-MxKSTUf8xSQZb9oL2NU:bmn6664) ([raw file](https://github.com/badgertechnologies/badger_amcl/blob/b18eb323751be188900c4c0042f0978184bc7fe3/src/amcl/pf/particle_filter.cpp#L203)):*
> ```cpp
>   {
>     sample = &(set->samples[sample_index]);
>     if (std::fabs(sample->pose[0] - mean_x) < dist_threshold_
> ```

practically this probably makes little difference, but technically this should be <=
___
*[src/amcl/pf/particle_filter.cpp, line 211 at r3](https://reviewable.io/reviews/badgertechnologies/badger_amcl/21#-MxKSc7v4549owRx5sLa:-MxKSc7v4549owRx5sLb:b-g1kqjy) ([raw file](https://github.com/badgertechnologies/badger_amcl/blob/b18eb323751be188900c4c0042f0978184bc7fe3/src/amcl/pf/particle_filter.cpp#L211)):*
> ```cpp
>   // Calculating what percentage of particles have converged
>   percent_converged = ((particles_converged/(sample_index)) * 100);
>   ROS_INFO_STREAM( percent_converged << "% of the particles are converging");
> ```

extra whitespace


<!-- Sent from Reviewable.io -->

2022-03-04 17:02 UTC, Ibrahim-Apata reviewed
> Reviewed 1 of 3 files at r1, 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/badger_amcl/21)* status: 1 of 3 files reviewed, 6 unresolved discussions (waiting on @12tbuchman and @Ibrahim-Apata)

___
*[-- commits, line 10 at r3](https://reviewable.io/reviews/badgertechnologies/badger_amcl/21#-MxKPrRD0eQm8S7d26In):*
<details><summary><i>Previously, 12tbuchman (Tyler Buchman) wrote…</i></summary><blockquote>

please add the ticket number
</blockquote></details>

Done.
___
*[src/amcl/node/node_3d.cpp, line 490 at r1](https://reviewable.io/reviews/badgertechnologies/badger_amcl/21#-MxFVa00DKgQXtjxxvCB:-MxKsP_W4OITnblmxKmL:b-896fix) ([raw file](https://github.com/badgertechnologies/badger_amcl/blob/954c1e519bc7f1d57490c8ff6c9497a68104f16b/src/amcl/node/node_3d.cpp#L490)):*
<details><summary><i>Previously, 12tbuchman (Tyler Buchman) wrote…</i></summary><blockquote>

Lets change the text to "Global localization convergence:" and we only want to publish this if `global_localization_active_` is true
</blockquote></details>

Done.
___
*[src/amcl/pf/particle_filter.cpp, line 21 at r3](https://reviewable.io/reviews/badgertechnologies/badger_amcl/21#-MxKSpZq4ghBb7doh2yy:-MxKjsCO7blttZLNEerI:bw3bvhj) ([raw file](https://github.com/badgertechnologies/badger_amcl/blob/b18eb323751be188900c4c0042f0978184bc7fe3/src/amcl/pf/particle_filter.cpp#L21)):*
<details><summary><i>Previously, 12tbuchman (Tyler Buchman) wrote…</i></summary><blockquote>

please review the includes section changes you made.
1. dont re-arrange the include statements, they are in a specific order justified by the C++ style guide
2. please justify the include statements you added. why are they required? make sure to check if the include is already in this .h file. If you need the include and its not in the .h file of this class then you can include it here, but if its not needed or already in the .h file then you should not add it here.
</blockquote></details>

1. Done
2. These includes allow us node handles to pull the parameters from the launch files  (lines 175 and 176). I didn't know if there was any other way to do that. If there is a better method let me know.
___
*[src/amcl/pf/particle_filter.cpp, line 173 at r3](https://reviewable.io/reviews/badgertechnologies/badger_amcl/21#-MxKPg4N9fu5sWWtoztv:-MxKk9PD2bWv2W6rtoh8:b-896fix) ([raw file](https://github.com/badgertechnologies/badger_amcl/blob/b18eb323751be188900c4c0042f0978184bc7fe3/src/amcl/pf/particle_filter.cpp#L173)):*
<details><summary><i>Previously, 12tbuchman (Tyler Buchman) wrote…</i></summary><blockquote>

this should be an int
</blockquote></details>

Done.
___
*[src/amcl/pf/particle_filter.cpp, line 203 at r3](https://reviewable.io/reviews/badgertechnologies/badger_amcl/21#-MxKSTUf8xSQZb9oL2NT:-MxKl0EM0vvxdDwt0fb4:b-896fix) ([raw file](https://github.com/badgertechnologies/badger_amcl/blob/b18eb323751be188900c4c0042f0978184bc7fe3/src/amcl/pf/particle_filter.cpp#L203)):*
<details><summary><i>Previously, 12tbuchman (Tyler Buchman) wrote…</i></summary><blockquote>

practically this probably makes little difference, but technically this should be <=
</blockquote></details>

Done.
___
*[src/amcl/pf/particle_filter.cpp, line 211 at r3](https://reviewable.io/reviews/badgertechnologies/badger_amcl/21#-MxKSc7v4549owRx5sLa:-MxKlDQ_6mGkSU7CLPeh:b-896fix) ([raw file](https://github.com/badgertechnologies/badger_amcl/blob/b18eb323751be188900c4c0042f0978184bc7fe3/src/amcl/pf/particle_filter.cpp#L211)):*
<details><summary><i>Previously, 12tbuchman (Tyler Buchman) wrote…</i></summary><blockquote>

extra whitespace
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-03-08 16:22 UTC, 12tbuchman requested changes
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/badger_amcl/21)* status: all files reviewed, 7 unresolved discussions (waiting on @12tbuchman and @Ibrahim-Apata)

___
*[src/amcl/node/node_3d.cpp, line 490 at r1](https://reviewable.io/reviews/badgertechnologies/badger_amcl/21#-MxFVa00DKgQXtjxxvCB:-MxeI2iz8cp0HuQ5PUkx:brtps1g) ([raw file](https://github.com/badgertechnologies/badger_amcl/blob/954c1e519bc7f1d57490c8ff6c9497a68104f16b/src/amcl/node/node_3d.cpp#L490)):*
<details><summary><i>Previously, Ibrahim-Apata wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I dont see the change. I think you changed the wrong info message.
___
*[src/amcl/node/node_3d.cpp, line 493 at r4](https://reviewable.io/reviews/badgertechnologies/badger_amcl/21#-MxeHzda99MZUhGsw2co:-MxeHzdb1E9zYycvfOMH:bt8c32c) ([raw file](https://github.com/badgertechnologies/badger_amcl/blob/72cf745f250c949d49c2b3af17cd2eb37314e79e/src/amcl/node/node_3d.cpp#L493)):*
> ```cpp
>   if (global_localization_active_)
>   {
>     ROS_INFO("Global localization convergence");
> ```

why did you change this to "convergance"?
___
*[src/amcl/pf/particle_filter.cpp, line 21 at r3](https://reviewable.io/reviews/badgertechnologies/badger_amcl/21#-MxKSpZq4ghBb7doh2yy:-MxeIKfJ2p4qEtoWr1Xq:b1vzaid) ([raw file](https://github.com/badgertechnologies/badger_amcl/blob/b18eb323751be188900c4c0042f0978184bc7fe3/src/amcl/pf/particle_filter.cpp#L21)):*
<details><summary><i>Previously, Ibrahim-Apata wrote…</i></summary><blockquote>

1. Done
2. These includes allow us node handles to pull the parameters from the launch files  (lines 175 and 176). I didn't know if there was any other way to do that. If there is a better method let me know.
</blockquote></details>

please remove excess white space after the lines.

please look into the following:
you have added "std_msgs/String.h", why?
you have re-arranged "ros/assert.h", why?
you have added "sstream", why?
you have added "ros/ros.h", why?
you have re-arranged "sensors/sensor.h", why?
you have added "std_msgs/String.h", why?
___
*[src/amcl/pf/particle_filter.cpp, line 203 at r3](https://reviewable.io/reviews/badgertechnologies/badger_amcl/21#-MxKSTUf8xSQZb9oL2NT:-MxeKMSv0cRszyaIm1pC:b-nkkrkl) ([raw file](https://github.com/badgertechnologies/badger_amcl/blob/b18eb323751be188900c4c0042f0978184bc7fe3/src/amcl/pf/particle_filter.cpp#L203)):*
<details><summary><i>Previously, Ibrahim-Apata wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I dont see this change made.
___
*[src/amcl/pf/particle_filter.cpp, line 211 at r3](https://reviewable.io/reviews/badgertechnologies/badger_amcl/21#-MxKSc7v4549owRx5sLa:-MxeKaaqD66iN-AbEuwJ:b-nkkrkl) ([raw file](https://github.com/badgertechnologies/badger_amcl/blob/b18eb323751be188900c4c0042f0978184bc7fe3/src/amcl/pf/particle_filter.cpp#L211)):*
<details><summary><i>Previously, Ibrahim-Apata wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I dont see this change made.


<!-- Sent from Reviewable.io -->

2022-03-08 16:23 UTC, 12tbuchman reviewed
Please see this request^^

> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/badger_amcl/21#-:-MxeKpHB1VGDZCSXMgQ4:b-cyeidx)* status: all files reviewed, 7 unresolved discussions (waiting on @12tbuchman and @Ibrahim-Apata)



<!-- Sent from Reviewable.io -->

2022-03-08 22:33 UTC, Ibrahim-Apata reviewed
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/badger_amcl/21)* status: 1 of 3 files reviewed, 5 unresolved discussions (waiting on @12tbuchman and @Ibrahim-Apata)

___
*[src/amcl/node/node_3d.cpp, line 490 at r1](https://reviewable.io/reviews/badgertechnologies/badger_amcl/21#-MxFVa00DKgQXtjxxvCB:-Mxf4UDI2-RPVYjPBycS:b-m31wmh) ([raw file](https://github.com/badgertechnologies/badger_amcl/blob/954c1e519bc7f1d57490c8ff6c9497a68104f16b/src/amcl/node/node_3d.cpp#L490)):*
<details><summary><i>Previously, 12tbuchman (Tyler Buchman) wrote…</i></summary><blockquote>

I dont see the change. I think you changed the wrong info message.
</blockquote></details>

I changed the wrong text.
___
*[src/amcl/node/node_3d.cpp, line 493 at r4](https://reviewable.io/reviews/badgertechnologies/badger_amcl/21#-MxeHzda99MZUhGsw2co:-Mxf4CUN4LNxNFe4Nv3Q:b-jzytnp) ([raw file](https://github.com/badgertechnologies/badger_amcl/blob/72cf745f250c949d49c2b3af17cd2eb37314e79e/src/amcl/node/node_3d.cpp#L493)):*
<details><summary><i>Previously, 12tbuchman (Tyler Buchman) wrote…</i></summary><blockquote>

why did you change this to "convergance"?
</blockquote></details>

I thought this was what you wanted me to change. My mistake.
___
*[src/amcl/pf/particle_filter.cpp, line 21 at r3](https://reviewable.io/reviews/badgertechnologies/badger_amcl/21#-MxKSpZq4ghBb7doh2yy:-Mxf8nZJEkqef38ZikFi:b-f4cq3k) ([raw file](https://github.com/badgertechnologies/badger_amcl/blob/b18eb323751be188900c4c0042f0978184bc7fe3/src/amcl/pf/particle_filter.cpp#L21)):*
<details><summary><i>Previously, 12tbuchman (Tyler Buchman) wrote…</i></summary><blockquote>

please remove excess white space after the lines.

please look into the following:
you have added "std_msgs/String.h", why?
you have re-arranged "ros/assert.h", why?
you have added "sstream", why?
you have added "ros/ros.h", why?
you have re-arranged "sensors/sensor.h", why?
you have added "std_msgs/String.h", why?
</blockquote></details>

1. I thought i would need it for the node handle but i only needed ros/ros.h
2.I was following the coding style from the document you sent me it mentioned that the other .h files are used near the bottom and with the new ros/ros.h i changed the format to what i thought was the proper format. If this isn't the proper format, please let me know.
3. sstream i believe lets me assign set my node hande to the variable i wanted but i realized that with ros/ros.h this is not needed.
4. A lot of roscpp related files depand on ros.h including the node handles i use to pull the convergence threshold parameter
5. For the same reason i re-arranged ros/assert.h


<!-- Sent from Reviewable.io -->

2022-03-09 01:58 UTC, 12tbuchman requested changes
> Reviewed 1 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/badger_amcl/21)* status: 2 of 3 files reviewed, 3 unresolved discussions (waiting on @12tbuchman and @Ibrahim-Apata)

___
*[src/amcl/pf/particle_filter.cpp, line 21 at r3](https://reviewable.io/reviews/badgertechnologies/badger_amcl/21#-MxKSpZq4ghBb7doh2yy:-MxgIEI_Em65C5k9ybwH:bsvvpfk) ([raw file](https://github.com/badgertechnologies/badger_amcl/blob/b18eb323751be188900c4c0042f0978184bc7fe3/src/amcl/pf/particle_filter.cpp#L21)):*
<details><summary><i>Previously, Ibrahim-Apata wrote…</i></summary><blockquote>

1. I thought i would need it for the node handle but i only needed ros/ros.h
2.I was following the coding style from the document you sent me it mentioned that the other .h files are used near the bottom and with the new ros/ros.h i changed the format to what i thought was the proper format. If this isn't the proper format, please let me know.
3. sstream i believe lets me assign set my node hande to the variable i wanted but i realized that with ros/ros.h this is not needed.
4. A lot of roscpp related files depand on ros.h including the node handles i use to pull the convergence threshold parameter
5. For the same reason i re-arranged ros/assert.h

</blockquote></details>

ros.h is an outside library, sensors.h is a class defined in this package just like pdf_gaussian.h, which is why they are together at the bottom.

you can tell when an include is using an in-package class because it uses the "" instead of <>. Im not sure thats a hard rule but its a good rule to follow.

The order is:

1. includes files for the class being implemented
2. c system headers (with a .h)
3. c++ standard library headers
4. other projects
5. this project

You are probably right to include ros.h, im fine if you leave it in there... it should probably be included in other classes in this project as well but we dont need to do that right now
___
*[src/amcl/pf/particle_filter.cpp, line 211 at r3](https://reviewable.io/reviews/badgertechnologies/badger_amcl/21#-MxKSc7v4549owRx5sLa:-MxgJ0e1CTCoffBcs5Mr:b-ny8e1c) ([raw file](https://github.com/badgertechnologies/badger_amcl/blob/b18eb323751be188900c4c0042f0978184bc7fe3/src/amcl/pf/particle_filter.cpp#L211)):*
<details><summary><i>Previously, 12tbuchman (Tyler Buchman) wrote…</i></summary><blockquote>

I dont see this change made.
</blockquote></details>

still dont see the change...
___
*[src/amcl/pf/particle_filter.cpp, line 205 at r4](https://reviewable.io/reviews/badgertechnologies/badger_amcl/21#-MxgMcdL54r8RHfeD7e7:-MxgMcdL54r8RHfeD7e8:brhgqg0) ([raw file](https://github.com/badgertechnologies/badger_amcl/blob/72cf745f250c949d49c2b3af17cd2eb37314e79e/src/amcl/pf/particle_filter.cpp#L205)):*
> ```cpp
>     if (std::fabs(sample->pose[0] - mean_x) < dist_threshold_
>         && std::fabs(sample->pose[1] - mean_y) < dist_threshold_)
>     {
> ```

why did you remove the braces? you need them because your conditional covers multiple lines.


<!-- Sent from Reviewable.io -->

2022-03-09 01:59 UTC, 12tbuchman requested changes
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/badger_amcl/21)* status: 2 of 3 files reviewed, 4 unresolved discussions (waiting on @12tbuchman and @Ibrahim-Apata)

___
*[-- commits, line 4 at r5](https://reviewable.io/reviews/badgertechnologies/badger_amcl/21#-MxgOfVw8sXRwK4iPyB1):*
copying my message above because it seems like you arent seeing it..
"Setting global localization active to true" sounds like you are switching a parameter. I would suggest "Adding threshold to global localization convergence"


<!-- Sent from Reviewable.io -->

2022-03-09 16:35 UTC, Ibrahim-Apata reviewed
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/badger_amcl/21)* status: 2 of 3 files reviewed, 4 unresolved discussions (waiting on @12tbuchman and @Ibrahim-Apata)

___
*[-- commits, line 4 at r5](https://reviewable.io/reviews/badgertechnologies/badger_amcl/21#-MxgOfVw8sXRwK4iPyB1):*
<details><summary><i>Previously, 12tbuchman (Tyler Buchman) wrote…</i></summary><blockquote>

copying my message above because it seems like you arent seeing it..
"Setting global localization active to true" sounds like you are switching a parameter. I would suggest "Adding threshold to global localization convergence"
</blockquote></details>

Done.
___
*[src/amcl/pf/particle_filter.cpp, line 205 at r4](https://reviewable.io/reviews/badgertechnologies/badger_amcl/21#-MxgMcdL54r8RHfeD7e7:-MxjTC0j3hEhc-FQASTw:b-1rmi42) ([raw file](https://github.com/badgertechnologies/badger_amcl/blob/72cf745f250c949d49c2b3af17cd2eb37314e79e/src/amcl/pf/particle_filter.cpp#L205)):*
<details><summary><i>Previously, 12tbuchman (Tyler Buchman) wrote…</i></summary><blockquote>

why did you remove the braces? you need them because your conditional covers multiple lines.
</blockquote></details>

I thought this was the whitespace you wanted removed


<!-- Sent from Reviewable.io -->

2022-03-09 19:22 UTC, 12tbuchman requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/badger_amcl/21)* status: 2 of 3 files reviewed, 2 unresolved discussions (waiting on @12tbuchman and @Ibrahim-Apata)

___
*[src/amcl/pf/particle_filter.cpp, line 185 at r7](https://reviewable.io/reviews/badgertechnologies/badger_amcl/21#-Mxk66pJBq_BsJ64XM2P:-Mxk66pJBq_BsJ64XM2Q:b3r17mb) ([raw file](https://github.com/badgertechnologies/badger_amcl/blob/7b3b2e4fc7a7c7b10db986ed9dc8709977eeb9ce/src/amcl/pf/particle_filter.cpp#L185)):*
> ```cpp
> 
>   int sample_index;
>   for (sample_index = 0; sample_index <= set->sample_count; sample_index++)
> ```

why did you set this to be <= instead of < ? wont this cause you to overcount by 1?
___
*[src/amcl/pf/particle_filter.cpp, line 197 at r7](https://reviewable.io/reviews/badgertechnologies/badger_amcl/21#-Mxk6GL-B2BmhWjS6HJV:-Mxk6GL-B2BmhWjS6HJW:bavt16x) ([raw file](https://github.com/badgertechnologies/badger_amcl/blob/7b3b2e4fc7a7c7b10db986ed9dc8709977eeb9ce/src/amcl/pf/particle_filter.cpp#L197)):*
> ```cpp
>   set->converged = true;
>   converged_ = true;
>   // Counting which particles have converged
> ```

Do you need this comment?


<!-- Sent from Reviewable.io -->

2022-03-09 19:37 UTC, Ibrahim-Apata reviewed
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/badger_amcl/21)* status: 2 of 3 files reviewed, 2 unresolved discussions (waiting on @12tbuchman)

___
*[src/amcl/pf/particle_filter.cpp, line 185 at r7](https://reviewable.io/reviews/badgertechnologies/badger_amcl/21#-Mxk66pJBq_BsJ64XM2P:-Mxk8ql-Aixr7KwjaKbx:b-yqvr8w) ([raw file](https://github.com/badgertechnologies/badger_amcl/blob/7b3b2e4fc7a7c7b10db986ed9dc8709977eeb9ce/src/amcl/pf/particle_filter.cpp#L185)):*
<details><summary><i>Previously, 12tbuchman (Tyler Buchman) wrote…</i></summary><blockquote>

why did you set this to be <= instead of < ? wont this cause you to overcount by 1?
</blockquote></details>

my mistake. I added it to the wrong line.
___
*[src/amcl/pf/particle_filter.cpp, line 197 at r7](https://reviewable.io/reviews/badgertechnologies/badger_amcl/21#-Mxk6GL-B2BmhWjS6HJV:-Mxk87TPCMZl06Lc8uTk:b-q16c9h) ([raw file](https://github.com/badgertechnologies/badger_amcl/blob/7b3b2e4fc7a7c7b10db986ed9dc8709977eeb9ce/src/amcl/pf/particle_filter.cpp#L197)):*
<details><summary><i>Previously, 12tbuchman (Tyler Buchman) wrote…</i></summary><blockquote>

Do you need this comment?
</blockquote></details>

not really. I just have a habit of over commenting in code.


<!-- Sent from Reviewable.io -->

2022-03-09 21:06 UTC, 12tbuchman requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/badger_amcl/21)* status: 2 of 3 files reviewed, 3 unresolved discussions (waiting on @12tbuchman and @Ibrahim-Apata)

___
*[src/amcl/pf/particle_filter.cpp, line 175 at r9](https://reviewable.io/reviews/badgertechnologies/badger_amcl/21#-MxkUknE-wy7-nF1Od1I:-MxkUknF8AwfzwU30Bl0:bt7l9up) ([raw file](https://github.com/badgertechnologies/badger_amcl/blob/c791ccea9b9326ec305bd90a7a026f0cfcdb4ff5/src/amcl/pf/particle_filter.cpp#L175)):*
> ```cpp
>   double converged_threshold;
>   ros::NodeHandle node("~");
>   node.getParam("global_localization_convergence_threshold", converged_threshold);
> ```

this should be a class variable. to do this, create the variable in the `private` area of the .h file under the ParticleFilter class. you should not create a nodehandle here but instead use the Node class that already has a nodehandle to read the parameter and pass it to the ParticleFilter constructor. Look at how other parameters in the ParticleFilter are set and follow this pattern. I think you can then remove ros.h as well once you have made this change.


<!-- Sent from Reviewable.io -->

2022-03-10 20:47 UTC, 12tbuchman requested changes
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/badger_amcl/21)* status: 2 of 5 files reviewed, 4 unresolved discussions (waiting on @12tbuchman and @Ibrahim-Apata)

___
*[include/amcl/pf/particle_filter.h, line 171 at r10](https://reviewable.io/reviews/badgertechnologies/badger_amcl/21#-Mxp_B234A-DLIVDG8uV:-Mxp_B234A-DLIVDG8uW:baaaro8) ([raw file](https://github.com/badgertechnologies/badger_amcl/blob/b817d1521e29049f7cfa23de1d789176052ff0da/include/amcl/pf/particle_filter.h#L171)):*
> ```objc
> 
>   double convergance_threshold //Global Localization Convergence Threshold
> ```

fix whitespace, and please name it global_localization_convergence_threshold_


<!-- Sent from Reviewable.io -->

2022-03-10 20:47 UTC, 12tbuchman requested changes
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/badger_amcl/21)* status: 2 of 5 files reviewed, 5 unresolved discussions (waiting on @12tbuchman and @Ibrahim-Apata)

___
*[src/amcl/node/node.cpp, line 79 at r10](https://reviewable.io/reviews/badgertechnologies/badger_amcl/21#-Mxp_UMB17forElO-Aqs:-Mxp_UMC0-xAZTDoQCtH:baewe41) ([raw file](https://github.com/badgertechnologies/badger_amcl/blob/b817d1521e29049f7cfa23de1d789176052ff0da/src/amcl/node/node.cpp#L79)):*
> ```cpp
>   private_nh_.param("odom_alpha4", alpha4_, 0.2);
>   private_nh_.param("odom_alpha5", alpha5_, 0.2);
>   private_nh_.param("global_localizaton_convergence_threshold", convergence_threshold);
> ```

global_localization_convergence_threshold_


<!-- Sent from Reviewable.io -->

2022-03-10 20:47 UTC, 12tbuchman requested changes
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/badger_amcl/21)* status: 2 of 5 files reviewed, 6 unresolved discussions (waiting on @12tbuchman and @Ibrahim-Apata)

___
*[src/amcl/node/node.cpp, line 257 at r10](https://reviewable.io/reviews/badgertechnologies/badger_amcl/21#-Mxp_XkA6UO2WHmc_kZe:-Mxp_XkA6UO2WHmc_kZf:baewe41) ([raw file](https://github.com/badgertechnologies/badger_amcl/blob/b817d1521e29049f7cfa23de1d789176052ff0da/src/amcl/node/node.cpp#L257)):*
> ```cpp
>   uniform_pose_generator_fn_ = std::bind(&Node::uniformPoseGenerator, this);
>   pf_ = std::make_shared<ParticleFilter>(min_particles_, max_particles_, alpha_slow_, alpha_fast_,
>                                          uniform_pose_generator_fn_, convergence_threshold);
> ```

global_localization_convergence_threshold_


<!-- Sent from Reviewable.io -->

2022-03-10 20:48 UTC, 12tbuchman requested changes
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/badger_amcl/21)* status: 2 of 5 files reviewed, 8 unresolved discussions (waiting on @12tbuchman and @Ibrahim-Apata)

___
*[src/amcl/pf/particle_filter.cpp, line 30 at r10](https://reviewable.io/reviews/badgertechnologies/badger_amcl/21#-Mxp__yj6YR8ZRi87Jbp:-Mxp__yj6YR8ZRi87Jbq:bl46fgc) ([raw file](https://github.com/badgertechnologies/badger_amcl/blob/b817d1521e29049f7cfa23de1d789176052ff0da/src/amcl/pf/particle_filter.cpp#L30)):*
> ```cpp
> 
> #include <ros/assert.h>
> #include "ros/ros.h"
> ```

i dont think you need this now
___
*[src/amcl/pf/particle_filter.cpp, line 208 at r10](https://reviewable.io/reviews/badgertechnologies/badger_amcl/21#-Mxp_kxI2jnJq5c4LcIg:-Mxp_kxI2jnJq5c4LcIh:buwlnvr) ([raw file](https://github.com/badgertechnologies/badger_amcl/blob/b817d1521e29049f7cfa23de1d789176052ff0da/src/amcl/pf/particle_filter.cpp#L208)):*
> ```cpp
>   ROS_INFO_STREAM(percent_converged << "% of the particles are converging");
> 
>   if (percent_converged >= convergence_threshold)
> ```

convergence_threshold_


<!-- Sent from Reviewable.io -->

2022-03-10 20:49 UTC, 12tbuchman requested changes
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/badger_amcl/21)* status: 2 of 5 files reviewed, 9 unresolved discussions (waiting on @12tbuchman and @Ibrahim-Apata)

___
*[src/amcl/pf/particle_filter.cpp, line 39 at r10](https://reviewable.io/reviews/badgertechnologies/badger_amcl/21#-Mxp_t4J8V2JaZbtLu1c:-Mxp_t4J8V2JaZbtLu1d:bi4mlcm) ([raw file](https://github.com/badgertechnologies/badger_amcl/blob/b817d1521e29049f7cfa23de1d789176052ff0da/src/amcl/pf/particle_filter.cpp#L39)):*
> ```cpp
> 
> // Create a new filter
> ParticleFilter::ParticleFilter(int min_samples, int max_samples, double alpha_slow,
> ```

you need to accept the new parameter convergence_threshold, and you need to make a class variable convergence_threshold_ in the .h file that you then store this value to


<!-- Sent from Reviewable.io -->

2022-03-10 20:57 UTC, 12tbuchman requested changes
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/badger_amcl/21)* status: 2 of 5 files reviewed, 7 unresolved discussions (waiting on @12tbuchman and @Ibrahim-Apata)

___
*[src/amcl/pf/particle_filter.cpp, line 39 at r10](https://reviewable.io/reviews/badgertechnologies/badger_amcl/21#-Mxp_t4J8V2JaZbtLu1c:-MxpbjEp9RALLI7Z_RHI:b82b9m2) ([raw file](https://github.com/badgertechnologies/badger_amcl/blob/b817d1521e29049f7cfa23de1d789176052ff0da/src/amcl/pf/particle_filter.cpp#L39)):*
<details><summary><i>Previously, 12tbuchman (Tyler Buchman) wrote…</i></summary><blockquote>

you need to accept the new parameter convergence_threshold, and you need to make a class variable convergence_threshold_ in the .h file that you then store this value to
</blockquote></details>

sorry, you need to add it to the Node .h file


<!-- Sent from Reviewable.io -->

2022-03-10 20:57 UTC, 12tbuchman requested changes
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/badger_amcl/21)* status: 2 of 5 files reviewed, 7 unresolved discussions (waiting on @12tbuchman and @Ibrahim-Apata)

___
*[src/amcl/node/node.cpp, line 79 at r10](https://reviewable.io/reviews/badgertechnologies/badger_amcl/21#-Mxp_UMB17forElO-Aqs:-MxpbnlV4lJyjWj5bE6G:b-5vqad) ([raw file](https://github.com/badgertechnologies/badger_amcl/blob/b817d1521e29049f7cfa23de1d789176052ff0da/src/amcl/node/node.cpp#L79)):*
<details><summary><i>Previously, 12tbuchman (Tyler Buchman) wrote…</i></summary><blockquote>

global_localization_convergence_threshold_
</blockquote></details>

this should be added to the node .h file



_Code quote:_
```cpp
  private_nh_.param("global_localizaton_convergence_threshold", convergence_threshold);
```


<!-- Sent from Reviewable.io -->

2022-06-02 16:36 UTC, 12tbuchman requested changes
> Reviewed 1 of 5 files at r12.
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/badger_amcl/21)* status: 2 of 6 files reviewed, 9 unresolved discussions (waiting on @12tbuchman and @Ibrahim-Apata)

___
*[`-- commits` line 2 at r12](https://reviewable.io/reviews/badgertechnologies/badger_amcl/21#-N3_G7VB0j147ONIfMbr):*
"Improving" -> "Improve"
___
*[`include/amcl/pf/particle_filter.h` line 170 at r12](https://reviewable.io/reviews/badgertechnologies/badger_amcl/21#-N3_GK7g9TnayFK8_iwj:-N3_GK7g9TnayFK8_iwk:b65a3li) ([raw file](https://github.com/badgertechnologies/badger_amcl/blob/3a66d13232736a8651e8d840ba291cd4cb5c1163/include/amcl/pf/particle_filter.h#L170)):*
> ```objc
>   double dist_threshold_;  // distance threshold in each axis over which the pf is considered to not be converged
> 
>   double convergence_threshold_; //Global Localization Convergence Threshold
> ```

Id still like this to have "global localization" in the name because theres lots of things this could be a convergance threshold for. whats the reason you dont want to include "global localization"?


<!-- Sent from Reviewable.io -->

2022-06-02 17:08 UTC, 12tbuchman requested changes
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/badger_amcl/21)* status: 2 of 6 files reviewed, 12 unresolved discussions (waiting on @12tbuchman and @Ibrahim-Apata)

___
*[`src/amcl/node/node.cpp` line 64 at r12](https://reviewable.io/reviews/badgertechnologies/badger_amcl/21#-N3_G_xXCzl8aFW7uoJV:-N3_G_xXCzl8aFW7uoJW:b-pks32b) ([raw file](https://github.com/badgertechnologies/badger_amcl/blob/3a66d13232736a8651e8d840ba291cd4cb5c1163/src/amcl/node/node.cpp#L64)):*
> ```cpp
> 
>   double param_val;
>   double convergence_threshold_;
> ```

you put this in the .h file so you dont want to create it again here
___
*[`src/amcl/node/node_3d.cpp` line 491 at r12](https://reviewable.io/reviews/badgertechnologies/badger_amcl/21#-N3_JxO13NCiQbAI18vj:-N3_JxO26G2YsBcDLlys:b-hhz6eo) ([raw file](https://github.com/badgertechnologies/badger_amcl/blob/3a66d13232736a8651e8d840ba291cd4cb5c1163/src/amcl/node/node_3d.cpp#L491)):*
> ```cpp
>   bool is_converged = pf_->isConverged();
>   ROS_INFO_STREAM("Global Localization Convergence: " << is_converged << ", Localization Active: " << global_localization_active_);
>   if (is_converged && global_localization_active_)
> ```

why do you only want to resample if we have converged?
___
*[`src/amcl/pf/particle_filter.cpp` line 30 at r10](https://reviewable.io/reviews/badgertechnologies/badger_amcl/21#-Mxp__yj6YR8ZRi87Jbp:-N3_LaOt-pa0z0fy3UzE:b-dv7eql) ([raw file](https://github.com/badgertechnologies/badger_amcl/blob/b817d1521e29049f7cfa23de1d789176052ff0da/src/amcl/pf/particle_filter.cpp#L30)):*
<details><summary><i>Previously, 12tbuchman (Tyler Buchman) wrote…</i></summary><blockquote>

i dont think you need this now
</blockquote></details>

i still dont think you need to add this import
___
*[`src/amcl/pf/particle_filter.cpp` line 39 at r10](https://reviewable.io/reviews/badgertechnologies/badger_amcl/21#-Mxp_t4J8V2JaZbtLu1c:-N3_M4V64vt6zuPqGnUd:b9d88ik) ([raw file](https://github.com/badgertechnologies/badger_amcl/blob/b817d1521e29049f7cfa23de1d789176052ff0da/src/amcl/pf/particle_filter.cpp#L39)):*
<details><summary><i>Previously, 12tbuchman (Tyler Buchman) wrote…</i></summary><blockquote>

sorry, you need to add it to the Node .h file
</blockquote></details>

so you are right to accept the parameter here but you want to store it in a class variable in the .h file for this class. In my previous comment I said store it in the Node.h file, which you do want to do, but you also want to store a copy of that parameter here in this .h file. So you will read the parameter from the Node.cpp class, store it to the Node class variable, pass it here, and store it in the ParticleFilter class variable (which you need to create in the ParticleFilter.h file)
___
*[`src/amcl/pf/particle_filter.cpp` line 174 at r12](https://reviewable.io/reviews/badgertechnologies/badger_amcl/21#-N3_LntlDi4fA1lIzhiD:-N3_LntlDi4fA1lIzhiE:bblvcih) ([raw file](https://github.com/badgertechnologies/badger_amcl/blob/3a66d13232736a8651e8d840ba291cd4cb5c1163/src/amcl/pf/particle_filter.cpp#L174)):*
> ```cpp
>   double percent_converged;
>   particles_converged = 0;
>   ros::NodeHandle nh("~");
> ```

we want to only call the param server from the Node classes. Thats the reason we are passing the parameter into the ParticleFilter class through the constructor. Please remove this call to the parameter server and pass the parameter through the constructor.
___
*[`src/amcl/pf/particle_filter.cpp` line 197 at r12](https://reviewable.io/reviews/badgertechnologies/badger_amcl/21#-N3_NwA46tmir5zeNExl:-N3_NwA46tmir5zeNExm:b-9wqj9l) ([raw file](https://github.com/badgertechnologies/badger_amcl/blob/3a66d13232736a8651e8d840ba291cd4cb5c1163/src/amcl/pf/particle_filter.cpp#L197)):*
> ```cpp
>   converged_ = true;
> 
>   for (sample_index = 0; sample_index <= set->sample_count; sample_index++)
> ```

Did you intend to make this <= instead of <?


<!-- Sent from Reviewable.io -->

2022-06-07 15:21 UTC, Ibrahim-Apata reviewed
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/badger_amcl/21)* status: 1 of 6 files reviewed, 12 unresolved discussions (waiting on @12tbuchman and @Ibrahim-Apata)

___
*[`-- commits` line 2 at r12](https://reviewable.io/reviews/badgertechnologies/badger_amcl/21#-N3_G7VB0j147ONIfMbr):*
<details><summary><i>Previously, 12tbuchman (Tyler Buchman) wrote…</i></summary><blockquote>

"Improving" -> "Improve"
</blockquote></details>

Done.
___
*[`include/amcl/pf/particle_filter.h` line 170 at r12](https://reviewable.io/reviews/badgertechnologies/badger_amcl/21#-N3_GK7g9TnayFK8_iwj:-N3_oE1l-KrdSPBbQ9_-:beiqu05) ([raw file](https://github.com/badgertechnologies/badger_amcl/blob/3a66d13232736a8651e8d840ba291cd4cb5c1163/include/amcl/pf/particle_filter.h#L170)):*
<details><summary><i>Previously, 12tbuchman (Tyler Buchman) wrote…</i></summary><blockquote>

Id still like this to have "global localization" in the name because theres lots of things this could be a convergance threshold for. whats the reason you dont want to include "global localization"?
</blockquote></details>

No particular reason. The name has been changed
___
*[`src/amcl/node/node.cpp` line 257 at r10](https://reviewable.io/reviews/badgertechnologies/badger_amcl/21#-Mxp_XkA6UO2WHmc_kZe:-N3ykB0KAWhLbrC8ViIs:b-896fix) ([raw file](https://github.com/badgertechnologies/badger_amcl/blob/b817d1521e29049f7cfa23de1d789176052ff0da/src/amcl/node/node.cpp#L257)):*
<details><summary><i>Previously, 12tbuchman (Tyler Buchman) wrote…</i></summary><blockquote>

global_localization_convergence_threshold_
</blockquote></details>

Done.
___
*[`src/amcl/pf/particle_filter.cpp` line 175 at r9](https://reviewable.io/reviews/badgertechnologies/badger_amcl/21#-MxkUknE-wy7-nF1Od1I:-N3yk7G-Cr1jJJOgYmB1:b-896fix) ([raw file](https://github.com/badgertechnologies/badger_amcl/blob/c791ccea9b9326ec305bd90a7a026f0cfcdb4ff5/src/amcl/pf/particle_filter.cpp#L175)):*
<details><summary><i>Previously, 12tbuchman (Tyler Buchman) wrote…</i></summary><blockquote>

this should be a class variable. to do this, create the variable in the `private` area of the .h file under the ParticleFilter class. you should not create a nodehandle here but instead use the Node class that already has a nodehandle to read the parameter and pass it to the ParticleFilter constructor. Look at how other parameters in the ParticleFilter are set and follow this pattern. I think you can then remove ros.h as well once you have made this change.
</blockquote></details>

Done.
___
*[`src/amcl/pf/particle_filter.cpp` line 30 at r10](https://reviewable.io/reviews/badgertechnologies/badger_amcl/21#-Mxp__yj6YR8ZRi87Jbp:-N3yk8N01frShgnJSMOU:b-896fix) ([raw file](https://github.com/badgertechnologies/badger_amcl/blob/b817d1521e29049f7cfa23de1d789176052ff0da/src/amcl/pf/particle_filter.cpp#L30)):*
<details><summary><i>Previously, 12tbuchman (Tyler Buchman) wrote…</i></summary><blockquote>

i still dont think you need to add this import
</blockquote></details>

Done.
___
*[`src/amcl/pf/particle_filter.cpp` line 174 at r12](https://reviewable.io/reviews/badgertechnologies/badger_amcl/21#-N3_LntlDi4fA1lIzhiD:-N3yk6JFEaFnAioTHsZS:b-896fix) ([raw file](https://github.com/badgertechnologies/badger_amcl/blob/3a66d13232736a8651e8d840ba291cd4cb5c1163/src/amcl/pf/particle_filter.cpp#L174)):*
<details><summary><i>Previously, 12tbuchman (Tyler Buchman) wrote…</i></summary><blockquote>

we want to only call the param server from the Node classes. Thats the reason we are passing the parameter into the ParticleFilter class through the constructor. Please remove this call to the parameter server and pass the parameter through the constructor.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-06-09 21:21 UTC, 12tbuchman reviewed
> Reviewed 3 of 4 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/badger_amcl/21)* status: 4 of 6 files reviewed, 2 unresolved discussions (waiting on @12tbuchman and @Ibrahim-Apata)



<!-- Sent from Reviewable.io -->

2022-06-09 21:28 UTC, 12tbuchman requested changes
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/badger_amcl/21)* status: 4 of 6 files reviewed, 3 unresolved discussions (waiting on @12tbuchman and @Ibrahim-Apata)

___
*[`src/amcl/node/node_3d.cpp` line 490 at r13](https://reviewable.io/reviews/badgertechnologies/badger_amcl/21#-N49LwKg1vmP2DIM03L7:-N49LwKg1vmP2DIM03L8:bj9h190) ([raw file](https://github.com/badgertechnologies/badger_amcl/blob/da15d20074e48dd2251fcf4eb322f20dbaf0f64c/src/amcl/node/node_3d.cpp#L490)):*
> ```cpp
>   pf_->updateResample();
>   bool is_converged = pf_->isConverged();
>   ROS_INFO_STREAM("Global Localization Convergence: " << is_converged << ", Localization Active: " << global_localization_active_);
> ```

Please keep this under the line length limit of 120 for C++


<!-- Sent from Reviewable.io -->

2022-06-10 15:11 UTC, Ibrahim-Apata reviewed
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/badger_amcl/21)* status: 1 of 6 files reviewed, 3 unresolved discussions (waiting on @12tbuchman and @Ibrahim-Apata)

___
*[`src/amcl/node/node.cpp` line 79 at r10](https://reviewable.io/reviews/badgertechnologies/badger_amcl/21#-Mxp_UMB17forElO-Aqs:-N4D77ip2oaVF9X8I9Ep:bb7f2mf) ([raw file](https://github.com/badgertechnologies/badger_amcl/blob/b817d1521e29049f7cfa23de1d789176052ff0da/src/amcl/node/node.cpp#L79)):*
<details><summary><i>Previously, 12tbuchman (Tyler Buchman) wrote…</i></summary><blockquote>

this should be added to the node .h file
</blockquote></details>

done
___
*[`src/amcl/node/node_3d.cpp` line 491 at r12](https://reviewable.io/reviews/badgertechnologies/badger_amcl/21#-N3_JxO13NCiQbAI18vj:-N4D5jklBmGb-p2QUuoI:bdd20qf) ([raw file](https://github.com/badgertechnologies/badger_amcl/blob/3a66d13232736a8651e8d840ba291cd4cb5c1163/src/amcl/node/node_3d.cpp#L491)):*
<details><summary><i>Previously, 12tbuchman (Tyler Buchman) wrote…</i></summary><blockquote>

why do you only want to resample if we have converged?
</blockquote></details>

This change doesn't do that. It's purpose is to make sure that our global localization is active and converged before we claim convergence and  set global_localization_active_ to false.
___
*[`src/amcl/node/node_3d.cpp` line 490 at r13](https://reviewable.io/reviews/badgertechnologies/badger_amcl/21#-N49LwKg1vmP2DIM03L7:-N4D6iI48YNwr1jWsoAo:b-896fix) ([raw file](https://github.com/badgertechnologies/badger_amcl/blob/da15d20074e48dd2251fcf4eb322f20dbaf0f64c/src/amcl/node/node_3d.cpp#L490)):*
<details><summary><i>Previously, 12tbuchman (Tyler Buchman) wrote…</i></summary><blockquote>

Please keep this under the line length limit of 120 for C++
</blockquote></details>

Done.
___
*[`src/amcl/pf/particle_filter.cpp` line 211 at r3](https://reviewable.io/reviews/badgertechnologies/badger_amcl/21#-MxKSc7v4549owRx5sLa:-N4Cyf0Z15jVnCud0LLJ:bb7f2mf) ([raw file](https://github.com/badgertechnologies/badger_amcl/blob/b18eb323751be188900c4c0042f0978184bc7fe3/src/amcl/pf/particle_filter.cpp#L211)):*
<details><summary><i>Previously, 12tbuchman (Tyler Buchman) wrote…</i></summary><blockquote>

still dont see the change...
</blockquote></details>

done
___
*[`src/amcl/pf/particle_filter.cpp` line 39 at r10](https://reviewable.io/reviews/badgertechnologies/badger_amcl/21#-Mxp_t4J8V2JaZbtLu1c:-N4Cz2BY2EeaJt0i7rfZ:b-7rl0jd) ([raw file](https://github.com/badgertechnologies/badger_amcl/blob/b817d1521e29049f7cfa23de1d789176052ff0da/src/amcl/pf/particle_filter.cpp#L39)):*
<details><summary><i>Previously, 12tbuchman (Tyler Buchman) wrote…</i></summary><blockquote>

so you are right to accept the parameter here but you want to store it in a class variable in the .h file for this class. In my previous comment I said store it in the Node.h file, which you do want to do, but you also want to store a copy of that parameter here in this .h file. So you will read the parameter from the Node.cpp class, store it to the Node class variable, pass it here, and store it in the ParticleFilter class variable (which you need to create in the ParticleFilter.h file)
</blockquote></details>

done.
___
*[`src/amcl/pf/particle_filter.cpp` line 197 at r12](https://reviewable.io/reviews/badgertechnologies/badger_amcl/21#-N3_NwA46tmir5zeNExl:-N4CyhcN88fM5h3oTWvF:b-7xlsv3) ([raw file](https://github.com/badgertechnologies/badger_amcl/blob/3a66d13232736a8651e8d840ba291cd4cb5c1163/src/amcl/pf/particle_filter.cpp#L197)):*
<details><summary><i>Previously, 12tbuchman (Tyler Buchman) wrote…</i></summary><blockquote>

Did you intend to make this <= instead of <?
</blockquote></details>

my mistake. 


<!-- Sent from Reviewable.io -->

2022-06-10 15:31 UTC, 12tbuchman requested changes
> Reviewed 3 of 5 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/badger_amcl/21)* status: 4 of 6 files reviewed, 3 unresolved discussions (waiting on @12tbuchman and @Ibrahim-Apata)

___
*[`src/amcl/node/node_3d.cpp` line 491 at r12](https://reviewable.io/reviews/badgertechnologies/badger_amcl/21#-N3_JxO13NCiQbAI18vj:-N4DCf7c0xON2_3zGmuP:b-uq1cwc) ([raw file](https://github.com/badgertechnologies/badger_amcl/blob/3a66d13232736a8651e8d840ba291cd4cb5c1163/src/amcl/node/node_3d.cpp#L491)):*
<details><summary><i>Previously, Ibrahim-Apata wrote…</i></summary><blockquote>

This change doesn't do that. It's purpose is to make sure that our global localization is active and converged before we claim convergence and  set global_localization_active_ to false.
</blockquote></details>

right, thanks
___
*[`src/amcl/node/node_3d.cpp` line 490 at r13](https://reviewable.io/reviews/badgertechnologies/badger_amcl/21#-N49LwKg1vmP2DIM03L7:-N4DC0qEBMiko6uT5xcz:b-yw9oxe) ([raw file](https://github.com/badgertechnologies/badger_amcl/blob/da15d20074e48dd2251fcf4eb322f20dbaf0f64c/src/amcl/node/node_3d.cpp#L490)):*
<details><summary><i>Previously, Ibrahim-Apata wrote…</i></summary><blockquote>

Done.
</blockquote></details>

still over the line length limit. try
```
ROS_INFO_STREAM("Localization Converged: " << is_converged
                << ", Localization Active: " << global_localization_active_);
```
___
*[`src/amcl/pf/particle_filter.cpp` line 39 at r10](https://reviewable.io/reviews/badgertechnologies/badger_amcl/21#-Mxp_t4J8V2JaZbtLu1c:-N4DCsyCAQrtJjk4H042:bnuhas6) ([raw file](https://github.com/badgertechnologies/badger_amcl/blob/b817d1521e29049f7cfa23de1d789176052ff0da/src/amcl/pf/particle_filter.cpp#L39)):*
<details><summary><i>Previously, Ibrahim-Apata wrote…</i></summary><blockquote>

done.
</blockquote></details>

Please make sure your whitespace is lined up. you will have to make the function parameters 3 lines. you can line up `double global_localization_convergence_threshold` with the parameter on the line above it and line up `std::function...` with `double global_localization...` so it would look liike
```
ParticleFilter::ParticleFilter(int min_samples, int max_samples, double alpha_slow, double alpha_fast,
                               double global_localization_convergence_threshold,
                               std::function<Eigen::Vector3d()> random_pose_fn)
```
___
*[`src/amcl/pf/particle_filter.cpp` line 205 at r14](https://reviewable.io/reviews/badgertechnologies/badger_amcl/21#-N4DDjtLEnrY-mG5kIoJ:-N4DDjtLEnrY-mG5kIoK:bsh0q4k) ([raw file](https://github.com/badgertechnologies/badger_amcl/blob/769d66077f4f00bf4d716860a2f94b702b6aa150/src/amcl/pf/particle_filter.cpp#L205)):*
> ```cpp
>   }
> 
>   percent_converged =(static_cast<float>(particles_converged) / static_cast<float>(sample_index)) * 100;
> ```

you need a space between the `=` and `(`, and I dont think you need the outer parenthesis anyways


<!-- Sent from Reviewable.io -->

2022-06-10 16:09 UTC, Ibrahim-Apata reviewed
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/badger_amcl/21)* status: 3 of 6 files reviewed, 3 unresolved discussions (waiting on @12tbuchman and @Ibrahim-Apata)

___
*[`src/amcl/node/node_3d.cpp` line 490 at r13](https://reviewable.io/reviews/badgertechnologies/badger_amcl/21#-N49LwKg1vmP2DIM03L7:-N4DFLJ89DX88hNzAaM2:b-4b7dwz) ([raw file](https://github.com/badgertechnologies/badger_amcl/blob/da15d20074e48dd2251fcf4eb322f20dbaf0f64c/src/amcl/node/node_3d.cpp#L490)):*
<details><summary><i>Previously, 12tbuchman (Tyler Buchman) wrote…</i></summary><blockquote>

still over the line length limit. try
```
ROS_INFO_STREAM("Localization Converged: " << is_converged
                << ", Localization Active: " << global_localization_active_);
```
</blockquote></details>

Ah! Thanks!
___
*[`src/amcl/pf/particle_filter.cpp` line 39 at r10](https://reviewable.io/reviews/badgertechnologies/badger_amcl/21#-Mxp_t4J8V2JaZbtLu1c:-N4DFZ5x0x-MJcKM5PHQ:bszzn47) ([raw file](https://github.com/badgertechnologies/badger_amcl/blob/b817d1521e29049f7cfa23de1d789176052ff0da/src/amcl/pf/particle_filter.cpp#L39)):*
<details><summary><i>Previously, 12tbuchman (Tyler Buchman) wrote…</i></summary><blockquote>

Please make sure your whitespace is lined up. you will have to make the function parameters 3 lines. you can line up `double global_localization_convergence_threshold` with the parameter on the line above it and line up `std::function...` with `double global_localization...` so it would look liike
```
ParticleFilter::ParticleFilter(int min_samples, int max_samples, double alpha_slow, double alpha_fast,
                               double global_localization_convergence_threshold,
                               std::function<Eigen::Vector3d()> random_pose_fn)
```
</blockquote></details>

Done. Thanks for letting me know.
___
*[`src/amcl/pf/particle_filter.cpp` line 205 at r14](https://reviewable.io/reviews/badgertechnologies/badger_amcl/21#-N4DDjtLEnrY-mG5kIoJ:-N4DFePABcY4uXJ2wwAK:b-896fix) ([raw file](https://github.com/badgertechnologies/badger_amcl/blob/769d66077f4f00bf4d716860a2f94b702b6aa150/src/amcl/pf/particle_filter.cpp#L205)):*
<details><summary><i>Previously, 12tbuchman (Tyler Buchman) wrote…</i></summary><blockquote>

you need a space between the `=` and `(`, and I dont think you need the outer parenthesis anyways
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-06-10 16:35 UTC, 12tbuchman requested changes
> Reviewed 1 of 5 files at r14, 2 of 2 files at r15, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/badger_amcl/21)* status: all files reviewed, 1 unresolved discussion (waiting on @Ibrahim-Apata)

___
*[`src/amcl/node/node.cpp` line 264 at r15](https://reviewable.io/reviews/badgertechnologies/badger_amcl/21#-N4DSyG-3XuMU7ZR2P2H:-N4DSyG-3XuMU7ZR2P2I:bnltv47) ([raw file](https://github.com/badgertechnologies/badger_amcl/blob/42bdf4258dff42c75223b13af4921a30bd6b18c7/src/amcl/node/node.cpp#L264)):*
> ```cpp
>   uniform_pose_generator_fn_ = std::bind(&Node::uniformPoseGenerator, this);
>   pf_ = std::make_shared<ParticleFilter>(min_particles_, max_particles_, alpha_slow_, alpha_fast_,
>                                         global_localization_convergence_threshold_, uniform_pose_generator_fn_);
> ```

this needs to be lined up with the `m`


<!-- Sent from Reviewable.io -->

2022-06-10 16:35 UTC, 12tbuchman requested changes
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/badger_amcl/21)* status: all files reviewed, 2 unresolved discussions (waiting on @Ibrahim-Apata)

___
*[`src/amcl/node/node.cpp` line 642 at r15](https://reviewable.io/reviews/badgertechnologies/badger_amcl/21#-N4DT398DNXGuzq9FtKi:-N4DT398DNXGuzq9FtKj:bfozq69) ([raw file](https://github.com/badgertechnologies/badger_amcl/blob/42bdf4258dff42c75223b13af4921a30bd6b18c7/src/amcl/node/node.cpp#L642)):*
> ```cpp
>   uniform_pose_generator_fn_ = std::bind(&Node::uniformPoseGenerator, this);
>   pf_ = std::make_shared<ParticleFilter>(min_particles_, max_particles_, alpha_slow_, alpha_fast_,
>                                         global_localization_convergence_threshold_,uniform_pose_generator_fn_);
> ```

this needs to be lined up with the m


<!-- Sent from Reviewable.io -->

2022-06-10 17:54 UTC, Ibrahim-Apata reviewed
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/badger_amcl/21)* status: 5 of 6 files reviewed, 2 unresolved discussions (waiting on @12tbuchman)

___
*[`src/amcl/node/node.cpp` line 264 at r15](https://reviewable.io/reviews/badgertechnologies/badger_amcl/21#-N4DSyG-3XuMU7ZR2P2H:-N4DcNdt4EWPThjofY34:b-896fix) ([raw file](https://github.com/badgertechnologies/badger_amcl/blob/42bdf4258dff42c75223b13af4921a30bd6b18c7/src/amcl/node/node.cpp#L264)):*
<details><summary><i>Previously, 12tbuchman (Tyler Buchman) wrote…</i></summary><blockquote>

this needs to be lined up with the `m`
</blockquote></details>

Done.
___
*[`src/amcl/node/node.cpp` line 642 at r15](https://reviewable.io/reviews/badgertechnologies/badger_amcl/21#-N4DT398DNXGuzq9FtKi:-N4DcO7OClfcLY-8eqq5:b-896fix) ([raw file](https://github.com/badgertechnologies/badger_amcl/blob/42bdf4258dff42c75223b13af4921a30bd6b18c7/src/amcl/node/node.cpp#L642)):*
<details><summary><i>Previously, 12tbuchman (Tyler Buchman) wrote…</i></summary><blockquote>

this needs to be lined up with the m
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-06-10 18:06 UTC, 12tbuchman approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/badger_amcl/21#-:-N4Dn2i8EMn5Ng2ZAOnv:bnfp4nl)* status: 5 of 6 files reviewed, all discussions resolved (waiting on @12tbuchman)



<!-- Sent from Reviewable.io -->

2022-06-12 22:41 UTC, 12tbuchman requested changes
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/badger_amcl/21)* status: 5 of 6 files reviewed, 1 unresolved discussion (waiting on @12tbuchman and @Ibrahim-Apata)

___
*[`include/amcl/pf/particle_filter.h` line 97 at r15](https://reviewable.io/reviews/badgertechnologies/badger_amcl/21#-N4P40aK4F9ckGwXkQ34:-N4P40aK4F9ckGwXkQ35:b-xyr1s) ([raw file](https://github.com/badgertechnologies/badger_amcl/blob/42bdf4258dff42c75223b13af4921a30bd6b18c7/include/amcl/pf/particle_filter.h#L97)):*
> ```objc
>   // Create a new filter
>   ParticleFilter(int min_samples, int max_samples, double alpha_slow, double alpha_fast,
>                 double global_localization_convergence_threshold, std::function<Eigen::Vector3d()> random_pose_fn);
> ```

please line up "double" with the "int" above


<!-- Sent from Reviewable.io -->

2022-06-13 00:38 UTC, 12tbuchman approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/badger_amcl/21#-:-N4PUwwB26egnoSSEmeh:bnfp4nl)* status: 4 of 6 files reviewed, all discussions resolved (waiting on @12tbuchman)



<!-- Sent from Reviewable.io -->

2022-06-13 00:39 UTC, merged